### ISSUE TITLE
Should restore focus on text field when switching apps

### ISSUE THREAD

**Issue by jiahaog** [jiahaog/nativefier#1]
If `cmd-tab` is executed while the cursor is on a textfield and ready for text input, returning to the app will cause the currently selected text input field to lose focus, and occasionally causes the backspace key to stop working.

**Comment by ronjouch** [comment]
> *"If `cmd-tab` is executed while the cursor is on a textfield and ready for text input, returning to the app will cause the currently selected text input field to lose focus, and occasionally causes the backspace key to stop working."*

No longer as of Nativefier 7.1.0 / electron 1.6.6 :) , closing.
