### ISSUE TITLE
Password Saving

### ISSUE THREAD

**Issue by avikj** [jiahaog/nativefier#100]
I think a very useful feature to add would be saving passwords or even automatically logging the user in. For example, if I use nativefier to create a desktop application for Facebook Messenger,  I have to log in every time I run the app. It would be much more user friendly if this process was automated or at least simplified.

**Comment by jiahaog** [comment]
Are you sure you have to log in every time? On my side I can just log in once into WhatsApp / Facebook Messenger and when I quit and return to the app, I am still logged in.

**Comment by avikj** [comment]
Yeah you're right, never mind. I wasn't saving my password / checking "keep me logged in"

**Comment by dsandstrom** [comment]
I think this would be helpful if the site doesn't offer a way to stay logged in.  Is Chromium's password manager available to Electron apps?  I couldn't find any info on this.

**Comment by solepixel** [comment]
I'm using this for Wave (https://www.waveapps.com/accounting/) and there isn't a "Remember me" option. I find after 1 day or several hours I have to re-login. I would also like to know how to implement this. It seems with --inject there could be some utility, but not sure of a secure way to do this. Would be great to have LastPass integration.
