### ISSUE TITLE
Unable to login to nativefied app with google

### ISSUE THREAD

**Issue by Nathan22211** [jiahaog/nativefier#1003]
**Bug description**
Trying to log into a nativefied app with Google, even with the internal URL set in the command will not work

- [X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [X] I searched existing open & closed issues. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
Give your ***full*** nativefier command, with the ***`--verbose` flag***, on a ***public*** site:
1. Run `nativefier --verbose --internal-urls https://accounts.google.com/ --name "Wattpad" https://www.wattpad.com/home` Note: With verbose enabled the google auth wouldn't even launch in my tests. Without it, it was able to launch.
2. Try to log in with google. to my knowledge. it doesn't nessacarly have to be the site I tried.

**Expected behavior**
It should log in and I'd see my Wattpad account, or whatever you logged into for your test

**Actual behavior**
the login thing still shows even after authenticating

**Debug info**
Verbose logs (command-line and/or in app DevTools console), error message, screenshots
I couldn't get anything from verbose when trying to log in, because it wouldn't work with that flag on, and I didn't get any errors to my knowledge

**Context**
 - Nativefier: 9.0.0
 - Node.js: 14.x, It was from https://github.com/nodesource/distributions/blob/master/README.md so I only know the Major version rn.
 - Npm: Whatever version came with the package (I have no clue how to check)
 - OS: Zorin OS 15.2, Which uses Ubuntu 18.04
 - Is it a regression? Not to my knowledge
 - Additional context:

**Comment by cmangla** [comment]
Could it be due to the pinned Google authentication issue? If so, the workaround from the latest comment in issue #831 might help.

**Comment by Nathan22211** [comment]
yeah in my tests google docs worked without that but I've yet to try others. My recommendation, in the readme.md tell people how to enable login from stuff like google and facebook

**Comment by haroldao** [comment]
that's because Google only works with Safari, Chrome, Edge, etc... but not with Electron

**Comment by ronjouch** [comment]
Yup. Closing as dup of #831, see workarounds there. Nativefier could do better, patches welcome.
