### ISSUE TITLE
Polymail on Linux?

### ISSUE THREAD

**Issue by phodamentals** [jiahaog/nativefier#1008]
Hi all. I successfully created a 'nativefied' [Polymail](https://app.polymail.io), however the only thing lacking were the system notifications, which are pretty desirable for it being a mail client. I have tried the slew of configuration parameters, to no avail, so continuing to just run it in a browser tab still.

**OS:** Pop!_OS 20.04 LTS

Has anyone had luck with Polymail on Linux with closer full functionality?

**Comment by ronjouch** [comment]
@phodamentals 

1. Please fill the information requested by the [issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
2. What else apart from notifications is missing?
