### ISSUE TITLE
[Popup] Iframe / Window.opener() does not work

### ISSUE THREAD

**Issue by mcharron** [jiahaog/nativefier#101]
Hi there,

I tried the application my society is selling with nativefier, and we can't get our "window.opener" to work. It only return string data, which will be write in an input in the main window.

Do you already have this problem ? I thought Chromium manage these kind of JS implementations.

Cheers

**Comment by jiahaog** [comment]
Hi, do you have an example web page that I can test this on?

**Comment by mcharron** [comment]
Hi,

Sorry, I can't give you an example atm. Btw, I found that issue comes from Electron, not Nativefier ! I try to exec a JS function in the opener window, but if I do a window.opener, it returns me a BrowserWindowProxy object instead of the parent window, I have to find another way to do it.

**Comment by mcharron** [comment]
I found an alternative : use postMessage() function.

All you have to do is send a postMessage from the popup to the parent window, and in the parent window add an event listener on "message" type, and call a specific function to treat entering messages.
