### ISSUE TITLE
WhatsApp rendering appears corrupted / glitched (hardware acceleration?)

### ISSUE THREAD

**Issue by firefinchdev** [jiahaog/nativefier#1010]
**Homework**

- [ X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [ X] I searched existing issues, open & closed. Yes, my bug is new.
- [X ] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

See the following screenshot of app built using nativefier for web.whatsapp.com
Everything was working fine, but suddenly, when I opened the app rendering issues were present.
I used `nativefier "web.whatsapp.com" --icon "/Users/anirgupt/Downloads/icon.png"` to build the app.

**Steps to reproduce**
1. Run `nativefier "web.whatsapp.com" --icon "/Users/anirgupt/Downloads/icon.png"`. The build is successful.
2. Run the output app.
3. Login, and then go to app's settings (settings menu within the rendered app) and enable dark theme (Important)
4. Go back to main screen of the app.
5. After some time later, rendering issues are visible.
6. The rendering issue is present even when opening the developer tools. (2nd screenshot)

This issue is not present in official WhatsApp electron based app, and neither can it be observed on any browser (tried with Chrome).

The issue does seem to disappear if I disable dark theme from settings. But it still reappears if I open developer tools.

**Context**

 - Nativefier: 9.1.0
 - Node.js: 14.6
 - Npm: 6.14.7
 - OS: macOS 10.15.6

**Comment by firefinchdev** [comment]
<img width="1648" alt="Screenshot 2020-07-27 at 9 07 58 PM" src="https://user-images.githubusercontent.com/26357501/88562889-e5398500-d04e-11ea-8455-8fd47341c077.png">

**Comment by firefinchdev** [comment]
<img width="1648" alt="Screenshot 2020-07-27 at 9 08 12 PM" src="https://user-images.githubusercontent.com/26357501/88562915-ef5b8380-d04e-11ea-8a70-9617ed8894a1.png">

**Comment by ronjouch** [comment]
@firefinchdev this looks like broken Hardware Acceleration. Try:

1. Updating your OS and video drivers.
2. If 1. fails, try passing flag `--disable-gpu` . Con: a tiny bit of performance & energy efficiency loss (but that should not be very noticeable on an app like WhatsApp).

**Comment by firefinchdev** [comment]
I don't know how, but it was automatically resolved after one day. I literally did nothing (No updates, etc).
