### ISSUE TITLE
Option `--maximize` interferes with `--tray start-in-tray`

### ISSUE THREAD

**Issue by codekandis** [jiahaog/nativefier#1015]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

If a create an app with both options provided the app main window still starts visible.

**Steps to reproduce**

succeeding
```
nativefier "https://example.com" --tray start-in-tray
```

failing
```
nativefier "https://example.com" --tray start-in-tray --maximize
```

**Expected behavior**

The app starts minimized to tray and if opened it will be shown maximized.

**Actual behavior**

The app starts shown maximized.

**Context**

 - Nativefier: 9.1.0
 - Node.js: 14.6.0
 - Npm: 6.14.7
 - OS: Linux hostname 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
 - Is it a regression: unknown, while its the first attempt to build with the `--tray` option

**Comment by codekandis** [comment]
It's not working.

Expected:

* minimized to tray
* on activation it'll be shown maximized

Current:

* minimized to tray
* on activation it'll be shown in it's configured size

But I really think it's more an electron issue than a nativefier issue.

I took a look into your code ...

https://github.com/jiahaog/nativefier/blob/cf11a71a7c6efd366266fcf39ac6fc49783dd8c7/app/src/components/mainWindow.ts#L132-L151

If I provide both options, the main window will be maximized in the first and minimized to tray in the second place. This is the right and expected order. So I assume **electron won't show any app maximized from start** but **electron will show any app maximized during run**.

To be clear: A running maximized app will be minimized to tray. It'll be activated then and will be shown maximized again. But from the start it won't save its maximized state if hidden to tray immediately afterwards.

That's sad ... but in fact the current --fixed-- state is much better than the previous one. So thank you very much for the fix.

**Comment by ronjouch** [comment]
Ping @sorhtyre : any comment on the above?

**Comment by sorhtyre** [comment]
@ronjouch I believe this sounds like bug #884
@codekandis I assume you already ran a previous version of nativefier on the URL in question.
If you did this in Linux, there is a cached profile in `~/.config`. The folder will be named `appname-nativefier-xxxxxx`.
For example my Netflix app's cache folder is `netflix-nativefier-0d3911`.
Delete that folder and rerun your app, it will generate a new cache folder with the correct setting.

I do not know where that file is stored in other OSs...

**Comment by codekandis** [comment]
@sorhtyre I cannot confirm your assumption. I'm on linux and update `nativefier` via `ansible` and (re-)create all my apps with shell aliases. These aliases already delete the old configs.

**Comment by sorhtyre** [comment]
@codekandis can you provide more information as to how the shell aliases delete the old configs? For clarification, I'm not referring to the app folder that nativefier creates when it nativefies a website. I'm referring to the cache that is created once you run that app.
