### ISSUE TITLE
ERROR: A failure occurred in package() - 05/08/2020

### ISSUE THREAD

**Issue by Lucifer-Kali** [jiahaog/nativefier#1017]
When installing whatsapp-nativefier it says :

`==> Making package: nodejs-nativefier 9.1.0-1 (Wed Aug  5 09:55:32 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Found nativefier-9.1.0.tgz
==> WARNING: Skipping verification of source file checksums.
==> Extracting sources...
==> Entering fakeroot environment...
==> Starting package()...
find: '/tmp/bauh/arch/build_1596601526/nodejs-nativefier/pkg/nodejs-nativefier/usr': No such file or directory
==> ERROR: A failure occurred in package().
Aborting...`

So i went and tried installing nodejs-nativefier as it is and got this error:

`Building nodejs-nativefier...
==> Making package: nodejs-nativefier 9.1.0-1 (Wed 05 Aug 2020 10:01:52 AM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found nativefier-9.1.0.tgz
==> Validating source files with sha1sums...
    nativefier-9.1.0.tgz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
find: ‘/var/tmp/pamac-build-username/nodejs-nativefier/pkg/nodejs-nativefier/usr’: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...`

**Comment by ronjouch** [comment]
Hi @Lucifer-Kali . Please either report a full detailed/reproducible Nativefier bug here, or report your AUR problem as a comment on https://aur.archlinux.org/packages/whatsapp-nativefier/ . Thanks.
