### ISSUE TITLE
Recommendation: Electron-SuperKit

### ISSUE THREAD

**Issue by MakuSensei** [jiahaog/nativefier#102]
Hello I wanted to recommend, this module Electron, containing interesting features :D 
[https://github.com/Aluxian/electron-superkit](url)
- native crash reporting
- windows installer
- Debugging & profiling
- native menus & notifications

- dmg installer for OS X
- deb & rpm packages for Linux
- SS6 write JavaScript code ES5 ship
- write LESS stylesheets, ship CSS code
- AppVeyor use to build Windows releases
- task to publish releases to GitHub
- live reload in development

**Comment by jiahaog** [comment]
Thanks for this, I'll look into it in the future!
