### ISSUE TITLE
Allow for OSX build to set current working directory to the directory that contains the App

### ISSUE THREAD

**Issue by johnblackmon** [jiahaog/nativefier#1020]
I've done my homework, and can't find a way to get this working with the current Nativefier.

I am looking to use Nativefier to run a directory of local HTML files that I would distribute with the built EXE/APP so that it can be run offline. I can get it to work easily on Windows by building an instance that points to any website, and then editing the "targetUrl" parameter in the nativefier.json file to be a relative path to the HTML. However, on OSX, the current directory is always set to "/", so the relative path always points to the root, making it impossible to load relatively placed HTML.

There are a few potential ways to fix this:
- allow for specifying a "file:///" URL as the URL for creating the EXE/APP, and adding that content to the resulting build package, ensuring that the current  directory is set so that it will be loaded correctly
- Add a new option --set_working_dir that sets the working directory to the directory the App is in
- or just always set the current working directory to the directory that the app is in, I can't imagine that would hurt anything

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/jiahaog/nativefier/issues/45
