### ISSUE TITLE
Google Login problem: "Couldn't sign you in"

### ISSUE THREAD

**Issue by VietnameZe** [jiahaog/nativefier#1025]
Google Login issue

I created an app used "nativefier --name 'myCalendar' 'calendar.google.com'" but the newly created app doesn't let me log in. 
![Screen Shot 2020-08-16 at 4 45 26 PM](https://user-images.githubusercontent.com/10421864/90343645-7bbeed80-dfe0-11ea-819b-91b5f7f67c2f.jpg)

**Comment by ronjouch** [comment]
See https://github.com/jiahaog/nativefier/issues/831
