### ISSUE TITLE
Does Not redirect back to NativeFier Desktop Application

### ISSUE THREAD

**Issue by hardikSinghBehl** [jiahaog/nativefier#1026]
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [ ] I searched existing issues, open & closed. Yes, my question is new.
- [ ] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Your question**

I have converted my Web App running locally for now to Desktop App, It Consumes Spotify's API, when the user clicks "get started" button on my website, a new window is opened on chrome browser in which the user has to provide his spotify accounts credentials and Provide Authorization to My App, On Providing the authorization, it redirects to my web app on the chrome browser and not to the desktop application, i am only able to click the "Get Started" button from desktop application, you can find my web app in github account, How can i make this work

**Steps to reproduce**

```
C:\Users\josen>nativefier -p windows -a x64 http://localhost:8080
Cannot automatically retrieve the app icon: Error: write EPROTO 184432:error:1408F10B:SSL routines:ssl3_get_record:wrong
version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16) {
errno: 'EPROTO',
code: 'EPROTO',
syscall: 'write'
}

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform win32 x64 using electron v9.2.0

Finalizing build...
```

**Context**
Nativefier 9.2.0
Node 12.18.2
Npm 6.14.5
OS windows 10

**Comment by ronjouch** [comment]
@hardikSinghBehl you must pass an `--internal-urls` flag, so that the auth page loads inside Nativefier. See https://github.com/jiahaog/nativefier/blob/master/docs/api.md#internal-urls
