### ISSUE TITLE
dynamic url port

### ISSUE THREAD

**Issue by jjgalvez** [jiahaog/nativefier#1027]
I'm using nativefiyer to create the front end for a desktop app which is run from a local server. I'd like the port its served on to be randomly determined with I start it, how can I pass that to electron so that it can point to the correct url?
My server is running off of python quart, not that it would make much difference, but I start the server and then start electron. closing electron signals that I can kill the server
thanks

**Comment by jjgalvez** [comment]
would love to see an official option for this, but at the moment I am creating the app using localhost and then using sed to replace options.targetUrl with "http://localhost:"+porcess.env.port.  obviously I am setting the environment variable before starting app. Works on linux (arch specifically) going to see how it works on windows

**Comment by ronjouch** [comment]
> would love to see an official option for this, but at the moment I am creating the app using localhost and then using sed to replace options.targetUrl with "[http://localhost:"+porcess.env.port](http://localhost:%22+porcess.env.port). obviously I am setting the environment variable before starting app

@jjgalvez 👍, this seems totally reasonable, as your server has knowledge of A. the port, and B. where the option file lives, so your server is the right place to do what you want, not Nativefier.

I don't see how a new Nativefier option would work, and it's so niche I think I'd rather not have the feature in. With that, closing.

**Comment by jjgalvez** [comment]
Fare enough, thanks for keeping nativefier working, its a great app,
