### ISSUE TITLE
simple video showing how to run nativefier apps on ubuntu 20.04

### ISSUE THREAD

**Issue by pleabargain** [jiahaog/nativefier#1029]
simple video showing how to run nativefier apps on ubuntu 20.04
Here's the video
https://youtu.be/SRAbfP7_CiA

It took me nearly 1 hour to figure out how to open the app :( 

cd into directory
./NAMEOFAPP

This doesn't cover how to create desktop or app links though.

**Comment by ronjouch** [comment]
@pleabargain thanks for the suggestion. Fixed, here is what it looks like under Linux now:

```
App built to <...> , move it wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for"linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
```
