### ISSUE TITLE
want to use apple icloud keychain with apps -- would there be a way to use safari instead of chromium as backend?

### ISSUE THREAD

**Issue by jamesfranklinnetsec** [jiahaog/nativefier#1030]
title is the description.

**Comment by ronjouch** [comment]
Hi. Nativefier is entirely based off Electron and there is no plan to move off it. I know other similar apps use the Safari engine, give them a try.

**Comment by gingerbeardman** [comment]
Even using WebKit, I don't believe macOS allows Keychain autofill for that use case.
