### ISSUE TITLE
Is Nativefier App Self Contained

### ISSUE THREAD

**Issue by waltder** [jiahaog/nativefier#1034]
**Homework**

- [x ] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [ x] I searched existing issues, open & closed. Yes, my question is new.
- [ ] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Your question**
I see that nativefier includes several dlls and folders after nativefier command is ran.
What dependencies does a Nativefier app have on a user's PC?
Is everything Nativefier/Electron needs encapsulated into final executable and folder structure?

Specifications
Version of Nativefier (run $ nativefier --version): v8.0.6
Version of Node.js (run $ node --version): v12.9.1
OS: Windows 10
Architecture 64bit

**Comment by ronjouch** [comment]
> Is everything Nativefier/Electron needs encapsulated into final executable and folder structure?

Yes. The output folder is static/self-contained, you can move it around, it will run.

**Comment by waltder** [comment]
Thanks @ronjouch 

What I need to know if this self contained app reaches out to other dlls/files outside of the self contained folder?

**Comment by ronjouch** [comment]
> What I need to know if this self contained app reaches out to other dlls/files outside of the self contained folder?

@waltder I know that Electron bundles are "quite very static", but yes it will use a few external DLLs. Run `ldd` (or the windows equivalent) on the executable to know.

**Comment by waltder** [comment]
@ronjouch Thanks!
