### ISSUE TITLE
Error: EACCES: permission denied, mkdir 'nativefier/linux-x64-template'.

### ISSUE THREAD

**Issue by Jalr4ever** [jiahaog/nativefier#1035]
Hi, Developer guys:

I just found that when I executed nativefier by docker, which its image constructed by jiahaog, it appeared permission denied bug，how to deal with this bug ?

Running Platform:

- CentOS 7

- Docker Lasted 2020-8-27

Bug Info:

![image](https://user-images.githubusercontent.com/23929139/91381247-85a2e500-e859-11ea-946a-759c912c353e.png)

**Comment by wunderdojo** [comment]
Ran into the same issue. The npm version did work for me.

**Comment by Jalr4ever** [comment]
> Ran into the same issue. The npm version did work for me.

Guys, I found that it's about privilege

So finally we just did things like: `chomod -R 777 nati-apps` , which work for this issue.
