### ISSUE TITLE
[MAC] Swipe for page navigation not present

### ISSUE THREAD

**Issue by mhuusko5** [jiahaog/nativefier#104]
Title says it. Would *love* to be able to use trackpad swipes for navigation like in Safari/Chrome.

**Comment by jiahaog** [comment]
Yeap, I do agree that it'll be great, would someone like to give this a go?

**Comment by BugiDev** [comment]
As a help reference to anyone working on this, guys from N1 already added solution for this to Electron. https://github.com/atom/electron/pull/4181

**Comment by jiahaog** [comment]
This is an underlying feature for electron, which will be automatically added once they have implemented it.
