### ISSUE TITLE
invalid guest id when i try to login my website using google

### ISSUE THREAD

**Issue by abdullah4one** [jiahaog/nativefier#1043]
In my website i added google login and when user click on google login it showing 
`invalid guest id`
after few try now it is showing as `Access denied to guestId: 4  Dismiss`

**Comment by ronjouch** [comment]
Closing as incomplete. Please provide the information requested by the [bug report template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and I will re-open.
