### ISSUE TITLE
Build for Cordova

### ISSUE THREAD

**Issue by ssshake** [jiahaog/nativefier#1047]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [X] I searched existing issues, open & closed. Yes, my feature request is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Problem statement**

Nativefier should support Cordova as a build target WITH non-ssl support so that I can make use of this awesome package on my phone, to connect to local web services on my network.

**Context**

 - OS: Android && iOS

Besides the ease of use, what I love immediately about nativefier is that it supports non-ssl connections. This is really important for rolling custom/personal-use application for LAN devices which do not have SSL. 

One example is Octoprint for my 3D printer. This is a very popular product. It runs on your local network. I made a desktop app for it using this package and the results were great. 

However for mobile I have tried to hand roll a cordova package but I cannot seem to find a way to get around the requirement of SSL to connect to this service.

Your packages seems to have figured that out for electron. I'm hoping you know how to do the same for cordova. 

One use case is making custom home automation / iot devices using an ESP8266. It is so easy and convenient to make products using this device. But once again it does not have SSL support, and when on a local area network there's no convenient way to get a signed cert for each device. 

Because of this it's not easy (maybe not possible) to make an iphone app to connect to these iot devices. The alternative is opening safari/chrome and navigating to the devices IP.

**Comment by ronjouch** [comment]
As I was closing https://github.com/jiahaog/nativefier/issues/1098 , closing this one too.

This is extremely improbable, so remote and different that it would be a different project. With that, closing.
