### ISSUE TITLE
This is amazing. Is it possible to generate an entire working app source code with all the script to build package and installers

### ISSUE THREAD

**Issue by grandtiger** [jiahaog/nativefier#105]
I found this last week, and I was very impressed. Then today I ran into an issue with my simple Electron prototype app, where the app run a batch file on windows to start up a local web sever on a specified port, and then the electron app load the URL from localhost:port. However, I kept getting some weird error from the Electron app, whereas directly loading the same page on Firefox or IE11 works fine. I then tried nativefier using localhost:port, the app created works just fine. This makes me wonder what exactly went wrong. It would be super helpful if I can compare the source code generated by nativefier vs my own code.

Is this something possible today? If so, please advise how to do it, otherwise, could you please consider adding this feature in the future? Thanks a lot! I am a newbie in web technology stack and still have a lot to learn, otherwise, I could have mess around with the source code and debug through the steps. But I couldn't even get passed the "npm run dev-up" step. I got the following error on windows server 2012:
```
C:\GitHub\nativefier>npm run dev-up

> nativefier@6.7.0 dev-up C:\GitHub\nativefier
> npm install && (cd app && npm install) && npm run build

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN nativefier-placeholder@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\f401036\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\
npm-cli.js" "run" "build"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.3

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitHub\nativefier\app\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\f401036\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\
npm-cli.js" "run" "dev-up"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! nativefier@6.7.0 dev-up: `npm install && (cd app && npm install) && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativefier@6.7.0 dev-up script 'npm install && (cd app && npm install) && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativefier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && (cd app && npm install) && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativefier
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nativefier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitHub\nativefier\npm-debug.log
```
[npm-debug-log.txt](https://github.com/jiahaog/nativefier/files/110069/npm-debug-log.txt)

**Comment by jiahaog** [comment]
Hey there, I'm afraid I don't really understand what are you requesting for. Could you provide me with the following:

> Version of Nativefier (run $ nativefier --version)
Version of Node.js (run $ node --version)
Command line parameters
OS and architecture you are running Nativefier from
Stack trace from the error message (if any)
Instructions to reproduce the issue

I'll also look into why `npm run dev-up` is not working, it seems to be working fine for me.

**Comment by zweicoder** [comment]
@grandtiger The source code that you want is actually inside the `<packaged_app_dir>/resources/app/src/main.js`. Good luck!

**Comment by grandtiger** [comment]
@jiahaog I'll provide you the information first thing on next Monday from work. I tried using my home laptop, and I got similar errors as shown below. The environments are slightly different between the two PCs. I have problem with "npm run dev-up" only, Nativefier is working fine. I am looking for enhancement.

Here is what I get at home:

- Version of Nativefier: 6.8.0
- Version of Node.js: v5.4.1
- Command line parameters: npm run dev-up
- OS: Windows 7 and Windows Server 2012
- Just type "npm run dev-up" in the nativefier github source repo to reproduce the following error.

```
npm WARN EPACKAGEJSON nativefier-placeholder@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! missing script: build
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GitHub\nativefier\app\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "dev-up"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! nativefier@6.8.0 dev-up: `npm install && (cd app && npm install) && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativefier@6.8.0 dev-up script 'npm install && (cd app && npm install) && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativefier package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && (cd app && npm install) && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls nativefier
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GitHub\nativefier\npm-debug.log
```

**Comment by grandtiger** [comment]
@zweicoder Thanks a lot! I did try looking at the code inside that directory and managed to fixed my error. But I am not able to take the source code from the directory to build an entire working Electron app though. Coming from different technology background, I have a lot to learn to get my head around in the Node.js/JavaScript world. Thanks again for your help and have a great weekend!

**Comment by jiahaog** [comment]
Windows is the problem here in building for development. Please do the following instead of `npm run dev-up` as a temporary workaround.

```
git clone https://github.com/jiahaog/nativefier.git
cd nativefier
npm install
cd app
npm install
cd ..
npm run build
```

Apparently the issue is this line which defines `npm run dev-up` in the `package.json` `scripts` which not supported on windows. Sigh.

```
"dev-up": "npm install && (cd app && npm install) && npm run build",
```
