### ISSUE TITLE
Deep linking

### ISSUE THREAD

**Issue by SubMGRru** [jiahaog/nativefier#1051]
I have studied the API documentation for a long time, but alas, I have not found information on using deeplinking, but judging by other Issues, this issue was raised.  Is this function present?  If so, how to use it.  Thanks.

**Comment by ronjouch** [comment]
What do you mean by deep linking?

Which other issues?

People don't read your mind, please add a bit of detail.

**Comment by SubMGRru** [comment]
I mean links (deeplink, App Protocol), upon clicking on which the application will be launched.  Example: github:// When you click on this link, the corresponding application will open in the browser

**Comment by ronjouch** [comment]
> I mean links (deeplink, App Protocol), upon clicking on which the application will be launched. Example: github:// When you click on this link, the corresponding application will open in the browser

👍. As you mentioned, yeah there are existing issues for that: https://github.com/jiahaog/nativefier/issues/405 , https://github.com/jiahaog/nativefier/issues/574 . Closing as duplicate.
