### ISSUE TITLE
How do you install apllication

### ISSUE THREAD

**Issue by notrealsynapse** [jiahaog/nativefier#1055]
I am not sure how to download Nativefier

**Comment by austin-engle** [comment]
All the information needed is in the readMe. They have instruction on how to install it with node

**Comment by ronjouch** [comment]
@austin-engle thanks for pointing to the readme 🙂.

@notrealsynapse if you're still unable to install & use Nativefier after reading the README, please chime in here with details of what's unclear, I'll update the README.

With that, closing.
