### ISSUE TITLE
Add flag to enable / disable loading spinner

### ISSUE THREAD

**Issue by bjoernm** [jiahaog/nativefier#106]
It would be great to have a boolean flag to enable / disable the loading spinner at the start of the app. This would be helpful for if you package web apps that have implemented their own loading spinner. In this case, two different loading spinners are shown after each other.

**Comment by jiahaog** [comment]
Hi, what version of nativefier are you using? I believe that in the later versions I have disabled the preset loading spinner completely due to a change in how the target page is loaded.

**Comment by bjoernm** [comment]
I just updated nativefier and the loading spinner is gone. Thanks for the fast reply!
