### ISSUE TITLE
How can I double click a tray icon to open application

### ISSUE THREAD

**Issue by Walkerby** [jiahaog/nativefier#1069]
I'm using gnome. And I found I couldn't open the nativefiered app by double clicking it like other apps.

**Comment by ronjouch** [comment]
Hi @Walkerby . Please read the message you got at the end of building your Nativefier app:

> Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
