### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by c00kie55** [jiahaog/nativefier#1070]
i have made a app but it takes like 10 seconds to open the webpage i would like to have a background image or a gif while loading
i have tried to inject a custom css. but its not working.

//custom.css
body { background-image url("image.png")

navifier --name "test" --inject custom.css "https:/test.com"

**Comment by ronjouch** [comment]
Hi @c00kie55 . This is not supported; indeed the custom CSS will not be applied at the early time of loading.

**Comment by MX-Qulin** [comment]
have you found the solution?



At 2020-11-16 20:22:46, "c00kie55" <notifications@github.com> wrote:

i have made a app but it takes like 10 seconds to open the webpage i would like to have a background image or a gif while loading
i have tried to inject a custom css. but its not working.

//custom.css
body { background-image url("image.png")

navifier --name "test" --inject custom.css "https:/test.com"

**Comment by MX-Qulin** [comment]
@ronjouch could you please add that? it's not good to show white screen for a long time.
