### ISSUE TITLE
What to do next?

### ISSUE THREAD

**Issue by SparkScrach-P** [jiahaog/nativefier#1071]
**My question**

I have extracted it's .zip on my PC. I have node.js 15.0.1 installed in my system.What to do next,type the given code in node?If yes,what is the application of This there/?

**Comment by ronjouch** [comment]
@SparkScrach-P hi. There's nothing to do with a .zip. You seem unfamiliar to npm, please search a bit on how to use it on your OS of choice. Then see https://github.com/jiahaog/nativefier#installation and https://github.com/jiahaog/nativefier#usage .

**Comment by SparkScrach-P** [comment]
### thanks
