### ISSUE TITLE
Google doesn't like you

### ISSUE THREAD

**Issue by hrdwdmrbl** [jiahaog/nativefier#1075]
![Screen Shot 2020-11-24 at 18 43 59](https://user-images.githubusercontent.com/554881/100164210-6a119f80-2e85-11eb-9709-0c47dc3a87cf.png)
pi.md

**Comment by kiprasmel** [comment]
there's an open pinned issue with a workaround available:

https://github.com/jiahaog/nativefier/issues/831#issuecomment-563997663

**Comment by ronjouch** [comment]
> there's an open pinned issue with a workaround available: [#831 (comment)](https://github.com/jiahaog/nativefier/issues/831#issuecomment-563997663)

Yup. Thanks @kiprasmel ! Closing.
