### ISSUE TITLE
Is there a way to change the name of an audio output stream?

### ISSUE THREAD

**Issue by luvicsoura** [jiahaog/nativefier#1081]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

Is there a way for me to change the name of audio output streams? I'd like to be able to list my webapps with their respective names under the inputs section on POP!_OS, instead of "Playback - Chromium".

**Comment by sorhtyre** [comment]
On Linux (specifically Debian variants), this is hardcoded into PulseAudio to take the name from the underlying app. In this case, it comes from the chromium built by [Electron](https://github.com/electron/electron). You would need to custom build Electron with a new internal name before building your Nativefier app for each app.
