### ISSUE TITLE
start-in-tray + maximize parameters do not work well together

### ISSUE THREAD

**Issue by vinifmor** [jiahaog/nativefier#1082]
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [X] I searched existing issues, open & closed. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

When you set `--tray=start-in-tray` and `maximize` parameters, the app will launch maximized instead of just minimized on the system tray.

**Steps to reproduce**

Command used to create: `nativefier https://slack.com/intl/en-br --name slack /home/user/.local/share/bauh/web/installed/slack --single-instance --maximize --internal-urls=.* --tray=start-in-tray`

**Expected behavior**

The app icon starts attached to the sytem tray and when you click on it, it would launch the app maximized.

**Actual behavior**

App icon starts attached to the tray and the window is opened maximized at the same time.

**Context**

 - Nativefier: 7.7.1 -> 11.0.2
 - Node.js: 12.18 and 14.15.1
 - Npm: 6.14.8
 - OS: ArchLinux
 - Is it a regression? Exists since 7.7.1

**Comment by ronjouch** [comment]
@vinifmor today is your lucky day 🙂, this was fixed in https://github.com/jiahaog/nativefier/pull/1079 , which will be released soon, probably this weekend or the one after. Closing.

**Comment by vinifmor** [comment]
haha great ! Thanks @ronjouch
