### ISSUE TITLE
Window location not setable due invalid argument (long / short option)

### ISSUE THREAD

**Issue by codekandis** [jiahaog/nativefier#1084]
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [X] I searched existing issues, open & closed. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Bug description**

The application location cannot be set with options neither `--x` and `--y`

```none
Invalid argument passed: --x .
Nativefier supports short options (like "-n") and long options (like "--name"), all lowercase. Run "nativefier --help" for help.
Aborting
```

nor `-x` and `-y`.

```none
error: unknown option '-x'
```

**Steps to reproduce**

```none
nativefier foobar https://google.com --x 10 --y 10
```

**Expected behavior**

The location will be set or a short and long option will be available.

**Context**

 - Nativefier: 42.0.1
 - Node.js: 14.15.1
 - Npm: 6.14.9
 - OS: (for example: Windows 10 build 1809)
 - Is it a regression? yes - last working 11.0.2

**Comment by ronjouch** [comment]
@codekandis thaaaanks for the fast and precise report! Fixed in 42.0.2, available now in npm.

**Comment by codekandis** [comment]
You're sooo much welcome! I really appreciate your hard work on it and I really like what I get from it!

I can confirm the options are working now. I'd suggest to change the old options `--x` and `--y` to the short options `-x` and `-y` to become strict with all other options. In conclusion you'd need to introduce the new long options `--x-position` and `y-position` in the next major release.

**Comment by ronjouch** [comment]
> I'd suggest to change the old options `--x` and `--y` to the short options `-x` and `-y` to become strict with all other options. In conclusion you'd need to introduce the new long options `--x-position` and `y-position` in the next major release

@codekandis nope, won't do that, because holy backwards compatibility. I do my best to preserve it, so I prefer a little inconsistency of [a special case tested by a unit test](https://github.com/jiahaog/nativefier/commit/7fd0c748ba18240d7a29f37a2bd290652fb5d097) over annoying users.

**Comment by codekandis** [comment]
Beside my suggestion I totally agree with that.
