### ISSUE TITLE
How to inject css into a application

### ISSUE THREAD

**Issue by idgafidc** [jiahaog/nativefier#1086]
**Homework**

- [ ] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [ ] I searched existing issues, open & closed. Yes, my question is new.
- [ ] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

See so I made a game website called krunker.io into a client, but i want to inject my own css into the application. How do I accomplish this? Thank you

*

**Comment by mattruzzi** [comment]
https://github.com/jiahaog/nativefier/blob/master/docs/api.md#inject

**Comment by ronjouch** [comment]
Thanks @mattruzzi !

@idgafidc as pointed out by @mattruzzi , this is already documented. Please give it a try, and if documentation is unclear, chime in here and we'll improve the documentation.
