### ISSUE TITLE
whatsapp-nativefier works with chrome 60+

### ISSUE THREAD

**Issue by samueleisalinuxuser** [jiahaog/nativefier#1097]
Hi there, I get the problem above after updating `whatsapp-nativefier` from [this AUR](https://aur.archlinux.org/packages/whatsapp-nativefier/) with `makepkg -i`.
I also tried to reinstall `nodejs nodejs-nativefier whatsapp-nativefier` (as some time ago I get the same error but I solved it by reinstalling all the packages).

----

Operating System: Arch Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.6-arch1-1
OS Type: 64-bit

**Comment by ronjouch** [comment]
Hi @samueleisalinuxuser, thanks for the feedback.

This is #719, closing as duplicate, feel free to ask there for help. From what I see of your AUR package pkgbuild and injected files, it already has the workaround mentioned at https://github.com/jiahaog/nativefier/issues/719#issuecomment-672546866 , so maybe WhatsApp changed things recently and more working around is needed. You should ask at #719, that's where you'll reach people knowledgeable about this problem.

---

Side note: [WhatsApp is changing their terms of use](https://www.bloomberg.com/news/articles/2021-01-11/why-whatsapp-s-privacy-rules-sparked-moves-to-rivals-quicktake), paving the way to data collection and ad targeting by Facebook. Maybe it's time to consider another app.

**Comment by samueleisalinuxuser** [comment]
> Hi @samueleisalinuxuser, thanks for the feedback.
> 
> This is #719, closing as duplicate, feel free to ask there for help. From what I see of your AUR package pkgbuild and injected files, it already has the workaround mentioned at [#719 (comment)](https://github.com/jiahaog/nativefier/issues/719#issuecomment-672546866) , so maybe WhatsApp changed things recently and more working around is needed. You should ask at #719, that's where you'll reach people knowledgeable about this problem.
> 
> Side note: [WhatsApp is changing their terms of use](https://www.bloomberg.com/news/articles/2021-01-11/why-whatsapp-s-privacy-rules-sparked-moves-to-rivals-quicktake), paving the way to data collection and ad targeting by Facebook. Maybe it's time to consider another messaging app.

Ok, thanks a lot, I switched to Telegram years ago, but unfortunately most of my contacts still use whatsapp and that makes me have to use it :( .
