### ISSUE TITLE
WhatsApp Web

### ISSUE THREAD

**Issue by jiahaog** [jiahaog/nativefier#11]
WhatsApp web now seems to be checking for user agent strings. By manipulating the user agent, we are still able to access it.

```bash
$ nativefier --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36" web.whatsapp.com 
```

I'm not sure if such a user agent should be a default parameter in all wrapped apps, it would be certainly a lot easier to use in that case as we can ommit that long `--user-agent` parameter.

**Comment by gabrihellmateus** [comment]
+1

**Comment by bevenky** [comment]
+1
