### ISSUE TITLE
Widevine support

### ISSUE THREAD

**Issue by Anakros** [jiahaog/nativefier#113]
Hello. I want to build the Netflix app.
I edited `./node_modules/nativefier/app/lib/main.js` and inserted the following code after the line 90 as described in https://github.com/atom/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md, but it doesn't work (no active plugins in navigator.plugins output in webtools console and Netflix still want me to enable Widevine). When I build the app, it doesn't output some errors.

```
app.commandLine.appendSwitch('widevine-cdm-path', '/Users/xxx/projects/temp/widevinecdmadapter.plugin');
// The version of plugin can be got from `chrome://plugins` page in Chrome.
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.866');
```

Any ideas, please?
Sorry for bad English.

**Comment by jiahaog** [comment]
I believe documentation has been added here: atom/electron#3961, it'll be great if you could implement this in and make a pull request!

**Comment by jiahaog** [comment]
The current version of electron (0.36.x) runs on chrome 47, while the public release of electron is chrome 48. I am unable to simply reference the plugin file directly because the plugin needs to be built for the same version of chrome, and I don't really want to bundle the plugin binary directly in nativefier as an npm module.

That being said, I also don't have access to the widevine plugin for chrome 47, it'll be nice if someone could provide this (for windows, mac and linux) so that some progress can be made to determine if there is even a solution if the plugin is bundled.

**Comment by pascalwhoop** [comment]
was this issue solved or just mistakenly closed during an issue cleanup? Afaik widevinecdm is still not working correctly

**Comment by jiahaog** [comment]
It's not working but I've left the future tag for anyone who wishes to work on it!

**Comment by spencerthayer** [comment]
Has there been any progress on this issue?

**Comment by trobotham** [comment]
^^ It would be awesome to have a separate Netflix app, it is unfortunate that Widevine doess not work.

**Comment by quanglam2807** [comment]
@Anakros @pascalwhoop @spencerthayer @trobotham It has been fixed in WebCatalog webcatalog/desktop#4

**Comment by spencerthayer** [comment]
@quanglam2807 I had no idea WebCatalog existed. Great!

**Comment by mikhoul** [comment]
I'm new with nativefier and I had the same problem with  Spotify, browsing the issue **I think it was fixed** but is have to be approved before going in the main branch: https://github.com/jiahaog/nativefier/pull/440 

Sorry if I'm a newbie with github terms,

Regards :octocat:

**Comment by brunolemos** [comment]
:(

**Comment by ryanmusante** [comment]
I have tried with latest nativefier build and widevine and it is not working.

**Comment by klemy** [comment]
Hello,

I have try today with the latest version and Netflix does now work either. Same as @ryanmusante
