### ISSUE TITLE
Opening links in the same site in tabs

### ISSUE THREAD

**Issue by simonweil** [jiahaog/nativefier#116]
Hi,
Thanks for this great app and all the updates and fixes!

Is it possible to open pages for the same domains in different tabs?

For example:
- In gmail, clicking `d` should open the new message in a new tab
- In JIRA I'd like to open links in new tabs (via context menu would be great

**Comment by wodow** [comment]
+1 This is something [Fluid](http://fluidapp.com) can do.

**Comment by AdrianoCahete** [comment]
+!

**Comment by jiahaog** [comment]
This is referenced in #23

**Comment by wodow** [comment]
@jiahaog , is this not a different issue/request? #23 refers to external links and this refers to internal links (same site/subdomain). We could have one without the other.

**Comment by paularmstrong** [comment]
Can we reopen this? Seems like it was closed incorrectly. This is a feature request for tabs in the same window, just like a normal browser is able to do.

**Comment by svenyonson** [comment]
Looks like this might be possible using the electron-tabs package. I'd be happy with the addition of a File menu ( File->New Window, File->New Tab )
