### ISSUE TITLE
Hi i have a problem with node.js and nativefier

### ISSUE THREAD

**Issue by markazie** [jiahaog/nativefier#117]
when type this command in node.js:
$ nativefier "http://example.com.com"
or
$ nativefier maps.google.com
i get this error :
SyntaxError: Unexpected indentifier
at Object.exports.createScript (vm.js:24:10)
at REPLServer.defaultEval (repl.js:225:25)
at bound (domain.js:287:14)
at REPLServer.runBound as eval
at REPLServer. (repl.js:417:12)
at emitOne (events.js:82:20)
at REPLServer.emit (events.js:169:7)
at REPLServer.Interface._onLine (readline.js:210:10)
at REPLServer.Interface._line (readline.js:549:8)
at REPLServer.Interface._ttyWrite (readline.js:826:14)

Please help to solve this issue.

BR

**Comment by rosolko** [comment]
@markazie What version of nodejs do you use?

**Comment by markazie** [comment]
hi

**Comment by markazie** [comment]
@rosolko 
node -v = v4.2.6
npm -v = 3.6.0

**Comment by rosolko** [comment]
@markazie Can you try to update nodejs to v5 and try to use nativefier again?

**Comment by markazie** [comment]
@rosolko  How can i update 4.2.6 to 5 ???
I think, I download latest version from 
https://nodejs.org/en/download/

**Comment by rosolko** [comment]
@markazie You can use [package manager](https://nodejs.org/en/download/package-manager/) for this

**Comment by markazie** [comment]
@rosolko  You mean v5.5.0 Stable ????

**Comment by rosolko** [comment]
@markazie Yes. On a site just switch from LTS to Stable releases.
![att_47](https://cloud.githubusercontent.com/assets/11458319/12748180/ba9656c0-c9b9-11e5-9aa1-80b223086f99.png)

**Comment by markazie** [comment]
@rosolko  yes, I download this version now and check again. I have same error.

**Comment by markazie** [comment]
@rosolko 
![node](https://cloud.githubusercontent.com/assets/16987161/12748238/43fe464e-c9be-11e5-8923-7dcc2eefee4d.jpg)

**Comment by rosolko** [comment]
@markazie Do you try to start console as admin?
When i using previous version of nativefier on ubuntu - required condition was `sudo` appender.
It can be also aplicable for windows.

**Comment by markazie** [comment]
@rosolko yes this is run as admin
![node1](https://cloud.githubusercontent.com/assets/16987161/12748374/10f15592-c9bf-11e5-9adb-25e9c4fbe02c.jpg)

**Comment by rosolko** [comment]
@markazie Oh, `sudo` its for *nix like systems. As I unerstand using brackets `nativefier "<url>"` isn't resolve problem?

**Comment by markazie** [comment]
@rosolko  no, nativefier "url" isn't work.

**Comment by rosolko** [comment]
@markazie As sad stackoverflow:

> Try to use without executing `node`, just execute `node module.js`.

In this case: Add nodejs to env variables and try to use from admin cmd:
`node nativefier "<url>"`

**Comment by markazie** [comment]
@rosolko  If you mean like this, this is result
![cmd](https://cloud.githubusercontent.com/assets/16987161/12748609/a13f6282-c9c0-11e5-905c-de1d3b4b97f2.jpg)

**Comment by rosolko** [comment]
What is the target installatio directory for nativefier?
Seems like nodejs cant find nativefier.

**Comment by markazie** [comment]
@rosolko I think i don't have nativefier, and when i want to use this command for install nativefier; this is result
![native](https://cloud.githubusercontent.com/assets/16987161/12748713/59681fb6-c9c1-11e5-805e-1ed7179ea078.jpg)

**Comment by markazie** [comment]
@rosolko Sorry i think i should be say again "I'm Beginner"
Now i think this is my problem, I don't have nativefier package.
Right?
If yes, how can i install it. As you see that is error for install command.

**Comment by markazie** [comment]
@rosolko 
I think i shall be fixing npm permissions
I follow this link : https://docs.npmjs.com/getting-started/fixing-npm-permissions
But this command is not work for me too:
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

**Comment by rosolko** [comment]
Install nativefier using command:
`npm install nativefier -g` if you're in the node

**Comment by rosolko** [comment]
@markazie In this case for first init nodejs console as you do previously and after that use npm for install package

**Comment by markazie** [comment]
@rosolko yes as you see in above picture i'll install package but have error

**Comment by rosolko** [comment]
@markazie But you try to install package from windows cmd not from nodejs cmd

**Comment by jiahaog** [comment]
@markazie Hi there, you have to run `npm install nativefier -g` while you are in your command prompt, and not when you are in the node.js REPL. This means that you open a command prompt (as per the instructions [here](http://windows.microsoft.com/en-sg/windows-vista/open-a-command-prompt-window)) and Node.js installed, you type `npm install nativefier -g` into the prompt that appears. Hope that helps!

**Comment by markazie** [comment]
@jiahaog  @rosolko
Hi, yes try to install package from windows cmd because in node.js i have error for this command.
This is result in node.js:
![nodejs](https://cloud.githubusercontent.com/assets/16987161/12808248/a0ba3330-cb2a-11e5-85cd-823846ed9fbb.jpg)

**Comment by rosolko** [comment]
@markazie inside node use `npm install nativefier -g`

**Comment by jiahaog** [comment]
You're not doing it correctly! You're running the command in the node.js command prompt instead of your windows command prompt. What you want to do is follow these steps exactly

1. Press windows key + r on your keyboard
2. Type `npm install nativefier -g`
3. Press enter

Nativefier should be installed now

**Comment by markazie** [comment]
@jiahaog
Hi
I try this too, But same error. 
Windows_NT 6.1.7601
![nodejs](https://cloud.githubusercontent.com/assets/16987161/12808248/a0ba3330-cb2a-11e5-85cd-823846ed9fbb.jpg)

**Comment by jiahaog** [comment]
This is a problem with npm itself. Some googling has led to https://github.com/npm/npm/issues/10897 but I'm not entirely sure how to resolve it.

**Comment by markazie** [comment]
@jiahaog 
Thank you very much Dear Jiahaog
This solution solve my problem.
many thanks.
now i want to create first app for test so use this command like help file
nativefier maps.google.com
app created but when i want to run it i have this error
![maps](https://cloud.githubusercontent.com/assets/16987161/13323578/568b6d26-dbef-11e5-9e0c-c1cc4c2b77a6.jpg)
Please help.
BR

**Comment by jiahaog** [comment]
I've fixed this bug in `6.10.1`, please update and try again!

**Comment by markazie** [comment]
@jiahaog 
Thanks, Fix it.
How can i make a app for android and ios ?

BR

**Comment by jiahaog** [comment]
You can't, nativefier is for osx, windows and linux only.

**Comment by markazie** [comment]
@jiahaog 
Thanks
i have a question
after create app for example for windows, we have many file and folders
How can i change them to one .exe portable file without install need.

**Comment by jiahaog** [comment]
It's not supported now, this was proposed in #83 as well
