### ISSUE TITLE
Custom userscripts and stylesheets [feature request]

### ISSUE THREAD

**Issue by ankushg** [jiahaog/nativefier#12]
It could be nice to be able to customize these for certain websites

**Comment by jdsimcoe** [comment]
@jiahaog I totally agree... see my comment here on being able to customize link behavior: https://github.com/jiahaog/nativefier/issues/23#issuecomment-173688731

**Comment by jdsimcoe** [comment]
@jiahaog I actually solved it for Figma by modifying code in `index.js`:

```js
webView.addEventListener('new-window', function (e) {
  webView.src = e.url;
});
```

**Comment by SethCalkins** [comment]
@jdsimcoe I don't see where you solved this?... How do I add custom user script and stylesheets ? I'm on OS X ... 

Do I have to pass a cli option? 
Do I add a folder to the Nativerfier_Package.app ? 
Do I edit the existing ../../MyNativefierApp.app/Contents/Resources/app/lib/main.js ?

**Comment by jiahaog** [comment]
This can be implemented in the near future, I believe @zweicoder is working on it!

**Comment by MattiSG** [comment]
+1

**Comment by jiahaog** [comment]
@MattiSG this has already been implemented since 6.10.0!

**Comment by MattiSG** [comment]
I guess through the [`--inject`](https://github.com/jiahaog/nativefier/blob/development/docs/api.md#inject) option? I searched for "user script" throughout the codebase and found only this issue, which was closed without mentioning resolution status  :wink:

Thanks!

**Comment by jiahaog** [comment]
Yup, sorry about the confusion!

**Comment by cryogenx** [comment]
so what would be the process for injecting a user script

**Comment by nemethit** [comment]
4 years later and no response?!
