### ISSUE TITLE
TypeError: nativefier is not a function

### ISSUE THREAD

**Issue by miduga** [jiahaog/nativefier#120]
Steps to reproduce:

`~ npm install --save nativefier`

Copying example of using nativefier as module. Executing:

```index.js:25
nativefier(options, function(error, appPath) {
^
TypeError: nativefier is not a function
    at Object.<anonymous> (/Users/miguel/desarrollo/hubii-nativefier/index.js:25:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

`node -v -> 5.5.0`
`npm -v -> 3.6.0`

**Comment by miduga** [comment]
I'm thinking if that has something to do with the fact that I've already nativefier installed as a global package...

**Comment by miduga** [comment]
`node -v -> 5.5.0`
`npm -v -> 3.6.0`

**Comment by jiahaog** [comment]
Sorry about the late reply, I've been quite busy with school nowadays. Could you try the following:

```javascript
// note the `default`
var nativefier = require('nativefier').default;

nativefier({}, function(error) {
	console.log(error);
});
```

I believe the problem is due to the way I've exported the modules (written in ES6 and compiled to ES5 before being pushed to npm with Babel) which breaks compatibility with `require`. I need to read up more about this, could you try this workaround first?

**Comment by miduga** [comment]
Yeah, that's it. :+1:

**Comment by jiahaog** [comment]
This is related to https://phabricator.babeljs.io/T2212, I might add a babel plugin or something to fix the ugly `.default` syntax. Not sure what the rationale for why they killed it is though :/

**Comment by miduga** [comment]
Sadly, I'm not an expert with babel but you might add this plugin: https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by jiahaog** [comment]
Yup! I'll just update the docs now to use the `.default`
