### ISSUE TITLE
Shortcuts for back/forward navigation does not show up

### ISSUE THREAD

**Issue by jottr** [jiahaog/nativefier#121]
When trying to navigate back/forward, it is not possible to use `Command-Left`/`Command-Right` shortcuts, as one would in Chrome. 
Currently back/forward navigation has to be done by using the menubars view menu.

**Comment by krishkumar** [comment]
I added the shortcuts last week and it was working fine. 

https://github.com/jiahaog/nativefier/commit/8041663d828db844eac619a69d02a1bb0b06bb09

Are the shortcuts not working for you? What version of nativefier are you on?

**Comment by jottr** [comment]
I'm on `6.8.0`. `Command-Left/Right` do not work. 
As per your referred commit it seems that you implemented it so that `Ctrl-[` or `Cmd-[` should go back in history, which also does not work for me. 
I've tried with nativefied youtube and gmail.

**Comment by jottr** [comment]
I just tested with soundcloud. Problem remains. 
Also, there is no means of telling the actual key binding:

<img width="456" alt="scl" src="https://cloud.githubusercontent.com/assets/2744198/12796447/12017434-cabf-11e5-8bc1-8a462826ab7c.png">

**Comment by michaelparenteau** [comment]
It would be rad if/when this is implemented that the trackpad gestures to go back and forward worked as well. I am a huge keyboard fan.. but there is some real convenience there when you are in a cursor movement mode to have the back/forward behavior baked into a gesture.

**Comment by krishkumar** [comment]
Thanks @jottr for the info. 

Yes the shortcuts don't seem to be working in the latest version 6.8.0. However they are working if I build the package locally. You can try that as a workaround.

**Comment by enypha** [comment]
I was able to rectify this by editing resources\app\lib\main.js. I used backspace and shift+backspace.
The result that is working looks like this:

```
label: 'View',
	        submenu: [{
	            label: 'Back',
                accelerator: 'BackSpace',
	            click: function click() {
	                onGoBack();
	            }
	        }, {
	            label: 'Forward',
                accelerator: 'Shift+BackSpace',
	            click: function click() {
	                onGoForward();
```

**Comment by adambair** [comment]
@enypha Very helpful -- thanks!

**Comment by adambair** [comment]
Also, it looks like this is already in the development branch but using these shortcuts: 

```
{
                    label: 'Back',
                    accelerator: 'CmdOrCtrl+[',
                    click: () => {
                        goBack();
                    }
                },
                {
                    label: 'Forward',
                    accelerator: 'CmdOrCtrl+]',
                    click: () => {
                        goForward();
                    }
                },

```

**Comment by jiahaog** [comment]
Please check if you are on the latest version of Nativefier, this has been added since `6.9.0`!

**Comment by adambair** [comment]
So yeah. I was all... I CAN PR THIS... checked out the source. And saw shortcuts had been added. My bad. :facepalm:

Hello Internet. If you're here for shortcuts for back and forward navigation for Nativefier -- it's was added in 6.9.0! (Silly me, thanks @jiahaog - hehe)

**Comment by jiahaog** [comment]
Yay awesome!

**Comment by adambair** [comment]
Cheers! Thanks for the awesome software :)
