### ISSUE TITLE
Disable or customize the right click menu

### ISSUE THREAD

**Issue by superandrew** [jiahaog/nativefier#122]
I think the right menu is not optional. In some webapp the right click menu is disabled in some scenarios. It would be useful to have an option to disable the production of the right click menu.
<img width="229" alt="img 2016-02-03 at 14 44 39" src="https://cloud.githubusercontent.com/assets/71364/12783963/b2efb3dc-ca84-11e5-836c-0d04c7c512d5.png">

**Comment by simonweil** [comment]
+1

In JIRA the context menu comes above JIRA's menu.

On the other hand on links (also in JIRA) I do need the context menu to open links or copy them (which currently is not available).
<img width="328" alt="screen shot 2016-02-04 at 12 10 06 am" src="https://cloud.githubusercontent.com/assets/2317562/12798736/b925e150-cad3-11e5-9044-3251f1f02e64.png">

**Comment by jiahaog** [comment]
Hi! I suppose a menu checkbox option would be a possible solution to allow the user disable the right click menu on-demand

**Comment by superandrew** [comment]
@jiahaog it seems a much better option to me as well

**Comment by thegrubbsian** [comment]
I think this could even be a command-line flag when building the app.  For example, Google Drive and Docs makes extensive use of the secondary-click and it would be nice to just globally turn off the native menu for those apps.

**Comment by amslezak** [comment]
I would love the option to disable during build or have a menu checkbox.  I use this for c9.io and it would be super helpful to have the webapp's right-click properties take precedence over electron's right-click menu.  Thanks for considering the enhancement, and a super awesome module!

**Comment by priezz** [comment]
+1 Using for locally launched C9 as well, right-clicking is often used there.

**Comment by jiahaog** [comment]
Perhaps a menu bar toggle would be better for this, so you do not need to rebuild the app to change the behaviour of the right click menu?

**Comment by priezz** [comment]
For me command line argument seems to be more useful as I rebuild apps anyway (I use my own script to launch the local C9 env for a given folder like that `c9ide /path/to/my/project`, this approach allows to run as many local instances of C9 as required). In my case the app is built within /tmp and is not reused after the quit.

**Comment by janjongboom** [comment]
I opened a PR to add an option to disable the context menu in #187.
