### ISSUE TITLE
[OS X] Print missing from file menu

### ISSUE THREAD

**Issue by MacWorks** [jiahaog/nativefier#123]
I have noticed that the option to Print is not available as a keyboard shortcut nor is it present in the file menu. However using window.print does present a print dialog box.

Is there any way to add the print functionality so that it's present via keyboard shortcut and in the File menu?

**Comment by jiahaog** [comment]
Electron does not support this, and hence I have no plans to implement it myself

**Comment by andersonkida** [comment]
Hello. How's the printing issue? Is the printer call already supported?!

**Comment by andersonkida** [comment]
printer
