### ISSUE TITLE
Automatically retrieved `.ico` files are not set properly

### ISSUE THREAD

**Issue by SalahAdDin** [jiahaog/nativefier#124]
I try to create a shortcut icon and i want use the app icon but i have a error with png icon:
![area de trabajo 1_054](https://cloud.githubusercontent.com/assets/5034215/12794864/347f112c-ca85-11e5-81cd-cb3990516429.png)

Is the same problem that Os X ?

Thanks for your great app! Oh, will be great that native apps will be put in `/opt/` folder.

**Comment by TomTasche** [comment]
I had the same problem. I worked around it by replacing icon.png with an icon I downloaded manually.

**Comment by SalahAdDin** [comment]
@TomTasche i do it too. And i change the app folder and now it's creat :dancer: 
But, i think that should be solved this issue.

**Comment by jiahaog** [comment]
Hi, I believe this is a known bug where the app icon provided is actually a .ico file from the current API I'm using to retrieve the icons. What website are you trying to nativefy?

**Comment by SalahAdDin** [comment]
I'm nativefy Wunderlist.

**Comment by peterfnfn** [comment]
I'm having the same problem - unable to get an icon. This is what I was using;

nativefier --name "Hypem" "hypem.com" -i, --icon <path> (but I actually insert the path)

**Comment by jiahaog** [comment]
I've made quite a lot of fixes to the way icons are handled, this should be up in the next release!

**Comment by SalahAdDin** [comment]
Thank's you!
