### ISSUE TITLE
Zoom settings lost on close/refresh

### ISSUE THREAD

**Issue by ncocacola** [jiahaog/nativefier#125]
Hello,

First off, thank you very much for this great tool.

I have used `nativefier` to create a desktop app for Trello, but I have a problem with zoom settings. 

When I open Trello, I like to zoom out to have a better overview of all my lists/cards. In (regular) Chrome, the zoom settings remain the same when I close/open the page again

With the `nativefier` app, Trello opens with the default zoom settings, and I have to zoom out every time.

Is there any way to save the zoom settings so I can get them back when I open the app again?

Thanks!

**Comment by jiahaog** [comment]
Hi! It should be possible to save the state of the zoom when the app is exited

**Comment by lexelby** [comment]
As a workaround until this feature is implemented, use `--inject` with a .js file like this:

```
document.body.style.zoom="75%";
```

I found that works with most apps.  Sometimes it's necessary to delay this a bit:

```
setTimeout(function() {document.body.style.zoom="75%";}, 3000);
```
