### ISSUE TITLE
[Bug] executable icon no longer gets converted to app icon

### ISSUE THREAD

**Issue by devils-shadow** [jiahaog/nativefier#128]
On the previous builds, when using an .ico file, the resulting executable for your application would get the icon specified in the .ico. 
As of the latest update, .png's no longer theme the .exe file.
Please add a parameter to specify .ico files along with .png files. Or at least make the .png apply to the compiled .exe as well.

**Comment by BrendanDonaWho** [comment]
Not sure if this I'm having the same issue or not but I cannot get a .png to become the app icon. I'm wrapping Asana on Windows, Nativefier 6.8.0, Electron v0.36.4.

**Comment by dsandstrom** [comment]
@BrendanDonaWho Are you using overwrite?  On OSX, when using the overwrite flag, the png isn't converted and set as the icon.  The default icon is not used either.  However, when I manually delete the destination folder and re-run `nativefier`, the png is converted and used.

The ico problem seems like a different issue.  When I try to use an ico file, the package is not built.  I've only just starting trying nativefier today, so I may be missing something.

**Comment by BrendanDonaWho** [comment]
I have not been overwriting.  I've been deleting the folder and starting from scratch each time.  I was originally using a .icns file unsuccessfully on an earlier version of nativefier.  I tried again with a .png when I saw it was supported on newer versions. I haven't been able to come up with anything other than the Electron icon so far.

**Comment by izakman** [comment]
Same problem here; png files aren't getting applied to the exe file, and it won't accept ico files.

**Comment by jiahaog** [comment]
This should have been fixed in f48ad3790b678a6cec516754600bc2052ad9657a!
