### ISSUE TITLE
Soundcloud.com app is detected as robot activity in login page

### ISSUE THREAD

**Issue by davidleejy** [jiahaog/nativefier#1291]
**Homework**

- [X ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ X] I searched existing issues, open & closed. Yes, my question is new.
- [ X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

nativefier creates an app for soundcloud.com just fine. Problem is, log in attempts are detected as robot log in activity. I can log in just fine through firefox. I suspect this has something to do with nativefier's default settings.

![nativefiersoucndloud](https://user-images.githubusercontent.com/1690072/136165483-eb497772-e6bd-4d97-a359-f9543ca54b1d.jpg)

**Steps to reproduce**

Tried default & with honest user-agent:

```bash
nativefier "soundcloud.com"
```

```bash
nativefier "soundcloud.com" --honest
```

**Context**

 - Nativefier: 45.0.4
 - OS: mac 11.6

**Comment by ronjouch** [comment]
> the suggestions (`--user-agent firefox` and `--inject JS`) don't dissuade soundcloud's robots. Soundcloud still finds my log-in activity highly robotic.

@davidleejy okay. To you or other passersby: fiddling welcome.

One note: I didn't suggest to `--inject JS`, I suggested to `--inject` <JS of your own making, but it is yours to figure out and write to defeat Soundcloud's detection>. See [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for example, e.g. Spotify.

**Comment by Matthew-Hine** [comment]
Hi all, 

Was also impacted by this the other day. 

I built Soundcloud against the widevine electron build, which allowed me to log in as expected.

@davidleejy might be worth giving this a try. Specific command I used was

`nativefier --name "Soundcloud" --disable-dev-tools "https://soundcloud.com/" --widevine
`

**Comment by davidleejy** [comment]
Gonna sound weird but running the command with `--widevine` returns `error: unknown option '--widevine'` (As opposed to something like widevine not found). Do nativefier users have to do something extra to get widevine to work? Maybe something like http://man.hubwiz.com/docset/electron.docset/Contents/Resources/Documents/docs/tutorial/using-widevine-cdm-plugin.html

I notice I don't have electron on npm and could use nativefier fine so far. Installing the latest version of electron (15.1.0) and running `npm install nativefier` did not help.

**Comment by ronjouch** [comment]
> Gonna sound weird but running the command with `--widevine` returns `error: unknown option '--widevine'`

@davidleejy full Nativefier command, please. Also, `nativefier --version`, please.

**Comment by davidleejy** [comment]
@ronjouch Would you happen to know if the nativefier release on homebrew (https://formulae.brew.sh/formula/nativefier#default) is official? Noticed it depends on node 16.11.0 (LTS version is v14.18.0). In comparison, this github readme instructs users to use NPM for installation and states that nativefier merely needs node >= 12.9.
