### ISSUE TITLE
[Linux Mint 17.3] doesn't create anything

### ISSUE THREAD

**Issue by thob** [jiahaog/nativefier#132]
I think I got all the packages but when I do `nativefier "URL"` nothing happens; not even an error message.
i'm sure I'm missing something, any idea?

**Comment by jiahaog** [comment]
Ah I'm not really sure, I am unable to test on this distro. Could you provide the details 

Version of Nativefier (run $ nativefier --version)
Version of Node.js (run $ node --version)
Command line parameters
OS and architecture you are running Nativefier from
Stack trace from the error message (if any)
Instructions to reproduce the issue

**Comment by thob** [comment]
maybe this is the issue. I get
`wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25"," `

Hmm, wonder how to upgrade my distro doesn't give me the latest
