### ISSUE TITLE
[Enhancement] Maximization of browser window

### ISSUE THREAD

**Issue by BugiDev** [jiahaog/nativefier#133]
I would like to maximize my application (browser window) when it is opened, rather than to rely on width and height. 

I have managed to do this change in my local env and would like to propose this as an enhancement, adding a flag `-max, --maximize` that will maximize the application on open.
I wanted to ask you first if this is something that you would include in nativefier before i do a pull request.

**Comment by jiahaog** [comment]
Sure, it'll be great to have this!

**Comment by jiahaog** [comment]
Thank you so much for the PR!
