### ISSUE TITLE
Inject Javascript or CSS

### ISSUE THREAD

**Issue by thegrubbsian** [jiahaog/nativefier#135]
First, this is really awesome, thanks so much for releasing this!

I'm a big fan of browser plugins that allow you to edit CSS or run arbitrary JS after a page is loaded.  For example, I use something like this on Chrome to fix a bunch of layout things about GMail.  It would be great to be able to do something similar with nativefier.  For example, just to be able to specify an arbitrary JS file when building the app that would run when any page finishes loading in the app.

Just a thought.  Otherwise, truly love this thing.

**Comment by jiahaog** [comment]
Yup, there was some work on this in #47 and is mentioned in #108 as well, I plan to expose something like this via the command line

**Comment by geeeeeeeeek** [comment]
Looking forward to your work. Bothered by the electron webview issues for days.

**Comment by jiahaog** [comment]
This has been implemented since 166aa8962e791a2dbf734deaac3fcaecaab6fbf6
