### ISSUE TITLE
 Full screen?

### ISSUE THREAD

**Issue by Bobeta** [jiahaog/nativefier#136]
Is it possible to have the app started in full screen mode? What would be a good approach to that? Thanks!

**Comment by jiahaog** [comment]
See #139 for this!

**Comment by Bobeta** [comment]
Thanks! It's cool that it remembers. However, is it possible to make it open in full screen by itself from first time it opens?

**Comment by jiahaog** [comment]
@Bobeta Are you sure it does not remember its full screen state? It seems to work for me. I'm on nativefier 6.9.1 on OSX 10.11.2

**Comment by Bobeta** [comment]
Thanks for the reply! It does remember the full screen state, but lets say I deploy it to a bunch of units. I would like it to start full screen for all of them each time, or at least the first time so that it remembers the state. Some config attribute to do that would be great.
