### ISSUE TITLE
CPU usage 100%

### ISSUE THREAD

**Issue by ronilaukkarinen** [jiahaog/nativefier#137]
I have noticed this uses crazy amount of CPU, often caps to 100% and makes my OS X 10.11.3 really slow. Any way to make it lighter? I use this mainly with [koel](https://github.com/phanan/koel). The same CPU usage doesn't happen with Chrome, Firefox or Safari.

**Comment by jiahaog** [comment]
Ah, I'm not really sure. Could you open the developer tools and see if there is anything strange going on inside?

**Comment by Fmstrat** [comment]
I have this problem when running Google Voice in nativefier on Mac. I looked in Developer Tools and nothing seems awry, minus a check every few seconds I assume for new messages.

**Comment by Fmstrat** [comment]
@jiahaog Here's a screenshot for reference. I should note, it doesn't always happen, it just fires up into high gear turning on fans for a while and then stops requiring so much CPU eventually.

<img width="569" alt="screen shot 2018-07-25 at 8 15 29 pm" src="https://user-images.githubusercontent.com/971474/43234028-8a5e6072-9047-11e8-9a01-aee160c513d0.png">
