### ISSUE TITLE
[Q] app for subdir

### ISSUE THREAD

**Issue by thob** [jiahaog/nativefier#140]
is it possible to create an app based on a subdir like `example.com/subdir/`?

**Comment by mbilker** [comment]
Of course! I used Nativefier to "nativefy" https://discordapp.com/channels/@me

**Comment by thob** [comment]
Hmm, I get
`/usr/local/lib/node_modules/nativefier/lib/options.js:148
        throw 'Your Url: "' + normalized + '" is invalid!';`

**Comment by mbilker** [comment]
Worked for me...
```
[~]── - nativefier https://example.com/subdir
Cannot automatically retrieve the app icon: besticon: not found
Unable to automatically determine app name, falling back to 'APP'
Packaging app for platform linux x64 using electron v0.36.4
App built to /home/mbilker/app-linux-x64
```

**Comment by thob** [comment]
what does the `normalized` mean?

**Comment by jiahaog** [comment]
Hi, could you please provide the following: 


- Version of Nativefier (run `$ nativefier --version`)
- Version of Node.js (run `$ node --version`)
- Command line parameters
- OS and architecture you are running Nativefier from
- Stack trace from the error message (if any)
- Instructions to reproduce the issue

**Comment by thob** [comment]
- 6.8.0
- v4.3.1
- nativefier --name "SocialwareKanboard" "https:/socialware.at/kanboard/"
- Linux Mint 17.3 (64-bit)

**Comment by thob** [comment]
got it working.

**Comment by jiahaog** [comment]
What's the error/stack trace you get?

**Comment by thob** [comment]
see above

**Comment by jiahaog** [comment]
Oh, the reason why this fails is because the url you used is invalid. You left out the second slash after the url `https:/xxx.at/kanboard/` :D

**Comment by thob** [comment]
Sorry but it's just a typo here on GH

Am 25. März 2016 14:29:01 MEZ, schrieb Jia Hao <notifications@github.com>:

**Comment by jiahaog** [comment]
I don't really understand why it doesn't work for you... 

Could you try 
```bash
$ nativefier google.com ~/Desktop
```

**Comment by thob** [comment]
worked without any problem
