### ISSUE TITLE
[Question] How to inject javascript or css?

### ISSUE THREAD

**Issue by geeeeeeeeek** [jiahaog/nativefier#141]
I wonder if there is some way for me to inject javascript or css into the page, rather than simply apply `nativefier xxx`?

For example, my target page is `whatsapp.com`, and I want to inject js in the page.

**Comment by jiahaog** [comment]
Hi! This is a duplicate of #135

**Comment by thegrubbsian** [comment]
Hi, looks like this issue and #135 are both marked as closed.  I was just wondering if this was a feature that was still on someone's radar.  I'd be happy to attempt to fix it but I will need some guidance as to where to start.  Can someone point me in the right direction for a potential patch?

**Comment by jiahaog** [comment]
I'm actually working on it right now!

**Comment by jiahaog** [comment]
@thegrubbsian this has been added since 166aa8962e791a2dbf734deaac3fcaecaab6fbf6
