### ISSUE TITLE
How to make one for PWA that works offline?

### ISSUE THREAD

**Issue by mizzunet** [jiahaog/nativefier#1428]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

https://hoppscotch.io/ provides a PWA that can work can offline.

I made a nativefier for it but it doesn't work at offline. Is this possible to make it run offline? I guess, they do store it's data in the cache or somthing

**Comment by TheCleric** [comment]
What version of Nativefier are you using?
What OS are you running?

I just tested making an app by running `nativefier https://hoppscotch.io/ --name Hoppschotch` and then loaded it (online) once.

I closed it, and disabled my network, and opened it again and it still worked (with a warning on the page that I was in offline mode).

**Comment by TheCleric** [comment]
As well if you tried distributing the app to someone else and it didn't work, you may need to use the [--portable](https://github.com/nativefier/nativefier/blob/master/API.md#portable) flag, but PLEASE read the security notice on that first.
