### ISSUE TITLE
[Question] Enable Adobe Flash

### ISSUE THREAD

**Issue by resilva87** [jiahaog/nativefier#143]
Hi, is there anyway to enable Adobe Flash in nativefied application? I'm building an application for Spotify, which requires it.

Thanks in advance!

**Comment by jiahaog** [comment]
I'm actually in the process of adding it! Just gonna take a bit of time because I want it to be able to automatically determine your chrome flash plugin location without you specifying int

**Comment by resilva87** [comment]
@jiahaog Oh that's great, please let me know if you need any help, I would be very glad to assist you :smiley:

**Comment by jiahaog** [comment]
Preliminary flash support has been implemented since dab9a067748d56ccb002e255ff8ea4f7d6f38723 in `v6.8.1`, please see #152 for any issues with flash!

**Comment by resilva87** [comment]
Working like a charm, thanks buddy :beers: :satisfied:
