### ISSUE TITLE
Preserve state of nativefied app

### ISSUE THREAD

**Issue by garymoon** [jiahaog/nativefier#144]
### Description
When an identical nativefied application is created (same command line args), they don't share their data dir (a new random string is appended to the folder name). This makes it impossible to update the nativefied application without losing state.

### Steps to Reproduce Issue
* Create a nativefied application.
* Use it for a short time (login etc)
* Create it again (perhaps with a newer version of nativefier)
* You will need to login again

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.8.0`
- Version of Node.js (run `$ node --version`): `v5.5.0`
- OS: `OS X 10.9.5`
- Architecture `x64`
- Stack trace from the error message (if any)

```
N/A
```
### Proposal
Ideally we would be able to select the location of the data directory from the command line. I'd be happy to submit a PR but I couldn't find the relevant code. Could you point me in the right direction please?

Thank you.

**Comment by jiahaog** [comment]
Hi there! Yup, I agree with you and it's annoying when the state of the app is not kept when they are recreated. 

Actually, I was thinking the data directory should be include a hash of the target url, as such 

`<app-name>-<target-url-hash>-nativefier`

Currently it's simply generating a random hash whenever an app is created, and this makes every packaged app unique. 

In addition, there should be a menu option to clear the cache if desired. It seems to be too much if you ask the user to specify the data directory, as I'm trying to keep the configuration for creating apps minimal.

**Comment by garymoon** [comment]
@jiahaog I meant only optionally specify the data directory (which may solve #42), but for this particular use case I like your idea much better. If you're interested in a PR please point me in the right direction and I'll see what I can do.

I'm unfamiliar with Electron's internals, but I would have thought clearing the cache while the app was running would be difficult to do?

**Comment by jiahaog** [comment]
Oh, a PR would be cool! Actually its just a simple fix in `src/build/buildApp.js` from line 58. 

I don't know if deleting the cache while the app is running will cause any problems, that will actually take some testing. Ideally, if the deletion works without a restart, it should immediately trigger a refresh of the target url. If it fails, I think the app should restart itself automatically or something.

**Comment by garymoon** [comment]
Jeez, not sure how I missed that, thanks. Would you prefer we import options to get the URL or use the normalized app name which we already have?

Would you like me to open a separate issue about the cache clearing?

**Comment by jiahaog** [comment]
I think the fix here would be to change the `postFixHash` in line 62 `return `${normalized}-nativefier-${postFixHash}`;` to a hash of the target url, and that'll be it!

Yeah, the cache clearing should be another issue, but it should be completed together with this change before I can release the next version

**Comment by jiahaog** [comment]
@garymoon Hi, may I know how's it coming along? If you're working on it I'll wait a bit for you to be done first!

**Comment by garymoon** [comment]
Hi @jiahaog. I'm having trouble figuring out where to import/access the options. I haven't used babel so perhaps some of the newer es stuff is turning me around. I'm happy to keep going if you can point me in the right direction please.

**Comment by jiahaog** [comment]
Oh, what options are you referring to?

**Comment by garymoon** [comment]
The application options. Specifically, the target URL. `normalizeAppName` receives only the app name in its arguments, and I don't see any relevant imports.

**Comment by jiahaog** [comment]
Yup! I think the fix here is simply to change the `postFixHash` to a hash of the target url, and that'll be enough!

**Comment by garymoon** [comment]
Yes I agree. In the context of `normalizeAppName`, how do I get the target URL is my question.

**Comment by jiahaog** [comment]
Oh, appArgs in line 19 is an object which contains the targetUrl. 

So maybe one way would be to add another parameter to `changeAppPackageJsonName` and `normalizeAppName` to pass the targetUrl in?

**Comment by garymoon** [comment]
Ah, thank you. Working on it now.

**Comment by jiahaog** [comment]
No problem!

**Comment by garymoon** [comment]
@jiahaog I've encountered a build error I don't know enough to resolve myself:

    stream.js:74
          throw er; // Unhandled stream error in pipe.
          ^
    Error: ./app/src/components/mainWindow/mainWindow.js
    Module not found: Error: Cannot resolve module 'electron-window-state' in /Users/gary/nativefier/nativefier/app/src/components/mainWindow
    resolve module electron-window-state in /Users/gary/nativefier/nativefier/app/src/components/mainWindow
      looking for modules in /Users/gary/nativefier/nativefier/node_modules
        /Users/gary/nativefier/nativefier/node_modules/electron-window-state doesn't exist (module as directory)
        resolve 'file' electron-window-state in /Users/gary/nativefier/nativefier/node_modules
          resolve file
            /Users/gary/nativefier/nativefier/node_modules/electron-window-state doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/electron-window-state.webpack-node.js doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/electron-window-state.js doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/electron-window-state.json doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/electron-window-state.node doesn't exist
    [/Users/gary/nativefier/nativefier/node_modules/electron-window-state]
    [/Users/gary/nativefier/nativefier/node_modules/electron-window-state]
    [/Users/gary/nativefier/nativefier/node_modules/electron-window-state.webpack-node.js]
    [/Users/gary/nativefier/nativefier/node_modules/electron-window-state.js]
    [/Users/gary/nativefier/nativefier/node_modules/electron-window-state.json]
    [/Users/gary/nativefier/nativefier/node_modules/electron-window-state.node]
     @ ./app/src/components/mainWindow/mainWindow.js 15:27-59./app/src/helpers/helpers.js
    Module not found: Error: Cannot resolve module 'wurl' in /Users/gary/nativefier/nativefier/app/src/helpers
    resolve module wurl in /Users/gary/nativefier/nativefier/app/src/helpers
      looking for modules in /Users/gary/nativefier/nativefier/node_modules
        /Users/gary/nativefier/nativefier/node_modules/wurl doesn't exist (module as directory)
        resolve 'file' wurl in /Users/gary/nativefier/nativefier/node_modules
          resolve file
            /Users/gary/nativefier/nativefier/node_modules/wurl doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/wurl.webpack-node.js doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/wurl.js doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/wurl.json doesn't exist
            /Users/gary/nativefier/nativefier/node_modules/wurl.node doesn't exist
    [/Users/gary/nativefier/nativefier/node_modules/wurl]
    [/Users/gary/nativefier/nativefier/node_modules/wurl]
    [/Users/gary/nativefier/nativefier/node_modules/wurl.webpack-node.js]
    [/Users/gary/nativefier/nativefier/node_modules/wurl.js]
    [/Users/gary/nativefier/nativefier/node_modules/wurl.json]
    [/Users/gary/nativefier/nativefier/node_modules/wurl.node]
     @ ./app/src/helpers/helpers.js 7:12-27    

Here is a diff of my changes:

    diff --git a/src/build/buildApp.js b/src/build/buildApp.js
    index f2fb022..f743255 100644
    --- a/src/build/buildApp.js
    +++ b/src/build/buildApp.js
    @@ -24,15 +24,15 @@ function buildApp(src, dest, options, callback) {
             }
    
             fs.writeFileSync(path.join(dest, '/nativefier.json'), JSON.stringify(appArgs));
    -        changeAppPackageJsonName(dest, appArgs.name);
    +        changeAppPackageJsonName(dest, appArgs.name, appArgs.targetURL);
             callback();
         });
     }
    
    -function changeAppPackageJsonName(appPath, name) {
    +function changeAppPackageJsonName(appPath, name, url) {
         const packageJsonPath = path.join(appPath, '/package.json');
         const packageJson = JSON.parse(fs.readFileSync(packageJsonPath));
    -    packageJson.name = normalizeAppName(name);
    +    packageJson.name = normalizeAppName(name, url);
         fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson));
     }
    
    @@ -55,9 +55,11 @@ function selectAppArgs(options) {
         };
     }
    
    -function normalizeAppName(appName) {
    +function normalizeAppName(appName, url) {
         // use a simple 3 byte random string to prevent collision
    -    const postFixHash = crypto.randomBytes(3).toString('hex');
    +    let hash = crypto.createHash('md5');
    +    hash.update(url);
    +    const postFixHash = hash.digest('hex');
         const normalized = _.kebabCase(appName.toLowerCase());
         return `${normalized}-nativefier-${postFixHash}`;
     }

MD5 is the shortest hash available in node, but leads to a very long folder name. I'm not sure what, if anything, can be done about that, or whether or not we care.

**Comment by jiahaog** [comment]
I think that problem is because you did not set up the development environment properly, see [here](https://github.com/jiahaog/nativefier#development).

I think it'll be alright to simply truncate the hash to 6 characters?

**Comment by garymoon** [comment]
Redoing it from scratch has worked. I've fixed a typo and the patch is working.

Truncating the hash of course leaves us very open to collisions, but those would only occur if someone was using a different URL with the same app name.

Code is at PR #149. Let me know what you think.

**Comment by jiahaog** [comment]
Fixed with #149
