### ISSUE TITLE
Spelling and Grammar is missing

### ISSUE THREAD

**Issue by vukasin0** [jiahaog/nativefier#145]
### Description
I'm using nativefier to wrap few web chats - mainly whatsapp, fb messenger and fleep.io but what I really missing is spelling and grammar for English which works out of the box in chrome.

### Steps to Reproduce Issue
Type asdfadsfadf in any form - should be underlined with red line.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.8.0`
- Version of Node.js (run `$ node --version`): `v0.10.25`
- OS: `Ubuntu 15.10`
- Architecture `x86_64`
- Stack trace from the error message (if any)

```
N/A
```

**Comment by jiahaog** [comment]
Thanks for the feedback! However, this is an issue with Electron itself, please see atom/electron#3189.
