### ISSUE TITLE
Use --electron-version 0.36.x does not work?

### ISSUE THREAD

**Issue by amslezak** [jiahaog/nativefier#146]
### Description
When trying to specify an electron version to use, nativefier does not respect the version requested.  It always downloads 0.36.4.  I've also tried doing the request via command line (below) and via Programmatic API, with the same results.  I've tried requested electron 0.36.3 through 0.36.8, and electron 0.36.4.  I've also tried rm'ing contents of ~/.electron before running the command without success.  

I'm trying to use electron 0.36.8, but can not currently.

### Steps to Reproduce Issue
```
gmail-native  nativefier --name "Gmail" --platform "darwin" --arch "x64" --electron-version "0.36.8"  --overwrite --conceal https://mail.google.com/mail/u/0/
Skipping icon conversion from `.png` to `.icns`:  { stdOut: 'Cannot find required ImageMagick Convert executable\n',
  stdError: undefined }
Packaging app for platform darwin x64 using electron v0.36.4
App built to /Users/aslezak/gmail-native/Gmail-darwin-x64
```

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.8.0`
- Version of Node.js (run `$ node --version`): `v5.6.0`
- OS: `10.11.4 Beta (15E39d)`
- Architecture `x64`

**Comment by jiahaog** [comment]
Oops, thanks for this!

**Comment by amslezak** [comment]
I tested via dev-build instructions and it works.  Thanks for the super-fast turnaround.

**Comment by MAJDA55** [comment]
Hi,i have a problem with the version of electron.. i trying use electron version 0.36.4..
wath is the compatible version of node and sqlite3 with electron ?

**Comment by jiahaog** [comment]
@MAJDA55 What are you trying to do?

**Comment by MAJDA55** [comment]
I'm new in the use of electron, I install electron with node js and npm , and I have problem when i try to install Sqlite3 by node js , I think that the version of electron,node js and sqlite3 must be compatible
