### ISSUE TITLE
Where is HTML5 localStorage kept?

### ISSUE THREAD

**Issue by eformx** [jiahaog/nativefier#147]
I have a web app that I converted with nativefier on Windows 10 and it works great! I haven't tried this yet, but just wondering if you know what happens if I use Html5 localStorage...Does it save it in the container (the executable) or one of the files that nativefier creates.  So If I have some settings in localStorage and then move the nativefier app to another machine, will the localStorage items move with the app to the new machine?

**Comment by jiahaog** [comment]
Hi! I believe this is related to #144 and #7. Currently, it is stored in your [appData](https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname) directory, and its in the following format

```
<app-name>-<nativefier>-<random-hash>
```
