### ISSUE TITLE
Feature Request: Global keyboard shortcuts

### ISSUE THREAD

**Issue by 2xAA** [jiahaog/nativefier#15]
Would it be possible to create a config (or JavaScript) file to bind some keypresses to JavaScript console injections?

For example, music players could bind the media keys to JavaScript commands to start, stop and skip.

**Comment by zweicoder** [comment]
@2xAA Which website are you looking at specifically? This might be possible but you would probably have to define your own functions and specify what DOM elements to click.

**Comment by 2xAA** [comment]
@zweicoder Specifically Google Play Music. The ability to bind a system's media keys to control that would be great!
I think it would be useful for other apps too, but I can't think of any off the top of my head.

(there is a project which wraps GPM as a desktop app called Radiant Player, but Flash is required to play back the music as they're using an OS X WebView, whereas nativefier uses Chromuim so GPM doesn't require flash)

**Comment by Gusbenz** [comment]
I second this. Would be wonderful. atom-shell does some system level binding, or so I read somewhere. Some answers might be here: https://github.com/twolfson/google-music-electron

**Comment by 2xAA** [comment]
@Gusbenz Woah, hadn't seen that before - thanks!

**Comment by rnarian** [comment]
:+1:

Another website would be [soundcloud.com](http://soundcloud.com)

**Comment by zweicoder** [comment]
For anyone still wondering, it's possible to do this with the most naive methods being programmatic macros loaded in `preload.js` and hooked to key listeners like `doc.onkeydown`. 

You can see [here](https://github.com/zweicoder/nativefier/tree/scripts/whatsapp/app/src/static) for an example of how I'm using it to add various hotkeys and extra logic for WhatsApp.

**Comment by 2xAA** [comment]
@zweicoder I'm assuming that doesn't bind the keypresses to system listeners, such as media keys right?

**Comment by zweicoder** [comment]
@2xAA Nope, but I assumed you can find out the keycode for the media keys. Honestly not sure though

**Comment by axe312ger** [comment]
Hey @jiahaog should we reopen this one to track the progress of my PR @ #698 ? :)

**Comment by axe312ger** [comment]
Yay thanks @ronjouch  :)

**Comment by ronjouch** [comment]
Released in v7.6.9. Thanks @axe312ger !
