### ISSUE TITLE
Downloading electron-v0.36.4-darwin-x64.zip Error: connect ETIMEDOUT 54.231.2.161:443

### ISSUE THREAD

**Issue by wpfpizicai** [jiahaog/nativefier#150]
I have downloaded electron via other method and installed it ;but when I use `nativefier "http://medium.com"` nativefier will download again;and the issue as the title come out!

**Comment by jiahaog** [comment]
Please edit your issue to follow the [issue template](https://github.com/jiahaog/nativefier/blob/development/.github/ISSUE_TEMPLATE.md)!

**Comment by kidsit** [comment]
@jiahaog @wpfpizicai ,
I have the similar issue. How to fix it? I am in shanghai, i am not sure whether or not it has something to do with the networking. I have tried well working VPN, it also shows the same error info.
I do not know why in the code, it will always download such kind of staff, it is a little strange.
