### ISSUE TITLE
Inject JS

### ISSUE THREAD

**Issue by adyz** [jiahaog/nativefier#153]
### Description
I'm trying to inject a simple JS file that does an alert and I can't see the alert, neither the file name in the developer tools.

### Steps to Reproduce Issue
JS file (mycustom.js) located on my desktop
The content of the file is `alert('I am the file');`
I run: 
`nativefier http://apple.com --inject ./mycustom.js ~/Desktop`
The app build fine, no warnings or errors, but the alert does not show up.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.9.1`
- Version of Node.js (run `$ node --version`): `v4.2.6`
- OS: `OSX El Capitan 10.11.3`

**Comment by jiahaog** [comment]
Ah yeap, I have not pushed the new fix to npm yet, give me a bit of time to get some other fixes done

**Comment by adyz** [comment]
@jiahaog Thanks a ton. I've updated today and I've seen this feature. Great work!

**Comment by jiahaog** [comment]
Yeap, it's been added in `6.10.0`

**Comment by adyz** [comment]
Awesome! Thanks. 

I noticed that if I try to include two JS files, neither one is included. Is it possible to include two JS files? If so, how?

**Comment by jiahaog** [comment]
Are you sure neither js file is included? I've tested it and it includes at least one of them. One solution for multiple js files would be to concatenate them yourself or browserify them into one file

**Comment by adyz** [comment]
I am pretty sure:

`nativefier http://apple.com --inject ~/Desktop/js/jquery.js,~/Desktop/js/index.js ~/Desktop --overwrite

**Comment by adyz** [comment]
Actually, jQuery is included, but the second JS file not.

**Comment by jiahaog** [comment]
Nope, you are doing it wrong. You have to do something like 
```
nativefier http://apple.com --inject SOME_JS.js --inject SOME_CSS.css ~/Desktop --overwrite
```

It only supports using one js file so you will have to somehow concatenate multiple files on your own.

**Comment by adyz** [comment]
Owww, that was my question. Thanks a lot. I'll try with browserify.

**Comment by monecchi** [comment]
Hey there @jiahaog Would you mind to tell me what does the flag `--overwrite` mean when building it up? Thanks in advance.
