### ISSUE TITLE
Requires login everytime (does not store cookies)

### ISSUE THREAD

**Issue by felipead** [jiahaog/nativefier#155]
### Description

I'm frustrated that every time I close and open an application generated by nativefier, I need to re-enter my credentials for the website I'm using. It does not store session cookies like a web browser does.

### Steps to Reproduce Issue

I reproduced this on hangouts.google.com and mail.google.com. 

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.10.1`
- Version of Node.js (run `$ node --version`): `v5.5.0`
- OS: `Mac OS X El Capitan`
- Architecture `x86_64`

**Comment by jiahaog** [comment]
Hmm, I've just tested it on my side and it appears to work. Are you sure you didn't set yourself to login privately or something?

**Comment by jiahaog** [comment]
Could you show me the exact command you used to build gmail?

**Comment by felipead** [comment]
`nativefier -n "Hangouts" -i 1456778044_hangouts.icns http://hangouts.google.com`
`nativefier mail.google.com --counter`

I also forget to say that I'm using a corporate version of Gmail behind an Okta firewall. However, this issue does happen when I'm using the browser (I don't need to login again if I close and reopen the browser).

**Comment by jiahaog** [comment]
Could you try just regular Gmail without the firewall? I've tried it out on a few web pages and the session cookies seem to work; I'm on OSX 10.11.2 as well

**Comment by felipead** [comment]
Works with non-firewalled gmail. Thanks!

**Comment by cowai** [comment]
I am using plain Zimbra web mail, and it doesnt store the cookies as well.

**Comment by dprothero** [comment]
Same problem here using Gmail w/ Okta. Why doesn't this work? It works fine in browsers. Is it because the Okta cookies are stored under a different domain? Is nativefier only storing cookies for the primary site that the app was built for?
