### ISSUE TITLE
Can't login to 22tracks.com using social network login (O-Auth)

### ISSUE THREAD

**Issue by felipead** [jiahaog/nativefier#156]
### Description

I created a nativefier application to wrap 22tracks.com. To login to the application, you must authenticate using either Twitter, Facebook or Gmail. It thens opens a pop-up window where I can login using a social network of my choice and authorize 22tracks using OAuth.

However, when I try to do this inside nativefier, the Twitter pop-up window is stuck at "Redirecting you to the app", and the 22tracks screen says it could not login due to an error.

### Steps to Reproduce Issue

- Create a nativefier app for 22tracks.com.
- Try to login with Twitter or other social network.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.10.1`
- Version of Node.js (run `$ node --version`): `v5.5.0`
- OS: `Mac OS X El Capitan`
- Architecture `x86_64`

**Comment by jiahaog** [comment]
Yeah, this is related to #19, there are some websites with a different implementation of OAuth that prevents the redirection from working. Could you try reloading the page after you have logged in with twitter?

**Comment by jiahaog** [comment]
I've created #164 which consolidates all problems with logging in!
