### ISSUE TITLE
window.open()-ed windows are locked at 800x600 resolution

### ISSUE THREAD

**Issue by jdsimcoe** [jiahaog/nativefier#157]
### Description

When you open links that spawn a new window they always open in a small size and there is no way to override it.
### Steps to Reproduce Issue
- Click a link that spawns a new window.
- The window will always by `800 x 600` resolution and there is no way to change it.
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.10.1`
- Version of Node.js (run `$ node --version`): `v0.12.7`
- OS: `OS X 10.11.4 Beta (15E56a)`
- Architecture `x64`

**Comment by jiahaog** [comment]
Yes, this is because the new windows created have dimensions that are not defined. I don't think this is a problem, because more often than not the new windows are for logins.

**Comment by jdsimcoe** [comment]
@jiahaog I'm having a problem using it with https://www.figma.com/ because each artboard opens in a new window. Is there a way that I can specify what they are in my app bundle code to mitigate this problem?

**Comment by jiahaog** [comment]
Is there another web site that I can use to test this? I don't have access to figma.

**Comment by jdsimcoe** [comment]
@jiahaog Try using Panda:

```
nativefier --name Panda "https://usepanda.com/app/#/" --show-menu-bar false
```

It spawns new windows and does the exact same thing.

**Comment by tmikaeld** [comment]
Any way of defining the size of the new window?

**Comment by ronjouch** [comment]
> *"Yes, this is because the new windows created have dimensions that are not defined. I don't think this is a problem, because more often than not the new windows are for logins."*

This, and the fact that browsers now default to opening `window.open()`-ed windows in tabs, which we don't have :-/ . I'm afraid there isn't much we can do at this point, but maybe we don't have to, as the trend in single-page apps is certainly not to pop tons of new windows (contradictions welcome). Figma, for example, stopped doing this and works just fine now. Closing this issue, feel free to re-open if new elements deserve consideration.
