### ISSUE TITLE
minimize to systray

### ISSUE THREAD

**Issue by MakuSensei** [jiahaog/nativefier#158]
### Description
hello there some way to go to close or minimize systray

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.11.0`
- Version of Node.js (run `$ node --version`): `v5.8.0`
- OS: `Windows 10` <3
- Architecture `64bits`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by jiahaog** [comment]
Duplicate of #127, WIP!
