### ISSUE TITLE
Flash of Unstyled Content FOUC

### ISSUE THREAD

**Issue by markoradak** [jiahaog/nativefier#159]
### Description

If possible, inject should load styles before page load. The way it is at the moment - there is inevitable FOUC before inject kicks in.

### Specifications

- Version of Nativefier (run `$ nativefier --version`): `v6.11.0`
- Version of Node.js (run `$ node --version`): `v4.1.1`
- OS: `OS X`
- Architecture `x64`

**Comment by jiahaog** [comment]
Yeah this is probably because I loaded it in the following chunk of `app/src/components/mainWindow/mainWindow.js`.

```javascript
    mainWindow.webContents.on('did-finish-load', () => {
        mainWindow.webContents.send('params', JSON.stringify(options));
        mainWindow.webContents.insertCSS(getCssToInject());
    });
```

I think it might be possible to [change the event](https://github.com/atom/electron/blob/master/docs/api/web-contents.md#events) and use another that does not cause the FOUC.

**Comment by iammarkoradak** [comment]
You're correct! Just sent a PR with a fix - changed a function to emit on `'did-get-response-details'`.

**Comment by jiahaog** [comment]
@iammarkoradak I had to revert this because `did-get-response-details` fires multiple times in certain apps and leads to #191 and #172. I'm not really sure how else to avoid the FOUC, I've tried the `did-start-loading` and `dom-ready` events, but the fouc still appears...

**Comment by iammarkoradak** [comment]
I see... Yeah I've tried pretty much every event that made sense - when I decided on `did-get-response-details` - as that was the only one to actually make it work. Just took a look at #191 and #172 - and yes, I understand the issue... 

Not sure about what to do next though... You can leave this issue open if you want, and I'll try to further investigate when I get the chance.

**Comment by joeytwiddle** [comment]
Sorry to suggest the obvious, but how about keep using `did-get-response-details` but this time set a boolean flag so it won't inject the CSS multiple times?

**Comment by jiahaog** [comment]
@joeytwiddle I can't believe it didn't cross my mind > <. It's a little more complicated already but I've managed to fix it!

**Comment by lexelby** [comment]
Excellent solution :)
