### ISSUE TITLE
'Sunrise' website no works

### ISSUE THREAD

**Issue by revengel** [jiahaog/nativefier#161]
### Description
The website https://calendar.sunrise.am/ no works with nativefier application. The application freezes after login attempt.

### Steps to Reproduce Issue
1.Create application
`nativefier -n "Sunrise calendar" -o -i sun.png --width 1500 --height 800  --counter --insecure https://calendar.sunrise.am/`
2. Run application
3. Click "Log In". i.e. via google
4. Loading throbber shows so long

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.10.1`
- Version of Node.js (run `$ node --version`): `v5.8.0`
- OS: `Linux (Arch linux)`
- Architecture `amd64`

**Comment by jiahaog** [comment]
Did you try refreshing the original page via the menu bar, or closing and opening the app and repeating the process again?

**Comment by revengel** [comment]
Yes, of course. I tried all options to fix it.

**Comment by jiahaog** [comment]
I've created #164 which consolidates all problems with logging in!
