### ISSUE TITLE
Problem with nativefiering skype for web

### ISSUE THREAD

**Issue by rosolko** [jiahaog/nativefier#163]
### Description

When create app for web skype using command `nativefier "https://web.skype.com"`, start it and sign in, site say: `Please update your browser to start using Skype`

### Steps to Reproduce Issue
1. Create app: `nativefier "https://web.skype.com"`
2. Start application
3. Sign in

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.12.1`
- Version of Node.js (run `$ node --version`): `v4.4.0`
- OS: `Ubuntu linux 15.10`
- Architecture `64`

![att_54](https://cloud.githubusercontent.com/assets/11458319/13736880/9588c27a-e9c9-11e5-99ec-92617b902d43.png)

**Comment by jiahaog** [comment]
Try to use a later version of the user agent.

```bash
$ nativefier "https://web.skype.com" --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
```

This works for me. However, it requires me to install a chrome extension to make voice or video calls, which is not supported on nativefier :(

**Comment by rosolko** [comment]
@jiahaog Thanks. 
It's working. 
As a linux user it's better to use this solution instead of Skype v4.
And I don't need to use calls and this solution is better :)
