### ISSUE TITLE
Feature request: chromeless windows

### ISSUE THREAD

**Issue by timdp** [jiahaog/nativefier#165]
First of all, really nice project you've got going here!

According to [this post](http://www.mylifeforthecode.com/making-the-electron-shell-as-pretty-as-the-visual-studio-shell/), you can pass `frame: false` to the `BrowserWindow` constructor to hide the frame added by the window manager. It looks like you're already using it in [loginWindow.js](https://github.com/jiahaog/nativefier/blob/b2e05c925bca14777299dc675c260da353bdfd63/app/src/components/login/loginWindow.js#L9) but it's not being exposed as an option for the main window. I thought it could be a nice feature. Thanks!

**Comment by jiahaog** [comment]
Oh, the reason why I didn't implement this is because of the fact that it makes the window undraggable, and creates a whole bunch of additional issues. It might be possible to play with the [draggable region](https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#draggable-region) and experiment if theres a suitable default though.

**Comment by rubencodes** [comment]
There's a -webkit CSS rule that allows you to designate certain elements as "draggable". I've used this in other Electron projects (not using nativefier; not sure if it works out of the box or if there's something fancy you have to do).

**Comment by priezz** [comment]
Actually, when using together with window managers like Amethyst (https://github.com/ianyh/Amethyst) dragging is not necessary at all. So command line argument like `--frameless` would be very nice to have.

**Comment by jiahaog** [comment]
@priezz I've never really used a window manager before, that actually sounds like a good idea just for people using window managers

**Comment by priezz** [comment]
@jiahaog, without frames it looks like ![that](https://i.imgur.com/zsZytCl.png)  (I have changed the code inalready installed nativefier package)

**Comment by priezz** [comment]
Strange, but `--hide-window-frame`, `--disable-context-menu` and many other options are not shown when running `nativefier --help` (6.14.0).

**Comment by jiahaog** [comment]
This seems to be an issue with node.js v6, `v6.2` seems to solve the problem
