### ISSUE TITLE
Alt+Shift keyboard shortcut causes menu bar to appear

### ISSUE THREAD

**Issue by revengel** [jiahaog/nativefier#168]
### Description

If keyboard layout switched by Alt+Shift - window main menu is appearing.
### Steps to Reproduce Issue
1. Open nativefier application (i.e. Twitter)
2. Click "new Tweet"
3. Press "Alt+Shift"
4. See that the main menu is appeared.
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.10.1`
- Version of Node.js (run `$ node --version`): `v5.9.0`
- OS: `Linux - archlinux`
- Architecture `amd64`

**Comment by jiahaog** [comment]
Sorry for the late reply! Could you try updating and using the latest version of nativefier?

**Comment by revengel** [comment]
Hello. Do I must to remove my applications and create them again?
7 апр. 2016 г. 15:18 пользователь "Jia Hao" <notifications@github.com>
написал:

**Comment by jiahaog** [comment]
You have to replace them again if you want them to be built with the latest version of nativefier. However, you can test if the same issue occurs by creating an app just to test it out

**Comment by revengel** [comment]
I have installed nativefier via

npm install nativefier -g

and recreate application by following command

nativefier -n Twitterr -o -i twitter.png --width 500 --height 850 -u
"Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML,
like Gecko) Version/9.0 Mobile/13B143 Safari/601.1" --counter -d Twitter
https://mobile.twitter.com/

problem still exists


On 7 April 2016 at 15:23, Jia Hao <notifications@github.com> wrote:

> You have to replace them again if you want them to be built with the
> latest version of nativefier. However, you can test if the same issue
> occurs by creating an app just to test it out
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jiahaog/nativefier/issues/168#issuecomment-206852278>
>



-- 
__________________________________
C Уважением, *Пащенко Олег*.
*e-mail:* oleh.paschenko@gmail.com
*Skype*: oleh.paschenko

**Comment by revengel** [comment]
I have installed nativefier via

`npm install nativefier -g
`

and recreate application by following command

```
nativefier -n Twitterr -o -i twitter.png --width 500 --height 850 -u
"Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML,
like Gecko) Version/9.0 Mobile/13B143 Safari/601.1" --counter -d Twitter
https://mobile.twitter.com/
```

problem still exists

**Comment by joeytwiddle** [comment]
Here on Ubuntu but running Fluxbox, the app's menu appears and disappears whenever I press Alt on its own.

It looks like Electron has an option for this: [autoHideMenuBar](https://github.com/electron/electron/blob/master/docs/api/browser-window.md). I tried added that option to `~/.config/<app_name>/window-state.json`, on the offchance, but it had no effect.

**Comment by joeysino** [comment]
I'm guessing this is Linux specific.

The menu is actually toggling every time I Alt-Tab to switch off or onto the app!

**Comment by joeytwiddle** [comment]
I'm guessing this is Linux specific.

The menu is actually toggling every time I Alt-Tab to switch off or back onto the app!

For anyone bothered by this, it looks like [this small patch](https://github.com/paflopes/nativefier/commit/cc76b170ccd93fcdc9c57aa5550b231da25dc607) can disable the menu bar entirely.

**Comment by ronjouch** [comment]
@joeytwiddle @revengel is this bug still valid? Here under Linux (Arch/GNOME) the menubar behaves well: Alt+Shift doesn't reveal it, Alt+Tab doesn't either, only pressing *only* Alt reveals it. That might have changed in recent Electrons, can you try with a recent one? (I just tried `nativefier -e 1.6.6 "https://google.com"`).

Closing, please come back if the bug is still present!

**Comment by joeytwiddle** [comment]
My issue with Alt and Alt-Tab and Ctrl-Alt-Arrow (switch desktops) toggling the menubar has gone away. 

Now I have a constant menu bar which doesn't toggle. That removes the annoyance. :+1:

I see there is also a compile-time option: `--disable-context-menu`

It might be nice in future to have another one: `--disable-menubar` for those who don't want it.

**Comment by ronjouch** [comment]
@joeytwiddle this option exists, and defaults to hiding the menu bar:
```
~ nativefier --help | grep menu-bar
    -m, --show-menu-bar             set menu bar visible, defaults to false
```

Can you try fiddling with it on the latest nativefier? Here it works, if it doesn't for you it's a bug, then please come back with all the info you can get (nativefier version, node version, os, full nativefier command used).

**Comment by itziks00** [comment]
Hi,
I have an issue on windows. 
I don't want to see the nenu bar, but pressing alt, shows it.
The only way to avoid showing the menu bar is using the --hide-window-frame, but I need the frame.
I tried --show-menu-bar false but it doesn't work.

Any suggestion?
Thanks.

**Comment by ronjouch** [comment]
> *"I don't want to see the nenu bar, but pressing alt, shows it."*

@itziks00 hi, thanks for the feedback! That's upstream Electron behavior we AFAIK have no control on (I might be wrong, then please point to APIs supporting changing the behavior). Please search for / file a bug at [electron](https://github.com/electron/electron).

**Comment by itziks00** [comment]
Thanks @ronjouch .
As you mentioned, at https://github.com/jiahaog/nativefier/pull/58 this solution works but it's just a workaround and requires to change it manually every build.

**Comment by zsinba** [comment]
how to hide the menu ?

**Comment by luca-demma** [comment]
> Thanks @ronjouch . As you mentioned, at #58 this solution works but it's just a workaround and requires to change it manually every build.

it also removes the possibility to zoom in / out with CTRL + and CTRL -

**Comment by denis3509** [comment]
same problem on ubuntu 23.04. Didnt find a solution
