### ISSUE TITLE
Nativefier reports old User Agent string, even using recent Electron, causing warning messages in e.g. Gmail

### ISSUE THREAD

**Issue by ronjouch** [jiahaog/nativefier#169]
### Description

Even when bundling with the most recent Nativefier v6.12.1 and Electron v0.37.2 (which has been on Chrome 49 since [Electron v0.37.0](https://github.com/atom/electron/releases/tag/v0.37.0)), nativefier-generated apps report an old user agent string (Chrome 41), causing some applications like Gmail to complain (and potentially causing degradation by websites disabling features based on UA sniffing):

![selection_028](https://cloud.githubusercontent.com/assets/522085/13920195/2e21be0a-ef48-11e5-9ca3-ac3c3a8809b8.png)

→ Shouldn't nativefier apps report a user agent string matching the Chrome version bundled by Electron?

Manually setting a recent UA using the `--user-agent` parameter works around the issue, but it would be nice to not have to :)

### Steps to Reproduce Issue

1. Package gmail using the latest Nativefier v6.12.1 with Electron v0.37.2: `nativefier -o -e "0.37.2" --name "gmail" "https://mail.google.com/"`. Success:  
    `Packaging app for platform linux x64 using electron v0.37.2`  
    `App built to /home/ronj/gmail-linux-x64`  
2. Open the generated app.  
→ A yellow bar warns that *"This version of Chrome is no longer supported. Please upgrade to a supported browser. Dismiss"*
3. Ctrl+Shift+I to get Chrome's console, then get `navigator.userAgent`  
→ "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/41.0.2227.0** Safari/537.36"

### Specifications
- Version of Nativefier:`v6.12.1`
- Version of Node.js: `v5.9.0`
- OS: `Ubuntu Linux 14.04.3`
- Architecture `x86_64`

**Comment by ronjouch** [comment]
Duplicate of https://github.com/jiahaog/nativefier/issues/166 , which was submitted earlier and includes a patch proposal. Closing.

**Comment by fiznool** [comment]
I just installed via `npm` and I get this warning when packing up GMail. Has the patch landed?

**Comment by ronjouch** [comment]
@fiznool yes, the patch landed, Nativefier 7.0.1 (check it with `nativefier --version`) will report the chrome user agent associated to your Electron version.

However, the *default* Electron used by Nativefier 7.0.1 is still old, you should set it manually to a recent one using the `-e` switch; for example I nativefy Gmail with the latest [Electron 1.6.5beta](https://github.com/electron/electron/releases) using `nativefier -e 1.6.5 --name "gmail" --icon /opt/icon-gmail.png "https://mail.google.com/mail/"`

Finally, anticipating question *"but why is the default electron version so old?"*, the project maintainer didn't have much time recently, we are working on getting a new release, see https://github.com/jiahaog/nativefier/issues/326.

**Comment by fiznool** [comment]
@ronjouch thank you for the quick and detailed response. 👍
