### ISSUE TITLE
Unable to increase font-size, etc. inside of Nativefied app

### ISSUE THREAD

**Issue by jacobsmith** [jiahaog/nativefier#17]
When I go to a website with text that is very small, I would expect to be able to do `Command-+` to increase the font-size and other aspects of the webpage. This may be a bug in Electron (or just a design choice for what Electron is typically used for), but had caused me some problems. Any advice or work-arounds would be great!

**Comment by jiahaog** [comment]
Hmm, I think this is possible by setting a keyboard listener to the window [webframe](https://github.com/atom/electron/blob/master/docs/api/web-frame.md), I'll look into it!
