### ISSUE TITLE
Fatal error: Unable to commit changes

### ISSUE THREAD

**Issue by arieljannai** [jiahaog/nativefier#171]
### Description

Gettings the following error:

```
nativefier github.com
  packaging [================================                  ] 63%Packaging app for platform win32 x64 using electron v0.36.4
Fatal error: Unable to commit changes

  packaging [========================================          ] 80%
```

Every time it fails on 63-64%, and about the same commit changes error.
I've tried:
- multiple sites (`github.com`, `web.telegram.org`, `web.whatsapp.com`, `medium.com`), all resulted the same.
- running the command under a git repo or with admin privileges to verify that's not the problem.
- running from regular cmd and bash shell

Couldn't find logs of the process, are there any logs somewhere? (`--verbose` did nothing), no logs in the install location, nativefier location, node, npm etc
### Steps to Reproduce Issue

try to install something with nativefier (`github.com`, `web.telegram.org`, `web.whatsapp.com`, `medium.com`, etc..)
### Specifications
- Version of Nativefier: `v6.13.0`
- Version of Node.js: `v0.12.4`
- OS: `Windows 7`
- Architecture `x64`

**Comment by jiahaog** [comment]
Hmm I've never encountered this before. Could it be due to the current working directory? Try cd-ing into desktop or something?

**Comment by arieljannai** [comment]
Already tried from different folders (permissions, git folder etc) when I tried switching shells.
I'll try later to look for a little hope with `procmon`

**Comment by arieljannai** [comment]
I'll report at the evening

**Comment by giza182** [comment]
Any progress on this? Having the same issue on v6.13

**Comment by changzhiga** [comment]
@jiahaog I got the same issue on the latest version, any way to solve this?

**Comment by StephenTung-CR** [comment]
For me, it worked when I switched to a different directory. I was running nativefier from C:\Windows\System32 and switching to appdata\roaming\npm worked for me.

Node v6.1.0
Nativefier 7.0.1
Windows 10 Pro x64

**Comment by arieljannai** [comment]
Just check it another time, with newer versions - working great!
(didn't changed anything from the default installation setup)

Node v7.8.0
Nativefier 7.0.1
Windows 10 (version 1607)

**Comment by arieljannai** [comment]
I guess it can be closed if no one else is experiencing it

**Comment by ronjouch** [comment]
@arieljannai 👍, closing this.

@sellomkantjwa @changzhiga, if you are still experiencing the issue, could you try with a recent node/nativefier and maybe try the suggestion at https://github.com/jiahaog/nativefier/issues/171#issuecomment-281549638 . If that still doesn't help, please chime in (debug information welcome :) and we'll re-open this.
