### ISSUE TITLE
Console poluted

### ISSUE THREAD

**Issue by adyz** [jiahaog/nativefier#172]
### Description
I get a log every 2-3 seconds

### Steps to Reproduce Issue
Create any app

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.13.0`
- Version of Node.js (run `$ node --version`): `v4.2.6`
- OS: `Mac`
<img width="652" alt="screen shot 2016-03-30 at 6 03 51 pm" src="https://cloud.githubusercontent.com/assets/611174/14146926/1e01ae48-f6a2-11e5-931a-7d73e266c784.png">

**Comment by jiahaog** [comment]
Yeah I get this as well on certain webpages. Is it only for YouTube or do you get the same logs for other web pages?

**Comment by adyz** [comment]
On facebook too. Not sure, but I think this causes a performance hit too.

**Comment by chengyin** [comment]
I have a similar issue on [Slack](https://slack.com)
