### ISSUE TITLE
On app close

### ISSUE THREAD

**Issue by adyz** [jiahaog/nativefier#173]
### Description
This is a question.
How can I detect from my injected js that the user is closing the app?
I tried this approach: https://github.com/atom/electron/blob/master/docs/api/app.md and did not worked.

Thanks

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.13.0`
- Version of Node.js (run `$ node --version`): `v4.2.6`
- OS: `Mac OSX`

**Comment by jiahaog** [comment]
Hmm, are the events not fired when the app is closed?

**Comment by adyz** [comment]
On the link above they say to use `const app = require('electron').app;` but if I run `console.log(app)` I get `undefined`

**Comment by adyz** [comment]
I managed to achieve this with `remote` and what this browser window API provides https://github.com/electron/electron/blob/master/docs/api/browser-window.md


Thanks a ton for your help and answering!
