### ISSUE TITLE
Can't build any application on Linux

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jiahaog/nativefier#176]
### Description
I can't buid any application on Linux

### Steps to Reproduce Issue
There's no steps, i just installed nativefier, tried to build an app for Messenger using `nativefier "https://www.messenger.com"`

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v5.13.0`
- Version of Node.js (run `$ node --version`): `v5.10.0`
- OS: `Linux (Archlinux)`
- Architecture `x64`
- Stack trace from the error message (if any)

```
Erreur de segmentation (core dumped)
```

**Comment by jiahaog** [comment]
Do you mean version `6.13.0` or `5.13.0` of nativefier?

**Comment by bil-elmoussaoui** [comment]
Sorry, it's 6.13.0

**Comment by tonytamps** [comment]
@bil-elmoussaoui I just did this on Ubuntu twice successfully with the same Node and Nativefier versions.

The only difference with my build was I did `nativefier messenger.com` - No quotes, protocol, www, etc..

**Comment by bil-elmoussaoui** [comment]
@tonytamps Thanks! but i still have the same issue...
![capture du 2016-04-08 11-34-56](https://cloud.githubusercontent.com/assets/7660997/14380069/f1f70806-fd7d-11e5-99bd-c8f3406dd8ee.png)

**Comment by rosolko** [comment]
@bil-elmoussaoui How do you install nodejs? (I mean from root or personal user)

**Comment by bil-elmoussaoui** [comment]
@rosolko Using Arch package manager `sudo pacman -S nodejs`

**Comment by rosolko** [comment]
@bil-elmoussaoui Ok. Try to make messenger file executable: `sudo chmod +x messenger`

**Comment by bil-elmoussaoui** [comment]
@rosolko Thanks for your help but i'm still getting the same result 
![capture du 2016-04-17 13-20-31](https://cloud.githubusercontent.com/assets/7660997/14586624/3df540c4-049f-11e6-88c0-203ea2c5ae25.png)

**Comment by rosolko** [comment]
@bil-elmoussaoui Also, you can try something from [this](https://bbs.archlinux.org/viewtopic.php?id=154511)

**Comment by bil-elmoussaoui** [comment]
Everything works fine now, maybe it's due to a missing library or it was fixed thanks to the latest version of Electron
