### ISSUE TITLE
Convert PNG to ICNS automatically

### ISSUE THREAD

**Issue by zeke** [jiahaog/nativefier#180]
I'd be willing to submit a PR that would allow PNG files to be used as icon input. Are you open to this?

**Comment by jiahaog** [comment]
Hi! I think it conversion of pngs to icon input has already been implemented a few versions back

**Comment by zeke** [comment]
Oh sweet! I misread the README. Thanks for creating and maintaining this great tool, @jiahaog.

**Comment by jiahaog** [comment]
You're welcome!
