### ISSUE TITLE
Ideas on adding generated app to Unity Dash?

### ISSUE THREAD

**Issue by jc00ke** [jiahaog/nativefier#182]
I've generated a few different apps and I'd like to run them via the Dash, `Super + a` and then `Trello` for example. I have the Electron app launchers symlinked inside `$PATH` in my terminal but I'm not sure how I might "lift" those launchers out( besides putting them in `/usr/local/bin`)

Thanks for any pointers you might have.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.13.0`
- Version of Node.js (run `$ node --version`): `v5.5.0`
- OS: `Ubuntu 15.10`
- Architecture `x64`

**Comment by jiahaog** [comment]
Do you mean the Ubuntu application dock? I think you can simply drag them into it?

**Comment by jc00ke** [comment]
I think they're added to `/usr/local/bin` which I guess is something I could try.

This is the `HUD` I'm speaking of:

![_workspace 1_004](https://cloud.githubusercontent.com/assets/18191/14588802/4016af54-0487-11e6-9379-2285507c96a2.png)

**Comment by eduardo-robles** [comment]
I've did something similar on Fedora 22 with the Telegram app. Basically what you've done (simlink) all appropriate files to the correct directories should allow you to launch the app. But the step I think you may be missing is adding a Menu Shortcut, you need to create a ".desktop" file. Under Fedora they are located /usr/share/applications/NAME_OF_APP.desktop this file tells your DE what icon to use for the app. It appears that Unity does support .desktop files check this [wiki](https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles). Hope this helps.

**Comment by jc00ke** [comment]
Thanks @eduardo-robles, I ended up doing this for http://www.meetfranz.com/ which I've switched over to. Still, love the idea of Nativifier.

**Comment by eduardo-robles** [comment]
No problem @jc00ke I've been using Franz as well but wanted an Open Source solution so I stumbled on Nativefier. Kinda funny that we came across these apps from different directions.
