### ISSUE TITLE
Systemwide list of nativefiered webapps

### ISSUE THREAD

**Issue by CaptainQuirk** [jiahaog/nativefier#184]
### Description

To my knowledge, there doesn't seem to be a way to keep a **systemwide list** of all nativefiered webapps that could be persisted **accross computers and operating systems**.

It would be great if nativefier could expose a `--save` flag, much like `npm install`, that would write an entry in a `nativefier.json` with all the options used.

For **icons**, nativefier could copy the image file to a `$HOME/.nativefier` directory and reference this path in the abovementioned config file.

**Comment by jiahaog** [comment]
Right, you mean this is like a global config file where you can run something like `nativefier install` in a new computer to install all the apps you have installed?

**Comment by matthewdias** [comment]
^ if that's the case you could just keep a shell script with nativefier commands for all your apps

**Comment by CaptainQuirk** [comment]
@jiahaog exactly !
@matthewdias sure.

I'll be willing to work on a generic install command.

**Comment by CaptainQuirk** [comment]
I've started working on this [here](https://github.com/CaptainQuirk/nativefier/commits/systemwide-nativefier-file)

**Comment by CaptainQuirk** [comment]
Started to work on:

- **Saving an application's options** as an entry in a $HOME/.nativefier.json file
- **Implement an install subcommand** that retrieves the abovementioned file and install all the applications referenced

It could be interesting to implement an **uninstall** subcommand that would remove an application either by a name referenced in the config file or by a path.

**Comment by jiahaog** [comment]
Hey this looks great man! I'm kinda busy at the moment but let me know if you need any help with it!

**Comment by deksden** [comment]
Interesting idea. Here is my 50 cents:

Actually, nativefier app is URL + some options + some injected scripts (all that stuff that we specified at CLI for package app). So we can have only one instance of nativefier app as runner, and use it to launch multiply apps. OSX app folder can have reference to proper app, not actual app (or maybe small cocoa launcher with icon).

**Comment by CaptainQuirk** [comment]
Hi,

I don't get what you mean !

**Comment by deksden** [comment]
@CaptainQuirk : idea is simple. Any Electron app is BIG - because it includes whole chrome runtime and all that stuff. But Nativefired app is only small pack of settings, so we can have some optimization: build some generic "runner" app and use it to run "installed" apps. Only one problem: we need some "app" in app's folder. But this can be solved same way as Steam do - symlink to "runner" app.

**Comment by ronjouch** [comment]
@CaptainQuirk closing this issue, feel free to request merging your changes in your fork anytime as a PR, we'll look at it :) . In the meantime, users interested in such a feature can follow @matthewdias workaround:

> *just keep a shell script with nativefier commands for all your apps*
