### ISSUE TITLE
Allow downloading files

### ISSUE THREAD

**Issue by jkmassel** [jiahaog/nativefier#185]
### Description
It'd be handy to be able to right click a URL and download that file, and even support auto-downloading files of types that make sense (PDF, JPEG, etc) by clicking a link leading to one. 

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `6.13.0`
- Version of Node.js (run `$ node --version`): `5.3.0`
- OS: `10.11.4 (15E65)`
- Architecture `x64`

**Comment by jiahaog** [comment]
You're right, this is a good suggestion and sometimes I want to download files as well.

**Comment by sindresorhus** [comment]
You could depend on [`electron-dl`](https://github.com/sindresorhus/electron-dl). It handles everything automagically for you.

**Comment by jiahaog** [comment]
@sindresorhus Thank you! This is amazingly awesome, just what I needed!

**Comment by martin-braun** [comment]
@jiahaog Why did you close this, though? I think your suggestion makes sense. Nativefier should support such feature, too, it would make many life easier.
