### ISSUE TITLE
Support for WebRTC

### ISSUE THREAD

**Issue by rosolko** [jiahaog/nativefier#190]
### Description

Hello, after [this](http://blogs.skype.com/2016/04/15/new-seamless-skype-video-calling-on-microsoft-edge-preview/) MS release I try to create application for web skype with user agent (Windows 10 and Edge):
`nativefier "https://web.skype.com" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"`

All goes well but when I start application and try to get call I get an error in console:
`[2707:0417/164251:ERROR:webrtcsession.cc(1258)] SetAudioSend: No audio channel exists.`

Is it possible to add WebRTC support? Or it's environment issue and I need to install/fix some on system?
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.13.0`
- Version of Node.js (run `$ node --version`): `v5.10.1`
- OS: `Linux. Ubuntu 15.10`
- Architecture `64`
- Stack trace from the error message (if any)

```
[2707:0417/164251:ERROR:webrtcsession.cc(1258)] SetAudioSend: No audio channel exists.
```

**Comment by lexelby** [comment]
I think webrtc at least partially works.  I'm running in Linux and I was able to wrap and use Hangouts just fine.  However, Hangouts's screen sharing support doesn't work.

**Comment by maxhq** [comment]
Hi @lexelby, it would be great if you shared how you managed to get WebRTC running.

**Comment by lexelby** [comment]
@maxhq I didn't do anything special.  I just ran nativefier on the base hangouts url and video chat works fine.  Screen sharing doesn't, though.

**Comment by maxhq** [comment]
@lexelby Ah I see, thank you for answering!

**Comment by jiahaog** [comment]
@rosolko Sorry for the late reply! I'm not sure if electron supports webrtc, I've looked through their docs but there's not much mention about that
