### ISSUE TITLE
deprecated electron-packager@5.2.1: Critical security bug fixed in v7.0.0

### ISSUE THREAD

**Issue by tanhauhau** [jiahaog/nativefier#193]
### Description
[deprecated electron-packager@5.2.1: Critical security bug fixed in v7.0.0](https://github.com/electron-userland/electron-packager/issues/333)

**Comment by jiahaog** [comment]
Hi, I'm kind of working on this in the latest development branch. However, what's stopping me from releasing it is that there seems to be issues moving directories created by electron packager v7, when I'm on OSX 10.11.4. I'm able to remove these directories from the command line with `rm -rf` with no problem, but when I try to delete them finder prompts me for an admin password, but still does nothing after I input it. I'm not too sure what's wrong with this, but I'll have to look into it a little more.

**Comment by jiahaog** [comment]
I've found a workaround for this since 60823a21bb2425fd4e745c5029b88b767784113b and it'll be in the next release!

**Comment by tanhauhau** [comment]
Great.
