### ISSUE TITLE
A questions (and/or suggestions)

### ISSUE THREAD

**Issue by ddofborg** [jiahaog/nativefier#194]
Nativefier is a very cool app. I have some questions about the features or suggestions if the features are not there yet.

1. Is there a way to disable `Developer Tools` in the app?
1. Is there a way to use `Chrome Extensions` within the app?
1. Is there a way to have two windows within the same app? So I can run them side by side? Or maybe a split screen?

**Comment by jiahaog** [comment]
1. It's always enabled, for easy debugging. It would be possible to set a command line flag to prevent it from showing up though.

2. I believe this has been brought up before, but this is not supported :(

3. You can right click on certain links to open them in a new window, but the purpose of nativefier is for single page apps like twitter, whatsapp etc.!

**Comment by moreofmorris** [comment]
I'd love for a way to disable Developer Tools!

**Comment by ddofborg** [comment]
(1) (Y)

(3) It would be great to have multiple windows open per default, because some one window apps are even more great next to each other. Like Gmail.

**Comment by blazeworx** [comment]
+1 for command line flag to disable developer tools. This is extremely necessary for a project I'm building. I do not want my end users to have the ability to open dev tools. @jiahaog any chance we could get this added? I feel this is a feature many people would appreciate.

**Comment by jiahaog** [comment]
Hmm, I don't think supporting multiple windows is a good idea, it requires a lot of functionality (such as address bar, back button) for each window that makes it too similar to a browser, and you might as well use chrome instead?

**Comment by ddofborg** [comment]
@jiahaog I don't think there is a need for address bar, back button, etc. I'd like a single application to run in multiple windows next to each other. Just having two different URLs open in two windows. It's like starting two apps.

Something like:

    nativefier https://mail.google.com/mail/u/0/ https://mail.google.com/mail/u/1/

Will create one app and when you run it, it will open two windows next to each other (like split screen) which two different gmail accounts. It would be even better if the whole app is just one windows which is split in half.

The biggest difference for me which running Chrome is that I want to have dedicated app for different tasks. So I can start my MailApp, which opens 2 of my most used e-mail clients. Or SocialApp, which opens Twitter and Facebook next to each other etc.


Is my use case more clear now?

**Comment by jiahaog** [comment]
Sorry for the late reply! I understand your use case, and it makes alot of sense to have all my email accounts on one app, and social accounts on another app. It is definitely possible to do so, by specifying different configurations to the MainWindow when it is instantiated. It is going to take some work to do so, to generalise the CLI to allow multiple urls as well as to restructure the app to be linked to multiple windows, which I currently do not have time to do so :( Would you like to work on a pull request for this?

**Comment by ddofborg** [comment]
@jiahaog At this moment I don't have the experience (and time) to work on a pull request. Just add it to the TODO, maybe something will change after the summer :)

**Comment by jiahaog** [comment]
I'll add it to future, thanks so much!
