### ISSUE TITLE
Why a single app take up 108+MB disk space?

### ISSUE THREAD

**Issue by idf** [jiahaog/nativefier#196]
### Description
Why a single app take up 108+MB disk space?
<img width="529" alt="screen shot 2016-04-26 at 12 28 50" src="https://cloud.githubusercontent.com/assets/2493622/14831433/a2f25ffe-0baa-11e6-907b-4a47c895a702.png">

### Steps to Reproduce Issue
nativefier --name Messenger  https://www.messenger.com

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.13.0`
- Version of Node.js (run `$ node --version`): `v0.12.2`
- OS: OS X el capitan
- Architecture x86
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by jiahaog** [comment]
It's because electron works by packaging the chrome binary within the app itself so it is a standalone app when packaged.

**Comment by idf** [comment]
Cool, I see. 

However it seems that Chrome binary not only consumes spaces but also is energy hungry. 

Hope eletron will improve in the future. 👍
