### ISSUE TITLE
Incompatible architecture x87 detected

### ISSUE THREAD

**Issue by tristan-k** [jiahaog/nativefier#198]
### Description

Unable to create apps. 

### Steps to Reproduce Issue

$ nativefier -n "Roundcube" -i roundcube.png --maximize "https://mail.brian.de"
  infering [                                                  ] 0%
/home/brian/.npm-global/lib/node_modules/nativefier/lib/infer/inferOs.js:25
        throw 'Incompatible architecture ' + arch + ' detected';
        ^
Incompatible architecture x87 detected

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.13.0`
- Version of Node.js (run `$ node --version`): `v4.3.1`
- OS: `Debian testing/unstable`
- Architecture `Intel Atom CPU N270 @ 1.6GHz`

**Comment by jiahaog** [comment]
Hey, could you try specifying the architecture version with either `--arch ia32` or `--arch x64`? I have not tested this on x87 before
