### ISSUE TITLE
Icon conversion for OS X does not require ImageMagick

### ISSUE THREAD

**Issue by vitorgalvao** [jiahaog/nativefier#199]
References the [optional dependencies section](https://github.com/jiahaog/nativefier#icon-conversion-for-osx).

ImageMagick is not required, as OS X has a `sips` command that’ll work. `bash` function that works for the conversion:

``` bash
function make_icns {
  local file="${1}"
  local iconset="$(mktemp -d)"
  local output_icon="$(mktemp).icns"

  for size in {16,32,64,128,256,512}; do
    sips --resampleHeightWidth "${size}" "${size}" "${file}" --out "${iconset}/icon_${size}x${size}.png" &> /dev/null
    sips --resampleHeightWidth "$((size * 2))" "$((size * 2))" "${file}" --out "${iconset}/icon_${size}x${size}@2x.png" &> /dev/null
  done

  mv "${iconset}" "${iconset}.iconset"
  iconutil --convert icns "${iconset}.iconset" --output "${output_icon}"

  echo "${output_icon}" # so its path is returned when the function ends
}
```

**Comment by jiahaog** [comment]
You're right, thanks man. This can definitely be implemented to remove the dependency!

**Comment by vitorgalvao** [comment]
Found this while looking at old issues. Took the chance to improve the function in the top post (does the same, but it’s shorter).

**Comment by ronjouch** [comment]
See https://github.com/jiahaog/nativefier/pull/279
