### ISSUE TITLE
Support flash [Feature request]

### ISSUE THREAD

**Issue by Darkle** [jiahaog/nativefier#2]
It's be great if you could maybe support flash with a command line option. I found this page on the Electron github repo so I think it might be possible if you just pass the path to where the flash plugin resides on your system: https://github.com/atom/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md

**Comment by skewedlines** [comment]
Hmm I think that could work! I'll look into it this weekend. Thanks for the link!

**Comment by wedtm** [comment]
+1 on this! Unfortunately Nest (Dropcam) still uses flash for their viewer.

**Comment by blalor** [comment]
And Amazon Music, and Pandora.  What the hell is wrong with these people? :-)

**Comment by resilva87** [comment]
Why is the Flash support reverted? Didn't work?
