### ISSUE TITLE
Application will not run from `/Applications` directory on OS X.

### ISSUE THREAD

**Issue by nicksergeant** [jiahaog/nativefier#201]
### Description

Cannot run application when placed in the `/Applications` folder.

### Steps to Reproduce Issue

Build application. Move the `.app` file to the `/Applications` folder.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v6.13.0`
- Version of Node.js (run `$ node --version`): `v0.12.10`
- OS: `OS X`
- Architecture `64 bit`

**Comment by jiahaog** [comment]
Hey I can't seem to replicate this error. Could you try building an app with a later version of node.js?

**Comment by nicksergeant** [comment]
Huh, strange, I cannot reproduce this either. Maybe a one-time OS X bug?

At any rate, thanks a bunch for checking for me. Closing.

**Comment by Nooshu** [comment]
I've had a similar problem to this today. Creating an application directly in the applications folder, then when you come to try and run it I get the message "This application cannot be run".

The fix for this was to move the folder out of the applications folder (to desktop in my case) then move it back in. Then the application runs fine. My guess is that it is some sort of permissions issue.

**Comment by joshrivers** [comment]
+1. Very strange. App Runs from the build folder. Runs copied to ~/Desktop or ~/Applications but copied to /Applications it fails. 

Console output:
`10/27/16 5:35:10.618 PM com.apple.xpc.launchd[1]: (com.electron.dropbox_paper.449632[27667]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/Dropbox - Paper.app/Contents/MacOS/Electron
10/27/16 5:35:10.618 PM Finder[1296]: spawn_via_launchd() failed, errno=111 label=com.electron.dropbox_paper.449632 path=/Applications/Dropbox - Paper.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #1136 LaunchApplicationViaLaunchDJobLabel() q=com.apple.root.default-qos
10/27/16 5:35:10.618 PM Finder[1296]: spawn_via_launchd() failed, errno=111 label=com.electron.dropbox_paper.449632 path=/Applications/Dropbox - Paper.app/Contents/MacOS/Electron flags=1
`

I note that there are a few nearby messages in the Console log from McAfee. @nicksergeant @Nooshu any chance you have AV installed?

**Comment by nicksergeant** [comment]
Nope no AV over here. Strangely this issue became a non-issue after a reboot.
