### ISSUE TITLE
Feature request: Add a way to allow other URLs

### ISSUE THREAD

**Issue by ColtonDRG** [jiahaog/nativefier#203]
As it stands, it seems the apps I create are limited to the domain that I created the app with and subdomains thereof. I would like to have it so that certain other URLs can work, but not nesessarily other domains. For example, if I create an app with the domain foo.com, I want it to be able to load foo.org/bar if there's a link or redirection or something, but not necessarily be able to load any page on foo.org. If there was a way to do this for just a few links while keeping all other outside links loading in a separate browser, that would be awesome. Like a whitelist for certain domains or URLs.

**Comment by jiahaog** [comment]
Hey, I believe subdomains will open in the same window, and only external links should open in the default browser. Is this not the behaviour you are experiencing?

**Comment by ColtonDRG** [comment]
It is, but that's not what I'm asking about. I want to have a whitelist of specific URLs that will not open in the default browser.

**Comment by stevenrombauts** [comment]
@ColtonDRG Did you ever find a workaround for this issue? I have a few applications that require logging in using a Google Account. So any link to Google's login opens up in the default browser, making it impossible to login.

**Comment by ColtonDRG** [comment]
No, in one specific case I was able to sign in using that separate browser and then reload the app and it worked fine (I think it was TweetDeck, but I don't remember) but I never found a way to do anything like what I asked initially

**Comment by stevenrombauts** [comment]
Ok, too bad. Thanks for the info!
