### ISSUE TITLE
No issue. 

### ISSUE THREAD

**Issue by lifeluvr** [jiahaog/nativefier#205]
### Description
Windows installer, with Desktop shortcut, Start Menu item,  web link in Start Menu and an uninstaller!

### Steps to Reproduce Issue
Download "Inno Script Studio"
Run it, select 'Simple Script' and follow the easy wizard!
To change every icon you can use "ResHacker"

### Specifications
All Windows OS's!

```
<Stack trace here>
```

**Comment by jiahaog** [comment]
I'm just building a small hobby project to do the same thing as well!
