### ISSUE TITLE
HTML5 <video> freezes browser (YouTube)

### ISSUE THREAD

**Issue by eladnava** [jiahaog/nativefier#209]
### Description
First off, thanks for this awesome project!

When using nativefier for YouTube, it starts to freeze up as soon as the HTML5 video starts playing, causing the video to freeze sometimes (while the audio keeps playing) and the entire page to become unresponsive (scrolling does not work). The whole interface becomes laggy (e.g. clicking the seek position of the video takes an additional second instead of immediately registering the click)

Is this a known issue?

### Steps to Reproduce Issue

Run:
```
nativefier www.youtube.com
```
1. Open generated app
2. Click a YouTube video
3. Try to scroll the page and interact with it -- it freezes up

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.0`
- Version of Node.js (run `$ node --version`): `v4.4.5`
- OS: `OS X El Capitan`
- Architecture `x64`

**Comment by eladnava** [comment]
Seems like a manifestation of #191.

**Comment by jiahaog** [comment]
Let's consolidate this issue under #191!
