### ISSUE TITLE
Seems that preventDefault doesn't work for right-click menu

### ISSUE THREAD

**Issue by KolesnichenkoDS** [jiahaog/nativefier#211]
### Description
[c9.io](http://c9.io) prevents default right-click menu in its editor, but **nativefier** ignores that

### Steps to Reproduce Issue
1. Pack application using `nativefier` command: `nativefier --name "c9" "http://c9.io"`
2. Launch application `cd c9-linux-x64/ && ./c9`
3. Create a new workspace or open an existing one
4. Try to click right mouse button on the editor

#### Expected behaviour (Chromium):
![](https://pp.vk.me/c631918/v631918626/360ec/Yw3h2xvMeGI.jpg)

#### Actual behaviour (Nativefier):
![](https://pp.vk.me/c631918/v631918626/360e5/KA4R4PtbavE.jpg)

### Specifications
- Version of Nativefier: `v7.0.0`
- Version of Node.js: `v6.2.0`
- OS: `Ubuntu 15.10 wily`
- Architecture `x86_64`

**Comment by jiahaog** [comment]
Yup! The current behaviour is for the context menu to always displayed, you can use the [`--disable-context-menu`](https://github.com/jiahaog/nativefier/blob/development/docs/api.md#disable-context-menu) flag to override this.
