### ISSUE TITLE
[OSX]Builded app to slow.

### ISSUE THREAD

**Issue by kazak1377** [jiahaog/nativefier#220]
### Description

Hello, i've wanted to make an google photos native app, but builded bundle is to slow. Scrolling is laggy, i have to wait several second for photo to open. But on safari site google.photos.com is working quite well.

### Steps to Reproduce Issue
nativefier --name "Google photos" photos.google.com

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.0`
- Version of Node.js (run `$ node --version`): `v4.1.0`
- OS: `OS X El Capitan`
- Architecture `Intel (darwin)`

**Comment by jiahaog** [comment]
Please use nativefier v7.0.1, this was reported in #191 and has been fixed since!

**Comment by kazak1377** [comment]
Yes, v7.0.1 is fine. Thank you)
