### ISSUE TITLE
[OSX] clicking on notification does nothing

### ISSUE THREAD

**Issue by pvinis** [jiahaog/nativefier#221]
### Description

When I get a notification, I click on it, expecting to open the app that notified. Instead, nothing happens.

Specifically, I use nativefier with messenger.com. I have the desktop notifications turned on. When I get a notification from a chat, I click on the notification, but nothing happens. I would expect that the nativefied messenger app would come up.
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v6.2.2`
- OS: `OSX 10.11.5`
- Architecture `darwin`

**Comment by jiahaog** [comment]
You're right, this is an handy UX improvement to the app. I'm not sure if electron supports this though, the api seems to suggest that everything is handled by the os...

**Comment by ronjouch** [comment]
> *"I'm not sure if electron supports this though, the [documentation](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md) seems to suggest that everything is handled by the os..."*

Indeed, and no changes on Electron / Apple HIG side. Closing for now, @pvinis please chime in and re-open if you see alternatives.
