### ISSUE TITLE
Support cacheless apps for local web development

### ISSUE THREAD

**Issue by ianclarksmith** [jiahaog/nativefier#223]
As a test I created an app for local web dev with `nativefier --name "Localhost" "http://localhost:8000"` so that I can easily tab between that, my editor, and miscellaneous tabs in the browser.

Unfortunately the changes in development do not propagate to the version displayed in the Localhost app despite reloading the page. Instead, I can quit the app and reopen it to see the changes or by disabling the cache in the Network tab of the Developer Tools (only works by refreshing while the panel is open).

I believe this could be fixed with #131 unless it's a separate Electron flag (`--disable-http-cache` from [here](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md)).

Edit: I could probably do this and file a pull request for the cache flag specifically unless it's unwanted for some reason.

**Comment by jiahaog** [comment]
Hmm, I've never encountered this problem while using it for development. Sure, I'll be open to a pull request!

**Comment by Thatkookooguy** [comment]
I work with something similar and it works perfectly. You can also open the developer tools, open settings, and check the `disable cache` checkbox

You can also temporarily disable your app's caching

**Comment by ronjouch** [comment]
> *"I believe this could be fixed with #131"*

@ianclarksmith yeah, looks like it, closing this issue as #131 seems like the general case. PR still welcome anyday if you feel like it :) . Cheers.
