### ISSUE TITLE
Does nativefier support beforeunload function?

### ISSUE THREAD

**Issue by chartrandf** [jiahaog/nativefier#224]
Hello

Does Nativefier support beforeunload function when we close the window? Here's the code I use : 

**Javascript**

```
$(window).on('beforeunload', alertOnBrowserExit);
```

**Command line**

```
nativefier http://mywebsite.com
```

Am I doing something wrong?

**Comment by jiahaog** [comment]
Hmm, are you referencing the correct `window`? I believe the window here refers to the electron [BrowserWindow](https://github.com/electron/electron/blob/12cb678562953a63de397f4753c91731831b8926/docs/api/browser-window.md), and not the global window object

**Comment by ronjouch** [comment]
Closing as didn't get feedback from @chartrandf. Feel free to come back and re-open :)
