### ISSUE TITLE
Support version-string

### ISSUE THREAD

**Issue by Purii** [jiahaog/nativefier#226]
Are there any intentions to support the [`version-string` object](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#version-string)?

```
// from electron-packager API
--version-string.CompanyName="company" --version-string.ProductName="product"
```
### Discussion about implementation

I started experimenting a little bit, but couldn't figure out how the pass an object via [commander](https://github.com/tj/commander.js) in an elegant way. The most obvious alternative might be the definition of every option separately:

```
// /src/options/cli.js
.option('--version-string.CompanyName <value>', 'set company name (win32 only)')
```

**Comment by jiahaog** [comment]
Hi, I'm open to a pull request if you could do so! 

Yeah, I don't think you can do that in commander. Another solution would be to pass in a json object for the version string with the relevant keys and values. I'm not too sure, but what's the convention for specifying an object as a command line flag in unix command line tools?
