### ISSUE TITLE
Open external links in the default browser

### ISSUE THREAD

**Issue by JacobDB** [jiahaog/nativefier#23]
Not sure if this is possible, but I'd love it if you could make external links open in the default browser, rather than just browsing to them within Electron.

For example, if you have an app set up for GitHub, and you click on a link to npmjs.org, that npmjs.org link would open in your default browser.

**Comment by tonytamps** [comment]
Just `command+click` them and they will.

**Comment by revxx14** [comment]
Good suggestion, but I still think making them open in the default browser helps create a more "app-like" experience. Could be a new option added to the build process, something like "if links aren't on these domains, open in new tab" where you provide a list of domains.

**Comment by jiahaog** [comment]
Hmm, that sounds interesting. Are you saying that say if an app is packaged for http://github.com, links that are outside the github domain should automatically open in the default browser? I do agree that it would add to the "app-like" experience.

**Comment by johnsheehan** [comment]
I believe that is what they are saying. Fluidapp lets you configure what URL patterns should open in new tabs vs. the default browser. Since I wrap gmail, this is indispensable.

**Comment by revxx14** [comment]
Exactly. For example, if you have GitHub as an applciation, and you where to click on a link to npmjs.org, that link would open in your default browser.

**Comment by jdsimcoe** [comment]
I am actually looking for the opposite in some ways. I am trying to use [Figma](https://www.figma.com/) and when you try to open a design file it has `target=_blank` so it opens in the default browser and I want my Figma bundled app to open those links. Any ideas on this?

**Comment by jdsimcoe** [comment]
Solved this here: https://github.com/jiahaog/nativefier/issues/12#issuecomment-173702262

**Comment by jiahaog** [comment]
After implementing the OAuth support, this is the current behaviour for links:

- no `target`: Navigates to that url
- `target=_blank`: 
  - *Link is external*: Open link in default browser
  - *Link is internal*: Open another nativefier window

What is proposed is changing the links with no `target` to:
- *Link is external*: Open link in default browser
- *Link is internal*: Navigate to that url

It's a pretty easy addition for me to make, are there any side effects to doing so that we may have overlooked?

**Comment by revxx14** [comment]
The only problem I can think of is that there could be instances where a site has two domains but is in fact the same site. For example, something like gist..github.com and github.com. Should the gist subdomain count as an external site, or should it be considered an internal link?

I think the best way around that kind of situation is to assume that they're external by default, but allow a flag when generating the app to specific additional urls. Something like `--urls "github.com, gist.github.com"`.

**Comment by jdsimcoe** [comment]
Also there are many places when apps open external links (Google Apps, Figma, Coolors, etc.) that you want to open internally. This is another use case not accounted for here.

**Comment by simonweil** [comment]
Perhap there can be a white list of sites that can be configured to open in the same nativefier (see fluid as reference).

**Comment by aleksandar-todorovic** [comment]
@revxx14 Those are not two different websites, those are two different subdomains on the same website. 

I believe that, in the case of multiple subdomains of a same domain, the links should be opened in the application. If the domain is completely different, then it should be opened in the default browser.

**Comment by revxx14** [comment]
Good points, opening in-app by default is probably best. I'd still like a flag to make them open externally, even if it's all or none. Something like `--external-submdomains` would probably work well.

**Comment by englishextra** [comment]
You should prepare your html and js for opening external links in default browser:

in your js:

	/*!
	 * stackoverflow.com/questions/32402327/how-can-i-force-external-links-from-browser-window-to-open-in-a-default-browser
	 */
	var isElectron="undefined"!==typeof window&&window.process&&"renderer"===window.process.type||"";

	if(isElectron){const shell=require("electron").shell;}

	/*!
	 * community.phonegap.com/nitobi/topics/open_external_links_in_system_browser_phonegap_build_3_1_iphone_android_windows
	 */
	function openDeviceBrowser(a){isElectron&&shell.openExternal(a)||window.open(a,"_system","location=no")};

in your html:

<a href="#" onclick="openDeviceBrowser(&quot;http://m.soundcloud.com/user633010415/be-was-were-been&quot;)">Hear the sound bla bla bla</a>

I dont think nativefier is willing to do this work on the fly.

**Comment by jiahaog** [comment]
Sorry for the late reply, I was kinda focusing on something else. 
The default behaviour for external links is that they will be opened in the default browser, and this can be overridden with a right click context menu.

Since `6.6.2`, there is a right click context menu implemented that allows links to be opened in a new electron window for the user to log in, or for the links to be opened in the default browser, this should help with authentication issues such as #19. 

You guys are right in the issue of identifying subdomains to determine if a link is an external link, the command line flag proposed by @revxx14 seems like a good idea. I'll get around to working on this soon.

**Comment by jiahaog** [comment]
@englishextra Actually, there are no source html files, the packaged app merely points the browser window at the intended url and injects some javascript to prepare certain callbacks.

I'm not really sure why you mentioned phonegap and cordova, its not intended to be wrapped into a mobile app.

**Comment by englishextra** [comment]
@jiahaog because I believe developers create universal source html to build for different platforms using electron-packager and build.phonegap.com. This happans in my case and I believe I'm not alone. As for nativefier grabs url but doesn't package it locally - I'm sure this should be stated clearly in README file. Thanks for your work.

**Comment by zeke** [comment]
> universal source html to build for different platforms using electron-packager and build.phonegap.com

@englishextra what are you building? Just curious.

**Comment by englishextra** [comment]
A webapp that can serve as a normal website and also be embeded in Electron and NW.js

So I strongly face the need to open extarnal links in differen ways:

Here's my final working solution
```
var openDeviceBrowser = function (a) {
	var w = window,
	g = function () {
		var electronShell = require("electron").shell;
		electronShell.openExternal(a);
	},
	k = function () {
		var nwGui = require("nw.gui");
		nwGui.Shell.openExternal(a);
	},
	q = function () {
		var win = w.open(a, "_blank");
		win.focus();
	},
	v = function () {
		w.open(a, "_system", "scrollbars=1,location=no");
	};
	if (!!isElectron) {
		g();
	} else if (!!isNwjs) {
		k();
	} else {
		if (!!getHTTPProtocol()) {
			q();
		} else {
			v();
		}
	}
};
```

**Comment by tgottc** [comment]
Any idea on how to force open all links in **new _tabs_**?

**Comment by ronjouch** [comment]
I think `--internal-urls` (present in Nativefier since 7.1.0) will do the trick for most of the use cases asked about here. Quoting https://github.com/jiahaog/nativefier/issues/212#issuecomment-292689727 ,

> ```
> --internal-urls <value>:  regular expression of URLs to consider "internal"; 
>                           all other URLs will be opened in an external browser.
>                           (default: URLs on same second-level domain as app)
> ```
> 
> * Set it to a gibberish regex that will never match, and no link will be considered 'internal', forcing opening in browser
> * Set it to a match-all regex like `.*`, and all links should be considered 'internal', forcing in-app navigation.
> 
> Also, for an exact opposite take: https://github.com/jiahaog/nativefier/issues/23

**Comment by MrDrProfX** [comment]
If you want **ALL** `<a>` tags to open in the default browser, try this in your main.ts:
```
const shell = require('electron').shell;

mainWin.webContents.on('will-navigate', (event, url) => {
  event.preventDefault()
  shell.openExternal(url)
});
```
