### ISSUE TITLE
Open Files Within Nativefier or Push to Native PC - e.g PDF, WAV, etc. 

### ISSUE THREAD

**Issue by Paulser** [jiahaog/nativefier#242]
### User Information

I am just a beginner and I am created my first few apps with Nativefier. I am really enjoying playing with this app as a beginner. I am just making it clear that I am a beginner and apologise if I am in the wrong location to report this or if I am misunderstanding the technology or the purpose of the app.
### Users Case (Apps for Example)

I am experiencing this issue while using [OTRS](https://www.otrs.com/) with Nativefier.
### Description

When using OTRS with Nativefier I come across an error message when opening files within OTRS. The files are mainly PDFs but have also been WAV files. 
### Steps to Reproduce Issue

Clicking on the OTRS file link just shows a green bar on the OTRS icon on the task bar but no action happens (nothing happens). I then try right clicking and pressing 'Open In New Window' this throws an error that can be seen below.
### Work Around My Issue

If you right click and press open in default browser it allows you to download the files but you have to login to OTRS again using your browser (Firfox). This not ideal for the user to keep having to login if they want to open PDFs or other files. 
### My Aim (If Possible)

The app to open the file directly in the web app (PDF Viewer). 
Or 
To push the file onto my native PC (Into Download Folder) 
Or
To push the file onto native PC to be opened with default programs (Adobe Reader & VLC) by default.
### Specifications & Error Information
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v4.5.0`
- OS: `<Windows 10>`
- Architecture `<ARCH>`
- Error Message opening PDF

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.item.on
(C:\ElectronApp\nativefier\OTRS\OTRS-win32-x64\resources\app\lib\webpack:\app\~\el…:1)
    at emitOne (event.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```
### Disclaimer

I am unaware of the security implications my suggestions would cause and please do tell me if I am just using the wrong tool for the job. 

Thanks for reading this post.

Kind Regards,
Paul Serafini

**Comment by skive** [comment]
This issue actual for me too, i made gmail standalone app with nativefier, which fails when trying download any file.

**Comment by osdiab** [comment]
I have also experienced this. Any idea, anyone?

**Comment by osdiab** [comment]
Sounds like this is getting stale, may have to dip my toes into the source here

**Comment by Paulser** [comment]
Yes it does look like this is not getting to much attention. We also might be using the wrong tool for our three requirements. There might be something else out there we can use. 

I do not have the time or knowledge to review the source code but it is open source so you’re more than welcome to I think. Keep us updated osdiab when possible.

Thanks to everyone who reviewed this issue/feature request.

**Comment by antarasi** [comment]
Possible source of problem and solution:
https://discuss.atom.io/t/object-has-been-destroyed-when-open-secondary-child-window/30880

**Comment by dnbattley** [comment]
@antarasi please can you explain how the solution is applied for users of nativefier? This link appears to discuss modifying the program code. I have the same issue and am keen to fix it if possible.

**Comment by ronjouch** [comment]
@Paulser thanks for the report 👍. Downloading progress/completion is currently extremely unclear and we have https://github.com/jiahaog/nativefier/issues/335 for that, but it should work! Can you try looking at your OS Downloads folder, your downloaded files should be here.

**Comment by Paulser** [comment]
@ronjouch Thanks for the information sounds great. I will first re-create some Nativefier Apps for me to do some test. I will then test this process you provided. I will then report back on my progress. If this works I will provide directory locations for Windows & Ubuntu if anyone interested. I do not have a Mac so please can someone confirm it also works on that platform. 

Kind Regards,
Paul Serafini

**Comment by fransiskus182321** [comment]
> @ronjouch Thanks for the information sounds great. I will first re-create some Nativefier Apps for me to do some test. I will then test this process you provided. I will then report back on my progress. If this works I will provide directory locations for Windows & Ubuntu if anyone interested. I do not have a Mac so please can someone confirm it also works on that platform.
> 
> Kind Regards, Paul Serafini

So, any information more about this case?

**Comment by ronjouch** [comment]
See https://github.com/nativefier/nativefier/issues/335
