### ISSUE TITLE
Running in the Background

### ISSUE THREAD

**Issue by leovarmak** [jiahaog/nativefier#248]
Hey !
I really loved this thing. I was wondering if it is possible to keep the app running even if the window is closed on Windows OS. I know this can be done with OS X. If it is possible with Windows OS, how should I do it ?

Btw I was wondering, I latest version of electron is v1.3.x but why do you still use v1.1.3 ?

**Comment by Mayzie** [comment]
+1 if possible for Linux, too.

**Comment by ronjouch** [comment]
@leovarmak @Mayzie thanks for the feedback! Duplicate of https://github.com/jiahaog/nativefier/issues/304 , which was submitted later but has a bit more discussion. Closing this issue, feel free to subscribe to the other issue :)
