### ISSUE TITLE
Edit/repackage Elctron Sources 

### ISSUE THREAD

**Issue by Fragoel2** [jiahaog/nativefier#251]
I've created an app from a website with nativefier and it works great. 
I'd like to add a couple features to it (save/load of a textbox from file). I know I can add custom scripts with the --inject flag, but still it would be far more easer if could get the Electron source files, alter them and then compile them on my own... is there a way to do it?

**Comment by ronjouch** [comment]
@Fragoel2 thanks for the feedback. I understand you'd like deeper access to patching nativefier internals before bundling an app, but it's still fuzzy to me:

* Your use case is not clear to me: what kind of modifications do you bring?
* *"Get[ting] the [nativefier] source files, alter[ing] them and then compil[ing] them on my own"* is entirely feasible, be sure to check the [developer docs](https://github.com/jiahaog/nativefier/blob/development/docs/development.md)
* Did you consider contributing your changes as a PR?

Closing for now, feel free to chime in and re-open if I'm missing something.
