### ISSUE TITLE
Default zoom level only applied when zooming in/out

### ISSUE THREAD

**Issue by Mike-Sundays** [jiahaog/nativefier#253]
### Description

It seems that, whatever the default zoom level given in the command line, it only gets applied when I open the application and zoom in/out. If I just open it, the zoom defaults to 1.0, and not to the value I defined.
### Steps to Reproduce Issue

Running, for example, the command:

`nativefier --zoom 1.5 <application-website>`

and running the application.
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v4.5.0`
- OS: `Windows 10`
- Architecture `x64`

Thank you!

**Comment by BrowncoatShadow** [comment]
I can confirm this as an issue on macOS as well. Zoom level defined at build time is not used. This also applies to apps built using the Programmatic API.

### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v6.2.0`
- OS: `macOS Sierra 10.12`
- Architecture `x64`
