### ISSUE TITLE
enhancement: allow ctrl/alt clicking on links to open in default browser?

### ISSUE THREAD

**Issue by jstrachan** [jiahaog/nativefier#254]
the context menu is great to be able to open links either in a new window or in the default browser.  

It'd be really cool to be able to use a keyboard and click to open in default browser. e.g. 

```
click -> open in new (native) window
alt + click -> open in default browser
```

**Comment by zeke** [comment]
See also https://github.com/jiahaog/nativefier/issues/212

**Comment by eladnava** [comment]
If anyone wants to completely override the external link behavior, so all external links are automatically opened in the default browser and not a new nativefier window, you can temporarily patch `app/lib/main.js` within the compiled binary's source files until a PR is submitted.

Find:
```
mainWindow.webContents.on('new-window', function (event, urlToGo) {
```

Add Below:
```
event.preventDefault();
_electron.shell.openExternal(urlToGo);
return;
```

**Comment by ronjouch** [comment]
Hey @jstrachan, in Nativefier, that behavior is bound to `Shift` + Left-click. Hmmm but looking at browsers behaviors, Ctrl+Click also feels more logical to me. @jiahaog, any reason for `Shift` rather than `Ctrl`?

@eladnava https://github.com/jiahaog/nativefier/issues/212#issuecomment-292689727 might be a workable (albeit a bit arcane for now, going through a regex) option equivalent to your workaround.

**Comment by ronjouch** [comment]
> For me with version 7.1.0 it seems like `Shift` or `Cmd` and left click does `open in new window` then `Ctrl` + left click popups the choice between `open in default browser` and `open in new window`. 
>
> I've tried every permutation I can think of between `Shift`, `Ctrl`, `fn`, `cmd/splat` and a left click and I can't get `Open in default browser` to trigger.  Has anyone else figured out a way to do it?


@jstrachan nah you're right, the behavior you are describing is correct, I must have been hallucinating after hours of the big issue triage this answer was part of 😄. So, yeah, it's a feature request, but in the meantime see #212 and the `--internal-urls` option, maybe it will be useful to your use case.

**Comment by jstrachan** [comment]
@ronjouch many thanks! the `--internal-urls` works even better TBH! Great stuff!
