### ISSUE TITLE
Blank page on Google applications with Google Apps account and 2-step verification

### ISSUE THREAD

**Issue by shvchk** [jiahaog/nativefier#270]
### Description

When creating app for sites like keep.google.com or calendar.googe.com, all I get is blank white page, dev tools show no content in `<body>`. Tried `--insecure` and `--ignore-certificate` flags (just for test), that didn't change anything.
### Steps to Reproduce Issue
1. Setup Google Apps account (I can provide one for testing purposes)
2. Enable 2-step verification
3. Create an app for calendar.google.com (for instance) with nativefier
4. Launch created app
### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v6.7.0`
- OS: `Ubuntu 16.04.1 LTS`
- Architecture `64 bit`
- Stack trace from the error message (if any)

```
none
```

**Comment by Oleander2911** [comment]
It has nothing to do with 2 step verification.
I'm most certain that you just forgot to add https:// before the url.
So you proberly just wrote "keep.google.com", it works with "https://keep.google.com"

**Comment by shvchk** [comment]
No, I used https:// URL back then. But I've found a workaround. It seems Google have changed something, and while it still shows a blank page after login and password pages, it only seems to be blank, but it actually is a 2-step verification page, and verification code input is focused, so one could just enter verification code, hit enter, then restart the app, and it should work. At least it is for me :wink:

**Comment by royts** [comment]
happens to me as well

**Comment by ronjouch** [comment]
Heyho @shvchk @royts, `nativefier --electron-version 1.6.6 "https://calendar.google.com/"` works great for me. Not sure whether what in electron/nativefier/google fixed this; closing, feel free to chime in if the problem persists for you :)
