### ISSUE TITLE
Nativefier shows an error: `/usr/bin/env: ‘node’: No such file or directory`

### ISSUE THREAD

**Issue by ray6an1** [jiahaog/nativefier#273]
### Description

Nativefier is showing a error in Ubuntu 16.10
### Steps to Reproduce Issue

I have installed Node JS via Following command:

`sudo apt-get install -y nodejs`

when i try to install in normal mode, its tell me to run the command in root mode.
when i try to install it sudo mode it works installed.

`npm install nativefier -g`
`npm ERR! Please try running this command again as root/Administrator`

`sudo npm install nativefier -g`
it works

when i tried to make some web page to app, it shows following error:

`nativefier --name "Some Awesome App" "http://medium.com"`
`/usr/bin/env: ‘node’: No such file or directory`
### Specifications
- Version of Node.js (run `$ node --version`): `v4.2.6`
- Version of Nativefier (run `$ nativefier --version`): `unknown`
- OS: `<Ubuntu 16.10>`
- Architecture `<amd64>`

**Comment by gnijuohz** [comment]
Try `sudo ln -s "$(which nodejs)" /usr/bin/node`?

**Comment by ray6an1** [comment]
thanks, it's solved now :smiley:
