### ISSUE TITLE
Remember credentials for basic HTTP authentication

### ISSUE THREAD

**Issue by BarryMode** [jiahaog/nativefier#275]
### Description

https://github.com/jiahaog/nativefier/issues/100, https://github.com/jiahaog/nativefier/issues/155, https://github.com/jiahaog/nativefier/issues/261

Carrying the conversation forward about password saving, I have a web app that requires login every time it is launched and there is no option to "keep me logged in". This site is using a native login prompt, which in the app created by Nativefier looks like this:

![screen shot 2016-10-20 at 9 09 51 am](https://cloud.githubusercontent.com/assets/5648875/19563271/fd49cde0-96a4-11e6-8305-f02417e80745.png)

**Comment by barryanders** [comment]
Here we go. Maybe electron-cookies is the answer! https://www.npmjs.com/package/electron-cookies

**Comment by kranthikumar72638** [comment]
anyone found a solution to this problem yet???

**Comment by davibe** [comment]
You can write credentials in the url http://username:password@www.your.tfs.server.com (because that looks like tfs).

**Comment by ItsSohma** [comment]
I suppose that would work for one person, however, not if you wanted to distribute it. As it stands, I gave up and moved on to something else as what I was trying to do was not important at all.

**Comment by CraigZych** [comment]
Any solution?

**Comment by onedr0p** [comment]
@davibe that doesn't work.

**Comment by yifanwu** [comment]
Hi! I'm not sure if 4c581f9 addresses this issue --- I tried the CLI based approach but the website I use seems to only work with chrome password managers (they appear to have no cookies). Please let me know if I'm missing something. Thanks so much!!
