### ISSUE TITLE
Permissions not being requested

### ISSUE THREAD

**Issue by bilinkis** [jiahaog/nativefier#276]
### Description

Hello guys, I've just made my app using nativefier but i'm having trouble with one of it's features. We have a video-call app and we need to be able to ask the user for permission to use the camera and the microphone. Is there a way to ask for that permission?
### Specifications

Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v4.2.6`
- OS: `<Ubuntu 16.04.1 LTS>`
- Architecture `<x64>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by ronjouch** [comment]
Hi @bilinkis, thanks for the feedback! I just tested Nativefier 7.1.0 / Electron 1.6.6 with Google Hangouts (`nativefier --electron-version 1.6.6 "https://hangouts.google.com/"`), and video worked, do you confirm?
