### ISSUE TITLE
Does not remember window size

### ISSUE THREAD

**Issue by adriantombu** [jiahaog/nativefier#278]
I made a Trello app on MacOs El Capitan, but everytime I close and relaunch the app, the dimensions of the window are lost.
### Steps to reproduce the issue
- `nativefier https://trello.com/ --maximize`
- Open `Trello.app`, whose window is maximized
- Close the app
- Reopen `Trello.app`, which is not maximized and seems to have the [default width/height described in the api](https://github.com/jiahaog/nativefier/blob/development/docs/api.md#width)
### Specifications
- Version of Nativefier : `7.0.1`
- Version of Node.js : `v6.9.1`
- OS: `MacOs 10.11.6 El Capitan`

Thanks for your work, I don't seem to have other problems running it. I even get the notifications and badges on the app icon which are great stuff !

**Comment by pywebdesign** [comment]
I had the same problem with full screen and kind of fix it for my use case, see what I did here: https://github.com/pywebdesign/nativefier.

Hope it help you!

I think the default behavior is not accommodating for enough but I see why it is like it is!

**Comment by fletom** [comment]
I ran into this issue as well at first, but after resizing the window manually once (dragging with the mouse), the size was remembered after quitting and reopening the app. Might work for you as well.

**Comment by adriantombu** [comment]
Thanks @fletom, it works well with your solution !
