### ISSUE TITLE
Executable name shouldn't be always Electron under Windows 

### ISSUE THREAD

**Issue by somebody1234** [jiahaog/nativefier#28]

**Comment by diegoarigony** [comment]
Did you used the `-n`/`--app-name` flag? I tried in Windows 8 and it seems to work fine:
`$ nativefier --app-name "Some Awesome App" "http://medium.com"`

**Comment by thunfischbrot** [comment]
Even without specifying the --app-name it uses the website's name instead for me.

**Comment by somebody1234** [comment]
Wait a second, my bad. (I mean when I pin the executable to taskbar and right-click, it says 'Electron'.

**Comment by jiahaog** [comment]
I'm not really sure how to fix this, I kinda think it's something to do with the version string at https://github.com/electron-userland/electron-packager/commit/189fd022d715c840944ac6b6401388565bb56ee8 but changing it does not seem to work

**Comment by itziks00** [comment]
Hi @ronjouch ,
I did found a workaround for replacing the 'Electron' name in the mentioned places, using rcedit.exe:

For example:
rcedit "Application Name.exe" --set-version-string FileDescription "Application Name" --set-version-string ProductDescription "Application Name"

Is it something that can be integrated to the nativefier build?

Thanks.
