### ISSUE TITLE
Change process name on Windows

### ISSUE THREAD

**Issue by derekflynn** [jiahaog/nativefier#281]
### Description

Great tool by the way.  I use it for a couple of the web pages that I keep up all the time and it gives me much more of a app feel for those tools.

Currently, the process name that shows up in Task Manager in Windows is "Electron", which makes a lot of sense, of course.  I was playing around with electron-packager recently and stumbled into a --version-string.FileDescription arg that changes the process name for an Electron application and wondered if the same could be done with nativefier?

**Comment by MoltenTesseract** [comment]
+1. Having multiple apps is confusing, the only way to tell is by the exe name or icon.

**Comment by ronjouch** [comment]
Duplicate of https://github.com/jiahaog/nativefier/issues/28 , closing this one.
