### ISSUE TITLE
[Request] Cut a new release?

### ISSUE THREAD

**Issue by lostfictions** [jiahaog/nativefier#287]
Hey there, it's been almost five months since the last release. Any chance of cutting a new version sometime soon?

One particular fix that might be of interest to lots of folks is #263. Gmail proxies all external links in emails through an internal domain before redirecting, which has the unfortunate effect of making them open as new Nativefier windows. Without #263, links in some HTML emails simply can't be opened in an external browser.

**Comment by danimalweb** [comment]
Yes please!

**Comment by ronjouch** [comment]
@lostfictions @danimalweb done 😃! [Nativefier 7.1.0](https://github.com/jiahaog/nativefier/blob/development/docs/changelog.md#710--2017-04-07) has a bunch of fixes since 7.0.1 including my own #263. Thanks for the feedback!
