### ISSUE TITLE
Support macOS "hidden-inset" title bar style

### ISSUE THREAD

**Issue by audunolsen** [jiahaog/nativefier#289]
![screenshot 2016-11-08 00 51 19](https://cloud.githubusercontent.com/assets/16224137/20081099/ad51c510-a54d-11e6-8f20-272eba4149d8.jpg)

### Description

Could you please add an option flag for the hidden-inset style for the title bar? 🙏
It makes the traffic lights blend in more with the webpage making it look like a real native application.

Documentations for electron *titleBarStyle: ‘hidden-inset’* found [here](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#alternatives-on-mac)

### Specifications

- Version of Nativefier `v7.0.1`
- OS: `macOS`

**Comment by nansthomas** [comment]
Hey! Do you fix it ?

**Comment by ronjouch** [comment]
Broader issue: #35 - *Support setting BrowserWindow options (some? all? inset titleBarStyle, vibrancy, darkTheme, ...)*
