### ISSUE TITLE
How to upgrade an app

### ISSUE THREAD

**Issue by jlecour** [jiahaog/nativefier#291]
Hi,

I have a few apps made with nativefier. It's made my life easier and I thank you for making it and sharing it.

For example I've been using a GMail app and after some time, Google warned me that my version of Chrome is outdated… I've managed to rebuild a new version of the app and with the latest build of nativefier, I've got an up-to-date GMail app.

The (admittedly very small) problem is that it's brand new. I've lost history, cookies, identification…. So I wonder if there is a way to rebuild an app with the latest nativefier but preserving everything else (icon, cookies…).

Thanks.

**Comment by JasonScopServ** [comment]
I'm getting a similar problem with my Gmail app, I just built it with the latest version at this time 7.0.1. It is give me an error saying that this version of chrome is not supported anymore. Is this an electron version problem or nativefier?

**Comment by quanglam2807** [comment]
@jlecour @JasonScopServ Hi guys, you can try my app https://getwebcatalog.com. It might be what you are looking for. It has automatic update integrated.

**Comment by ronjouch** [comment]
@jlecour @JasonScopServ thanks for the feedback! There's no automatic update: yes a nativefied app is locked to a specific version of Chrome/Electron, which you can specify at build time using the `--electron-version` option (see `nativefier --help` for the full list of options, and go to [the electron/releases page](https://github.com/electron/electron/releases) to pick your favorite stable/beta flavor of Electron poison :) ). There's no plan to change that, as all the machinery for this is part of the nativefier builder and not the nativefied app.

However, you can upgrade an app by just re-running nativefier at the same place with a newer `--electron-version`. @jlecour re-bundling the same app at the same place shouldn't *"lose history, cookies, identification…."*, I just tried it on my Feedly app and was still (cookie) logged-in after re-bundling.
