### ISSUE TITLE
Support bundling local URLs (file:// scheme)

### ISSUE THREAD

**Issue by tfont** [jiahaog/nativefier#296]
Is there a way to do local project files? E.g. "nativefier --name "Native Launcher" "C://_/test.html""

Would throw "xxxxx" is invalid!

I would like to wrap local HTML graphical projects.

**Comment by ronjouch** [comment]
Duplicate (not exactly but the result is the same: bundling local stuff fails) of https://github.com/jiahaog/nativefier/issues/262, closing.
