### ISSUE TITLE
Support back/forward navigation with mouse

### ISSUE THREAD

**Issue by dustinpoissant** [jiahaog/nativefier#297]
### Description
I have a back button on my mouse and a back button on my keyboard. Also the backspace button use to go back in Chrome <54 (now alt+left in chrome 54+) but none of these buttons seem to do anything for nativifier apps.

### Steps to Reproduce Issue
1. Open a nativifier app
2. Navigate at least one page deep into the app.
3. Click the "back" button on a mouse / keyboard or backspace or Alt+left, none of these combinations navigate the app back to the previous page.

### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v4.2.2`
- OS: `Windows 10`
- Architecture `AMD64`

**Comment by danimalweb** [comment]
Same issue here.

**Comment by gsantner** [comment]
Yep, back, CTRL+Wheel for zooming (and pretty much every other combination, which I usually use while browsing do not work)

**Comment by sh06un** [comment]
I find that only single-page apps really benefit from this without some basic browser functionality so +1 on this feature.

**Comment by dustinpoissant** [comment]
This is the only thing preventing me from using nativefier. Without this id rather just use a shortcut that opens chrome.

**Comment by dschotman** [comment]
If you press `Alt` button (on Windows, not sure about other OS) but then it shows a top left menu which includes the following options:
![image](https://user-images.githubusercontent.com/17751791/75990767-a8c98900-5ef5-11ea-8e8e-039ad5c8252f.png)

It's different from what we're used to at any browser but still you can navigate in history

**Comment by ronjouch** [comment]
Alt+Left/Right now work to back/forward. I renamed the issue to focus on mouse keys.

**Comment by ronjouch** [comment]
Closing as wontfix until this lands in Electron proper. See https://github.com/electron/electron/issues/6996 , electron maintainers are not interested in adding support, and https://github.com/electron/electron/issues/6996#issuecomment-423873660 recommends using third-party package [mouse-forward-back](https://www.npmjs.com/package/mouse-forward-back), which would introduce binary module hell and X/Wayland/macOS/Windows-specific problems that we shouldn't have to deal with. Please contribute a patch to https://github.com/electron/electron/issues/6996 if you want this fixed.

**Comment by gsantner** [comment]
How about zoom with CTRL + mousewheel?

**Comment by ronjouch** [comment]
> How about zoom with CTRL + mousewheel?

@gsantner tracked in https://github.com/jiahaog/nativefier/issues/379 , this one is easy and I'd like it too, will ad it someday soon.

**Comment by gsantner** [comment]
cool, thanks!
