### ISSUE TITLE
command line flags -h (help) and -h (height) collide

### ISSUE THREAD

**Issue by dlindenkreuz** [jiahaog/nativefier#30]
```
Usage: nativefier [options] <targetUrl> [dest]

  Options:

    -h, --help                      output usage information
    ...
    -h, --height <value>            set window height, defaults to 800px
```

**Comment by jiahaog** [comment]
Thanks for this. Do you think the shortened version of height (and other flags) are necessary? Usually I would enter the full `--height` as it's a lot clearer.

**Comment by maxwellb** [comment]
I would expect -h to be --help, primarily.

**Comment by dlindenkreuz** [comment]
i second that. i'd use abbreviated names for generic flags such as 'help'.

also, another collision happens with `-p / --pretend` and `-p / --platform`

**Comment by bsonntag** [comment]
You could use `-H` and `-W` for `--height` and `--width`.
