### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by kyroskoh** [jiahaog/nativefier#300]
### Description

I have built OSX version ("darwin", x64) via my Windows x64 Machine but the latest release of Mac is now macOS as it stated it is not compatible.

### Steps to Reproduce Issue

Use the latest release of macOS, 10.12 (Sierra).

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v4.5.0`
- OS: `Windows`
- Architecture `x64`
- Stack trace from the error message (if any): No Error.

**Comment by ronjouch** [comment]
Hey @kyroskoh thanks for the feedback! I've read reports of Nativefier working fine under Sierra, could you be a bit more precise about what doesn't work?

**Comment by ronjouch** [comment]
Closing after two weeks as `need info` and successful tests under macOS Sierra. @kyroskoh feel free to chime in and re-open the discussion anytime.
