### ISSUE TITLE
Can't generate/download files from website

### ISSUE THREAD

**Issue by imagins** [jiahaog/nativefier#305]
While generating an app from the command prompt I realized that all the js that is supposed to generate Excel files from tables or generate and download backup files from the website won't work inside the app. (They work on all tested browsers). Did anyone manage to find a fix for this or is there something else I need to do?

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v6.9.1`
- OS: `Windows 7`
- Architecture `64`

**Comment by ronjouch** [comment]
@imagins thanks for the feedback! I'm not sure I understand your problem correctly, let me reformulate: you bundled a site that lets you download files, but downloading under Nativefier doesn't work. Right?

If I'm understanding correctly, your version of Nativefier should handle downloading of files right into your OS Downloads folder; this was implemented after https://github.com/jiahaog/nativefier/issues/185 . Can you check into your Downloads folder?

* If you confirm downloading works, I agree the downloading should be more visible and created issue https://github.com/jiahaog/nativefier/issues/335 for that.
* If downloading actually fails for you, can you give more debug information? (site used, steps to download a file)

**Comment by ronjouch** [comment]
Closing after two weeks as `need info`. @imagins feel free to chime in and re-open the discussion anytime.
