### ISSUE TITLE
On OS X Text Search (Cmd+F) Doesn't work anymore on version 7.0.1

### ISSUE THREAD

**Issue by brunorsini** [jiahaog/nativefier#306]
### Description

Absolutely needed for all of my workflows... Switched from another product to nativefier specifically for text search capability but now it's gone :(

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by swrobel** [comment]
It never worked... https://github.com/jiahaog/nativefier/issues/29
