### ISSUE TITLE
URL validator doesn't like mDNS addresses

### ISSUE THREAD

**Issue by stackfull** [jiahaog/nativefier#308]
### Description
Supplying URLs ending in `local.` are disallowed.

### Steps to Reproduce Issue
`nativefier "http://mything.local.:8080/app"`

### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v7.3.0`
- OS: `MacOS`
- Architecture `x86_^4>`
- Stack trace from the error message (if any)

```
/Users/paul/.yarn-config/global/node_modules/nativefier/lib/options/normalizeUrl.js:25
        throw 'Your Url: "' + normalized + '" is invalid!';
        ^
```

**Comment by ronjouch** [comment]
@stackfull thanks for the report; I didn't know such a thing exists. One question: is Chrome happy with this and able to open the URL?

**Comment by stackfull** [comment]
I can only vouch for browsers on Macs. But, yes, chrome can run the app with that URL. They are how "bonjour" addresses appear. I believe "avahi" on linux boxes resolve the addresses. In my case, there is a raspberry pi music player on my network using `musicbox.local.`

**Comment by ronjouch** [comment]
> *"I can only vouch for browsers on Macs. But, yes, chrome can run the app with that URL. They are how "bonjour" addresses appear. I believe "avahi" on linux boxes resolve the addresses. In my case, there is a raspberry pi music player on my network using `musicbox.local.`"*

@stackfull alright, thanks for the fast feedback 👍, un-marking as needinfo. However, I have no mDNS service to test a fix, could you test one for me? The fix would simply be to enable an option exposed by the validator library we use to validate URLs:

1. Open the `normalizeUrl.js` file reported by the error message and go to the line where current nativefier `throw`s an error. Then, replace:

```js
    if (!validator.isURL(normalized, {require_protocol: true, require_tld: false})) {
```

with

```js
    if (!validator.isURL(normalized, {require_protocol: true, require_tld: false, allow_trailing_dot: true})) {
```

2. Re-run nativefier on your mDNS address (also, please ask for a recent Electron/Chrome): `nativefier --electron-version 1.6.6 "http://mything.local.:8080/app"`
3. Run the nativefied app.

→ Does building work and does the nativefied app work as expected? If yes to both and if you have the time for that, go ahead and submit a PR!

**Comment by ronjouch** [comment]
@stackfull ~ding~, this is your friendly reminder: when you get a few minutes for that, could you try the patch above on your side? Thanks! 😃

**Comment by stackfull** [comment]
Works perfectly!

**Comment by ronjouch** [comment]
> Works perfectly!

@stackfull thanks for the test 👍, pushing the fix.
