### ISSUE TITLE
Add Homebrew support

### ISSUE THREAD

**Issue by kaishin** [jiahaog/nativefier#31]
Any plans to add Homebrew support? `npm` and `rubygems` are language-specifc dependency managers and are not suitable for distributing software on OS X. I'd open a PR if this was something I can do myself but alas I can't.

**Comment by jiahaog** [comment]
You're right, I'll get on this in a bit, just need to familiarise myself with creating a homebrew formula.

**Comment by jiahaog** [comment]
Hey there, I'm really confused with the homebrew formula syntax, do you know of any formulas of npm global modules that I can follow?

**Comment by farazfazli** [comment]
@jiahaog Please see this: http://apple.stackexchange.com/questions/97065/how-do-i-write-a-homebrew-recipe

**Comment by weihanglo** [comment]
The pull request homebrew/homebrew-core#9142 is accepted by homebrew team 🎉 . 
However, the formula lack for robust tests due to a [known issue](https://github.com/visionmedia/node-progress/pull/139) of node-progress.
