### ISSUE TITLE
Graphics Switching MacBook Pro

### ISSUE THREAD

**Issue by momosby** [jiahaog/nativefier#312]
### Description
When using Nativefier for Creating a Messenger.com (Facebook Messenger) App, the helper Process switches to discrete Graphics.

I already inspected pLists for both the Darwin app and the Messenger Helper pList. 
NVSupportsAutomaticGraphicsSwitching ist set to <TRUE> on both. 

### Steps to Reproduce Issue

nativefier --name "FB Messenger" "https://www.messenger.com" --counter -f --hide-window-frame

Run.

Observe GPU via gfxCardStatus

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `7.0.1`
- Version of Node.js (run `$ node --version`): `v7.2.1`
- OS: `<macOS 12.2.2>`
- Architecture `<x64>`

MacBook Pro Retina 15" Touchbar, Radeon Pro 460 / 4 GB

**Comment by maxdec** [comment]
I faced the same and got curious, so I did some research.
It seems to be an issue with Chrome and hardware acceleration.
Open https://messenger.com in a Chrome tab and you will see the same.

In Google Chrome you can disable hardware acceleration in the settings. I did that and now I doesn't switch to the dedicated GPU. But the window flickers and the FPS meter shows some low values.
And honestly I can't use the app in this situation.

So, even though it's possible to disable the GPU in Electron too (`app.disableHardwareAcceleration()`) and I just tried it on my nativefied app, I will stick to using the dedicated GPU until the Chrome rendering engine improves.

**Comment by ronjouch** [comment]
👍 for the research, @maxdec. We won't do any better than Chrome, then.

@momosby @maxdec closing this for now, if the situation gets better in Chrome feel free to chime in and we'll see what's within Electron reach by then. Thanks to both of you!
