### ISSUE TITLE
Packaging fails on macOS due to permissions error when moving electron from temp folder to ~/.electron

### ISSUE THREAD

**Issue by lockerdevs** [jiahaog/nativefier#315]
### Description

Hi i'm just trying to use this, when i'm doing the step:
**nativefier --name "Some Awesome App" "http://medium.com"**

Got and error when the terminal start to downloading and installing,  anyone know why? 

### Steps to Reproduce Issue
`{ Error: EACCES: permission denied, rename '/var/folders/3l/4l76c6p913jb3syqj78xqq380000gn/T/electron-tmp-download-19299-1485541144681/electron-v1.1.3-darwin-x64.zip' -> '/Users/luisfsabidoc/.electron/electron-v1.1.3-darwin-x64.zip'
  errno: -13,
  code: 'EACCES',
  syscall: 'rename',
  path: '/var/folders/3l/4l76c6p913jb3syqj78xqq380000gn/T/electron-tmp-download-19299-1485541144681/electron-v1.1.3-darwin-x64.zip',
  dest: '/Users/luisfsabidoc/.electron/electron-v1.1.3-darwin-x64.zip' }
  packaging [========================================          ] 80%`

### Specifications
- Version of Nativefier:  `v7.0.1`
- Version of Node.js: `v7.4.0`
- OS: `Sierra  v10.12.3`

**Comment by ronjouch** [comment]
@lockerdevs thanks for the feedback 👍 . We did a big dependencies upgrade as part of Nativefier 7.2.0, and I vaguely remember one of them fixed a bug along those lines. Could you try this new version and report if the problem persists? Thanks!

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. @lockerdevs feel free to chime in and re-open the discussion anytime 😃!
