### ISSUE TITLE
Support clearing data (cookies, cache, localstorage, etc) on exit

### ISSUE THREAD

**Issue by thea1exei** [jiahaog/nativefier#316]
Hello, tell me how to do to clear the cache in applications AppData\Roaming\<appname>-nativefier-<hash> folder on exit?
I found the function menu button, can you do something like that at the closing of the outlet or remove the application cache?
Thanks.

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v7.4.0`
- OS: `Windows`
- Architecture `32, 64`

**Comment by a1exBorn** [comment]
I found the cache cleaning feature on the menu button, tell me whether it is possible to insert it before exiting? I can not understand what the function of the output of the application is responsible.
Thank you.

`    const clearAppData = () => {
        dialog.showMessageBox(mainWindow, {
            type: 'warning',
            buttons: ['Yes', 'Cancel'],
            defaultId: 1,
            title: 'Clear cache confirmation',
            message: 'This will clear all data (cookies, local storage etc) from this app. Are you sure you wish to proceed?'
        }, response => {
            if (response === 0) {
                const session = mainWindow.webContents.session;
                session.clearStorageData(() => {
                    session.clearCache(() => {
                        mainWindow.loadURL(options.targetUrl);
                    });
                });
            }
        });
};`
[https://github.com/jiahaog/nativefier/blob/development/app/src/components/mainWindow/mainWindow.js#L81](url)

**Comment by Amrzxc** [comment]
anyone get this work ???

**Comment by llimz** [comment]
+1

I would really appreciate to get this feature.

**Comment by allo-** [comment]
It would be a nice feature, if it would only delete cookies, which are for other origins than the ``--internal`` URLs.

**Comment by bartektenDev** [comment]
**If you're just looking to clear cache:**
(not my code, just taken from Amrzxc)

`var session = mainWindow.webContents.session;
               session.clearStorageData(function() {
                   session.clearCache(function() {
                   });
               });`
