### ISSUE TITLE
Notify App Crash and Delayed Notifications

### ISSUE THREAD

**Issue by ChrisKendallVA** [jiahaog/nativefier#317]
When the browser window is closed and a notify message comes through, the app crashes and you cannot open it, you have to Ctrl+alt+delete to force the app to close. (this also occurs even when the app is in the foreground and active)

If you do manage to open the app, you cannot click on anything, just like you have loaded up an image on image viewer.

We have also noticed that Notifications can sometimes take a very long delayed amount of time to come through. The sound notify passed fine but sometimes up to 30 mins before the desktop notification appears.

- Version of Nativefier : `v7.0.1`
- Version of Node.js : `v6.0.0`
- OS: `win32`
- Architecture `ia32`

**Comment by ronjouch** [comment]
@ChrisKendallVA thanks for the bug report! To sum up the base problem, notifications crash/freeze your nativefied app. We'll need more debug information, could you:

* Try re-packaging your app with the latest Nativefier 7.1.0 and a recent Electron (e.g. 1.6.6) using option `--electron-version` 
* Precise the nativefied URL
* Precise your OS

**Comment by ChrisKendallVA** [comment]
well i am pleased to say that by following the above, The crashing upon notify no longer (or at the moment) exists. Also the JS Errors when downloading a file no longer exist either but do display a blank popup box with no download indicator :)

**Comment by ronjouch** [comment]
> crashing upon notify no longer (or at the moment) exists

@ChrisKendallVA 👍, thanks for the feedback! Closing.

> Also the JS Errors when downloading a file no longer exist either but do display a blank popup box with no download indicator :)

@ChrisKendallVA yeah the download experience sucks (downloading isn't explicit enough, and neither is the path to downloaded file), this is tracked in issue https://github.com/jiahaog/nativefier/issues/335.
