### ISSUE TITLE
Right-clicking should respect custom Javascript contextual menus

### ISSUE THREAD

**Issue by russianryebread** [jiahaog/nativefier#319]
### Description
Certain sites (Jira, in this case specifically) allow you to right click on certain pages / certain elements, and they provide a custom contextual menu to do things in the web app.  Nativefier overrides that, and shows the "open in default browser / open in new window" menu.

### Steps to Reproduce Issue
Create Native app from JIRA, AWS, etc; any site that has custom right-clicking functionality, and then right-click.

### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v7.4.0`
- OS: `macOS 10.12.3`

**Comment by Rob-pw** [comment]
In my case, I am able to see the custom context menu appear, with the Nativefier right click menu appearing in-front of it.

**Comment by HersonHN** [comment]
I have the same issue with Google Docs, I hope this issue get resolved soon.

**Comment by ronjouch** [comment]
Nativefier option `--disable-context-menu` will brighten your day :) . See `nativefier --help` for the full list of options.
