### ISSUE TITLE
Ability to copy and paste a URL with keyboard shortcut

### ISSUE THREAD

**Issue by pdame** [jiahaog/nativefier#32]
When you use applications like Asana, you often need to copy the URL of the page (task) being viewed so you can share it other locations. Without an address bar, there's no way to review, copy or paste the URL. How about adding a keyboard shortcut (or menu command) to copy the current URL. If a URL is in the clipboard and it matches the app's domain, provide an option to use it.

**Comment by jiahaog** [comment]
Yeap, this seems like a simple fix, I'll look into it. What do you mean by the following though:

> If a URL is in the clipboard and it matches the app's domain, provide an option to use it.

**Comment by somebody1234** [comment]
I'm pretty sure @pdame means if the URL in the clipboard is in the same domain as the Nativefied webpage, provide an option (presumably a shortcut/toolbar option) to go to the URL in the clipboard.

**Comment by pdame** [comment]
Thank you!
