### ISSUE TITLE
Silverlight Plugin

### ISSUE THREAD

**Issue by danimalweb** [jiahaog/nativefier#320]
Does anyone know how I would package the Silverlight plugin with Nativefier? Any starting point would be helpful.

I looked through the issues in Electron it looks like some plugin support is possible.

**Comment by ronjouch** [comment]
@danimalweb looks like it's possible, yeah, but I have no experience with it :-/ , try looking at https://github.com/electron/electron/issues/295 . If you end up with something working we'll be happy to accept documentation/guidelines to do that 😃.
