### ISSUE TITLE
Add single-instance option

### ISSUE THREAD

**Issue by anhskohbo** [jiahaog/nativefier#322]
Maybe someone (me) need a app with single instance instead of multiple instances by now.

Electron already support this: `makeSingleInstance`

https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback

An option when build app would be nice with this.

**Comment by darrenhaken** [comment]
@jiahaog any idea when this might be merged? Myself and a few others are keen for it.
