### ISSUE TITLE
Cookies are not saved. And no way to auto login.

### ISSUE THREAD

**Issue by gsantner** [jiahaog/nativefier#324]
### Description
I tried nativefier now on 3 services - Shaarli, NextCloud and TT-RSS. Logged in, browse some things. closed app. opened again some seconds later. have to login again.

There is also no option to provide some kind of credentials to application, and a path to make a POST request to. Without any of both working, I cannot see any use of this project. 

### Steps to Reproduce Issue
Make app from any webpage and login.  
close app  
see that nothing was saved..

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.0.1`
- Version of Node.js (run `$ node --version`): `v7.6.0`
- OS: `Arch`
- Architecture `x64`

**Comment by gasova** [comment]
I have the same issue. What did you do ? 

Thanks.

**Comment by gsantner** [comment]
I did just send POST requests at login with credentials loaded from gnome-keychain. But I quit the project then, may be easy to get a webpage displayed in a own window with this - but nothing more

**Comment by gasova** [comment]
Thanks, I just figured out why it wasn't working, in codeigniter's config.php the session expiration was set to 0 ("infinite"). I don't know if it's a bug in CodeIgniter 3.x but when I changed 0 with 1 year in seconds it worked.
