### ISSUE TITLE
Is this project supported?

### ISSUE THREAD

**Issue by darrenhaken** [jiahaog/nativefier#326]
I've seen many issues which have not had comments back on them and I was wondering if this project is still actively being maintained?

Is there room for more maintainers?

**Comment by ronjouch** [comment]
Project seems dead. I contacted @jiahaog by email in January and February, asking the same and proposing help, (starting with cutting a release, reviewing PRs, triaging issues). Didn't get an answer, I hope s/he's fine; is probably just busy, his/her GitHub activity shows recent activity in private repos.

@darrenhaken I'm pinging them once more, let's wait for a few days, then I'd be glad to help with a fork and maintenance. Thoughts?
