### ISSUE TITLE
Update dependencies (starting with Electron)

### ISSUE THREAD

**Issue by ambonium** [jiahaog/nativefier#327]
Absolutely love Nativefier @jiahaog, but the dependencies seem to be outdated, is it going to be upgraded anytime soon?
Thanks in advance.

**Comment by maxdec** [comment]
Do you know that you can choose the Electron version to use?

```
nativefier --name Messenger --electron-version 1.6.2 https://messenger.com
```

**Comment by ronjouch** [comment]
> *"is it going to be upgraded anytime soon?"*

@ambonium the original maintainer and two new maintainers are trying to get the train running again. We produced a new release 7.1.0 incorporating unmerged PRs, and releasing a new version with updated dependencies is high on our list up next. Hang on, and use @maxdec's suggestion to pick your Electron until then :) . Cheers!

**Comment by danimalweb** [comment]
I bumped many of the dependencies in my local version. No major issues so far.

**Comment by ronjouch** [comment]
> *"I bumped many of the dependencies in my local version. No major issues so far."*

@danimalweb AWESOME 👍 😍 💯, and thanks for the fast feedback. I'm currently starting helping maintenance with a big issue triage and haven't look at deps yet. If you have the time for that, a PR would be super awesome! If you're going ahead with this, maybe by the way incorporate the deps deletions proposed https://github.com/jiahaog/nativefier/pull/337 !

cc @jiahaog @darrenhaken

**Comment by darrenhaken** [comment]
I'll be working on testing this and we should have a release our shortly
