### ISSUE TITLE
Global Hotkey

### ISSUE THREAD

**Issue by codingmatty** [jiahaog/nativefier#330]
### Description

Electron seems to have support for global hotkeys, so it would be awesome to be able to use that feature with this tool.
https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md

**Comment by ronjouch** [comment]
Hi @codingmatty, thanks for the feedback!

Could you precise what you'd expect from this feature and provide use case(s) you have in mind? What would you use it for? What would the hotkey do?

In the meantime, if we are talking about simply focusing/unfocusing a nativefied app, I suggest looking at [AutoHotkey](https://www.autohotkey.com/) under Windows, and my own [marathon](https://github.com/ronjouch/marathon) for Linux.

**Comment by ronjouch** [comment]
Closing after two weeks as `need info`. @codingmatty feel free to chime in and re-open the discussion anytime.

**Comment by imadphp** [comment]
@ronjouch My feature request would probably be related to this one: it would be support for the media keys like play/pause. Right now the play key just starts iTunes. It might be related to this issue as well: https://github.com/electron/electron/issues/5268

Thanks in advance!

**Comment by ronjouch** [comment]
> My feature request would probably be related to this one: it would be support for the media keys like play/pause. Right now the play key just starts iTunes. It might be related to this issue as well: [electron/electron#5268](https://github.com/electron/electron/issues/5268)

For me, using electron v8.0.0-beta.3 (which you can use with Nativefier flag `-e`), the play/pause media key works right now under Linux to pause/play Bandcamp iframes.

**Comment by imadphp** [comment]
@ronjouch Thanks a lot for the quick reply! Unfortunately this version of Electron immediately crashes after start in OSX Catalina 10.15. I'm not sure if it's related to electron or nativefier. I'll try again when 8.x is out of beta.
