### ISSUE TITLE
Adblock integration?

### ISSUE THREAD

**Issue by featdd** [jiahaog/nativefier#34]
any plans of a adblock integration?

**Comment by jkatzer** [comment]
what is the need for adblock?
ads: If you are wrapping something like JIRA, or Trello, or Facebook Messenger, you don't need to worry about ads. 
privacy: If you are serious about privacy you may want to consider something like privoxy. Which can filter on the http level. also.

as a simple alternative to Fluid, there are many user stories i would prioritize over this.  mostly something like: #35

**Comment by featdd** [comment]
Thought it for sites using annoying ads and popups.
Not most important but useful in some case I think.

**Comment by jkatzer** [comment]
@featdd this app makes more sense for wrapping web apps instead of something like the new york times. but seriously, try checking out privoxy.

**Comment by jiahaog** [comment]
@featdd Nope, no plans at the moment. I do agree with what @jkatzer said, I don't think this is an important issue if you're wrapping web apps. Though it would be cool to have a `--no-ads` cli option to disable ads on pages like Facebook, you're more than welcome to submit a pull request if you can find a way to do this.

**Comment by featdd** [comment]
don't know how difficult it can be to integrate [adblock](https://github.com/adblockplus/adblockpluschrome), chrome plugin can be found on github.

**Comment by zweicoder** [comment]
@featdd It should be possible to port Chrome Extensions like Adblock into a `.js` script that is loaded by `app/src/preload.js`
