### ISSUE TITLE
Support for Output of One Packaged EXE on Windows

### ISSUE THREAD

**Issue by xd1936** [jiahaog/nativefier#342]
### Description
It would be really nice if `nativefier` would (perhaps optionally) spit out a single portable EXE when run, instead of having it output a bunch of files in a folder.

### Specifications
- Version of Nativefier: `v7.1.0`
- Version of Node.js: `v6.10.2`
- OS: `Windows`
- Architecture `x64`

**Comment by ronjouch** [comment]
Thanks for the feedback @xd1936 it would be awesome, yeah. But I'll close this for now:

* It would be electron-packager's job, who themselves closed https://github.com/electron-userland/electron-packager/issues/243 "How can I create self-contained executables in Windows and GNU/Linux?" ...
* ... as electron closed their https://github.com/electron/electron/issues/914 "Atom & App in one executable" with these words:

> *"The structure of Chromium is not designed for putting everything into an executable, and it would take too much effort to do that. So unless that situation in Chromium changed atom-shell won't support this."*

Maybe someday!

**Comment by xd1936** [comment]
Womp womp. Thanks for the info!
