### ISSUE TITLE
Javascript added via --inject is only executed once

### ISSUE THREAD

**Issue by oliverandrich** [jiahaog/nativefier#344]
### Description

I added some javascript via `--inject` and expected it to be injected into all web pages. But I only see it on the first page. It is not clear to me, if I misunderstood the feature or if it is broken.

### Steps to Reproduce Issue

`nativefier --inject my.js https://trello.com`

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.1.0`
- Version of Node.js (run `$ node --version`): `v6.10.2`
- OS: `<OS>` macOS
- Architecture `<ARCH>` x64

**Comment by ronjouch** [comment]
Hi @oliverandrich, thanks for the feedback. I can't reproduce the problem, though:

![ponies](https://cloud.githubusercontent.com/assets/522085/25067807/7e509952-221c-11e7-85d0-397378e672ba.gif)

→ Can you precise from/to which URL fails to trigger your script? From the nativefied app, open the Devtools with `Cmd+Shift+I` bo, then type `window.location.href`. Perform the action you'd expect to trigger your script, and re-get `window.location.href`.

**Comment by oliverandrich** [comment]
Damn, somehow it works now. I am not sure, what I did break yesterday. Thanks for the response and the effort you put into creating a video.

**Comment by asmirbelkic** [comment]
Hi, i have the same issue can @oliverandrich explain how dd you solve the problem. The script i use is runned only once on domcontentload and never on page change i have to manually refresh the page by F5 (disable cache in devtool doesn't help)
