### ISSUE TITLE
after convert to app there's No back or forward button..how do i add those?

### ISSUE THREAD

**Issue by Phe0nix** [jiahaog/nativefier#350]
after convert to app there's No back or forward button..how do i add those?

**Comment by Phe0nix** [comment]
is there any command for these?

**Comment by ronjouch** [comment]
@Phe0nix thanks for the feedback :)

There's no back/forward/reload/url bar and buttons in Nativefier apps, no. The goal is to package web applications and let the webapps themselves be the way users navigate inside them, with minimal interface around.

I'll close that for now, but feel free to add more comments, with enough understanding (please provide use cases, perceived benefits, examples where the lack is particularily painful, etc.) we can reconsider this into a feature request

**Comment by jb510** [comment]
FWIW, I too would love back/forward/reload/home _and_ on page text search.  I do not want a URL bar, just 4 icons plus a way to search for text on a page.  

Use case: I use Natifiver for several web apps like our project managment tool and it's really helpful to be able to search a long page for key words in a long threaded conversation.  

Additionally, when I click into an issue/task it's really nice to back out (I used cmd-[) but my normal method would be a button or right-click and back.  Yes, the web app provides a link backward to the "issue list" but it's not the best UI and hard to find/click.

Somewhat related #297

**Comment by jamesdh** [comment]
This basically renders Nativefier useless in web apps like GitHub, which are heavily dependent on linking between issues/PR's and subsequently using the back/forward buttons (or swiping on MacOS) extensively.
