### ISSUE TITLE
Icons not working: app attempts to load `icon.png`, ignoring `icon.ico`

### ISSUE THREAD

**Issue by danhawkes** [jiahaog/nativefier#351]
### Description
Running the example in the screencast (`nativefier web.whatsapp.com`), an icon is downloaded to `resources/app/icon.ico`, but launching the app does not show the icon. 

Strace shows the app is attempting to load `icon.png`. Manually converting the `.ico` to `.png` works to make the icon visible.

### Steps to Reproduce Issue
- `nativefier web.whatsapp.com`
- launch app

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.2.0`
- Version of Node.js (run `$ node --version`): `7.9.0`
- OS: `Ubuntu (gnome) 16.10`

**Comment by danh-spaggetti** [comment]
Apparently this is a linux-specific issue as it seems to work on OSX.

**Comment by ronjouch** [comment]
@danhawkes weird, using nativefier 7.2.0 and node 7.9.0 I get a PNG, which is visible in Alt+Tab and as Gnome Shell appicon, see below. Not the first time we get unreproducible reports about icon extraction; we'll have a look at the logic, thanks for the report 👍.

In the meantime, please try to work around the bug by manually extracting/finding a good PNG icon, then passing it at build time using the `--icon` flag (see `nativefier --help` for the full list of options). Does that work for you?

```bash
/opt/n nativefier web.whatsapp.com
Packaging app for platform linux x64 using electron v1.6.6
App built to /opt/n/whats-app-web-linux-x64

/opt/n sudo strace -o whatsapp.log ./whats-app-web-linux-x64/whats-app-web

/opt/n grep 'icon\.' whatsapp.log
open("/opt/n/whats-app-web-linux-x64/resources/app/icon.png", O_RDONLY) = 64

/opt/n la /opt/n/whats-app-web-linux-x64/resources/app/icon*
-rw-r--r-- 1 ronj ronj 47K Apr 26 07:43 /opt/n/whats-app-web-linux-x64/resources/app/icon.png
```

Appicon:  
![whatsapp-icon-gnome-shell](https://cloud.githubusercontent.com/assets/522085/25433037/fd5115b6-2a54-11e7-8b0a-7878480111e6.png)

**Comment by danhawkes** [comment]
Hmm, not sure what's happened, but I've upgraded to 7.3.1 and it seems to work. Will close this for now until I can reproduce the issue.
