### ISSUE TITLE
Access Electron shell on injected JS-files

### ISSUE THREAD

**Issue by Blueblau** [jiahaog/nativefier#358]
Is it somehow possible to access the [Electron Shell](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl) if you would like to open links in the user's default browser?

**Comment by ronjouch** [comment]
Hi @Blueblau, thanks for the feedback. Opening links in the user's default browser is doable via the "Open with default browser" context menu :)

**Comment by Blueblau** [comment]
Yeah, I know... But I would like to control that with Javascript, so that all external links would be opened in the users default browser. Is it possible within an injected script — to access the Electron shell methods?

**Comment by ronjouch** [comment]
> *I would like [...] all external links [...] opened in the users default browser*

@Blueblau that's clearer, thanks. Could `--internal-urls <regex>` work for you? See discussion at https://github.com/jiahaog/nativefier/issues/212#issuecomment-292689727 .

**Comment by Blueblau** [comment]
Thanks... I'm building from the scriptfile, not with the CLI. So `internalUsrls: <regex>` should be the equal solution right? Or does some things work with the CLI and not within the scriptfile?

**Comment by ronjouch** [comment]
@Blueblau should be, yes! And things *should* work equally well from the CLI vs. programmatically, if they don't it's a bug, and then please share your triggering code for easy reproducing on my side :) .

By the way, I have the same request on your bug https://github.com/jiahaog/nativefier/issues/359 "Build to folder", which is also about programmatic usage (this time of the `out` option): please share your code on the bug, it makes things easier for anyone to test and work on a fix.

Thanks.
