### ISSUE TITLE
Build to folder

### ISSUE THREAD

**Issue by Blueblau** [jiahaog/nativefier#359]
I've been unable to build to a folder, using the Node script to build. The documentation says nothing about the `out` option, but I imagine that this is where I should define the folder. 

My Node script has the following `options`.

```javascript
var options = {
    ...
    out: './builds',
    ...
};
```

I expected it to build to `./builds` but it builds to the root of the project.
I tried to create an empty folder, to see if that made a difference but it didn't.

What am I missing?

System: Mac OS 10.12.4
Node version: v7.7.1

**Comment by ronjouch** [comment]
@Blueblau can you share a ready-to-run js containing the code triggering the bug, pls? Thanks!

**Comment by ronjouch** [comment]
Closing as needing feedback. @Blueblau feel free to chime in with a minimal reproduction script, we'll re-open the discussion 😃.
