### ISSUE TITLE
Support --disable-gpu flag

### ISSUE THREAD

**Issue by kevinschaich** [jiahaog/nativefier#364]
### Description

Electron is using the discrete, high-performance GPU in very simple webapps. I think it would be nice to support a flag that uses the integrated, power-efficient Intel one for simple apps. This issue was mentioned in #312, but we never found a solution. In https://github.com/aluxian/Messenger-for-Desktop/pull/1184/commits/bedec614dabce14df3ef86c4a190be10e70e7410, the fix seems to be `app.disableHardwareAcceleration()`.

Please add CLI argument `--force-integrated-gpu` that invokes the **electron** `--force-integrated-gpu` flag for apps that will knowingly not require any intensive GPU processing. 

### Steps to Reproduce Issue

Run: 

`nativefier drive.google.com -n "Google Drive"`

Open and inspect in activity monitor:

![image](https://cloud.githubusercontent.com/assets/9244728/26084317/425d3bcc-39a9-11e7-9843-7d0df45f03ec.png)

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.3.1`
- Version of Node.js (run `$ node --version`): `v7.9.0`
- OS: `MacOS 10.12.4`
- Architecture `x64`

MacBook Pro Retina 15" w/ touch bar, Radeon Pro 460 / 4 GB

**Comment by ronjouch** [comment]
@kevinschaich thanks for the feedback! One thing, though:

> "*Electron is using the high-performance GPU...*"

Yes.

> ... *"which is both a drain on processing power and battery"*

You lost me here; all other things equal, GPU usage *saves* power and battery as compared to doing everything on the CPU. Looking at the title, I think I understand you want to force Electron to use the *integrated* (Intel, power-efficient) GPU, but Electron has no such feature as far as I know.

The request for a `--disable-gpu` flag remains valid (could be useful e.g. to work around crashy GPU drivers), so renaming the issue and leaving open as feature request.

**Comment by kevinschaich** [comment]
@ronjouch Thanks for the correction in terminology. As a revised problem statement, I think it would be helpful to have a `--disable-gpu` flag that uses the Intel integrated, power efficient GPU. Check out this API doc for electron: 

https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration

I believe if you call `app.disableHardwareAcceleration()` in `app/src/main.js`, it will work as expected.

**Comment by ronjouch** [comment]
@kevinschaich thanks for the fast reponse 👍, that's clearer: you're asking for a `--force-integrated-gpu` / `--forbid-discrete-gpu` flag. Would be super neat, agreed, but that doesn't seem likely for now:

* Reading [Electron docs / `app.disableHardwareAcceleration()`](https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration), I'm not sure your reading is correct. The doc states it *"disables hardware acceleration for current app"*, which to me reads *any kind* of HW acceleration, including your Intel chip. Said differently, it looks like the programmatic equivalent to Chromium flag `--disable-gpu`, which will force all computation to your CPU, ignoring your Intel chip. Tests/contradictions welcome, though!
* Reading https://github.com/electron/electron/issues/4380 , it still looks like no such switching feature is exposed by Electron. Commenters seem to be pointing towards helper tools such as [gfxCardStatus](https://gfx.io/), mentioned in the [Messenger-for-Desktop issue](https://github.com/Aluxian/Messenger-for-Desktop/issues/1172#issuecomment-277029497).

**Comment by kevinschaich** [comment]
@ronjouch perhaps this could still be useful for the prior issue you mentioned (e.g. to work around crashy GPU drivers), and perhaps we rename it either to `--disable-hardware-acceleration` or `--disable-gpu` as originally suggested?

**Comment by ronjouch** [comment]
@kevinschaich yup, leaving the issue open as is, asking for a `--disable-gpu` flag that disables acceleration altogether 👍.

**Comment by pshpsh** [comment]
`_electron.app.disableHardwareAcceleration()` needs on linux as default, if `--ignore-gpu-blacklist` isn't activated.

https://github.com/hql287/Manta/pull/128
