### ISSUE TITLE
Localstorage not accessible on app restart

### ISSUE THREAD

**Issue by haris4063** [jiahaog/nativefier#366]
I store users login credentials in localstorage to avoid login every time user visits my web app. But after converting my app via nativefier i have to login every time i run app. Somehow localstorage data is not accessible after app restart.

**Comment by ronjouch** [comment]
@haris4063 thanks for the feedback, but I cannot reproduce the issue. I just tried `nativefier --name "n-localstorage" "http://html5demos.com/storage"` under Nativefier 7.4.0 / electron 1.6.6, both Windows and Linux, and confirm localstorage is persisted across app restart.

Please come back with more information (nativefier command, OS, reproduction steps) and we'll reopen the discussion 🙂
