### ISSUE TITLE
callcack release at render process process startup

### ISSUE THREAD

**Issue by zucher** [jiahaog/nativefier#368]
### Description
Could take into account this pb in release context please:
https://github.com/electron/electron/issues/3778

Thank you

**Comment by ronjouch** [comment]
Hey @zucher, thanks for the feedback. Would you mind elaborating and providing a test scenario describing the problem? What do you mean by "release context"?

**Comment by zucher** [comment]
in case of usage of native code with callback and a browser refresh, sorry in release, I mean reload context.

**Comment by ronjouch** [comment]
@zucher again, sincere thanks for the feedback, but there's little I can do with so little information.

You must realize no one is paid to maintain this piece of software and there's no customer support to help you do the clarifying job. *Your* best chance to get what you want is by making the effort of laying out the problem as clearly as possible, to convince us something is wrong, as painfully obviously as possible. So, all these will be very, very welcome: 

* Issue reproduction scenario
* Problematic nativefier command used
* Intuitions
* Proposals
* (And of course, code fixing the problem, but I don't like the typical "Patch welcome" response, it's disrespectful as the user may not have the interest/time/knowledge to fix the problem.)

Closing in the meantime, will re-open if you come back with more info.

**Comment by zucher** [comment]
Hi @ronjouch ,

I cleary understand your feedback, at the meantime I have the head to the grindstone on an application using nativefier, I'm also trying to improve your framework too (later pull request will come soon...).

I'm in line with you around the contribution on opensource projects. I will provided enough use case informations on the occurring problem as soon I possible.

Thank a lot @ronjouch for your contribution.
