### ISSUE TITLE
Nativefier windows xp

### ISSUE THREAD

**Issue by arres2k** [jiahaog/nativefier#373]
### Description
Hello,
I am trying to generate a web app for the bone windows xp what is the command please?

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.4.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `windows 7`
- Architecture `ai32`
- Stack trace from the error message (if any)

```
<Stack trace here>
```

**Comment by petrk94** [comment]
@arres2k as first, I recommend really hopeful for you to switch from Windows XP to a current Windows version.

To your question. To run it, you type in the cmd.exe

`nativefier --name "Some Awesome App" "http://medium.com"
`
and it create a folder with the name in the path your cmd.exe is opened.
So I recommend to change the directory to the Desktop and than run the nativefier.
