### ISSUE TITLE
Add options for system tray icon and behavior

### ISSUE THREAD

**Issue by jamiewilson** [jiahaog/nativefier#378]
Follows discussion in https://github.com/jiahaog/nativefier/issues/318 . For example, how [Icons8](https://icons8.com/) implements this in their interface:

![screen shot 2017-05-31 at 11 34 45](https://cloud.githubusercontent.com/assets/3308673/26683592/f8dca77c-46a9-11e7-91fc-f409bafc9783.png)

The available options from above are:

**When window loses focus**  
- Default behavior
- Keep on top
- Hide
- Fade

**Application icon is in**  
- Menubar and Dock
- Menubar
- Dock

***

BUT, sort of like you suggested, I think the bulk of this feature could be achieved with one additional option. Something like:

**[tray-icon-only]**
```
--tray-icon-only <path>
```
So this would encompass the following:
- Add the specified icon to the menubar/system tray
- hide the standard dock/taskbar icon
- hide the window when it loses focus (or just leave this the system default 'bring to front' behavior)

***

### But, I think this feature _could_ include the following additions (or something like them) to the options API:

**[tray-icon]**
```
--tray-icon <path>
```

As for the option of where to display the application icon:

**[show-icon-in]**
```
--show-icon-in <value>
``` 
I'm not sure how to describe this without using Mac-specific language, and maybe passing in a string like this would be a bad idea, but maybe available values could include both Mac and cross-platform equivalents. For example:

- "menubar"
- "dock"
- "menubar and dock"
- "taskbar"
- "system tray"
- "taskbar and system tray"

For what to do when the window focus is lost, this one is hard. Maybe...

**[hide-unfocused]**
```
--hide-unfocused
```

***

Anyway, let me know what you think about any of this. Happy to help work through this more if needed. Also, thanks for making Nativefier. I'm a big fan!

**Comment by Aidoboy** [comment]
That could be really cool for messaging apps, like Discord and GroupMe! I know Discord has a dynamic favicon that indicates unread status, could there be some way to pull that for the system tray icon?

**Comment by ronjouch** [comment]
> Discord has a dynamic favicon that indicates unread status, could there be some way to pull that for the system tray icon?

@Aidoboy the `--counter` option already does kind-of-that on macOS in the Dock; yes, would be nice to have similar behavior in this hypothetical tray feature. Regarding updating the *whole* icon using the app's favicon, that might mean horrible-looking tray icons (favicons are often smaaaall!). Not as ugly as in the (bigger) dock (see discussion at https://github.com/jiahaog/nativefier/issues/367#issuecomment-302695787 ), but staying with `--counter`'s behavior of *overlaying* a count on the icon might yield better results.

@jamiewilson @Aidoboy just a note to manage expectations: as long as no one does feature requests, they remain requests. There are lots to do and we're only a few maintainers; if you want to give a stab at implementing this feature, the [developer guide](https://github.com/jiahaog/nativefier/blob/master/docs/development.md) awaits you 🙂.

**Comment by jamiewilson** [comment]
@ronjouch Absolutely. I'll take a deeper look at the source and see if I might be able to tackle this myself.

@Aidoboy I think having a sort of 'active' state of the system tray icon could be good. But maybe we should break that idea into a different issue, since there might be more discussion needed around it in particular.

**Comment by Aidoboy** [comment]
@ronjouch Yeah, I was just talking about the tray icon. I wonder what overlaying the tray icon with the favicon would look like? Nova Launcher on Android does something like that. [Here's and Android Authority article on it.](http://www.androidauthority.com/nova-launcher-beta-update-adds-dynamic-notification-badges-759295/)

@jamiewilson That might be a good idea.

**Comment by ronjouch** [comment]
Closing this as https://github.com/jiahaog/nativefier/pull/457 added a `--tray` flag. I don't think the new flag covers everything discussed in this issue, but it's a start. Please try it, then once familiar it, feel free to discuss missing stuff and we can re-open with a list of incremental improvements. All props go to @omouren for the work on #457.

**Comment by fuzzy76** [comment]
When I want applications in the menubar, it is instead of having them in the dock. This implementation puts it both places. The lack of the `--show-icon-in`option makes it unusable for me.
