### ISSUE TITLE
Monkeypatch window.Notification for badge support

### ISSUE THREAD

**Issue by contra** [jiahaog/nativefier#38]
I noticed in the README you mentioned it wasn't possible to figure out when a desktop notification happened. Why not inject code that monkeypatches window.Notification and emits a `notification-message` to electron any time a new one is constructed? :thought_balloon:

**Comment by jiahaog** [comment]
Actually I wanted to do so, but I'm not familiar with how to do so. Perhaps you would like to have a go at it?

**Comment by contra** [comment]
I'll wait until you land #33 then take a whack at it - let me know!

**Comment by jiahaog** [comment]
@contra I'm done with #33! I think all that needs to be done is to put the listener in `app/assets/js/index.js` under `DOMContentLoaded`
