### ISSUE TITLE
Flash won't work

### ISSUE THREAD

**Issue by LutzPS** [jiahaog/nativefier#385]
I build using this:
`nativefier --name "Speedtest.net" --disable-dev-tools --show-menu-bar --maximize --disable-context-menu "http://www.speedtest.net"`

But plugin don't load.

**Comment by ronjouch** [comment]
@LutzPS yes, you need to ask for Flash manually, see `nativefier --help`. So,

* Try `--flash`, which will let the builder try to find it on its own...
* ... and if it doesn't work, find it yourself (using your favorite filesystem search tool, see [inferFlash.js](https://github.com/jiahaog/nativefier/blob/master/app/src/helpers/inferFlash.js#L54) for the filenames to search) and pass it manually.

This worked for me: `nativefier --name "speedtest" --disable-dev-tools --show-menu-bar --maximize --disable-context-menu --flash-path "/home/ronj/.config/google-chrome-unstable/PepperFlash/26.0.0.123/libpepflashplayer.so" "http://www.speedtest.net"`
