### ISSUE TITLE
unpackaged version

### ISSUE THREAD

**Issue by hadifarnoud** [jiahaog/nativefier#386]
Is there any way to get the unbuilt version of the electron app so I can modify it a bit?
secondly, is there a way to cache some files locally?

**Comment by ronjouch** [comment]
Hey @hadifarnoud, thanks for the feedback.

1. Install from source, following our [development guide](https://github.com/jiahaog/nativefier/blob/master/docs/development.md), then feel free to fiddle with the template used to build electron app, it lives in the `app` folder.
2. I don't understand your question *"is there a way to cache some files locally"*, please precise.

**Comment by hadifarnoud** [comment]
thanks for quick reply @ronjouch. there are some assets like built js files that I'd like to pack inside the application itself. 

would be great to add auto-update stuff in there too. 

Thanks

**Comment by ronjouch** [comment]
> *there are some assets like built js files that I'd like to pack inside the application itself.*

See `nativefier --help`, would the `--inject` flag do the trick for you?

> *would be great to add auto-update stuff in there too*

See https://github.com/jiahaog/nativefier/issues/291: *There's no automatic update: yes a nativefied app is locked to a specific version of Chrome/Electron, which you can specify at build time using the `--electron-version` option (see `nativefier --help` for the full list of options, and go to [the electron/releases page](https://github.com/electron/electron/releases) to pick your favorite stable/beta flavor of Electron poison :) ). There's no plan to change that, as all the machinery for this is part of the nativefier builder and not the nativefied app.*

**Comment by hadifarnoud** [comment]
> See nativefier --help, would the --inject flag do the trick for you?
not sure. this is a Backbone.js app and the built js file is quite big. wanted to just have that inside the app and not loading via internet. this option could be used for big asset files such as fonts, js files, images, etc.

does it inject extra assets? that's not what I want to do

**Comment by ronjouch** [comment]
@hadifarnoud that's not supported for now, see https://github.com/jiahaog/nativefier/issues/192
