### ISSUE TITLE
Multiple tabs open when clicking a link

### ISSUE THREAD

**Issue by jacobsmith** [jiahaog/nativefier#39]
I've been using this for a Flowdock app and when clicking on an external link, it opens up multiple (2) tabs pointing to the link's destination, rather than only one. I have not seen this behavior in an app version of YouTube, but I'm not sure if it's widespread or not. This is not critical by any means, but I wanted to see if other people were also running into this problem.

**Comment by jiahaog** [comment]
Could you update nativefier and see if this is still a problem? There are a number of under the hood changes that might have fixed this.

**Comment by jacobsmith** [comment]
I just tried updating to the latest version ( `6.5.6` at time of writing) and the bug is still present. If there's anything you suggest I look at to try and reproduce or look for specific console messages, just let me know! Thanks

**Comment by jiahaog** [comment]
Could you give me a series of steps to reproduce this bug?
