### ISSUE TITLE
Nativefier when download file streaming generate ClientAbortException

### ISSUE THREAD

**Issue by SinvalMAO** [jiahaog/nativefier#393]
I using StreamSaver.js to save and store file streaming on disk, mas o mesmo esta gerando um erro.

**BACK END ERROR**

`org.apache.catalina.connector.ClientAbortException: java.io.IOException: Uma conexão estabelecida foi anulada pelo software no computador host`

**FRONT END ERROR**

```
native ReadableStream.js:393 Uncaught (in promise) TypeError: network error
bluebird.js:1542 Unhandled rejection TypeError: network error
```

**Comment by ronjouch** [comment]
Hi @SinvalMAO, thanks for the feedback! Unfortunately there isn't much we can do with this little information. As requested by the issue template, please provide:

- OS, node version, nativefier version
- Full nativefier command-line used.
