### ISSUE TITLE
Executable created is not working in Windows 7

### ISSUE THREAD

**Issue by febinjoy** [jiahaog/nativefier#394]
### Description
I tried to bundle a website to an app using nativeFier. In Windows 10 it is working fine, but it is not working in Windows 7 machines. It shows version compatibility error message - 
*"The version of this file is not compatible with the version of Windows you are running.."*
 while try to load the exe.  

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.4.0`
- Version of Node.js (run `$ node --version`): `v6.10.3`
- OS: `Windows 10`
- Architecture `64 Bit`
- Stack trace from the error message (if any)

```
"The version of this file is not compatible with the version of Windows you are running.."
```

**Comment by ronjouch** [comment]
@febinjoy thanks for the feedback 👍. Closing, as I'm not sure we as {`electron`, `electron-packager`} downstream can do much about it :-/ . Googling a little bit, the error message seems common, so I encourage you to research which of {`electron`, `electron-packager`} is the culprit, and report the problem up there. Soooorry; if I'm missing the point, arguments welcome and we can re-open the issue.

In the meantime, the obvious workaround is to build your app on a Windows 7 machine.
