### ISSUE TITLE
Any possibility that you can add configuration options around header values from the various builds? 

### ISSUE THREAD

**Issue by nomorechickenstrips** [jiahaog/nativefier#397]
I have a need to specify a header value from the "native" apps that specifies the originating platform.  Is there any way nativefier can embed this header in its build process so requests to the target web app include it?

**Comment by ronjouch** [comment]
@nomorechickenstrips thanks for the feedback, closing until you provide more details:

* You mean you'd want *all* requests to include a specific header?
* Can you precise a little bit your use case?
* Can you provide examples of how you'd do that in a regular Chrome? Through an extension?
* How are these headers defined? Global? Per domain?

**Comment by nomorechickenstrips** [comment]
Specify a header per platform, ideally.  The goal is to identify the originating platform when requests are received from them by the web app.  I personally would use this to provide `X-PLATFORM` headers containing `MACOSX64` or `WIN10X86`, for example.  All requests, yes.

**Comment by a0n** [comment]
> You mean you'd want all requests to include a specific HTTP header

Yeah that would be awesome because I want to use it for a Side that uses X-Auth-Token as a way to authenticate.

**Comment by a0n** [comment]
I think I understand howto do it in an extension.
Try to see howto to load one now.

**Comment by bfelbo** [comment]
Did you figure out a way to do this? We have the same issue

**Comment by sb2059** [comment]
> Did you figure out a way to do this? We have the same issue

@bfelbo I'd recommend creating a new issue as the developer has arbitrarily stonewalled my pretty clearly articulated request.
