### ISSUE TITLE
Ubnable to create application with icon for Windows platform when using Windows Bash (WSL)

### ISSUE THREAD

**Issue by coderabbi** [jiahaog/nativefier#398]
### Description
In order to create an application for the Windows platform using the icon parameter from Linux, the wine executable must be in the PATH. Unfortunately, wine is not compatible with Windows Bash (WSL). So the interesting catch-22 is you can't create a Windows app from Linux, which itself is running on Windows, without a Windows emulator, which won't work in Linux that is running in Windows. Turtles all the way down. :-) I wouldn't call this an *issue* with nativefier, but would be useful if wine could be bypassed when building for Window platform from Windows Bash.

### Steps to Reproduce Issue
`nativefier http://example.com --name example.com --icon example.ico`

### Specifications
- Version of Nativefier 7.3.1
- Version of Node.js v8.1.2`
- OS: Windows 10
- Architecture x64

```
Error: Could not find "wine" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and
win32metadata parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs:
   [ '/usr/lib/node_modules/nativefier/node_modules/rcedit/bin/rcedit.exe',
     '/mnt/c/GitHub-win32-x64/GitHub.exe',
     '--set-file-version',
     '1.0.0',
     '--set-product-version',
     '1.0.0' ] }
```

**Comment by ronjouch** [comment]
WSL is not supported, but Nativefier runs fine under Windows.

**Comment by coderabbi** [comment]
"WSL is not supported, but Nativefier runs fine under Windows **provided that you use Windows cmd**." 

There, I fixed that for you.
