### ISSUE TITLE
Video/GL-heavy sites causes apps to fail to honor --fullscreen option under Windows 10

### ISSUE THREAD

**Issue by brianblakely** [jiahaog/nativefier#402]
### Description
After first run, nativefier app will never launch in fullscreen again.

### Steps to Reproduce Issue
1. Run `nativefier youtube.com --full-screen`

2. Open app

3. Quit app (alt-f4)

4. Open app again

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.4.0`
- Version of Node.js (run `$ node --version`): `v8.1.3`
- OS: `Windows 10`
- Architecture `x64`

**Comment by ronjouch** [comment]
@brianblakely thanks for the feedback and PR 👍. I can't reproduce the issue, though, for me `nativefier --name "ddgfs" --full-screen "https://duckduckgo.com"` successfully remembers full-screen state between restarts. Could you precise your original broken use case? (OS, node/nativefier version, full nativefier command-line used). Leaving your PR unmerged for now.

**Comment by brianblakely** [comment]
>(is it really just the youtube example you're describing? No options other than just --full-screen?

Yes to both questions. PR was the only way I found to fix this, but I will re-test v7.4.0 today to make sure it wasn't some kind of aberrant behavior (and report back either way).

Thanks for your prompt and friendly reply.

**Comment by brianblakely** [comment]
It appears it's some use of the compositing that disrupts the ability to remember fullscreen, and this issue is per-app.

`reddit.com`, for example, works as expected, but `youtube.com` and `vimeo.com` both fail to remember the fullscreen state.  These two apps present some video or otherwise large composited content upon initial load.

So I proceeded to test `http://xproger.info/projects/OpenLara/`, which also fails.  I expected it to fail, because this is a WebGL game, and naturally has a large compositing layer.

I surmise that some aspect of how Electron leverages the Chromium compositor is confusing `electron-window-state`, as least on Windows.

**Comment by brianblakely** [comment]
Screen recording, demonstrating the issue: http://i.imgur.com/ioPNV7u.gifv

**Comment by brianblakely** [comment]
Any hopes of getting this PR fix into the next publish?

**Comment by ronjouch** [comment]
> Any hopes of getting this PR fix into the next publish?

@brianblakely [7.4.1](https://github.com/jiahaog/nativefier/releases/tag/v7.4.1) 🎺

**Comment by brianblakely** [comment]
🎉👍👍
