### ISSUE TITLE
It's allowing multiple instances of Nativefier, unlike other desktop app.

### ISSUE THREAD

**Issue by maheshprabhu2010** [jiahaog/nativefier#407]
### Description
Natifiered applications allowing multiple instances of the application, unlike mobile or desktop apps. 

### Specifications

Version of Nativefier (run $ nativefier --version): v7.4.0
Version of Node.js (run $ node --version): v6.10.3
OS: Windows 10
Architecture: 64 Bit

**Comment by ronjouch** [comment]
@maheshprabhu2010 use the `--single-instance` flag.
