### ISSUE TITLE
Hide menu bar?

### ISSUE THREAD

**Issue by kstawiski** [jiahaog/nativefier#41]
Is there a way to hide menu bar? This with "Edit", "View", "Window" and "Help".

**Comment by jiahaog** [comment]
I think this can be coupled together with #35 as a command line integration by setting the `autoHideMenuBar` option of browserWindow

**Comment by miduga** [comment]
If we start adding command line options we might do a mess as there'll be a lot of options to include https://github.com/atom/electron/blob/master/docs/api/browser-window.md. What about a json file with all the options availables?

**Comment by kstawiski** [comment]
Thank you @fearenales! The solution https://github.com/jiahaog/nativefier/pull/58 is working.

**Comment by fearenales** [comment]
Good to know @kstawiski ! Thank your for testing that :)

Anyway, I'd let the issue open until the PR is fully merged into `master`, don't you think?
