### ISSUE TITLE
PDF - Save/Download PDF not working, Print PDF button not showing/not working as well

### ISSUE THREAD

**Issue by ajspalma** [jiahaog/nativefier#413]
### Description
I'm trying to print a generated pdf report but pdf button where not visible unlike in chrome, so i tried to save/download it but it wont download. Is there a command options that i can add to make it possible and working good? 

### Steps to Reproduce Issue
1. Print PDF button must be present and working and should prompt a windows or anything like on google chrom.
2. Save/Download PDF should be working as well.
3. shortcuts like CTRL+S, CTRL+P or alike to this kind of function just to make this work.

### Specifications
- Version of Nativefier : v7.4.0
- Version of Node.js : v6.11.0
- OS: Windows 7 Ultimate
- Architecture x64

![image](https://user-images.githubusercontent.com/15847238/28311230-90330cea-6be1-11e7-9e39-98262b217dee.png)

**Comment by ronjouch** [comment]
@ajspalma thanks for the feedback 👍. Two questions:

* Please provide the full nativefier used to build your app.
* What do you mean by *"pdf button where not visible unlike in chrome"*?
* Could your problem be related to #335 ?

**Comment by ajspalma** [comment]
hi @ronjouch, 

- I included the nativefier version used in the specification above and it's v7.4.0 and the address was "http://192.168.0.91/Receiving" - (it is an in house system so it just uses local ip from other pc).
- _"pdf button wheren not visbile unlike in chrome"_ here it is:
in Chrome: 
![image](https://user-images.githubusercontent.com/15847238/28312082-695667a4-6be4-11e7-9ee9-669c666cdda2.png)
but in Nativefier App:
![image](https://user-images.githubusercontent.com/15847238/28312117-8feed69e-6be4-11e7-97d0-cb840e6e6fc1.png)
.. there is no print pdf button.


> 

>

**Comment by ronjouch** [comment]
@ajspalma I meant full nativefier *command*, sorry. But that answers the main question, this is a non-public site. Please provide a test scenario failing on a **public** website.

**Comment by ajspalma** [comment]
@ronjouch Thank you, I have noticed that yes! all the PDF files where downloaded straight from my Downloads folder and there a bunch of them (hit the download button couple times hehe). Thank you for this reference #355 I will make a custom js to fix this problem. :+1:

**Comment by iTheCode** [comment]
Sorry for my bad english but i solved this, solution:

1.- Go to the directory of nativefier, on macos "cd /usr/local/lib/node_modules/nativefier/app/".
2.- Install electron-pdf-viewer, on macos "npm install electron-pdf-viewer"
3.- Edit main.js, on macos "/usr/local/lib/node_modules/nativefier/app/lib/main.js"
4.- Replace this:
```

  mainWindow.webContents.on('new-window', (event, urlToGo) => {
    if (mainWindow.useDefaultWindowBehaviour) {
      mainWindow.useDefaultWindowBehaviour = false;
      return;
    }

    if (linkIsInternal(options.targetUrl, urlToGo, options.internalUrls)) {
      return;
    }
    event.preventDefault();
    _electron.openExternal(urlToGo);
  });

```
Whit This:
```
	  mainWindow.webContents.on('new-window', function (event, urlToGo) {
	    if(urlToGo.split('.').pop() === 'pdf'){
	    	event.preventDefault();
	    	const PDFWindow = require('electron-pdf-window')
		const win = new PDFWindow({
			   width: 800,
			   height: 600
		})
			 
		win.loadURL(urlToGo);
	    }else{
	    	    if (mainWindow.useDefaultWindowBehaviour) {
			      mainWindow.useDefaultWindowBehaviour = false;
			      return;
			    }

			    if (linkIsInternal(options.targetUrl, urlToGo, options.internalUrls)) {
			      return;
			    }
    			event.preventDefault();
	    		_electron.shell.openExternal(urlToGo);
	    }
	  });
```

5.- In your button to print pdf you can use javascript new window open, like this:

`window.open("http://url.com/to/print.pdf");`

When detect .pdf in the url to go, create a pdf viewer and can more options.


This works for me.

![captura de pantalla 2018-02-12 a la s 02 16 16](https://user-images.githubusercontent.com/4421999/36086489-bd080150-0f9a-11e8-9cd5-30c2caeee35e.png)

**Comment by ronjouch** [comment]
Thanks for sharing this, @iTheCode 👍. If you have the time to contribute your `electron-pdf-viewer`-based code as an optional flag, PR very welcome.

**Comment by flesoft** [comment]
@iTheCode in windows where I place the folder

**Comment by mdbiz** [comment]
> Sorry for my bad english but i solved it, solution:

Just a heads up for people trying to make it work with this:

This doesn't work with blobs.
electron-pdf-viewer doesn't support blob:// right now.

There are maybe solutions, if they still work. Example https://github.com/electron/electron/issues/13038#issuecomment-419396445

**Comment by RockGuitarist1** [comment]
@mdbiz The alternative solution that you found there works on Electron v2, but not v3. For some reason they completely disabled being able to load in local pdfs completely in v3. Instead, now you get a prompt to save said file somewhere instead of the native pdf viewer opening.
