### ISSUE TITLE
upon $_POST form request then new (tab, window, target="_blank") 

### ISSUE THREAD

**Issue by ajspalma** [jiahaog/nativefier#414]
### Description
I tried to do a post request, it is working good in google chrome but in the nativefier converted app, the new tab upon post request is not fetching the POST data instead it only redirect to that particular URL without the post data. so it just generate a blank data page.

`<form method="post" action="../reporting/purch_register_print.php" name="name1" target="_blank">`

### Steps to Reproduce Issue
1. POST data must be transferred and acquired in new tab/window after post form request
2. it should not only forwarding and opening new window without fetching the data posted from the previous action. 

### Specifications
- Version of Nativefier : v7.4.0
- Version of Node.js : v6.11.0
- OS: Windows 7 Ultimate
- Architecture x64

**Comment by ronjouch** [comment]
@ajspalma thanks for the feedback, but we cannot work without a reproducible test case on a public website. Please provide a minimal reproduction scenario and I'll re-open the ticket.
