### ISSUE TITLE
Save profile with app [feature request]

### ISSUE THREAD

**Issue by conchra** [jiahaog/nativefier#42]
Currently, the profle for a created app is saved to %APPDATA%\[app-name]-nativefier-[some_string] on Windows. It would be great if that profile data was also save to the app folder (in a folder called profile perhaps?). This should make the app portable-ish.

**Comment by jiahaog** [comment]
Hmm, you mean to suggest that the app data path is set to a folder within the created app itself?

**Comment by conchra** [comment]
Yes. Instead of the app data path going to %APPDATA%\[app-name]-nativefier-[some_string], save it to [dest]\[app-name]-nativefier-[some_string]. The Chrome/Chromium command to select a profile (other than the default) is --user-data-dir= (https://www.chromium.org/user-experience/user-data-directory) but this does not work, at least on Windows.

**Comment by jiahaog** [comment]
This has been resolved in #149!
