### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by codecowboy** [jiahaog/nativefier#421]
### Description

Attempted to natify evernote.com on elementaryos (Ubuntu 16.04)

### Steps to reproduce issue

```
nativefier --name "Evernote" "http://evernote.com"
Downloading tmp-26297-1-SHASUMS256.txt-1.6.6
[============================================>] 100.0% of 4.44 kB (4.44 kB/s)
Packaging app for platform linux x64 using electron v1.6.6
{ [Error: ENOENT: no such file or directory, rename '/var/log/linux-x64-template' -> '/var/log/evernote-linux-x64']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/var/log/linux-x64-template',
  dest: '/var/log/evernote-linux-x64' }
```

### Details

- Are you nativefying a *public* website? yes
- `nativefier --name "Evernote" "http://evernote.com"`
- Version of Nativefier (run `nativefier --version`): `v7.4.0`
- Version of node.js (run `node --version`): `v4.2.6`
- OS: Ubuntu 16.04 (elementaryos)
- Error:

```
{ [Error: ENOENT: no such file or directory, rename '/var/log/linux-x64-template' -> '/var/log/evernote-linux-x64']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/var/log/linux-x64-template',
  dest: '/var/log/evernote-linux-x64' }
```
neither of the above files mentioned in the error message exist.

**Comment by codecowboy** [comment]
What would the permissions need to be on that file? I tried creating it using touch but then get permission denied (ran as sudo, also tried changing owner to logged in user)

**Comment by ronjouch** [comment]
Thanks for the feedback, @codecowboy. Where did you run the nativefier command from? (what's your `pwd` and its permissions?)

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. feel free to chime in and re-open the discussion anytime 🙂!

**Comment by Fmstrat** [comment]
For anyone finding this issue, it's definitely a permissions thing. Make sure the directory you're writing to is writable by the user. I ran into this using the docker container in my root's home directory.
