### ISSUE TITLE
[dev question] What is loginWindow used for?

### ISSUE THREAD

**Issue by piggyslasher** [jiahaog/nativefier#426]
### Description

I'm trying to develop and extend nativefier. Is loginWindow.js? I've never seen it being called. It seems to be an ancient file.

**Comment by ronjouch** [comment]
Hi @piggyslasher. It's still used for HTTP authentication, see [`app/src/main.js#96`](https://github.com/jiahaog/nativefier/blob/master/app/src/main.js#L96)

**Comment by piggyslasher** [comment]
Thanks!

**Comment by ronjouch** [comment]
@piggyslasher sure! Hey, to follow-up on you saying you're *"trying to develop and extend nativefier"*: if you're looking for ideas,

* Here is a GitHub Issues query for [triaged, reproducible bugs](https://github.com/jiahaog/nativefier/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Abug%20-label%3A%22cannot%20reproduce%22%20-label%3A%22need%20info%22%20-label%3A%22help%20wanted%22)
* And here is a GitHub Issues query for [triaged, non-duplicate feature requests](https://github.com/jiahaog/nativefier/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22feature%20request%22%20-label%3A%22need%20info%22%20-label%3A%22help%20wanted%22)

Help welcome on all those 🙂, check the [developers guide](https://github.com/jiahaog/nativefier/blob/master/docs/development.md), and feel free to ask questions!
