### ISSUE TITLE
Run Nativefier app as absolute standalone.

### ISSUE THREAD

**Issue by asandoval4wall** [jiahaog/nativefier#427]
### Description

As a web developer, i'd like to have the option to run Nativefier against localhost and have it not only do what Electron Packager does but to also include it's own internal IIS or the like so that my users can run the application I developed on my machine without connecting to an external website and run it locally on their machine.

### Details

- Nativefying localhost
- Feature request/Instructions on how to implement if already available.

**Comment by ronjouch** [comment]
You are basically describing an [electron](https://electron.atom.io/) app. That's not the purpose of nativefier. Closing.
