### ISSUE TITLE
Right app name and right app icon are mutually exclusive

### ISSUE THREAD

**Issue by princejosuah** [jiahaog/nativefier#429]
### Description
When I nativefy a website, say https://linkedin.com : 
* if I specify the name "LinkedIn" with the '--name' parameter, I get a generic Electron icon ;
* if I drop the parameter, site icon is correctly inferred but then the name of the app is the full title, eg *LinkedIn Log In or Sign In*
I've tried with Twitter and Wordpress and got the same result.

### Steps to reproduce issue
Normal "nativefication" process ;)

### Details
- Are you nativefying a *public* website? **Yes**
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? **Yes, no related entry**
- Full nativefier command used to build your app: first `nativefier --name "LinkedIn" "https://www.linkedin.com"`then `nativefier "https://www.linkedin.com`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v8.4.0`
- OS: `macOS Sierra 10.12.6`

**Comment by ronjouch** [comment]
@princejosuah thanks for the feedback. Does manually passing an icon with `--icon /path/to/linkedin-icon.png` work around the issue?

**Comment by princejosuah** [comment]
Hey! Sorry, didn't get the Github notification on time.
I finally converted the png in icns and passed it directly, and now it works great!
Thanks a bunch. This issue can be marked as solved and closed.

**Comment by princejosuah** [comment]
Hey! Sorry, didn't get the Github notification on time.
I finally converted the png in icns and passed it directly, and now it works great!
Thanks a bunch. This issue can be marked as solved and closed.
