### ISSUE TITLE
Macbook pro trackpad force touch does not work.

### ISSUE THREAD

**Issue by nootfly** [jiahaog/nativefier#43]

**Comment by jiahaog** [comment]
Could you elaborate more on this?

**Comment by nootfly** [comment]
on Safari, force touching  a word can open a dictionary. I think the reason is an app is wrapped by Chromium which does not support force touch.

**Comment by jiahaog** [comment]
I don't have a force touch trackpad available, but when I turn on `Look up & data detectors` with Tap With three fingers, under System Preferences > Trackpad, it works for me. Is this simply problem simply for force touch?
