### ISSUE TITLE
Open Links in pop-up windows?

### ISSUE THREAD

**Issue by Anthony-K** [jiahaog/nativefier#431]
Suggestion: It would be nice to have an option to open all non-javascript links (leading to another page) in new windows so that the app would feel more native.

**Comment by ronjouch** [comment]
Hey @Anthony-K, thanks for the feedback 🙂. I think https://github.com/jiahaog/nativefier/issues/212#issuecomment-292689727 may do the trick for you. If not, chime in and I'll re-open your issue.

**Comment by Anthony-K** [comment]
@ronjouch Thanks!
