### ISSUE TITLE
Sessions are not restored between restarts, 

### ISSUE THREAD

**Issue by CraigZych** [jiahaog/nativefier#432]
Sessions are not restored between restarts, 

My app has a signin and it is displayed each restart instead of auto logging in if there is a valid session.

- Are you nativefying a *public* website?no
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?yes
- Full nativefier command used to build your app: ```nativefier --name "example" "www.example.com"```
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v7.7.4`
- OS: `windows 7`
- Error message / stack trace (if any):

**Comment by ronjouch** [comment]
@CraigZych thanks for the feedback. Please come back with a reproducible scenario on a public site.

**Comment by Craigzyc** [comment]
For anyone having this issue in the future, mine was caused by the cookie expiry not being set properly.. It was a server side issue. 
Thanks
