### ISSUE TITLE
Google Access Error

### ISSUE THREAD

**Issue by alvarezval** [jiahaog/nativefier#433]
Hi
The application does not synchronize my associated email account. Always Indicates Google Access Error
How can i solve this problem?
thank you very much
regards
Jesus

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
@alvarezval thanks for the feedback 🙂. We'll need more information to troubleshoot, though. Please describe in detail the problem and fill the information requested by the issue template.
