### ISSUE TITLE
[Feature] Add WidevineCdm plugin

### ISSUE THREAD

**Issue by Killmax** [jiahaog/nativefier#435]
### Description

I think it would be a great idea to add the WidevineCDM plugin into the app, because it can block certain website like Amazon Prime Video for example

See that link : https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md 

### Steps to reproduce issue
-> Go on Amazon Prime Video and Log In
-> Try to play a video

### Details

- Are you nativefying a *public* website?
--> Yes, https://www.primevideo.com/
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
--> Nothing seems to deal with that in help
- Full nativefier command used to build your app: `nativefier --name "Prime Video" "https://www.primevideo.com/"`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v6.11.1`
- OS: `Windows 10 Enterprise`

**Comment by mikhoul** [comment]
I'm new with nativefier and I had the same problem with  Spotify, browsing the issue **I think it was fixed** but is have to be approved before going in the main branch: https://github.com/jiahaog/nativefier/pull/440 

Sorry I'm a newbie with github technical terms,

Regards :octocat:

**Comment by anidotnet** [comment]
Tried creating app for Amazon Prime Video on Ubuntu 19.04. Installed the latest widevine 4.10.1196.0 
from here - https://gist.github.com/ruario/3c873d43eb20553d5014bd4d29fe37f1 and run nativefier for primevideo. When I try to play video from app, I am getting below issue

![image](https://user-images.githubusercontent.com/696662/62831307-8fe84600-bc3a-11e9-80ee-b0ac9aa8a99c.png)

Any pointer how to enable running protected content?

**Comment by Gougere89** [comment]
I'm getting the same problem trying to embed myCANAL (French TV broadcast service) into an app on macOS : Can't open DRM-protected content.

**Comment by nodefive** [comment]
Still not working.  Any workaround or fix?

**Comment by exander77** [comment]
I would like to know if the fix is available as well?

**Comment by BananaManCJ** [comment]
Would using this instead of the default electron give use WidevineCDM support? https://github.com/castlabs/electron-releases

**Comment by ronjouch** [comment]
Thanks to @sorhtyre over at https://github.com/jiahaog/nativefier/pull/1073 , which uses the alternative wvvmp Electron distribution by CastLabs, this is now solved. I'll cut a release soon.
