### ISSUE TITLE
Can't specify build-version or app-version

### ISSUE THREAD

**Issue by CraigZych** [jiahaog/nativefier#438]
I am unable to specify build-version or app-version or any options with a dash when using the config file or the programmatic api since the dash is not allowed in the name. Is there another way to specify these?

I need the File Version not to be 1.0.0.0 since it isn't compatible with squirrel and I can't make an installer with that version number

- Are you nativefying a *public* website? No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app:

```js
var nativefier = require('nativefier').default;

// possible options, defaults unless specified otherwise
var options = {
    name: 'Example', // will be inferred if not specified
    targetUrl: 'http://example.com', 
    arch: 'x64', // defaults to the current system
    version: '0.9.1',
    out: '.',
    overwrite: true,
    asar: false, // see conceal
    counter: false,
    width: 1280,
    height: 800,
    showMenuBar: false,
    fastQuit: false,
    insecure: false,
    honest: false,
    zoom: 1.0,
    singleInstance: true,
    build-version: '0.9.1',
    app-version: '0.9.1',
    dest: 'CAM'
};

nativefier(options, function(error, appPath) {
    if (error) {
        console.error(error);
        return;
    }
    console.log('App has been nativefied to', appPath);
});
```
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v7.7.4`
- OS: `windows 7`

**Comment by ronjouch** [comment]
@CraigZych crazy characters are allowed in JS objects, you have to surround them with quotes.

```js
var options = {
    name: 'Example',
    // ...
    "build-version": '0.9.1',
    "app-version": '0.9.1'
};
```

**Comment by CraigZych** [comment]
I tried that and it was ignored. The produced .exe still had 1.0.0.0 as the File Version

**Comment by ronjouch** [comment]
@CraigZych ah, wait. You are using `dash-separated` ***CLI*** options. With the ***programmatic*** API, options are `camelCase`, see https://github.com/githubbob42/nativefier/blob/master/src/options/optionsMain.js#L59-L60

So, `buildVersion: '0.9.1', appVersion: '0.9.1'`

**Comment by CraigZych** [comment]
Hmm, I did try that as well. It still produced the same result. 

I am reading it correctly that buildVersion should make the File Version under details of the produced .exe read whatever you insert?

**Comment by ronjouch** [comment]
@githubbob42 pinging you as you worked nearby recently. Any idea?

**Comment by githubbob42** [comment]
I have to agree with @ronjouch's comment (https://github.com/jiahaog/nativefier/issues/438#issuecomment-325687693) about the camelCase names (but I thought that `commander` would still pass any kebab-case options though as camelCase).  

However, I did not bump the version for nativefier in those changes (still at v.7.4.1).  Maybe trying running `npm update`?  Should we bump the version?

**Comment by ronjouch** [comment]
A-ha, good catch @githubbob42, this code hasn't been released yet 😄. Sorry, my mistake, I thought it made into 7.4.1, but it was merged a few days *after*. @CraigZych please [build nativefier from sources](https://github.com/jiahaog/nativefier/blob/master/docs/development.md), or wait for a release.

**Comment by CraigZych** [comment]
Ok, thank you for your responses. Any idea on a new release date?

**Comment by ronjouch** [comment]
@CraigZych when enough stuff has accumulated; I'd do one for you, if it wasn't for a few still-necessary manual steps. Try to build from source! Should be easy 🙂.

**Comment by CraigZych** [comment]
Thanks :)

**Comment by CraigZych** [comment]
I don't want to open an issue but it seems the command line option doesn't work either in the currently released version. 
```
nativefier --build-version "0.9.1" "http://gmail.com"
```
produces an exe that still has 1.0.0.0 for the File Version.
The main reason this is such an issue is the Electron windows-installer generator complains that this isn't semver compatible. Can you change the default file version to be 1.0.0 instead so it wouldn't complain.

I tried building from source but ran into issues. Its complaining since I had nativefier installed already, then when I removed nativefier it complained files didn't exist.

**Comment by githubbob42** [comment]
Hmmm, when I install `nativefier` globally, and look in `/usr/local/lib/node_modules/nativefier`, I don't see any of my changes in `lib/options/optionsMain.js`.  Was something missed when either building and/or deploying?  Were the changes actually deployed to `npm`?

When I build and run everything locally, it works fine.  Of course, it looks like the CLI only looks for kabab-base parameter names but that seems to be to pattern (kabab-case for cli and camelCase for programatic).  Again, if I run everything locally, it works fine.
