### ISSUE TITLE
Support --single-window and --dont-exit-on-mainwindow-close flags for better popup/multi-window experience

### ISSUE THREAD

**Issue by ronjouch** [jiahaog/nativefier#439]
`<a href=... target=_blank>` links produce a link that opens in a new window in nativefier (or tab, for real browsers). We should:

1. Have a `--single-window` flag that forces these links to instead open in the same, current window, effectively making nativefier single-window.  
Use case: would like this for Jupyter notebooks.
2. Have a `--dont-exit-on-mainwindow-close` flag that respects the window opening, but lets users close the first window (without quitting at this time) and do their work in the popup. Enables multi-window workflows, see e.g. with JIRA on #497.  
***EDIT*** should we really put this behaviour behind a flag? What about making it the new default behaviour? Any workflows depending on the current behaviour?

**Comment by watersalesman** [comment]
Also for some reason `<a href=... target=_blank>` links on https://office.com open in my default browser (Firefox). 

nativefier 7.4.0
node v8.8.0
OS: Arch Linux

**Comment by dansteen** [comment]
I would also want the `--dont-exit-on-mainwindow-close` flag to be the default.  That's pretty much the expected behavior as far as I can tell.  Windows closing by themselves is always annoying at best, and can cause information loss at worst.

**Comment by bacongravy** [comment]
The behavior of secondary windows is improved with PR #579, and may resolve the issue mentioned in duplicate #497.
