### ISSUE TITLE
Support using --java ?

### ISSUE THREAD

**Issue by netconstructor** [jiahaog/nativefier#441]
Quick question - I am attempting to create a localized app to allow staff with a simple method of accessing a website which can only be viewed on an old version of Firefox because it requires java web objects (JRE version 1.4.2) to be loaded (now blocked with google chrome).

Could you please clarify if it would be possible to accomplish this in a similar method to using the --flash parameter for localization? In addition the ignore certificate errors would be important.

The publicly accessible URL I am looking to localize can be found here:
https://spp.sdrc.org/

**Comment by ronjouch** [comment]
Thanks for the feedback @netconstructor. I understand your use case; a nativefied app with built-in JRE support would be neat to support this old app. But no, we have no JRE support, and with the direction taken by the web (as you mention: even Chrome itself, which Nativefier depends on, it actively going against it), we don't plan to add any.

If I was in your shoes, I'd try packaging a specially configured Firefox (forcing a home page to the your website, blocking updates in `about:config`, activating Java, hiding urlbar and other browser widgets with `userChrome.css`). Good luck.
