### ISSUE TITLE
Not remembering cached credentials

### ISSUE THREAD

**Issue by ChrisKendallVA** [jiahaog/nativefier#446]
When a cached user logs into the software it works perfectly within said window, however if the user clicks on "View invoices" a pop up (Normal) appears but then requires login again to the account. 

Then when the user goes back to the original cached window after closing the popup (if they logged into it) they have to log back in again with that original window. 

This should be cached information allowing continuous action throughout popups of that website. 

How do i go about rectifying this?

**Comment by ronjouch** [comment]
@ChrisKendallVA thanks for the feedback but there's little we can do with little of your help. Please provide a precise, reproducible test scenario:

- Which website?
- Full nativefier command used to build your app.
- Version of Nativefier (run `nativefier --version`)
- Version of node.js (run `node --version`)
- OS
- Error message / stack trace (if any)
