### ISSUE TITLE
When building offline, nativefier should not hang, and should provide advice on electron files needed to build offline

### ISSUE THREAD

**Issue by GitGeoCoder** [jiahaog/nativefier#448]
My org is interested to create desktop app using Nativefier. But doesn't like the dependence on internet connection. Is there a way to do it? 

In the referring step, what items are needed to download from Electron? I setup my own local icon, but it didn't help. 

Thanks!

Command:  `./node_modules/.bin/nativefier  -n "GXP_Platform_Client" localhost  --icon "D:\Temporary\JavaScripts\node_modules\nativefier\app\GXP_Platform_Client.ico" --show-menu-bar`

**Comment by ronjouch** [comment]
@GitGeoCoder thanks for the feedback. Yup, as you said you just need a few Electron files (named something like `electron-v1.6.6-win32-x64.zip` and `SHASUMS256.txt-1.6.6`) cached to build Nativefier apps without internet (I just checked, it works). 

On my Linux machine, these files live at `~/.cache/electron`, on your Windows machine they should be somewhere around `C:\Users\youruser\AppData\Local(maybeLocalLow?)\electron` (but maybe I'm wrong, in that case look for them –I recommend [Everything](https://www.voidtools.com/) for fast NTFS search–, and look for `electron-v`).

So: build from a machine with internet access, note the electron cache path, copy the files, and dump them to your offline build machine. Should work. I'm renaming this ticket to suggest implementing something that detects lack of connectivity, exits rather than hangs, and mentions the electron cache path. Thanks for the suggestion 👍.

**Comment by GitGeoCoder** [comment]
@ronjouch Thanks for the quick response. Problem solved.
BTW, which version of Electron should be downloaded? Latest or depend on the version of Nativefier?

**Comment by ronjouch** [comment]
@GitGeoCoder 

> *Thanks for the quick response. Problem solved.*

👍, thanks too for confirming.

> *BTW, which version of Electron should be downloaded? Latest or depend on the version of Nativefier?*

For my apps (feedly, gmail) I always roll with the latest/beta [Electron release](https://github.com/electron/electron/releases). I feel that upgrades become tricky for developers building *big* apps on top of the Electron platform (e.g. VS Code, Atom, Slack, Skype). But nativefier apps are much more modest, we're just packaging a web view and don't use a ton of platform APIs, which means small breakage potential.

So, we default to a stable Electron (currently 1.6.6, which we should upgrade to the latest 1.6.x one of these days), but it shouldn't be dangerous for you to try 1.7.x or even 1.8.x to get the latest fixes and Chrome engine. If you do and see broken stuff, please report it!

**Comment by ronjouch** [comment]
@GitGeoCoder 

> *Thanks for the quick response. Problem solved.*

👍, thanks too for confirming. Hey by the way, what was the path for Electron cached files in Windows?

> *BTW, which version of Electron should be downloaded? Latest or depend on the version of Nativefier?*

For my apps (feedly, gmail) I always roll with the latest/beta [Electron release](https://github.com/electron/electron/releases). I feel that upgrades become tricky for developers building *big* apps on top of the Electron platform (e.g. VS Code, Atom, Slack, Skype). But nativefier apps are much more modest, we're just packaging a web view and don't use a ton of platform APIs, which means small breakage potential.

So, we default to a stable Electron (currently 1.6.6, which we should upgrade to the latest 1.6.x one of these days), but it shouldn't be dangerous for you to try 1.7.x or even 1.8.x to get the latest fixes and Chrome engine. If you do and see broken stuff, please report it!

**Comment by GitGeoCoder** [comment]
@ronjouch  Is there is configuration for nativefier to download/use a specific version of electron?
I tried to download and put the electron-v1.6.13-win32-x64.zip into the cache dir
C:\Users\myname\AppData\Local\electron\Cache
OS: WINDOWS10

But the electron-v1.6.6-win32-x64.zip is downloaded instead.

**Comment by ronjouch** [comment]
> *Is there is configuration for nativefier to download/use a specific version of electron?*

@GitGeoCoder you're looking for flag `--electron-version`. Without it, nativefier defaults to a hardcoded known-to-work stable version (currently, as you said, 1.6.6). Check `nativefier --help` for the full list of supported flags.

**Comment by GitGeoCoder** [comment]
@ronjouch works!

**Comment by umarshark** [comment]
hello sir
you had just told to copy all files from cache folder and put them into local machine
But i can't understand this reply

I need to load my local files into nativefier but without the use of internet connection
Could you please help me

**Comment by moziar** [comment]
It works, thanks

**Comment by imydou** [comment]
export ELECTRON_GET_USE_PROXY=1 # 值为1或true
export GLOBAL_AGENT_HTTP_PROXY=http://proxy.example.com:1080
export GLOBAL_AGENT_HTTPS_PROXY=https://proxy.example.com:1080
