### ISSUE TITLE
Add custom `fonts` support

### ISSUE THREAD

**Issue by NaSabbir** [jiahaog/nativefier#454]
### Description

I think it would be best to add **font** changing/adding support!

> It is not showing Bangla fonts properly.

### Steps to reproduce issue
It's a feature request

### Details

- Website: https://www.messenger.com/
- Feature request: `will be seen messages in native language`
- Version of Nativefier : `v7.4.1`
- Version of node.js: `v8.3.0`
- OS: `Linux`

**Comment by ronjouch** [comment]
Hey @NaSabbir. Thanks for the feedback 👍, but what you are asking for is not clear to me. Please add some explanations, maybe screenshots, how other browsers behave, etc.
