### ISSUE TITLE
When minimized to tray (using --tray), re-running the app should activate and focus it

### ISSUE THREAD

**Issue by Gregory-K** [jiahaog/nativefier#462]
### Description

Once the app is minimized to tray you can open it again only from the tray icon.  
The app (the same instance, especially if it was built with --single-instance) should open again when it is called to launch by any other method (shortcut, executable file etc.).

Related #304 #457

### Steps to reproduce issue

nativefy with --single-instance --tray

### Details

- nativefying a *public* website
- Feature request OR Bug? (moderator decides)
- Full nativefier command used to build your app: `nativefier -i icon.png https://example.com/ --single-instance --tray`
- Version of Nativefier (run `nativefier --version`): `v7.4.1 + latest commits`
- Version of node.js (run `node --version`): `v6.11.4`
- OS: `Windows 10 64bit`

**Comment by ronjouch** [comment]
@Gregory-K seems legit, and feasible (just check Electron based Skype and Slack, they both do what you are describing).

**Comment by Gregory-K** [comment]
@ronjouch thanx for the revised title, I didn't give it a lot of thought.  
I know it is possible and I hope for a developer to find the time to implement it.
