### ISSUE TITLE
Right-click overrides don't work correctly (Google Calendar, OSX 10.13)

### ISSUE THREAD

**Issue by danielgwilson** [jiahaog/nativefier#467]
### Description

Hi—awesome app. It appears that sites which override right clicks don't function correctly. Google Calendar, for example, allows right clicking to delete events and change their color/details. Right clicking in a nativefied version of Google Calendar first produces the "Open with default browser" 3 option menu, then shows the Google right-click options after clicking away from the first menu.

### Steps to reproduce issue

1. Nativefy Google Calendar.
2. Sign in.
3. Right click an event.
4. Click away from the menu
5. Observe Google Calendar custom right-click menu still visible (and usable, just unexpected behavior).

### Details

- Full nativefier command used to build your app: `nativefier "http://calendar.google.com`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js (run `node --version`): `v8.7.0`
- OS: `OSX 10.13`

**Comment by AABatteries** [comment]
Using ```
--disable-context-menu
``` 
fixes this issue. Please read the API documentation first.
