### ISSUE TITLE
Add an option to enable the user specifying output path for the nativefied app

### ISSUE THREAD

**Issue by GitGeoCoder** [jiahaog/nativefier#469]
I have been using the following script to create my app
node ./node_modules/nativefier/lib/cli.js -n My_Desktop_Client localhost  --icon ./My.ico --show-menu-bar -p windows -e 1.6.8

But the output "My_Desktop_Client-win32-x64" is always in my current directory. It would be nice to specify the output dir.  Is there a workaround?

### Steps to reproduce issue
node ./node_modules/nativefier/lib/cli.js -n My_Desktop_Client localhost  --icon ./My.ico --show-menu-bar -p windows -e 1.6.8

### Details

- Are you nativefying a *public* website?  
No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes

- Full nativefier command used to build your app: `<command here>`
node ./node_modules/nativefier/lib/cli.js -n My_Desktop_Client localhost  --icon ./My.ico --show-menu-bar -p windows -e 1.6.8

- Version of Nativefier (run `nativefier --version`): `v0.0.0`
7.4.1
- Version of node.js (run `node --version`): `v0.0.0`
v8.5.0

- OS: `<OS here>`
Win10

- Error message / stack trace (if any):
N/A

<Error message / Stack trace here>
N/A`

**Comment by ronjouch** [comment]
@GitGeoCoder `nativefier --help` says *Usage: nativefier [options] <targetUrl> **[dest]***

Just specify the output dir as final parameter 🙂.
