### ISSUE TITLE
How can I scale web page?

### ISSUE THREAD

**Issue by AndreWin** [jiahaog/nativefier#470]
Hello! I created native version for trello.com with the latest version of nativefier:

```
nativefier "https://trello.com"
```

All works fine but I can't scale this page. I tried to scroll mouse wheel with ctrl button pressed, I tried ctrl + plus sign on digital part of keyboard -- nothing helped me.

Is it possible to scale web page in nativefier?

Best regards,
Andrey.

**Comment by AndreWin** [comment]
I tried the same with todoist.com -- the same problem.

In chrome both sites scales nice.

**Comment by ronjouch** [comment]
Hi @AndreWin. Yes it's possible to scale in Nativefier.

- Not with `Ctrl`+`Mousewheel`, no
- But `Ctrl`+`+`/`-` should work. Depending on your keyboard layout, maybe try `Ctrl`+**`Shift`**+`+`/`-`
- And give a try to build-time flag `--zoom`, which default to `1.0` but might work for you at, say, `1.3` or `1.5`

Keep us posted 🙂.

**Comment by AndreWin** [comment]
Just tested `ctrl` + `+`/`-`, but now I used keys not block of numerical keys but buttons at the top part of keyboard. And this works. Thanks :)

**Comment by ronjouch** [comment]
@AndreWin ah yes, there's https://github.com/jiahaog/nativefier/issues/379 to track that numpad bug 🙂. Glad it works for you!

**Comment by AndreWin** [comment]
I found that it's possible to inject own js/css file. But I have a poor knowledge of javascript. Can you help me to write script to scale page on mouse scroll?

**Comment by ronjouch** [comment]
> *I found that it's possible to inject own js/css file. But I have a poor knowledge of javascript. Can you help me to write script to scale page on mouse scroll?*

@AndreWin client-side JS (either page or nativefier user-injected js) won't let you zoom the page, that's browser responsibility and should be patched at Nativefier level. Try to patch nativefier then 🙂, bootstrap a development environment following the [dev docs](https://github.com/jiahaog/nativefier/blob/master/docs/development.md), then maybe start looking at how the [context menu](https://github.com/jiahaog/nativefier/blob/master/app/src/components/contextMenu/contextMenu.js) is set up to a right click, and try to set up a similar handler for Ctrl+Mousewheel. The [Electron docs](https://electron.atom.io/docs/) will help.
