### ISSUE TITLE
[HELP WANTED] How to run a bash file before aplication is initialized?

### ISSUE THREAD

**Issue by alequeiroz** [jiahaog/nativefier#473]
Hello guys, later on i´be working on Octprint, but it need to run a bash file when the aplication is initialized for the first time to buil the server, when i run nativefier it works fine, but the server have to be online for the app works properly. More info to build https://github.com/foosel/OctoPrint/wiki/Setup-on-Windows
Any suggestions how to do this?

**Comment by ronjouch** [comment]
@alequeiroz thanks for the interest, but we'll need more help to help you. Please detail what you need in a precise and reproducible way.

**Comment by alequeiroz** [comment]
@ronjouch I´m creating a bash to do all the setup of the Octoprint on windows, and i need to run this before the aplication itself, because i need to creat the server before the apllication run: 

(venv) C:\OctoPrint>octoprint serve
2017-11-01 10:56:22,329 - octoprint.server - INFO - ******************************************************************************
2017-11-01 10:56:22,332 - octoprint.server - INFO - Starting OctoPrint 1.3.2 (master branch)
2017-11-01 10:56:22,332 - octoprint.server - INFO - ******************************************************************************
 before the apllication run.

**Comment by AABatteries** [comment]
I think the best solution would be to write a bash script that creates the server you described and then follows (&&) with executing the binary of the app created with nativefier. Adding such functionality to nativefier doesn't seem sustainable as it can be acheived easily with very basic means.
