### ISSUE TITLE
"View > Zoom" resets, "forgets and remembers" settings

### ISSUE THREAD

**Issue by sogen** [jiahaog/nativefier#474]
### Description

Hi, the zoom in function seems to "forget" that is zoomed in.

### Steps to reproduce issue
(After you create the app and launch it)
1.- Click View > Zoom in
2.- Click somewhere, changing to a different page
3.- The zoom goes back to 0
4.- (This is where it gets more odd) Click View > Zoom in
5.- The zoom in is now BIGGER (it's as if the app suddenly remembered the previous zoom, and **Added** more zoom in)
6.- You can do this several times and the zoom will always default to 0 if you switch pages, and go to an even larger zoom in if you click View > Zoom in.

### Details

- Are you nativefying a *public* website?
Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Yes, saw that there's a --zoom option, but this is different, after the app is created.
- Full nativefier command used to build your app: `nativefier "http://app.hubspot.com" --name "HubSpot"`
- Version of Nativefier (run `nativefier --version`): `7.4.1`
- Version of node.js (run `node --version`): `v6.9.4`
- OS: `OSX Sierra`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
@sogen yeah, confirmed, I've experienced similar weirdness too. Here I'm working around the problem by never touching the in-app zoom controls, and only relying on build-time `--zoom` flag.

**Comment by sogen** [comment]
Yes, just made a new "app" using the --zoom flag, worked great.

**Comment by MichaelTunnell** [comment]
confirmed as well.

The issue with me is that the original URL is temporary for other usages so the zoom flag wont work for me so I have to do it manually each time but this is a bit awkward to deal with it.

**Comment by egustavson** [comment]
+1 I am also hitting this bug
