### ISSUE TITLE
--show-menu-bar doesn't seem to do anything

### ISSUE THREAD

**Issue by cwensel** [jiahaog/nativefier#475]
### Description

```--show-menu-bar``` doesn't seem to have an effect.

Honestly, I'm unsure what the menu bar is, but I was hoping it included the address/url bar and back/forward navigation buttons. 

If not, I'm happy to open a feature request for that (along w/ open link in tab).

### Details

- Version of Nativefier (run `nativefier --version`): `7.4.1`
- Version of node.js (run `node --version`): `v6.11.5`
- OS: `osx sierra`

**Comment by ronjouch** [comment]
Hi @cwensel, thanks for the feedback.

`--show-menu-bar` has no effect on macOS, no, as under this OS the menu bar is always visible, at the top of the screen. Under Windows and Linux, though, the menu bar will appear at the top of the window (constantly with the `--show-menu-bar` flag, and without it the bar remains invisible but accessible when the `Alt` key is pressed).

Regarding the request for an address bar and tabs, minimal UI is a *goal* for nativefier; navigation should be done in-app, using the app features. Nativefier's goal is not to re-build a web browser, web browsers are good at that. Its goal is precisely to cut down on browser UI to focus the experience to one app, and let the app do its best at letting the user navigate.

**Comment by cwensel** [comment]
ok, thanks for the explanation.

re the comments on address bar and tabs.

for an single page app like Gmail, the current model works quite well. 

for Google Drive, having tabs is very helpful as the root page is a list of artifact that one wants to edit. editing multiple artifacts simultaneously is helpful (think Pages or Word docs, one app, multiple windows). the address bar makes it easy to copy/paste an url (outof/into) the app.

when considering making github.com an app, having navigation in the bar is very handy. and having an url to copy (paste) is useful when sharing links.

thanks for all the work. I love the tool.

**Comment by ronjouch** [comment]
@cwensel 

> for an single page app like Gmail, the current model works quite well. for Google Drive, having tabs is very helpful as the root page is a list of artifact that one wants to edit. editing multiple artifacts simultaneously is helpful (think Pages or Word docs, one app, multiple windows).

True! I myself use Nativefier principally for Gmail and Feedly, and I wouldn't want to use Gdocs or GitHub or JIRA in Nativefier. But (*to me!*) that's fine: Nativefier is good for *some* apps that fit well a single-screen model (Gmail, Feedly, Whatsapp, Spotify, etc). Web apps not fitting that model and centered on individual documents deserving tabs can stay in the browser and it's alright 🙂. Starting adding an URL bar and tabs feels like a teeming bag of worms leading to (badly) re-implementing a browser. I don't want that, and I'm only a maintainer here but I strongly feel it breaks core qualities (simplicity, minimalism) of Nativefied apps.

> the address bar makes it easy to copy/paste an url (outof/into) the app [...] and having an url to copy (paste) is useful when sharing links

Note that:

- To copy the current URL: Menu → `Edit` → `Copy Current URL` (or its `Cmd`+`L` keyboard shortcut).
- To copy a link's URL: right-click the link, and "Copy link location"

> thanks for all the work. I love the tool.

Appreciated! Thanks for the nice words 🙂.

**Comment by cwensel** [comment]
fair enough. but tbh, the utility is in having each productivity tool/site as a single app. this requires a mix/match of browser features each site leverages while having the option of removing the clutter of those unused.
