### ISSUE TITLE
--tray doesn't work in Windows with https://messenger.com

### ISSUE THREAD

**Issue by lerayne** [jiahaog/nativefier#478]
### Description

--tray doesn't work in windows with https://messenger.com

### Steps to reproduce issue

First I created app without any flags and it worked. Then I tried to make it with `--zoom` flag - zoom added correctly. `--tray` didn't work and now when I'm trying to create app without --zoom - it is zoomed anyway. Probably the entire problem is something about cache? I delete the resulting app folder each time

### Details

- Full nativefier command used to build your app: `nativefier "https://www.messenger.com" --tray`
- Version of Nativefier (run `nativefier --version`): `v7.4.1`
- Version of node.js: `v7.6.0`
- OS: `Windows 10`

**Comment by ronjouch** [comment]
@lerayne thanks for the feedback. Not a bug, the `--tray` flag is simply super recent and not released yet to npm 🙂. Check `nativefier --help` in your 7.4.1, you'll see it's not here.

So just wait for 7.4.2 (should come soon, I asked yesterday the project owner for a release), or build your nativefier from `master` (it's not that hard/long!), following the [development setup guide](https://github.com/jiahaog/nativefier/blob/master/docs/development.md#environment-setup).
