### ISSUE TITLE
Enoent error with nativefier 7.5.0

### ISSUE THREAD

**Issue by billyfung** [jiahaog/nativefier#482]
### Description

Tried installing latest version on os x 

### Details

- Version of Nativefier (run `nativefier --version`): `v7.5.0`
- Version of node.js (run `node --version`): `v8.9.1`
- OS: `macOS High Sierra 10.13`
- Error message / stack trace (if any):

```
billy@Billys-MacBook-Pro  ~  sudo npm install nativefier -g                                                                                                                        ✔  172  17:09:38
Password:
npm ERR! path /usr/local/lib/node_modules/nativefier/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/nativefier/lib/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by ronjouch** [comment]
@billyfung thanks for the feedback, @jiahaog is on it.

**Comment by nkkollaw** [comment]
Same on Ubuntu 16.04 (just confirming it's not macOS-related), using Node 9.1 and Node 8.9.

**Comment by jiahaog** [comment]
Yeah I'm not really sure what is going on, I'll have to dig a little more

**Comment by jiahaog** [comment]
Hmm seems like even though we use travis to release with https://github.com/jiahaog/nativefier/blob/master/.travis.yml#L30-L38,

When I download the tar bundle directly from `npm view nativefier@7.5.0` https://registry.npmjs.org/nativefier/-/nativefier-7.5.0.tgz, only the lib and bin directories are present in the package. I've just manually released 7.5.1 now via my local machine, I'll have to look into why the autorelease didn't work properly.

**Comment by nkkollaw** [comment]
Ha! Awesome.

Do you have an ETA as to when we can try again from NPM?

**Comment by ronjouch** [comment]
> *"Do you have an ETA as to when we can try again from NPM?"*

@nkkollaw 7.5.1 is published to npm, give it a try now 🙂

**Comment by billyfung** [comment]
Older versions work fine too

**Comment by nkkollaw** [comment]
It works!!!

Good job, man.
