### ISSUE TITLE
Basic auth not working for OnShape website

### ISSUE THREAD

**Issue by AABatteries** [jiahaog/nativefier#484]
### Description

Opening nativefied cad.onshape.com application with added username and password doesn't work - user is greeted with website login screen with blank username and password fields.

### Steps to reproduce issue

Build cad.onshape.com with nativefier version 7.5.1 with the following command:

` nativefier --basic-auth-username XXXXXXXXX --basic-auth-password XXXXXXXX cad.onshape.com --disable-context-menu -n OnShape cad.onshape.com `

### Details

- Version of Nativefier v7.5.1
- Version of node.js v6.11.5
- OS: Fedora 25

**Comment by ronjouch** [comment]
@AABatteries thanks for the feedback. You're confusing http basic auth with cookie-based web authentication, which is this site (and most of websites) uses. Here's an example of a site using HTTP basic auth: https://www.httpwatch.com/httpgallery/authentication/

In your case, no need for `--basic-auth-{username,password}` flags; if OnShape responds with a cookie following login, it will be cached by Nativefier/Electron, and you'll be logged in when you re-run the nativefied app. I'm using Gmail and Feedly this way, it's working fine in 7.5.1.

**Comment by AABatteries** [comment]
@ronjouch thanks for the reply. However I am unable to get the login to persist through closing and opening the app again. I am brought to the login screen again with blank fields, does that mean that Electron is not storing the cookie? How can I debug/troubleshoot?

**Comment by ronjouch** [comment]
> *"I am unable to get the login to persist through closing and opening the app again. I am brought to the login screen again with blank fields, does that mean that Electron is not storing the cookie? How can I debug/troubleshoot?"*

@AABatteries first,

1. Does Chrome remember the login?
2.Aare you able to get known-to-remember-login (e.g. gmail) websites work as expected in Nativefier?

**Comment by AABatteries** [comment]
1. Unfortunately, no. Every time I go to cad.onshape.com I am greeted with the login screen, but the username and password fields are filled in due to Chrome's autofill feature. Maybe there is a chance to at least automate filling in the fields with predefined characters in nativefier?
2. Didn't test yet, will report back, but I presume it will work just like you described

**Comment by ronjouch** [comment]
@AABatteries then it's OnShape's job to implement that (or maybe they intentionally didn't for some reason, maybe regulatory). As for autofill, Nativefier doesn't have that feature, sorry.
