### ISSUE TITLE
`--tray` does nothing

### ISSUE THREAD

**Issue by Noedel-Man** [jiahaog/nativefier#485]
### Description

`--tray` does nothing for trello, calendar.google.com and web.whatsapp.com on Ubuntu 17.10 and Arch.

### Steps to reproduce issue
1) type `nativefier web.whatsapp.com --tray` in terminal.
2) start app `./whats-app-web-linux-x64/whats-app-web`
3) click clone button (red X)
4) no tray icon :(. App exited

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `nativefier web.whatsapp.com --tray`
- Version of Nativefier (run `nativefier --version`): `v7.4.0`
- Version of node.js (run `node --version`): `v8.4.0 (arch), v9.x.x (ubuntu)`
- OS: `Arch & Ubuntu 17.10`

Both are using Gnome as DE

**Comment by ronjouch** [comment]
@Noedel-Man `--tray` is new in nativefier 7.5.1, please upgrade your 7.4.0 🙂.

**Comment by kmleow** [comment]
Hi @ronjouch
I am using Ubuntu 17.10.
nativefier 7.5.4

When using `--tray`, closing the app will not show any tray icon.
The process is actually still running invisibly though, I can see 4 instances of `allo` running.

My command line was:
```bash
nativefier -n "Allo" https://allo.google.com/web --single-instance --tray --icon allo.png
```

My PNG file exists, I converted it manually from favicon.ico to allo.png using GIMP.
