### ISSUE TITLE
--tray flag crashes nativefied app under Windows

### ISSUE THREAD

**Issue by apersonnamedmike** [jiahaog/nativefier#486]
### Description
I was simply building Allo for Web, and when I opened the app for the first time I get an error message having to do with the tray icon. after it opens, the app runs as normal, except the tray icon isn't anywhere.

### Steps to reproduce issue
Open app after attempting to use `--tray`

### Details

- Are you nativefying a *public* website? yes
- Full nativefier command used to build your app: `nativefier --honest --tray --disable-dev-tools --single-instance  --electron-version 1.7.6 "https://allo.google.com/web"`
- Version of Nativefier (run `nativefier --version`): `v7.5.1`
- Version of node.js (run `node --version`): `v7.5.0`
- OS: `Windows 10`
- Error message / stack trace (if any):

![capture](https://user-images.githubusercontent.com/10731372/32758141-16fc3682-c8a0-11e7-80b3-5ce5e5a5befa.JPG)

**Comment by ronjouch** [comment]
Bug reproduced with minimal `nativefier --name allo --tray --electron-version 1.7.9 "https://allo.google.com/web"`, thanks @apersonnamedmike 👍. It's Windows-specific, no problem under Linux or macOS.

**Comment by ronjouch** [comment]
Pinging original feature author. @omouren, if you have the time/will to look at this Windows-specific failure of `--tray`, help welcome 🙂.
