### ISSUE TITLE
Improved Drag and Drop Support

### ISSUE THREAD

**Issue by jdsimcoe** [jiahaog/nativefier#49]
I created a Native app wrapper and it doesn't seem to support Drag and Drop. Dragging an image into the window forces the image to takeover the window and I have to restart the app. I added some code that it least prevents the takeover but I can't figure out how to get drag and drop files to pass to `<webview>`. See here from the referenced code I added:

https://github.com/jdsimcoe/figma-electron/blob/master/Figma.app/Contents/Resources/app/assets/js/index.js#L31

**Comment by jiahaog** [comment]
I've tried it out with http://html5demos.com/dnd-upload and facebook messenger and the drag and drop appears to work with nativefier `6.9.1` on OSX 10.11.2. Do you have an example website where this does not work?

**Comment by vinifmor** [comment]
It seems is not working for https://mega.nz. The error in DevTools is:
`Uncaught (in promise) TypeError: Cannot assign to read only property 'path' of object '#<File>'
    at pushFile (blob:https://mega.nz…-4998a867ca49:80101`
