### ISSUE TITLE
Sessions not saved

### ISSUE THREAD

**Issue by RwbyChan** [jiahaog/nativefier#491]
The website that I wanted to try this with saves logins as sessions, everytime I open the app I have to login again.

This is for a private website of mine

**Comment by ronjouch** [comment]
Hi @RwbyChan. Thanks for the feedback, but we'll need more info to troubleshoot. Help us help you, please provide the information we request as part of the [issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md).

Here Gmail and Feedly sessions are correctly persisted; without further info we can only assume *your* app is doing something wrong server-side.

Feel free to come back with more info and I'll re-open the issue. Cheers.

**Comment by RwbyChan** [comment]
Full nativefier command used to build your app: nativefier --name "Some Awesome WebApp" "website url"
Version of Nativefier (run nativefier --version): v7.5.1
Version of node.js (run node --version): v8.9.1
OS: Windows 10
