### ISSUE TITLE
Unable to download attachment

### ISSUE THREAD

**Issue by mdking117** [jiahaog/nativefier#493]
### Description

I was attempting to download an xls file that was attached to an email, when I received the attached error message.

### Steps to reproduce issue
1. Open a message with an attachment.
2. click the download icon to down the file.

### Details

- Are you nativefying a *public* website?No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):
![monosnap 2017-11-25 12 02](https://user-images.githubusercontent.com/21684359/33232771-c363e7d4-d1d9-11e7-836d-237b1f30ef49.jpg)

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
@mdking117 hi. You are posting here an issue about Nativefier, not the IBM Verse app. I infer IBM is using Nativefier to package their website, but we Nativefier maintainers have nothing to do with it. Please get in touch with the IBM Verse team. Good luck 🙂.
