### ISSUE TITLE
IBM Verse Mac App: unable to open Calendar link

### ISSUE THREAD

**Issue by mdking117** [jiahaog/nativefier#494]
### Description

I'm using the IBM Verse Mac App and trying to open my Calandar using the Calendar link (as well as the calendar icon).  When I do, I received the following error message:
Sorry, we cannot find the page you requested.

A link may be broken, or the Web address may be incorrect.

Return to Home

1404-404

All other links work as expected.
### Steps to reproduce issue
1. Open IBM Verse Mac App.
2. Click on the Calendar link at the top of the UI.  or click on the Calendar icon on the lower right of the UI.

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
@mdking117 hi. You are posting here an issue about Nativefier, not the IBM Verse app. I infer IBM is using Nativefier to package their website, but we Nativefier maintainers have nothing to do with it. Please get in touch with the IBM Verse team. Good luck 🙂.

**Comment by mdking117** [comment]
Thanks for the info.  On the app itself, they have a Report an Issue menu item that leads to this github.
