### ISSUE TITLE
Update the help prompt for --icon

### ISSUE THREAD

**Issue by PLNech** [jiahaog/nativefier#496]
### Description

Creating an app with an icon on Mac OS following the help prompt results in an app with no icon.
As #53 recommends to use a PNG on Mac OS too, the help prompt should be updated to reflect that.

### Steps to reproduce issue
- Following the filetype advice in the help prompt:
`-i, --icon <value>              the icon file to use as the icon for the app (should be a .icns file on OSX, .png for Windows and Linux)`
  I created a `.icns` file for my nativefier app.

- Generating the app with `nativefier --name "foo" "https://foo.bar" -i icon.icns` creates an app with no icon.

- Searching for a workaround, I saw in #53 that one should use PNG files for icons regardless of the platform.
- Indeed, using a PNG file instead solved the error.

### Details

- [ ] Feature request? No, docs update
- [x] Are you nativefying a *public* website?
- Full nativefier command used to build your app: `nativefier --name "foo" "https://foo.bar" -i icon.icns`
- [x] Version of Nativefier (run `nativefier --version`): `7.5.4`
- [x] Version of node.js (run `node --version`): `v6.3.1`
- [x] OS: `Mac OS`
- [] Error message / stack trace (if any):

**Comment by ronjouch** [comment]
@PLNech thanks for the feedback! Sure. Would you try submitting a PR? See #444 for inspiration, there should be just two files to amend :)

**Comment by PLNech** [comment]
@ronjouch sure! See PR #502. I checked the several files changed in #444, but as far as I understand only `src/cli.js` had to be modified (`docs/api.md` didn't need changes either).
