### ISSUE TITLE
Open links in native browser

### ISSUE THREAD

**Issue by VicCreatech** [jiahaog/nativefier#498]
### Description

Is there a way to control if a link will be opened in the application or a browser

### Details

we have attachments in the app and 2 buttons 
- open (in a browser) i.e. attached image
- download (i.e. zip) 

because both a served from the same web site the system treats it as a part of the app and opens new app window instead of a browser

is there a way to work around?

**Comment by ronjouch** [comment]
Yes 🙂, see https://github.com/jiahaog/nativefier/issues/460#issuecomment-334957504
