### ISSUE TITLE
Clicking a link that downloads a file, does not show "Save As" prompt

### ISSUE THREAD

**Issue by githubbob42** [jiahaog/nativefier#499]
### Description

Clicking a link that downloads a file, does not show "Save As" dialog.  Instead it just downloads the file in the background with no notification that it did so.  

In my particular case, we're using the `ApplicationCache` to store files via a manifest to get around the web storage limits.  The problem is that this is a magical black box and when you request one of these files, you get back a blob url with a random guid (i.e. every time you click the same link you get a different guid: e.g. `blob:http://localhost/89c1c201-671b-4fd3-85aa-8ad8d3f64776`).  The file gets saved ok, but with a random guid and no file extension.

I was able to set the `download` attribute with the correct filename and extension and that helps by saving the file with the correct name, but there is still no notification that the file was saved (or anything happened), so the user keeps clicking the link over and over, all the while, saving a new copy of the document to their Downloads folder with every click.

### Steps to reproduce issue

Have a link who's `href` is a url, a data url or a blob url, that points to a document of a non-displayable filetype (doc, docx, xlsx, etc).  Clicking on it should download the file.  

### Details

Nativefier is using [electron-dl](https://github.com/sindresorhus/electron-dl) for the downloads and under "Why?" of it's `readme.md` it states: 

> Saves the file to the users Downloads directory instead of prompting.

That's great and all, but in an app that is displaying a web page and you click on a link to download a file, you expect to get prompted on where to download and what to name it.

Looking at the `electron-dl` code, I see that the there are a few options for controlling the download bahavior (such as [showing the "Save As" dialog](https://github.com/sindresorhus/electron-dl/blob/0557fd3fb92a742f3131b35c5f51660be02da972/index.js#L53), etc) but they are never set as nativefier isn't [passing in any options](https://github.com/jiahaog/nativefier/blob/master/app/src/main.js#L15).

I would like to suggest that we default the `saveAs` option to `true` but I can understand if that is not desired for a particular reason.

However, we should be able to pass in options to control the behavior of downloads since the options are available.

I am working on a PR for this now.  The jist of it is:
```js
let fileDownloadOptions = Object.assign({ saveAs: true }, appArgs.fileDownloadOptions);
electronDownload(fileDownloadOptions);
```
The question is whether to default file downloads to show the Save As dialog or not.

**Comment by ronjouch** [comment]
Partially duplicate / related to #335. @githubbob42 yes, PR welcome 🙂, and if you're in a productive mood, feel free to look at the other items listed at #335 ^^.

> The question is whether to default file downloads to show the Save As dialog or not

As usual, I'm biased towards maximum backwards compatibility, so my vote goes towards

- Keeping the current default behavior as is and adding a `--prompt-download-folder` flag.
- As requested in #377, a "Save As" contextual action would be awesome, to let users of the default behavior occasionally go the Save As way.

@jiahaog @githubbob42 thoughts?

**Comment by githubbob42** [comment]
Thanks for the input @ronjouch.  I certainly understand the bias towards maximum backwards compatibility.

However, having only a `--prompt-download-folder` option seems limited since the `electron-dl` module supports additional options (some of which were requested in #335).   And providing a separate parameter/flag for each option seems a bit cumbersome and a maintenance headache if `electron-dl` adds a new or removes an option in a later release (we'd have to modify Nativefier again).

That is why I suggested passing an object to the `electronDownload` constructor/initializer.  This way, you can pass any option that `electron-dl` supports (or adds in the future). 

Perhaps instead of naming the parameter `fileDownloadOptions`, it should be called `electronDownloadOptions` (or `electron-dl-options`) to be more semantically correct.  I considered these names initially but wasn't sure if it would be meaningful or confusing to the end user/developer (e.g. is this for downloading files or downloading `electron` itself).  In my case, the end user would be able to specify/override the settings in the `nativefier.json` file, so `fileDownloadOptions` (or `file-download-options`) seemed the obvious name but I'm open to suggestions.  Plus the `api.md` documentation would direct them to the `electron-dl` page for the available options.

@jiahaog @ronjouch thoughts?

**Comment by ronjouch** [comment]
@githubbob42 awesome. 👍 for passing an object, and `electronDownloadOptions` seems sane yes, it is what it is and we’re not gonna pretend it’s something else or add a layer. Please give special attention to the docs yeah, concise / clear / with examples. Thanks again!
