### ISSUE TITLE
High kernel_task CPU usage running SoundCloud on macOS

### ISSUE THREAD

**Issue by hrdwdmrbl** [jiahaog/nativefier#503]
### Description

While running an application created with Nativefier, specifically in this case the website Soundcloud.com, after continued use I get sustained high CPU load from the application _and_ from the mac kernel_task process. High load would be 30-50% on my Macbook Pro.
I think the problem is likely some unfortunate interaction between the Soundcloud code, nativefier and maybe the Mac OS.

### Steps to reproduce issue

These steps are a bit fuzzy, since it's not a specific error. There are likely many ways to reproduce the error

1. Create an app from Soundcloud.com and start playing any track.
2. Scroll down a page that has infinite scroll. Scroll for a long time. The "Discover" page on list view should be good.
3. Navigate to another page, perhaps an artist page.
4. Return to the "Discover" page and scroll again.

After just doing this, I now have 18-25% CPU from two "helper" processes and around 17-20% CPU from kernel_task. This is sustained. And it can get much worse. The only fix is to restart the app.

### Details

- Are you nativefying a *public* website?

Yes, soundcloud.com

- Full nativefier command used to build your app: `<command here>`

`nativefier soundcloud.com`

- Version of Nativefier (run `nativefier --version`): `v0.0.0`

7.4.1

- Version of node.js (run `node --version`): `v0.0.0`

8.9.0

- OS: `<OS here>`

OSX 10.13.1

**Comment by ronjouch** [comment]
@hrdwdmrbl can you retry with a recent version of Nativefier / electron? Please install the latest Nativefier, or pass `--electron-version 1.8.4`

**Comment by hrdwdmrbl** [comment]
It does seem to still be happening, but only while playing now. Before it was happening while just browsing.

Using the app, playing a song
![screen shot 2018-04-26 at 11 06 47](https://user-images.githubusercontent.com/554881/39314350-0b93e100-4942-11e8-9ce6-5ad72a3c06b5.png)

Using the app, song is paused
![screen shot 2018-04-26 at 11 08 25](https://user-images.githubusercontent.com/554881/39314377-195fc934-4942-11e8-967b-250d74a847e5.png)

I wonder if maybe playing a song is just a really compute intensive task the way Soundcloud have implemented it.
It would be nicer if CPU usage while it wasn't playing was lower than 1.2%. Seems high for doing nothing, but I wouldn't call the problem critical.

**Comment by ronjouch** [comment]
@hrdwdmrbl can you try with a recent version of Nativefier / electron? Please install the latest Nativefier, or pass `--electron-version 1.8.4` . Also, does it happen under regular Chrome?

**Comment by hrdwdmrbl** [comment]
Yes, I used the most recent

**Comment by ronjouch** [comment]
> *"Chrome seems about the same"*

@hrdwdmrbl that closes the issue, then 🙂. Please report to Soundcloud and/or Chromium.
