### ISSUE TITLE
Download AJAX content?

### ISSUE THREAD

**Issue by cristiangradisteanu** [jiahaog/nativefier#505]
Hi,
This is mostly not an issue but a feature request.
I would like to use nativefier to create a desktop version of an website that is using AJAX to load the next page's content (most of the time it's just a video).
Is this possible?
I tried to create the desktop app and this works fine as long as there is an internet connection to the machine, but if there isn't an internet connection, the next page (video) does not load.
Is there any switch for pre-loading AJAX content in advance and save it into the app?
Thanks!

### Description

<Detail your problem here as clearly and concisely as possible 🙂. Help us help you by saying why and giving some context!>

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
@cristiangradisteanu thanks for the feedback. Two thoughts:

- Maybe you can implement your desired functionality using our script/css injection features. See our [documentation for `--inject`](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#inject).
- Or maybe the behavior you're expecting ought to be implemented in the webapp itself. The recent and awesome [ServiceWorker API](https://developer.mozilla.org/en/docs/Web/API/Service_Worker_API) comes to mind, it lets webapp developers intercept / play with / replace http requests.

Closing, but feel free to chime in if I'm missing something that you feel is still missing from Nativefier. If you do so, please bring as much detail as possible to explain what you're expecting. Thanks :)
