### ISSUE TITLE
use chrome extensions in nativefier?

### ISSUE THREAD

**Issue by ekimia** [jiahaog/nativefier#506]
Is this possible? Or a technical limitation?

**Comment by ronjouch** [comment]
Thanks for the feedback, @ekimia. No, for now we don't support bundling Chrome extension, and it's unlikely to come soon, given upstream (electron) position on this, see discussion at #207

**Comment by Rimseg** [comment]
@ekimia 

> Is this possible? 

Yes, but it's a workaround: https://github.com/jiahaog/nativefier/issues/246#issuecomment-718708717
