### ISSUE TITLE
npm run test fails on a slow connection

### ISSUE THREAD

**Issue by mdh34** [jiahaog/nativefier#508]
### Description

`npm run test` will fail on a slow connection - it times out while waiting for electron files to download

### Steps to reproduce issue
`npm run test`

### Details
It looks like the timeout implemented to test if promises return etc. doesn't take into account download times / speeds

**Comment by ronjouch** [comment]
Not going to fix this, this is out of our control (it's electron-dl's job) and yes, tests do lots of downloading various Electrons and it's good because it's what we want to test. Closing.
