### ISSUE TITLE
Print not work

### ISSUE THREAD

**Issue by khaninejad** [jiahaog/nativefier#509]
### Description
We have a page with a print feature it's work in a browser but when we compile and test it with desktop app it does not work.
### Steps to reproduce issue
open printable page.
click on a print button

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: default commend 
- Version of Nativefier (run `nativefier --version`): 7.5.4 
- Version of node.js (run `node --version`): 6.0
- OS:  Win10 x64
- Error message / stack trace (if any): no

```
<Error message / Stack trace here>
```
Print not work

**Comment by ronjouch** [comment]
@khaninejad thanks for the feedback 👍, but I couldn't reproduce the problem here with the "Print thread" feature of Gmail, nativefied on Linux / Node 9.3.0 / Nativefier 7.5.4. Please provide the problematic website.

**Comment by khaninejad** [comment]
@ronjouch thanks, I fixed my problem using this solution:
If you want to print a page with nativefier first open website with windows.open("https://printpagelocation"); then windows.print();

Thanks

**Comment by mohsenuss91** [comment]
@khaninejad just tried with window.open(window.location.href) but ain't working!

**Comment by luisemz** [comment]
I tried "pdfMake.createPdf(pdf).print()" and the nativefier (v. 7.6.8) don´t show anything.
What is wrong?

**Comment by jaezer123** [comment]
I have the same issue. I use dataTables plugin for printing. And also TCPDF. I hope you can fix this issue.
