### ISSUE TITLE
User Agent Settings

### ISSUE THREAD

**Issue by momosby** [jiahaog/nativefier#51]
I can't figure out, how to set the User Agent.
WhatsApp for example does not work with the default settings of Nativefier.

when I flag -u nothing changes

like -u "Chrome"

what are the values that go after the -u flag?

**Comment by jiahaog** [comment]
You have to enter in a user agent string after the -u flag. For example:

```bash
$ nativefier google.com -u "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36" ~/Desktop
```
You can google around to find example user agent strings, I simply copied it from http://www.useragentstring.com/pages/Chrome/

**Comment by momosby** [comment]
I get it ;) thanks - i tought there would be shorthands
