### ISSUE TITLE
[Feature Request] Add plugin support

### ISSUE THREAD

**Issue by shootsoft** [jiahaog/nativefier#513]
It would be very nice to have plugin support. Plugins that could be loaded before loading the web site or customized login page etc...

**Comment by ronjouch** [comment]
@shootsoft thanks for the feedback.

- If I understand correctly your *"plugins loaded before loading the web site"*, we have this, see [docs for `--inject`](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#inject).
- And if you're asking about packaging Chrome extensions, see https://github.com/jiahaog/nativefier/issues/207

**Comment by shootsoft** [comment]
@rohmanhm 

The plugin I mean JS that could be executed as part of nativefier not on loading the page but before loading any pages. Not injecting JS into the page.

A few cases:

- Detecting offline events
- Custom page loading
- Custom login page
- Custom loading errors

etc...
