### ISSUE TITLE
html5 datalist problem

### ISSUE THREAD

**Issue by TabrizAdmin** [jiahaog/nativefier#517]
### Description

Hi. There is a problem when using html5 datalist. when the list is preview there is an empty space between the list and field.

### Details

- Full nativefier command used to build your app: nativefier --name "myapp" --logo "icon.png" --arch "ia32" "http:linktomywebsite.com"
- Version of Nativefier: `v7.5.4`
- Version of node.js: `v9.1.0`
- OS: win 10 x64

**Comment by ronjouch** [comment]
Heyho @TabrizAdmin, thanks a lot for the feedback 🙂. Could you provide a reproduction scenario on a public website, please?

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. feel free to chime in and re-open the discussion anytime 🙂!
