### ISSUE TITLE
Spotlight/Alfred Searchability

### ISSUE THREAD

**Issue by momosby** [jiahaog/nativefier#52]
Would be awesome, if Nativefier somehow could get the created apps to be included in OS X's Spotlight Index

**Comment by jiahaog** [comment]
I've just tried it out and it seems like I'm able to search for them on Spotlight and Alfred without making any changes. Perhaps you have certain filters turned on that prevents your packaged apps from showing up?

**Comment by miduga** [comment]
I can confirm that I can see my app using Spotlight.

**Comment by momosby** [comment]
Ok - sorry I bothered you. Must be something odd, since all Other pkged apps work...

**Comment by miduga** [comment]
Maybe is it cached? Sometimes Spotlight gets "frozen" and doesn't update the database for a while. @momosby

**Comment by momosby** [comment]
No - i actually forced the Spotlight index to rebuild and der my alfred search scope to search for all file types... Does not resolve it. But thanks for the help

**Comment by simonweil** [comment]
Works for me too.

**Comment by momosby** [comment]
I moved my .app out of the Darwin-x64 folder and after that it works
