### ISSUE TITLE
login with classic asp form in our website

### ISSUE THREAD

**Issue by alexgoa** [jiahaog/nativefier#520]
### Description

Hello, I'm having a login page (classic vb asp) thru which different consultants will login to our webserver. 
I want to create a long strong password (255 characters) embedded into the exe in order to force them to use only the app to login and interact with our web server, since the password won't be given to them.
Is there any way to either embed an html file containing the web form with the credentials or any other way to land on a login.asp page which has already the given credentials?
Basic auth user and psw could be helpful but I don't succeed to have them intercepted on the login.asp page

Thanks a lot for the help.
Alessandro

- here the Nativefier command 
nativefier http://www.mysite.com/login.asp --icon D:\favicon.ico --flash --maximize --disable-dev-tools --crash-reporter http://www.mysite.com/crash_report.asp --single-instance --basic-auth-username aaaaaaa --basic-auth-password bbbbbbbbbb --disable-context-menu --honest --user-agent mywebsite.com --app-copyright "My Company Name"
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v8.9.4 lts`
- OS: `<windows 10 64 bit>`

**Comment by ronjouch** [comment]
> *"Is there any way to either embed an html file containing the web form with the credentials or any other way to land on a login.asp page which has already the given credentials?"*

@alexgoa nativefier's build flag [--inject](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#inject) should let you bundle / obfuscate filling the form with a bit of JS.

**Comment by alexgoa** [comment]
thanks a lot. 
I'm not practice with javascript. do you know any resource to use an example ?
thanks 
Alex
