### ISSUE TITLE
X Y Coordinates not working 

### ISSUE THREAD

**Issue by x3r4n0** [jiahaog/nativefier#523]
i tried to open my wrapper on a special location on the screen with --y --x but it dosnt work

i will open my wrapper behind the tray area on the right bottom corner.

i get no error it seems to that the wrapper overrides to the center area of the screen

**Comment by ronjouch** [comment]
@x3r4n0 thanks for the feedback but I don't understand. Can you reformulate what's broken and provide minimal debug information (first and foremost: full nativefier command line)?

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. feel free to chime in and re-open the discussion anytime 🙂!
