### ISSUE TITLE
Adding icon is not working properly

### ISSUE THREAD

**Issue by miduga** [jiahaog/nativefier#53]
OS: OSX 10.11.2

Executing:

```
nativefier -n "Hubii News" -o -i ./Hubii_App_Icon.icns "http://hubii.com"
```

It doesn't attach the icon on the application. The small size of the icon is correctly attached while the big one show the default icon. If I add the app to the dock, I can see only the default app icon instead the one I'm trying to attach. 

icns file:
[Hubii_App_Icon.icns.zip](https://github.com/jiahaog/nativefier/files/100784/Hubii_App_Icon.icns.zip)

Result where you can see the small icon correctly attached but where the previsualization icon is not correctly attached.
<img width="607" alt="captura de pantalla 2016-01-22 13 54 45" src="https://cloud.githubusercontent.com/assets/1561955/12511191/b8480fa6-c10f-11e5-9718-27d226cfe0ac.png">

If you need more info, please just tell me. If it's a normal behaviour, just close the ticket. Thanks!

**Comment by momosby** [comment]
Do it like the link for the .icns in the readme tells you. (Get info of an .icns, Click Icon in the Upper left, cmd+c // get Info ob your electron app (cmd+i), click the icon and hit cmd+v)

Takes a few seconds to take effect

**Comment by vberruezo** [comment]
@momosby but the idea is to build the app with the icon in the package.
I have the same issue as @miduga

**Comment by danqing** [comment]
My past experience indicates that running the script twice or using absolute path could work.

**Comment by jiahaog** [comment]
Hi, I believe this issue is because the `.icns` file you provided is missing certain assets. Could you try to provide a `.png` instead, after installing the dependencies specified in the readme for `v6.7.0`

**Comment by miduga** [comment]
I'll try it and I'll be back with more info.

**Comment by miduga** [comment]
Working nice with .png :+1: Good work!
