### ISSUE TITLE
Create application using Chrome profile

### ISSUE THREAD

**Issue by soeirodefaria** [jiahaog/nativefier#535]
### Description

Is there a way to create a app, say Google Docs, using Chrome profile, this way it know user and password?
I have 3 profiles in my Chrome, and would like to have one app per user(profile)

**Comment by ronjouch** [comment]
@soeirodefaria thanks for the feedback 🙂. Nope, we don't import anything from Chrome, you'll have to re-enter your passwords.

**Comment by soeirodefaria** [comment]
That was quick!
Thanks for the response..

Awesome tool
