### ISSUE TITLE
App freezing in windows, how can I monitor that? and the app opens 2 process in the task manager

### ISSUE THREAD

**Issue by johnico** [jiahaog/nativefier#536]
### Description

Chrome is freezing with  web page with lot of HTTP request

is it possible that the web page will freeze? the nativefire that run the chrome just freezing.
the app send requests to the local server every second and after few hours the app is freeze 

how can I check why it freezes? , the regular chrome is not freezing

has the new version get performance improved?

* also in windows task manager I see 2 processes running

### Steps to reproduce issue
Do not know how to 
### Details

- Are you nativefying a *public* website? no
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? yes
- Full nativefier command used to build your app: `nativefier --verbose --hide-window-frame --disable-context-menu  --full-screen --maximize  "<URL>"
` 
- Version of Nativefier (run `nativefier --version`): Nativefier v7.2.0
- Version of node.js (run `node --version`): latest version
- OS: `Windows` 
- Error message / stack trace (if any):

**Comment by ronjouch** [comment]
@johnico

> *"How can I check why it freezes? The regular Chrome is not freezing."*

Hit <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> to get the Developer Tools and use the console / performance tools to inspect what's wrong.

> *"has the new version get performance improved?"*

Yes. Please

1. Install the latest Nativefier
2. Try specifying the latest Electron (and thus, the latest Chrome / Node / V8) using the `--electron-version` flag. The latest Electron is 1.8.2, released yesterday 🙂. So: `nativefier --verbose --hide-window-frame --disable-context-menu --full-screen --maximize --electron-version 1.8.2 "<URL>"`

Then please confirm/infirm the performance trouble here, with any additional information that may help. Good luck; cheers.
