### ISSUE TITLE
Could not keep the full screen mode after click on F11 in windows 7 

### ISSUE THREAD

**Issue by johnico** [jiahaog/nativefier#537]
**Description**

Could not keep the full screen mode after click on F11 in windows 7
is it possible to disable F11?

**Steps to reproduce issue**

open the app, click F11, close the app and open again

**Details**

Are you nativefying a public website? no
Feature request? Have you looked at nativefier --help to see if an existing option could fit your needs? yes

Full nativefier command used to build your app: nativefier --verbose --hide-window-frame --disable-context-menu --full-screen --maximize "<URL>"
Version of Nativefier (run nativefier --version): Nativefier v7.4.1
Version of node.js (run node --version): latest version
OS: Windows
Error message / stack trace (if any):

**Comment by ronjouch** [comment]
@johnico thanks for the feedback. I don't understand what you're asking for, can you be more precise?
