### ISSUE TITLE
--file-download-options does not seem to be doing anything.

### ISSUE THREAD

**Issue by tjkohli** [jiahaog/nativefier#539]
### Description

The Save As dialog (or directory) options do nothing when setting the `--file-download-options` flag.

### Steps to reproduce issue

I just run that command and the app builds successfully. However, file downloads still don't trigger the Save As dialog. I even tried installing `electron-dl` in my build directory but that doesn't do anything.

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `nativefier --name "(Name redacted)" "(URL redacted)" --single-instance --file-download-options '{"saveAs": true}' --inject ~/Sites/( folder name redacted)/_/( file name redacted).css --inject ~/Sites/( folder name redacted)/_/( file name redacted).js --icon ~/Sites/( folder name redacted)/_/( file name redacted).icns --min-width 768px --min-height 550px`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v5.6.0`
- OS: `macOS 10.13.3`
- Error message / stack trace (if any): No errors. Build is successful.

**Comment by ronjouch** [comment]
@tjkohli thanks for the feedback! `--file-download-options` is a recently introduced feature, not yet published to npm. Just [build from source](https://github.com/jiahaog/nativefier/blob/master/docs/development.md#environment-setup) to get it.
