### ISSUE TITLE
App title at the beginning is "Electron" instead the app name

### ISSUE THREAD

**Issue by miduga** [jiahaog/nativefier#54]
When you first execute the app you can see the Electron title on the app instead the App Name that you've defined before. While I think that's a "feature" it would be nice to not show the Electron title never and instead show as window title the app name while the app is retrieving the info of the title.

Maybe in the future would be interesting as well to add an option to keep always the same title (the App Name) instead updating with the document.title.

**Comment by jiahaog** [comment]
Thanks for the heads up!
