### ISSUE TITLE
Nativefier- iFrame windows loads in the default browser

### ISSUE THREAD

**Issue by Senthilthirunavukkarasu** [jiahaog/nativefier#542]
Hi,

I have my company website developed with iFrame. I used the nativefier to build an desktop application for windows. On executing the .exe file, iFrame loads in the default browser whereas the rest of the application loads in the app. This causes a abnormal usage of nativefier and it blocks me from creating a desktop application using this. Any help appreciated.

Regards,
Senthil.

**Comment by ronjouch** [comment]
Hi @Senthilthirunavukkarasu, thanks for the feedback! I build several Nativefied apps that use `iframe`s (GMail, Feedly) and haven't encountered specific problems. Could your problem be on *your* application side? Closing, please investigate on your side and feel free come back with additional info 🙂.
