### ISSUE TITLE
permanent Chooser 

### ISSUE THREAD

**Issue by StuartZaq** [jiahaog/nativefier#543]
### Description

After I press Insert file from Dropbox and choose the file in Chooser and press OK, the Chooser opens again and keep reopening even if I click Cancel or the x button in corner. Only app restart helps.

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v7.1.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `MacOS 10.13.3`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Hi @StuartZaq and thanks for the feedback, but there isn't much we can do with this little information. This project is a hobby with few maintainers at the wheel, helping during spare time. Do not expect "customer support"-style interaction; we need *you* to investigate as much as possible before opening an issue: try to narrow it as much as possible, provide the minimum details requested by [the issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md), intuitions, a reproducible scenario, etc: help us help you 🙂, maintainers are not wizards and do not read your mind. Of course, the best you can provide is code, PR very welcome.

With that, closing, but will re-open if you find the time to bring details. Cheers!

*<sub>Text inspired by [uBlock's CONTRIBUTING.md](https://github.com/gorhill/uBlock/commit/d3cd79c5b019612abe64e753eecf0417af9dfb78)</sub>*
