### ISSUE TITLE
Feature Request : Support chrome extentons

### ISSUE THREAD

**Issue by vikrantk365** [jiahaog/nativefier#548]
### Description

Thanks for the awesome tool.
I use few extensions on chrome which are very useful to me e.g Dark Reader
Is there any way I can get them into Nativefier generated app?

### Details

- Are you nativefying a *public* website? No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `default command`
- Version of Nativefier (run `nativefier --version`): Latest
- Version of node.js (run `node --version`):  5.5.1
- OS: `<OS here>` Ubuntu 16.04a

**Comment by ronjouch** [comment]
Not currently, see #506 .

**Comment by vikrantk365** [comment]
Thanks
