### ISSUE TITLE
Modal electron window not working

### ISSUE THREAD

**Issue by sgroh** [jiahaog/nativefier#549]
### Description

We should be able to specify a nativefier flag to indicate that we want to maintain the nativefied app "always on top"

### Steps to reproduce issue
Just nativefy any public website with any flag combination and the result will be always a non modal window app.

I've tried to add the flag manually on main.js on all  new _electron.BrowserWindow({ ... modal:true}) but the created windows seems to ignore this flag.

### Details
- I've tried with a bunch of public websites and the result is always the same a non modal windows.
- Version of Nativefier: `v7.5.4`
- Version of node.js: `v8.2.1`
- OS: `linux`
- Error message / stack trace (if any): No errors since this can be an inprovement.

**Comment by ronjouch** [comment]
@sgroh thanks for the feedback 🙂. See discussion at https://github.com/jiahaog/nativefier/issues/436

**Comment by sgroh** [comment]
Thanks @ronjouch, yes I fond it after I create this ticket. BTW I still think that a tool like nativefier that is  providing really good cross-platform support and not provide a good feature like modal window to rely on native OS tools like aplay is a bit weird. 

Why not use electron-modal to solve this?

**Comment by ronjouch** [comment]
> *"Why not use electron-modal to solve this?"*

@sgroh two things:

1. – See https://github.com/jiahaog/nativefier/issues/436#issuecomment-325441120 – In Unix *[one thing well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)* spirit, to me your feature request sounds like the Window Manager's responsibility, and not the job of Nativefier.
    * Windows: [Google lists several solutions](https://encrypted.google.com/search?q=windows%20%22always%20on%20top%22).
    * Linux: it's just one `wmctrl -r "window title" -b add,above` away
    * macOS: seems to be more involved, but ["afloat" seems to do the job](https://www.maketecheasier.com/mac-keeping-your-application-window-always-on-top/)
2. Nativefier is in "maintenance mode", with no active developer and only me doing the occasional breaking bug fix, deps bump, and PR review/merge.

That being said, I understand the user value, and the straightforwardness of an `--always-on-top` build-time flag would be neat. So, PR welcome 🙂.

**Comment by sgroh** [comment]
Ok @ronjouch, I've created the PR: https://github.com/jiahaog/nativefier/pull/551
