### ISSUE TITLE
App icon dosen't work on notification

### ISSUE THREAD

**Issue by taiyoslime** [jiahaog/nativefier#55]
## Overview
I executed nativefier with .icns and create an app of `tweetdecks.twitter.com`.
Icon looks working,
<img width="62" alt="ss 2016-01-22 23 23 31" src="https://cloud.githubusercontent.com/assets/11515982/12513087/375dcf84-c15f-11e5-9fe1-a9fb34a358f9.png">

But only on notification , the icon replaced with official election icon , like this.
( Twitter notify )
<img width="329" alt="7e58fff8-c15f-11e5-80a6-22b12f9b5331" src="https://cloud.githubusercontent.com/assets/11515982/12513204/e860e3ca-c15f-11e5-9e75-4484d2be7079.png">

```
env:
OSX 10.10.2
nativefier,Electron,Electron-package are the latest version.
```

(Is it electron-packager's bug...?)

**Comment by jiahaog** [comment]
I believe it's working now in the latest version (v6.8.0)!
