### ISSUE TITLE
read app arguments?

### ISSUE THREAD

**Issue by UserNeo** [jiahaog/nativefier#550]
Hi,

Is it possible to read the app arguments? I would like to use the app via tel: but I have to be able to read out the transferred phone number. Is that possible with nativefier?

**Comment by ronjouch** [comment]
Hi @UserNeo, thanks for the feedback. I don't understand your use case and what you are asking for, please reformulate.

**Comment by UserNeo** [comment]
Hi, sorry for me bad english. I have developed a website, which is managing local SIP phones (especially Yealink desktop phones). Now i would like to when i click on a tel: link, than the nativefier generate app starts automaticlly. How can i get read out the given phone number?

**Comment by ronjouch** [comment]
@UserNeo you should be able associate your Nativefier to a custom protocol (e.g. `tel://...`) URL. Other users seem to have been able to do it, see https://github.com/jiahaog/nativefier/issues/390
