### ISSUE TITLE
Fail to nativefier Google Calendar with PostgreSQL error on darwin-x64-template

### ISSUE THREAD

**Issue by alexcombessie** [jiahaog/nativefier#554]
### Description

I am trying to nativefier my google calendar

### Steps to reproduce issue
`nativefier --name "gCalendar" "https://calendar.google.com/calendar/r"`

### Details

- Are you nativefying a *public* website? No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? yes
- Full nativefier command used to build your app: `nativefier --name "gCalendar" "https://calendar.google.com/calendar/r"`
- Version of Nativefier (run `nativefier --version`): `v7.5.4`
- Version of node.js (run `node --version`): `v9.8.0`
- OS: `macOS 10.13.3 High Sierra`
- Error message / stack trace (if any):

```
Downloading tmp-33300-1-SHASUMS256.txt-1.7.9
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
Packaging app for platform darwin x64 using electron v1.7.9
{ Error: ENOENT: no such file or directory, stat '/Library/PostgreSQL/9.6/bin/darwin-x64-template'
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Library/PostgreSQL/9.6/bin/darwin-x64-template' }
```

**Comment by ronjouch** [comment]
@alexcombessie make sure the directory you're writing to is writable by your user 🙂

**Comment by alexcombessie** [comment]
I see, thank you
