### ISSUE TITLE
EPERM Operation Not Permitted when running through Program Files

### ISSUE THREAD

**Issue by samirotiv** [jiahaog/nativefier#557]
### Description

I've created an installer for my nativefied app using Inno Setup. After installing, I get the following error:
![image](https://user-images.githubusercontent.com/4405935/37571954-ea72fed8-2b29-11e8-8e6e-130977e10dbb.png)

It seems to happen also when I simply copy the nativefied folder to program files and run it from there.

### Steps to reproduce issue

Create a nativefied app and copy it to program files, run it from there. Tested the 32 bit build on 64 bit Windows 10.

It does not happen consistently, unfortunately, but has been happening inconsistently (70% of the time) across several computers.

**Comment by ronjouch** [comment]
@samirotiv thanks for the feedback 🙂. Could you provide more information regarding your permissions?

- User type (regular/admin)
- Permissions for `Program Files`
- Permissions for `Program Files\nativefied-app`
- Permissions for `Program Files\nativefied-app\package.json`

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. feel free to chime in and re-open the discussion anytime 🙂!
