### ISSUE TITLE
End point federation not working

### ISSUE THREAD

**Issue by suzanne-spalinger** [jiahaog/nativefier#558]
### Since this morning I can't pass the Endpoint federation of Verse.
Have re-installed verse.. but it doesn't help.

<img width="1067" alt="screen shot 2018-03-19 at 08 59 12" src="https://user-images.githubusercontent.com/37532273/37583954-e22e090a-2b53-11e8-9091-4a4404380fff.png">

**Comment by ronjouch** [comment]
@suzanne-spalinger please direct your support requests for IBM Verse to IBM 🙂.
