### ISSUE TITLE
Backward workaround

### ISSUE THREAD

**Issue by rosolko** [jiahaog/nativefier#56]
Hello,

I'm using this application on linux and I have no ability to go back from current the page.

Can you please add(enable) chrome context menu for application?
It will be very nice solution.

Something like this:
![att_14](https://cloud.githubusercontent.com/assets/11458319/12513327/608e4626-c12e-11e5-8d1a-ed3f4d58445c.png)

**Comment by jiahaog** [comment]
I've implemented navigating backward and forward via the application menu in e0de7bf463f7611e10fcb6ed5d10b2c830d3952d, let me know if that works for you.

**Comment by rosolko** [comment]
No, that not working for me.
I have no options for navigating in any menu entry.

App version: 
![att_17](https://cloud.githubusercontent.com/assets/11458319/12544030/f277e9a6-c346-11e5-8035-224c031673f6.png)

Edit:
![att_18](https://cloud.githubusercontent.com/assets/11458319/12544032/f664e0b4-c346-11e5-8dc0-76f0118570c7.png)

View:
![att_20](https://cloud.githubusercontent.com/assets/11458319/12544036/ffd3e67c-c346-11e5-9363-ab9807c70f95.png)

Window:
![att_20](https://cloud.githubusercontent.com/assets/11458319/12544039/04d78e1c-c347-11e5-997e-a87f17a0c9aa.png)

**Comment by jiahaog** [comment]
What version of nativefier are you using?

**Comment by rosolko** [comment]
6.6.1

**Comment by rosolko** [comment]
UPD: After update nodejs to v5.5.0 and nativefier to 6.6.2 - menu with back and forward is appear.
Seem that bug can be closed.
PS: If it's possible add shortcut keys for back and forward options.
Thanks.
