### ISSUE TITLE
There no spell check feature

### ISSUE THREAD

**Issue by mmeirduvid** [jiahaog/nativefier#565]
### Description

<Detail your problem here as clearly and concisely as possible 🙂. Help us help you by saying why and giving some context!>

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Hi @mmeirduvid, thanks for the feedback. Indeed, there is not, see #283 and code welcome 🙂. Closing as duplicate.
