### ISSUE TITLE
Microsoft To-Do often crashes with out-of-memory error

### ISSUE THREAD

**Issue by zhouk** [jiahaog/nativefier#566]
### Description

Trying to create a nativefier app for Microsoft To-Do, but app consistently goes blank screen after a short period of idle time.

Tried it on 3 different Macs, same behavior.

### Steps to reproduce issue
1. Create app using `nativefier https://to-do.microsoft.com --name "Microsoft To-Do"`
2. Launch the app and sign in using any Microsoft Account
> You probably need to create several to-do items in order for sync to happen
3. Let app open for a couple of mins, page will go blank

### Details

- Are you nativefying a *public* website?
Yes. `https://to-do.microsoft.com`
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Yes
- Full nativefier command used to build your app: `nativefier https://to-do.microsoft.com --name "Microsoft To-Do"`
- Version of Nativefier (run `nativefier --version`): `v7.6.1`
- Version of node.js (run `node --version`): `v6.10.0`
- OS: `macOS 10.13.4 High Sierra`
- Error message / stack trace (if any):
No error message

**Comment by ronjouch** [comment]
@zhouk thanks for the feedback! Can you precise what you mean by "app goes blank screen"? Can you pop open the developer tools (Ctrl + Shift + I) and report:

1. Potential errors in the 'Console' tab
2. The state of the DOM (what do you see in the 'Elements' tab?)

**Comment by zhouk** [comment]
Hi @ronjouch, the app canvas turns into white space, and there's no output on console and there's no DOM elements eithers. It feels like the rendering process has crashed.

**Comment by ronjouch** [comment]
@zhouk can you try another [electron version](https://github.com/electron/electron/releases), using build-time flag `-e` ? Namely,

- An older stabler version: `-e 1.7.13`
- A bleeding-edge version: `-e 2.0.0-beta.6`

**Comment by zhouk** [comment]
The older `1.7.131` hasn't crashed so far. But I was able to witness the potential crash signal from the console. Refer to screenshot below. Latest and 2.0beta6 both crashes.

![out_of_memory_crash](https://user-images.githubusercontent.com/3815466/38284637-27f7cf60-3771-11e8-9d30-7e38ec7d7e01.png)

**Comment by zhouk** [comment]
**Update:**
It turns out that as long as I keep the console open and the debugger is able to pause it before it crashes. If I don't open the console/debugger, the page still goes blank.

**Comment by ronjouch** [comment]
@zhouk questions regarding Chrome DevTools say `Paused before potential out-of-memory crash`:

- Is your memory usage indeed high? What does it look like in your OS task manager?
- How much memory does this machine have?
- You have this problem only on the {Nativefier, Microsoft To-Do} combination, right? No problem with MS To-Do under Chrome? No Out-Of-Memory problem with other Nativefier apps?

Feels like the problem is at least partially due to Microsoft To-Do...

**Comment by zhouk** [comment]
@ronjouch I did some more monitoring, I was wrong that it wasn't consuming much memory. The web worker in MS To-Do is consuming a massive amount of memory. After web worker initiation, it can grow from 2-300MB to 2-4GB. That explains the out-of-memory crash.

**Comment by mostness** [comment]
I had this same issue and just worked with To Do support to resolve it.  The issue was a To Do item (a completed one in my case) with very long notes.  Deleting this task resolved the out of memory issue for me.

**Comment by zhouk** [comment]
> I had this same issue and just worked with To Do support to resolve it. The issue was a To Do item (a completed one in my case) with very long notes. Deleting this task resolved the out of memory issue for me.

Thanks for sharing. My issue resolved when switched from personal edition to Office 365 edition, but the root cause could very well be caused by a long item like you mentioned. If it happens again. I'll try your approach.
