### ISSUE TITLE
Code ENOENT, Syscall lstat error when using nativefier command

### ISSUE THREAD

**Issue by gust11** [jiahaog/nativefier#567]
### Description

Attempted to natify the webapp Granblue Fantasy, received an error with missing files. Completely new to this so have no idea what I'm doing.

### Steps to reproduce issue

`nativefier game.granbluefantasy.jp
  packaging [==============================                    ] 61%Packaging app for platform darwin x64 using electron v1.8.4
  packaging [===================================               ] 70%{ Error: ENOENT: no such file or directory, lstat '/var/folders/_v/g9g1hnjs50n1fdv1xvv9fqm40000gn/T/tmp-514514IMUKfTHCb5w/icon.icns'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/var/folders/_v/g9g1hnjs50n1fdv1xvv9fqm40000gn/T/tmp-514514IMUKfTHCb5w/icon.icns' }
  packaging [========================================          ] 80%`

^ Was not sure about privacy so replaced user name with 'user'

### Details

- Are you nativefying a *public* website? Yes?
- `nativefier game.granbluefantasy.jp`
- Version of Nativefier (run `nativefier --version`): `v7.6.1`
- Version of node.js (run `node --version`): `v9.10.1`
- OS: `<Mac OS Sierra Version 10.12.6>`
- Error message:
`{ Error: ENOENT: no such file or directory, lstat '/var/folders/_v/g9g1hnjs50n1fdv1xvv9fqm40000gn/T/tmp-49012QqSApZfRcOn3/icon.icns'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/var/folders/_v/g9g1hnjs50n1fdv1xvv9fqm40000gn/T/tmp-49012QqSApZfRcOn3/icon.icns' }`

I tried tracing the path above but could only get to folder T, /tmp-49012QqSApZfRcOn3/icon.icns doesn't exist.

**Comment by acaid** [comment]
I've been getting the same issue EXCEPT for pages that have a sub directory. 
Was trying to make an app for https://www.duolingo.com/ and it kept failing with the same error.
Managed to do a work-around with this:
`nativefier --name "Duolingo" "https://www.duolingo.com/../"`
Hope that helps

**Comment by gust11** [comment]
``
