### ISSUE TITLE
'nativefier' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mokhosh** [jiahaog/nativefier#568]
### Description

I installed nativefier as was told. i got this:
```
+ nativefier@7.6.1
added 323 packages in 111.369s
```

 this is the error i get when i try to use it:
```
'nativefier' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps to reproduce issue

Install nativefier
Run nativefier

### Details

- Are you nativefying a *public* website? **yes**
- Full nativefier command used to build your app: **`nativefier`**
- Version of Nativefier (run `nativefier --version`): **`'nativefier' is not recognized...`**
- Version of node.js (run `node --version`): **`v9.3.0`**
- OS: **`Win 10`**
- Error message / stack trace (if any):

```
'nativefier' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ronjouch** [comment]
@mokhosh be sure to install globally (the `-g` in `npm install -g nativefier`). If that still doesn't work, that means your node's `bin` folder is not in your `$PATH`. [This guide](https://github.com/nodeschool/discussions/wiki/Installing-global-node-modules-(Linux-and-Mac)) seems sensible. Good luck 🙂.

**Comment by mokhosh** [comment]
@ronjouch thanks for the response. i did use `-g` "as i was told".
the guide didn't help since 1. it's not for windows 2. i used the standard installer for node which i assume has done that automatically and every other global package seems to work just fine.

**Comment by gusbemacbe** [comment]
@ronjouch 

I would like to run non-globally because I would to keep Nativefier on `/home` of the HDD instead of `/` of SSD to keep my SSD less fat.
