### ISSUE TITLE
TypeError: log.log is not a function

### ISSUE THREAD

**Issue by kainecy** [jiahaog/nativefier#571]
OS: Mac OSX
nativefier: 7.6.1
node: v7.9.0
nativefier --name "google" --flash --file-download-options '{"saveAs": true}' "https://www.google.com"

/usr/local/lib/node_modules/nativefier/lib/helpers/helpers/packagerConsole.js:26
    log.log(this.logs.join(' '));
        ^
TypeError: log.log is not a function

**Comment by ronjouch** [comment]
Fixed with [loglevel 1.5.0](https://github.com/pimterry/loglevel/releases/tag/1.5.0), which we use as we specify ^1.6.1
