### ISSUE TITLE
Typecheck ?

### ISSUE THREAD

**Issue by LeoIannacone** [jiahaog/nativefier#572]
Is there anyway to add typecheck ?

**Comment by ronjouch** [comment]
@LeoIannacone what do you mean?

**Comment by LeoIannacone** [comment]
![screenshot from 2018-04-16 18-56-15](https://user-images.githubusercontent.com/1774748/38826490-dad96d92-41a7-11e8-8fa9-7dab972d2c86.png)

type check ^

**Comment by ronjouch** [comment]
@LeoIannacone ah, spellchecking. It's not supported, unfortunately. Feel free to follow discussion at #283
