### ISSUE TITLE
.icns icon building fails on macOS with lstat ENOENT error (workaround: explicit --icon)

### ISSUE THREAD

**Issue by crimsoncrust** [jiahaog/nativefier#573]
### Description

The error happens when trying to convert icon.icns using the normal nativefier command. I think it could be an Electron issue. Please let me know if so.

### Details

- Are you nativefying a *public* website?
Yes

- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Yes

- Full nativefier command used to build your app: `nativefier https://www.ranchhand.com`

- Version of Nativefier (run `nativefier --version`): Most Recent

- Version of node.js (run `node --version`): `v8.11.1`
- OS: `<10.13.4>`

- Error message / stack trace (if any):

"You can’t open the application “Electron” because it may be damaged or incomplete."

```
<Error message / Stack trace here>
```
Extract Error

```
Downloading tmp-2410-1-SHASUMS256.txt-1.8.4
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)
Packaging app for platform darwin x64 using electron v1.8.4
{ Error: ENOENT: no such file or directory, lstat '/var/folders/c9/2w45zsjs7413fpf2068rqthc0000gp/T/tmp-2410gKETAI9P4YDT/icon.icns'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/var/folders/c9/2w45zsjs7413fpf2068rqthc0000gp/T/tmp-2410gKETAI9P4YDT/icon.icns' }
```

**Comment by ronjouch** [comment]
@crimsoncrust does passing a `--name "ranchhand"`  option solve your issue? See https://github.com/jiahaog/nativefier/issues/567

**Comment by crimsoncrust** [comment]
Hello @ronjouch thanks for the quick reply! Sorry, it does not change anything, but the output folders name does change. I still get the following error:

"ENT: no such file or directory, lstat '/tmp/tmp-25253fHIwP0SFO3M/icon.icns'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/tmp/tmp-25253fHIwP0SFO3M/icon.icns' }"

**Comment by crimsoncrust** [comment]
Hello @ronjouch that worked!

Thanks!

**Comment by ronjouch** [comment]
@crimsoncrust thanks for confirming! I don't have a Mac for testing and got a few similar reports. Good to know where the issue is, and have a workaround. Cheers!

**Comment by bacongravy** [comment]
I experience this issue if I do not have imagemagick installed and the icon does not exist in the icon cache.  The changes in #583 will make this issue less likely to occur, as natievefier will fallback on sips when imagemagick is not present, but this may still be useful if icon conversion can fail for other reasons.

**Comment by pixelass** [comment]
This issue still occurs

```
14:23 $ nativefier --name "SOME_NAME" --icon ./MYICON.png  "https://codepen.io/pixelass/debug/XXXXXXXXX" 
  packaging [==============================                    ] 61%Packaging app for platform darwin x64 using electron v1.8.4
  packaging [=================================                 ] 65%{ Error: ENOENT: no such file or directory, lstat '/PATH/TO/MY/PROJECT/MYICON.icns'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/PATH/TO/MY/PROJECT/MYICON.icns' }
  packaging [========================================          ] 80%✔ ~//PATH/TO/MY/PROJECT/ 
```

**Comment by ronjouch** [comment]
Re-opening. Recent changes thanks to @bacongravy might help with that (thanks!). @pixelass please try [running the latest dev build](https://github.com/jiahaog/nativefier/blob/master/docs/development.md), or wait for the next release 🙂.

**Comment by pixelass** [comment]
I just provided a .icns file for now. thx.

**Comment by yazeed** [comment]
Still occurs, latest build, 9.2.0, not sure why.

**Comment by fuzzy76** [comment]
Is this a duplicate of #321 ?
