### ISSUE TITLE
Permissions error when launching app

### ISSUE THREAD

**Issue by mussingtonr** [jiahaog/nativefier#575]
Hello all! 

I'm trying to bundle all the Google services into apps (Gmail for Desktop, Inbox for Desktop, Calendar for Desktop, etc) and I've ran into an issue where permissions are throwing me java errors. 

- Setup -

I'm creating standalone applications so that each user can use the apps from /Application. Once created, I wanted to make a .mpkg package for users to select what they want. When created, the current app receives the permission set: 

system | Read/Write
admin | Read only
everyone | Read only

When the application is launched, I receive this error below that's attached.

![screen shot 2018-04-17 at 12 14 29 pm](https://user-images.githubusercontent.com/15366203/38882748-f9c804b6-4238-11e8-82ac-3ef375d75c20.png)

If I move the app from Applications (for example, to /Desktop) the app runs. If I move it back after moving it from applications, it runs also. (This is because it changes the permissions to the current users being Read/Write). When I launch the app after doing any of those steps from another user account, it throws the same error. 

Goal: I want to make the apps flexible so multiple user accounts can use it from /Applications. 

Info: 
- Command used
- Nativfier 7.6.1
- Node 9.10.1
- OS-X High Sierra

**Comment by bacongravy** [comment]
The symptom you are experiencing is due to the `./Contents/Resources/app` folder inside of the packaged application having it permissions set to deny all access to everyone but the owner (`0700`).
Only the owner can see the contents of the `app` folder, so only the owner can launch the application.

You can fix the permissions on an installed application `Electron.app` like this:

    sudo chmod a+rx /Applications/Electron.app/Contents/Resources/app

**Comment by mussingtonr** [comment]
@bacongravy Wow, I didn't even notice the tmpdir permissions when I looked over it. It looks like it's working on my test machine, so I'll try to implement this on the other machines I have at work on Monday and return the results/close.

You are a life (and time) savor. Thank you very much!
