### ISSUE TITLE
Can't close pgadmin client

### ISSUE THREAD

**Issue by wiryonolau** [jiahaog/nativefier#577]
### Description

Hi I can't close pgadmin client

### Steps to reproduce issue

Run pgadmin docker
`docker run -d --rm -p 127.0.0.1:5050:5050 -v $(pwd):/data chorss/docker-pgadmin4`

Create nativefier
`docker run --rm -v $(pwd):/target jiahaog/nativefier --name pgadmin --icon /target/pgadmin.jpeg http://localhost:5050/browser/ /target/`

Run the app and cannot close the window.

How do I check for error message ? The developer tools doesn't show anything.

**Comment by ronjouch** [comment]
@wiryonolau thanks for the feedback. Could you be having the same problem as https://github.com/jiahaog/nativefier/issues/545 ?

**Comment by wiryonolau** [comment]
I don't need to fill any form, it just cannot exit after open. Maybe something in pgadmin block it. I don't know how to debug. Since I connect to localhost, if I haven't start the pgadmin server ( empty window ) it will be ok.

Right I'm using Gnome Ubuntu 16.04

Check on other app like Portainer, it's work normally.

**Comment by ronjouch** [comment]
> *"I don't need to fill any form, it just cannot exit after open"*

@wiryonolau a form doesn't have to be visible. Dirty forms are the de-facto mechanism to block exiting an app, and we don't handle it properly. I'm pretty sure that's the problem, so, closing, please follow #545 and feel free to re-open if I'm wrong and you find some *other* bug is causing the issue.

**Comment by wiryonolau** [comment]
Hi, looks like I found why it cannot be close

When I try on firefox/chrome during closing window it popup a window that ask us to stay, like what mention in this website https://code-maven.com/prevent-leaving-the-page-using-plain-javascript

On nativefier app it doesn't show.

Something to do with onbeforeunload, Is there a way to inject script to disable this ? or perhaps show this window will be better
