### ISSUE TITLE
[macOS] Support setting macOS `vibrancy` options

### ISSUE THREAD

**Issue by austin-guevara** [jiahaog/nativefier#578]
### Description

Hey, thanks for an awesome project.

Would it be possible to introduce a flag that sets the window title bar color? The color could be specified with a hex code. By default, macOS creates a light grey gradient – it would be awesome to be able to set that to a color that matches the page, enhancing the native look and feel.

**Comment by ronjouch** [comment]
@austin-guevara yup, totally possible using Electron options. Passersby, that's an easy thing to add, check the [Electron doc](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions) and [see that PR for an example of adding a similar flag](https://github.com/jiahaog/nativefier/pull/584).

**Comment by ronjouch** [comment]
Ah, forgot it was already requested in https://github.com/jiahaog/nativefier/issues/35 . @austin-guevara please follow discussion there. Closing.
