### ISSUE TITLE
IBM Verse stuck at Fidelity End point.

### ISSUE THREAD

**Issue by vhkpanjani** [jiahaog/nativefier#589]
### Description

Once we login to IBM Verse, initially it works fine. But the very next day, when we try to login, it stays at Fidelity End Point.

### Steps to reproduce issue
Once we login to IBM Verse, initially it works fine. But the very next day, when we try to login, it stays at Fidelity End Point.

### Details

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Hi @vhkpanjani . This is Nativefier, the software IBM Verse is based on. We Nativefier have no control on fixing IBM Verse. Please contact the support for IBM Verse with your problem, and please also tell them we'll welcome a patch to customize the "Help → Report an issue" link. Thanks 🙂.
