### ISSUE TITLE
New windows are not configured properly

### ISSUE THREAD

**Issue by bacongravy** [jiahaog/nativefier#590]
### Description

When opening a secondary window using the "Open Link in New Window" context menu item, the created window is not configured properly.  JavaScript does not work, and this error appears in the console:

```
Electron Security Warning This renderer process has Node.js integration enabled and attempted to load remote content. This exposes users of this app to severe security risks.
For more information and help, consult https://electronjs.org/docs/tutorial/security
(anonymous) @ /Applications/Puppet Tickets.app/Contents/Resources/electron.asar/renderer/init.js:162
```

### Steps to reproduce issue

Wrap `tickets.puppet.com`. Try to open a link to a ticket in a new window.  Notice that the content looks garbled and that the JavaScript console contains lots of errors.

### Details

This problem occurs because the new window is created like this:

    new BrowserWindow()

No options are specified; among others, these critically are missing:

    webPreferences: {
      javascript: true,
      nodeIntegration: false,
    }

**Comment by ronjouch** [comment]
@bacongravy would this https://github.com/jiahaog/nativefier/issues/408 be due to that?

**Comment by bacongravy** [comment]
I haven't checked, but it seems likely. The "New Window" feature has probably only ever been useful for doing simple things like opening images or text files in new windows.
