### ISSUE TITLE
Under Linux, check (in post-install script?) for availability of libgconf and ask to install if not found

### ISSUE THREAD

**Issue by ghost** [jiahaog/nativefier#593]
Just upgraded Ubuntu from 17.10 to 18.04 and creating app stopped working. Was working perfectly in 17.10

I noticed that the progress bars when both inferring the app stops at 60%, and packaging the app stops ~68%. It appears to complete creating the app files but the executable does not launch. Not seeing any other indicators that there are issues.

**Comment by skylundy** [comment]
Update- trying to launch from the terminal yielded this message: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

Installing that using  sudo apt-get install libgconf-2-4 fixes the issue. Hope that helps some other people out.

**Comment by ronjouch** [comment]
Thanks @skylundy ! Looks like https://github.com/electron/electron/issues/1518 , we'll probably have more of such reports, I guess Debian/Ubuntu are stopping installing libgconf by default due to dconf. Renaming the issue.

**Comment by ronjouch** [comment]
I tested recently-released 8.0.4 in a bare docker of Ubuntu 19.10, and I think this is no longer an issue. Closing, feel free to reopen if I'm missing anything.
