### ISSUE TITLE
Prevent contextmenu

### ISSUE THREAD

**Issue by basu90** [jiahaog/nativefier#596]
Is it possible to prevent the app contextmenu on specific Elements like event.preventDefault() in js.

**Comment by ronjouch** [comment]
@basu90 no, we only have [`--disable-context-menu`](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#disable-context-menu), which is global. What's the use case?

**Comment by ronjouch** [comment]
@basu90 Nativefier's context menu doesn't prevent apps to have a custom context menu. Here are two screenshots of me right-clicking in my nativefied Gmail with Nativefier's context menu enabled (no `--disable-context-menu`):

- Clicking on an entry of the list of emails invokes Gmail custom contextmenu:  
![selection_001-fs8](https://user-images.githubusercontent.com/522085/39601961-bb8f21dc-4ef1-11e8-9896-b1279b170cbb.png)
- Clicking on a link invokes Nativefiers link handler:  
![selection_003-fs8](https://user-images.githubusercontent.com/522085/39601976-ccdfe4d0-4ef1-11e8-88ae-5f78200d1770.png)

**Comment by tjkohli** [comment]
@basu90 It seems the issue here is not with Nativefier, but rather in your application. Perhaps you could try this: https://stackoverflow.com/questions/381795/how-to-disable-right-click-context-menu-in-javascript

**Comment by ronjouch** [comment]
Yup. Thanks for stepping in, @tjkohli 🙂. Closing.
