### ISSUE TITLE
Build Fails when trying to use the Conceal Option

### ISSUE THREAD

**Issue by shadowdao** [jiahaog/nativefier#597]
### Description

No matter the options along with conceal, the build ends before building the conceal archive.

```
Packaging app for platform win32 x64 using electron v1.8.6
[ { Error: ENOENT: no such file or directory, open 'C:\Users\user\APP-win32-x64\resources\app\icon.ico'
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Users\\user\\APP-win32-x64\\resources\\app\\icon.ico' } ]
```

### Steps to reproduce issue

Use the conceal option to do a build

`nativefier -c "http://medium.com"`

### Details

- Are you nativefying a *public* website?
-- Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
-- Yes
- Full nativefier command used to build your app: `<command here>`
-- nativefier -c "http://medium.com"
- Version of Nativefier (run `nativefier --version`): `v7.6.2`
- Version of node.js (run `node --version`): `v8.11.1`
- OS: `Windows 10 Pro`
- Error message / stack trace (if any):

```
Packaging app for platform win32 x64 using electron v1.8.6
[ { Error: ENOENT: no such file or directory, open 'C:\Users\user\APP-win32-x64\resources\app\icon.ico'
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Users\\user\\APP-win32-x64\\resources\\app\\icon.ico' } ]

```

**Comment by ronjouch** [comment]
@shadowdao can you try downloading a PNG somewhere (e.g. `C:\Users\shadowdao\Downloads\medium.png`) and passing it explicitly to Nativefier:
```
nativefier --conceal --name medium --icon C:\Users\shadowdao\Downloads\medium.png "http://medium.com"
```

**Comment by shadowdao** [comment]
Here are the results from running the command.

C:\Users\shado>nativefier --conceal --name medium --icon
C:\Users\shado\Downloads\medium.png "http://medium.com"
  copying [==========                                        ] 20%WARNING:
The callback-based version of packager() is deprecated and will be removed
in a future major version, please convert to the Promise version or use the
nodeify module.
  packaging [==============================                    ]
61%Packaging app for platform win32 x64 using electron v1.8.6
  packaging [================================                  ] 65%Error:
rcedit.exe failed with exit code 1. Fatal error: Unable to set icon
    at ChildProcess.<anonymous>
(C:\Users\shado\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  packaging [========================================          ] 80%

**Comment by ronjouch** [comment]
Thanks. Probably related to #501, please have a look there.

**Comment by sarweshparajuli** [comment]
This issue is related to `--conceal` / `-c`
To solve this install `asar` to extract app.asar located in `myapp/resources/app.asar` 
Then run  `npm install -g asar`
After `asar` gets installed. Navigate to `myapp/resources` and run `npx asar extract app.asar destfolder`
After that place your icon named as `icon.ico` in `myapp/resources/destfolder/`
Then delete app.asar and run  `asar pack destfolder app.asar`
Now, your natified app will work
