### ISSUE TITLE
Verse does not display unread count for folders

### ISSUE THREAD

**Issue by ujwalmahule** [jiahaog/nativefier#601]
Verse does not display unread count for folders

I cannot see the number of unread emails, or which folder has unread email, I have to check each and every folder to find any new email, or see all documents view.

![image](https://user-images.githubusercontent.com/35648578/39762295-cfd3516c-530c-11e8-8ad6-3cfddd4887aa.png)

**Comment by ronjouch** [comment]
Hi @ujwalmahule . This is Nativefier, the software IBM Verse is based on. We Nativefier have no control on fixing IBM Verse. Please contact the support for IBM Verse with your problem, and please also tell them we'll welcome a patch to customize the "Help → Report an issue" link. Thanks 🙂.
