### ISSUE TITLE
Open system-wide URLs in App

### ISSUE THREAD

**Issue by jancbeck** [jiahaog/nativefier#604]
### Description

It would be great if clicking a link in any application would open that link in the dedicated nativefier App, if one existed. Like when I get a Trello notification in Mail.app it will open that link directly in Trello.app (created by nativefier) or when I'm viewing this Github issue in Safari.app clicking this link https://trello.com/b/2qoP0DQ3/todo would open the board in Trello.app instead of navigating there using Safari.

There is an app called [Choosy](https://www.choosyosx.com) that almost gets the job done. It lets you select a default browser based on the URL itself so I created a rule for Trello. 

<img width="780" alt="screen shot 2018-05-12 at 11 05 28" src="https://user-images.githubusercontent.com/865311/39955717-66cf3292-55d4-11e8-9c69-9b8a25be9d94.png">

There are two issues with this workaround:
1) It's not working if the app isn't running already
2) The nativefier app does not follow the link that is passed onto it. It will always open using the default "home" url.

The big feature request would be that nativefier implements what Choosy is doing namely that it hooks into system-wide URLs and opens them using a created app. The option would be similar to `--internal-urls` (say `--external-urls`) and accept regex patterns.
The small feature request would be that nativefier apps accept URLs that are passed to it. That would allow using an app like Choosy as I have outlined it above.
I'm using Trello as an example here but this obviously applies for any web app.

### Steps to reproduce issue
1. Create Trello app
2. Install Choosy. Enable Choosy for links. Add Trello.app as a browser. Create custom rule to always open links beginning with "https://trello.com" in Trello.app
3. Click a link to a Trello board anywhere (Safari, Mail, URL shortcut...) or use Terminal `open https://trello.com/b/2qoP0DQ3/todo -a Trello.app`
4. if Trello.app is opened it just shows the default URL. If Trello.app is not open, nothing happens. It should show the given board.

### Details

- Are you nativefying a *public* website? YES
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? YES. 
- Full nativefier command used to build your app: `nativefier --name "Trello" "https://trello.com"`
- Version of Nativefier (run `nativefier --version`): `7.6.1`
- Version of node.js (run `node --version`): `v10.0.0`
- OS: `MacOS High Sierra 10.13.4`

**Comment by jancbeck** [comment]
Ok, this is likely a duplicate of #405 and can be closed

**Comment by ronjouch** [comment]
> *"Ok, this is likely a duplicate of #405 and can be closed"*

Yup. By the way, renaming #405 to your clearer formulation: *"Support opening URLs passed as parameter to Nativefied application"*.

Also, to potential passersby: here's a [neat Linux solution](https://superuser.com/questions/688063/is-there-a-way-to-redirect-certain-urls-to-specific-web-browsers-in-linux) to do the per-domain dispatching that @jancbeck does here with Choosy
