### ISSUE TITLE
Can't locate app after creation

### ISSUE THREAD

**Issue by dyspop** [jiahaog/nativefier#605]
### Description

I've installed nativefier and it ran fine but the app didn't save to my desktop.

### Steps to reproduce issue

nativefier --name "asana" "https://app.asana.com"

### Details

- Are you nativefying a *public* website? yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? no
- Full nativefier command used to build your app: `nativefier --name "asana" "https://app.asana.com"`
- Version of Nativefier (run `nativefier --version`): `7.6.2`
- Version of node.js (run `node --version`): `v8.0.0`
- OS: `macOS Sierra 10.12.6`
- Error message / stack trace (if any):

```
  copying [==========                                        ] 20%WARNING: The callback-based version of packager() is deprecated and will be removed in a future major version, please convert to the Promise version or use the nodeify module.
Downloading tmp-1444-1-SHASUMS256.txt-1.8.6
[============================================>] 100.0% of 5.74 kB (5.74 kB/s)
Packaging app for platform darwin x64 using electron v1.8.6


```

**Comment by ronjouch** [comment]
> *"it ran fine but the app didn't save to my desktop"*

@dyspop check `nativefier --help`, it says `Usage: nativefier [options] <targetUrl> [dest]`. If you expect a specific destination, specify it as `[dest]`, else Nativefier writes to the current directory. So,

```bash
nativefier --name "asana" "app.asana.com" /Users/dyspop/Desktop
```
