### ISSUE TITLE
getting a error when trying to use it on any website

### ISSUE THREAD

**Issue by CMBAPPS** [jiahaog/nativefier#607]
Error log:
```
C:\Users\Charles>nativefier discordpanel.xyz
  copying [==========                                        ] 21%WARNING: The callback-based version of packager() is deprecated and will be removed in a future major version, please convert to the Promise version or use the nodeify module.
  packaging [==============================                    ] 61%Packaging app for platform win32 x64 using electron v1.8.6
  packaging [========================================          ] 80%Error: rcedit.exe failed with exit code 1. Cannot open icon file 'C'
Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\Charles\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

- Are you nativefying a *public* website? - yes
- Full nativefier command used to build your app: `nativefier discordpanel.xyz`
- Version of Nativefier (run `nativefier --version`): `7.6.2`
- Version of node.js (run `node --version`): `v6.9.4`
- OS: `<Windows 10>`

**Comment by ronjouch** [comment]
@CMBAPPS thanks for the feedback. May be related to https://github.com/jiahaog/nativefier/issues/501

Can you try downloading an icon and passing it explicitly to nativefier:

```bash
nativefier --icon 'C:\Users\CMBAPPS\Downloads\icon-discordpanel.xyz' 'http://discordpanel.xyz/'
```

**Comment by CMBAPPS** [comment]
Tried that but still getting an error? 
`nativefier --name "Discord Panel" --icon 'C:\Users\Charles\Downloads\discordpanel.ico' "http://discordpanel.xyz"`

Error: 
`Your environment has been set up for using Node.js 10.1.0 (x64) and npm.

C:\Users\Charles>nativefier --name "Discord Panel" --icon 'C:\Users\Charles\Downloads\discordpanel.ico' "http://discordpanel.xyz"
(node:3752) ExperimentalWarning: The fs.promises API is experimental
  copying [==========                                        ] 21%WARNING: The callback-based version of packager() is deprecated and will be removed in a future major version, please convert to the Promise version or use the nodeify module.
  packaging [==============================                    ] 61%Packaging app for platform win32 x64 using electron v1.8.6
  packaging [====================================              ] 72%Error: rcedit.exe failed with exit code 1. Cannot open icon file '''
Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\Charles\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
  packaging [========================================          ] 80%
C:\Users\Charles>`

**Comment by ronjouch** [comment]
@CMBAPPS forgot to mention; can you try passing a `png` icon?

**Comment by MrAlexEsisteGia** [comment]
same error
Windows 10
command: nativefier --name "****" --maximize -i "***.png" "****"

**Comment by chikei** [comment]
Currently nativefier on windows cannot convert png to ico, use some other tool convert icon png to ico format and run with --icon '<ico path>' will do.

**Comment by RichusX** [comment]
Same result when using an `*.ico` file.
```node
C:\Windows\System32>nativefier "https://lounge.richusx.me" --icon C:\Users\Ritvars\Pictures\icons\thelounge.ico
Fatal error: Unable to set icon
    at ChildProcess.<anonymous> (C:\Users\Ritvars\AppData\Roaming\npm\node_modules\nativefier\node_modules\rcedit\lib\rcedit.js:68:16)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
  packaging [========================================          ] 79%
```

**Comment by ydixt** [comment]
same error here.

- nativefier 7.6.12
- node 10.15. and 8.16.0
- Windows 1809 LTBS
