### ISSUE TITLE
Which output files are necessary to keep?

### ISSUE THREAD

**Issue by glappen** [jiahaog/nativefier#609]
Hello,
I am trying out nativefier and i used https://trello.com as my URL on linux and got a directory named "trello-linux-x64" generated.  Do I need everything in side that directory to run the new app, or can I remove some of the files?  It's over 100MB in side which seems larger than necessary.

Thanks!

**Comment by ronjouch** [comment]
Hi @glappen. Yes everything is necessary, welcome to the wonderful world of Electron apps ¯\\\_(ツ)\_/¯.
