### ISSUE TITLE
Autoupdate?

### ISSUE THREAD

**Issue by caske33** [jiahaog/nativefier#61]
Will this executable always have the latest version of the website or do you need to generate a new executable?

**Comment by zweicoder** [comment]
+1. There is some sort of support for auto-update by Electron [here](https://github.com/atom/electron/blob/master/docs/api/auto-updater.md) but it seems inconsistent for different platforms

**Comment by jiahaog** [comment]
As of now, the executable that is built is permanent and will not update. To update your executable to the latest version that can be built with nativefier, you have to update nativefier (by calling `$ npm update -g nativefier` and repackage a new executable. 

Perhaps some sort of autoupdate system could be implemented in the future.

**Comment by caske33** [comment]
@jiahaog To give more context,

We have a website with a service worker for example. So are app should work offline anyway. However, we think users will use our webapp more if it's an executable, but we don't want to lose the advantages of the fast updates our webapp has (we sometimes release multiple times a day). 

Just something else I wanted to bring into the conversation. I'm not sure what the best solution would be. That's also why I started this issue.

**Comment by jiahaog** [comment]
Oh, perhaps I misunderstood you there. I believe this functions like a regular chrome browser. Have you tried it out on your webapp yet?

**Comment by kagorastidis** [comment]
I packaged a web app I made with meteor. I can confirm that when I pushed changes to the app, the wrapped one was updated also(if that is your question).

**Comment by FGRibreau** [comment]
@jiahaog the issue is more related with the fact that we may want to add some features **to the electron executable** and if we do, we have to find a way to tell the user to update its app. The best way to do this is indeed to build an auto-update feature into the executable itself.

It's clearly something I would like to see in nativefier, I don't use it currently for this reason and it's the only reason why I don't use it :)

**Comment by philip-ulrich** [comment]
Just as a quick note: this is still a desired feature. :)
