### ISSUE TITLE
--counter does not work if the number contains punctuation

### ISSUE THREAD

**Issue by bacongravy** [jiahaog/nativefier#610]
### Description

When using an app such as Gmail, the unread count is included in the title, and the `--counter` feature displays that number on the dock icon.  However, when the number is larger than 999, it includes commas in the number (e.g. "1,000"), and the number is no longer displayed on the dock icon.

### Steps to reproduce issue

Run nativefier (v7.6.2) on gmail.com, log in, and then select a mailbox with more than 999 unread messages.

### Details

The problem appears to be due to the regular expression being used in trayIcon.js to match the count in the title:

    /[([{](\d*?)\+?[}\])]/

The regex does not take into account the possibility that the number might contain punctuation.

### Suggestions

How about something like this:

    /[([{](((\d){1,3})((,(\d){3})*|((\d){3})*)\+?)[}\])]/

or perhaps something a lot more permissive:

    /[([{](((\d){1,3})([,.]?(\d){3})*\+?)[}\])]/

In either case, the surrounding code may need to be updated to strip out the punctuation.

Please me know if you would accept a PR with either of these approaches, or another.

**Comment by ronjouch** [comment]
@bacongravy 👍, PR welcome. Both regexes may work, I trust your judgement to use what makes sense and doesn't cause false positives.
