### ISSUE TITLE
DPWBA0311W Unable to contact runtime security services.

### ISSUE THREAD

**Issue by Tanutk** [jiahaog/nativefier#612]
Can't log-in from IBM Verse app.

**Comment by ronjouch** [comment]
Hi @Tanutk. This is Nativefier, the software IBM Verse is based on. We Nativefier have no control on fixing IBM Verse. Please contact the support for IBM Verse with your problem, and please also tell them we'll welcome a patch to customize the "Help → Report an issue" link. Thanks slightly_smiling_face.

**Comment by Tanutk** [comment]
Hi Ronan,
 
Thank you, it's working now.
With warm personal regards, I remain
Sincerely,
Tanut Karnwai 
Strategy Consultant - Tech & Data Strategy | Global Business Services
M: +66-8-9988-6490 (TH), +65-9165-0345 (SG), +60-11-6137-1923 (MY)
E: tanutk@th.ibm.com 

IBM iX: http://www.ibm.com/ibmix 
IBM IGNITE: https://ibm.com/services/applications/testing
This e-mail, including attachments, is for the sole use of the individual(s) to whom it is addressed, and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you have received this email in error, please notify the sender by reply email and destroy this message and its attachments. Please use a secured network and/or system in sending your personal information. IBM shall not be liable for any disclosure of your personal information.
 
 
----- Original message -----From: Ronan Jouchet <notifications@github.com>To: jiahaog/nativefier <nativefier@noreply.github.com>Cc: Tanutk <tanutk@th.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [jiahaog/nativefier] DPWBA0311W Unable to contact runtime security services. (#612)Date: Thu, May 17, 2018 7:33 PM 
Closed #612.
