### ISSUE TITLE
Open Matching URLS in another nativefier app.

### ISSUE THREAD

**Issue by briancordanyoung** [jiahaog/nativefier#615]
When using Nativefier to wrap several web apps, it would be ideal to be able to assign a regex that when a URL matches It in the current nativefier, opens that URL in another Nativefier app.  This could be implemented in a number of ways, including using the feature requests: #314 & #405

**Comment by ronjouch** [comment]
@briancordanyoung thanks for the feedback 🙂. Yup, supposing a fix for #405 and combining with `--internal-urls` you could do that. Closing, feel free to follow #405.
