### ISSUE TITLE
Local App Data prevents mail load in the main window after Verse timeout while using single sign-on.

### ISSUE THREAD

**Issue by alallen098** [jiahaog/nativefier#617]
### Description

When using Federated SSO after Verse times out, Verse Federated Services window is blank. Verse does not load any data in the main window, and appears stuck, even though SSO authentication was successful. See screenshot. 
Workaround: Every time the app times out I have to clear App Data from the menu and repeat single sign-on again (see screenshot). After this Verse loads successfully. Using MacOS 10.13.4 High Sierra, Verse version - Nativefier 7.5.4 

### Steps to reproduce issue
1. Sign in to Verse Mac application with SSO.
2. Allow Verse to time out.
3. Refresh mail window, or try to open Calendar window. Verse redirects to SSO login screen.
4. Login using SSO.
5. Verse redirects to Federated Services window which is blank.
Bug: --> Mail does not load.

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by alallen098** [comment]
<img width="1435" alt="screen shot 2018-05-23 at 10 36 21 am" src="https://user-images.githubusercontent.com/487739/40452352-678fb84e-5e96-11e8-8ce8-74afaf6d3efe.png">
<img width="1054" alt="screen shot 2018-05-23 at 10 36 53 am" src="https://user-images.githubusercontent.com/487739/40452366-6eb0e256-5e96-11e8-9378-8fbf75b15a5a.png">
<img width="1299" alt="screen shot 2018-05-23 at 10 48 54 am" src="https://user-images.githubusercontent.com/487739/40452381-7ca631a4-5e96-11e8-9822-6f53fe9e94d1.png">

**Comment by ronjouch** [comment]
Hi @alallen098. This is Nativefier, the software IBM Verse is based on. We Nativefier have no control on fixing IBM Verse. Please contact the support for IBM Verse with your problem, and please also tell them we'll welcome a patch to customize the "Help → Report an issue" link. Thanks 🙂.

**Comment by alallen098** [comment]
Ronan,

Sorry, silly me! :) I will chase them down and ask to fix the link too.

Alex

On May 23, 2018, at 3:01 PM, Ronan Jouchet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @alallen098<https://github.com/alallen098>. This is Nativefier, the software IBM Verse is based on. We Nativefier have no control on fixing IBM Verse. Please contact the support for IBM Verse with your problem, and please also tell them we'll welcome a patch to customize the "Help → Report an issue" link. Thanks 🙂.

**Comment by ronjouch** [comment]
@alallen098 no worry! And yeah you're the first to respond positively to my request to link to your internal support. That would be awesome, hope you find the time to do it. Good day!

**Comment by alallen098** [comment]
Hey Ronan,

I promised to chase them down on that and I will. Can’t promise they fix it though :) I know you guys do awesome things and deserve a lot of respect. I would think fixing that link would be just a small token of appreciation for your generosity and dedication of time.

Alex

On May 24, 2018, at 5:07 AM, Ronan Jouchet <notifications@github.com<mailto:notifications@github.com>> wrote:


@alallen098<https://github.com/alallen098> no worry! And yeah you're the first to respond positively to my request to link to your internal support. That would be awesome, hope you find the time to do it. Good day!
