### ISSUE TITLE
Is this a nativeflier issue or .js issue?

### ISSUE THREAD

**Issue by LWFlouisa** [jiahaog/nativefier#618]
I'm currently trying to run ./nativeflier.js but I seem to keep getting permission denied.

It seems to also be happening in localtunnel as well.

And only in Mint 18.1

**Comment by LWFlouisa** [comment]
I'll see if I can find a length error report. Thanks for the patience.

**Comment by LWFlouisa** [comment]
./nativefier.json: line 2: name:: command not found
./nativefier.json: line 3: targetUrl:: command not found
./nativefier.json: line 4: badge:: command not found
./nativefier.json: line 5: width:: command not found
./nativefier.json: line 6: height:: command not found
./nativefier.json: line 7: showMenuBar:: command not found

Are there certain dependencies I'm missing?

**Comment by ronjouch** [comment]
Hey @LWFlouisa. Just provide the information requested in the [issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md) please.

**Comment by bacongravy** [comment]
@LWFlouisa JSON files are not executables, I suspect you are not invoking the command correctly.

**Comment by LWFlouisa** [comment]
Ah ok, how do I do that? I'll look up a bit in the source material.^ ^

**Comment by LWFlouisa** [comment]
I resolved the issue, it seems to be working now.
