### ISSUE TITLE
Links to external sites are opening in tabs

### ISSUE THREAD

**Issue by bacongravy** [jiahaog/nativefier#621]
As reported by @poliva in the comments of #579, in response to explaining why the new tab feature wasn't working as desired:

> I use nativefier for Fightcade2 app, we have links to external sites such as social profiles, FAQs, manuals, etc which I prefer to open in the default browser rather than in a tab inside the app.

The problem is that the tab feature introduced by #579 included a change that checks the 'disposition' parameter and conditionally creates tabs, and that check was placed prior to the check to see if the URL is external. Reversing the order of these checks should resolve the issue.

**Comment by Aidoboy** [comment]
How can I disable this? It break Google OAuth.
