### ISSUE TITLE
cookies 

### ISSUE THREAD

**Issue by LikeFroyo** [jiahaog/nativefier#630]
It would be better we can store cookies. We have to login every time we use the app.

**Comment by ronjouch** [comment]
@akash86167 thanks for the feedback. Nativefier *does* store cookies. If login is not remembered, something else is not working. Please report the information requested by the [Issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by CrispyCrafter** [comment]
how are cookies stored/shared between electron sessions ? 

Let me explain my use case. We use whatsapp web for business coms. This however means all browser instances also share a whatsapp web session.

Ideally we don't want our FB overlords to loom over every search query internally at the company.
Would nativefier/electronjs ensure that all session cookies are localised and sandboxed to that instance, or is it shared by all instances using electron?

Sorry for the wordy question
