### ISSUE TITLE
Launch local webserver and open it

### ISSUE THREAD

**Issue by brouillon** [jiahaog/nativefier#639]
Hello @all !

As many php developers, I want to embed my webapp into a desktop application.
The easy way : php binary can run an internal webserver, so let's use it !
My question is : Is there a way to run a custom command in startup of nativefier ? 
Adding somewhere ( in nativefier/app/src/main.js ? ), something like :
```
/path/to/php/bin/ -S localhost:8000 -t /path/to/my/scripts/
```
Or maybe with gulp :
```
var path = require("path");
var php = require("gulp-connect-php");
php.server({
    port: 8000,
    base: path.resolve(__dirname) + '/www',
    bin: path.resolve(__dirname) + "/php/bin/php"
});
```
And then open localhost:8000

Can you provide some advices for this use case ?

Thanks

**Comment by ronjouch** [comment]
Hi @brouillon. That could work, yes, check our [developer docs](https://github.com/jiahaog/nativefier/blob/master/docs/development.md) and give it a try.
