### ISSUE TITLE
Build stops logging to stdout, giving the impression the build failed/stalled

### ISSUE THREAD

**Issue by xiewl** [jiahaog/nativefier#641]
### Description

<Detail your problem here as clearly and concisely as possible 🙂. Help us help you by saying why and giving some context!>

### Details

- Are you nativefying a *public* website?  yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v7.6.4`
- Version of node.js (run `node --version`): `v8.9.1`
- OS: `MacOS`

<img width="938" alt="wx20180628-202455 2x" src="https://user-images.githubusercontent.com/15881722/42034052-5fd7c366-7b11-11e8-9d9e-badd00ee0189.png">

**Comment by ronjouch** [comment]
Hi @xiewl, thanks for the feedback. Are you behind China's GFW, or running a proxy/VPN? Can you look at https://github.com/jiahaog/nativefier/issues/479 ?

**Comment by xiewl** [comment]
yeah，I am behind GFW。Now I run failed too after close vpn。

**Comment by FoolishExcalibur** [comment]
Having the same error with 
* nativefier version: 7.6.4
* node version: 10.5.0
on Arch Linux and not running any VPN.

**Comment by Lachlantula** [comment]
I also receive the same error.

- Nativefier 7.6.4
- Node 9.5.0
- macOS 10.13.5
- fish 2.7.1
- Installed globally with Yarn 1.6.0.

No output; exits at 61% the majority of the time but it once stopped at 60%. Running on an unfiltered internet connection. Link used was 'https://open.spotify.com'.

**Comment by ronjouch** [comment]
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/479

**Comment by ronjouch** [comment]
> I'm still having this issue yet I'm not behind a proxy nor a VPN

@Lachlantula and neither behind China's GFW?

**Comment by Lachlantula** [comment]
No - Australian here.

**Comment by Lachlantula** [comment]
@ronjouch Thanks for the suggestion; whilst it does still cut off at 61% I can see the export location which does indeed contain the app, which seems to function fine. 

![image](https://user-images.githubusercontent.com/12870244/43118963-d2f1b500-8f57-11e8-9724-5c7619a529cf.png)

**Comment by woolson** [comment]
succeed with `--verbose`

**Comment by ronjouch** [comment]
Fixed in Nativefier 8.0.4, which does simpler logging and got rid of the progress bar.

**Comment by imydou** [comment]
export ELECTRON_GET_USE_PROXY=1 # 值为1或true
export GLOBAL_AGENT_HTTP_PROXY=http://proxy.example.com:1080
export GLOBAL_AGENT_HTTPS_PROXY=https://proxy.example.com:1080
