### ISSUE TITLE
Accessing HTML DOM in main.js

### ISSUE THREAD

**Issue by jhcsu** [jiahaog/nativefier#646]
I've created an app using nativefier (for Gmail), and am playing around with the resulting main.js to try to improve determination of unread message count for updating the application's badge.  This task is currently performed by the function ```get_counter_value``` in main.js.

(Currently, the function looks for a number enclosed by (), [], or {} in the document title; the limitation being that Google doesn't include this in the title unless the user has the Inbox displayed.)

My question certainly shows my newness to javascript programming: but I'd like to modify function```get_counter_value``` by using methods from the HTML DOM (things like ```document.getElementsByTagName()```, where the document in question is whatever is open in the active tab.  However I have no idea how to access this information from within that function.  Would someone be able to point me in the right direction here?  Thank you.

**Comment by ronjouch** [comment]
@jhcsu cool that you're giving it a try. You seem to be on the right track, inside `getCounterValue`, you should be able to make your call here.

And be sure to follow the [developer docs](https://github.com/jiahaog/nativefier/blob/master/docs/development.md) for your setup.

Closing as question, but feel free to ask more 🙂, I'll receive notifications.
