### ISSUE TITLE
How combine all files as one .exe file?

### ISSUE THREAD

**Issue by damithruwan1234** [jiahaog/nativefier#648]
There are a few folders and lot of files we receive when we run `nativefier "http://medium.com" `

How to make all files as one file? When a client ask a file, I wan to send just a one file. I don't want to send all the folder and then tell click the exe file.

**Comment by ronjouch** [comment]
Hi @damithruwan1234 and thanks for the feedback. That's a frequently-requested feature and would be super neat, but it's completely out of nativefier's reach; you should ask about it to our dependencies that does the packaging work: [electron](https://github.com/electron/electron/) and [electron-packager](https://github.com/electron-userland/electron-packager).
