### ISSUE TITLE
How can I recompile the app after making some changes to the .js?

### ISSUE THREAD

**Issue by harikuts** [jiahaog/nativefier#651]
Hi, I'm a bit new to web and application development, I'm venturing over here from hardware land, so I hope you can forgive me haha. I've made some small tweaks in main.js (some title bar options that aren't available with the typical nativefier arguments when a web app is nativefied). How can I go about recompiling the app with these changes?

**Comment by ronjouch** [comment]
Hi @harikuts, welcome! Follow [our developer docs](https://github.com/jiahaog/nativefier/blob/master/docs/development.md). And feel free to submit a PR if you think your changes can interest other users! 🙂
