### ISSUE TITLE
Injected CSS/JS should survive page reloads

### ISSUE THREAD

**Issue by marclipovsky** [jiahaog/nativefier#653]
### Description
Functionality for CSS/JS injection exists. However, it does not persist when a page reloads or page changes within the app. I'm proposing to allow for persisted CSS/JS through entire in-app experience.

### Steps to reproduce issue
1. Create a CSS or JS file to inject
2. Run nativefier with --inject flag with filename
3. Open app and note that css and js does not persist after navigating from initial page

### Details
- Are you nativefying a *public* website? Yes.
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `nativefier --counter --bounce --honest --single-instance --inject ./style.css --title-bar-style 'hiddenInset' --icon ./android-messages.png --name "Android Messages" "https://messages.android.com/"`
CSS file:
```
// Padding
/* Add padding above Messages heading */
body > div > c-wiz > div > div > div > div > div > div {
  padding-top: 20px;
}

/* Allow Message heading wrapper to be draggable */
body > div > c-wiz > div > div > div > div > div > div > div {
  -webkit-app-region: drag;
}

/* Add no-drag to menu button within heading wrapper */
body > div > c-wiz > div > div > div > div > div > div > div > div + div {
  -webkit-app-region: no-drag;
}
```
- Version of Nativefier (run `nativefier --version`): `v7.6.4`
- Version of node.js (run `node --version`): `v8.9.1`
- OS: `macOS 10.13.3`
- Error message / stack trace (if any): n/a

**Comment by ronjouch** [comment]
@marclipovsky hmmmm yeah, totally, thanks for the feedback. I guess no one complained about that yet because commonly nativefied app are Single-Page Apps that you don't reload.

To you or interested passersby: PR welcome. Nativefier is in maintenance mode these days, with no developer working actively on it. If you have the time & will, read our [developer docs](https://github.com/jiahaog/nativefier/blob/master/docs/development.md) and give it a stab!

**Comment by ronjouch** [comment]
Closing as js&css survive both page reloads and clicking internal links in Nativefier 8.0.4. Please chime and re-open with fresh debug info if I'm missing anything.

**Comment by ericclemmons** [comment]
As I've begun using `nativefier`, this has caught me by surprise in #953.

I've been injecting `css` and `js`, reloading the window, and JS re-runs, but the CSS seems to persist.  This means that I have to close the app entirely & re-start it between CSS changes!

My expectation is that it injection would happen with each DOM contentReady event (read: with each page navigation), but be removed entirely with the reload event.

I'm happy to dig into the specific of `8.0.4` if we can agree on the heuristics for retaining/removing injected assets 🙏
