### ISSUE TITLE
Not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by carriopablo** [jiahaog/nativefier#658]
### Description

The created app doesn't open on Ubuntu 18.04 even if I created it in that system. On ubuntu 16.04 works fine. When I make double-click on the executable nothing happens.

### Steps to reproduce issue

Any page with any options in Ubuntu 18.04 OS

### Details

- Are you nativefying a *public* website? It doesn't matter
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: I've tried multiple commands from simple to more complex
- Version of Nativefier (run `nativefier --version`): `v7.6.4`
- Version of node.js (run `node --version`): `v3.5.2`
- OS: `Ubuntu 18.04 LTS`:

**Comment by ronjouch** [comment]
@carriopablo no such problem here on my Ubuntu 18.04 box. Closing, please come back with more information (running from console for logs, logs for a `nativefier --verbose` run, trying with Node 8.x, other ideas welcome) 🙂.
