### ISSUE TITLE
Nativefier with own code

### ISSUE THREAD

**Issue by airbenich** [jiahaog/nativefier#661]
Hey there,

is it possible to generate with nativefier the electron source code and compile later?
So I could enhance the features with own code and use nativefire as my base.

Thank you for your help!

**Comment by ronjouch** [comment]
@airbenich hi! Why not just work on a local branch and rebase regularly?

**Comment by airbenich** [comment]
Hey @ronjouch Thank you for your reply! Not sure if we're on the same boat. I would like to "generate" a nativfier app via cli as usual. This generates an .app or .exe file. What I would like to do is now to extend the generated app and build in some other features.

When I got this right the folder `nativefier/app` holds the template for the app. Like the normal electron source code. Is it possible to generate instead of an .app or .exe file the corresponding source code? Then I could build in my wanted features an behaviors and compile the .app / .exe file later on for myself like a normal electron app. Thank you for your help & greetings from Germany!

**Comment by jraspiprojects** [comment]
Can't you just inject JS/CSS with the <code>--inject </code> flag?
