### ISSUE TITLE
Hangouts Screen Sharing responds with error.

### ISSUE THREAD

**Issue by jraspiprojects** [jiahaog/nativefier#665]
### Description
Screen sharing on hangouts.google.com responds with an error.

### Steps to reproduce the issue
Start Hangouts call in a nativefier app, click screen sharing.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? YES
- Full nativefier command used to build your app: `nativefier https://hangouts.google.com`
- The version of Nativefier `Latest of 8/6/2018 `
- The version of node.js (run `node --version`):  <code>8.11.3</code>
- OS: `Microsoft Windows 10 Build 1083`

**Comment by ronjouch** [comment]
@jraspiprojects thanks for the feedback. Which error; can you pasteit here? (As displayed, error console, network logs ... all welcome)

**Comment by jraspiprojects** [comment]
no error just a screen that says, "sorry an error occured while screensharing"

**Comment by ronjouch** [comment]
Hangouts looks like a very specific app doing crazy stuff with Chrome. Closing that one, just use Chrome. But as usual, patches welcome.
