### ISSUE TITLE
"Couldn't Load Plugin" error when attempting to nativefying something with flash

### ISSUE THREAD

**Issue by Thestickman391** [jiahaog/nativefier#667]
### Description

I get a "Couldn't Load Plugin" error when attempting to nativefying something with flash

### Steps to reproduce issue

Just try to nativefy a website with flash

### Details

- Are you nativefying a *public* website? 
Yes
- Full nativefier command used to build your app: `nativefier --flash "https://icer.ink/media1.clubpenguin.com/play/v2/games/quests//q1//quest.swf"`
- Version of Nativefier (run `nativefier --version`): `v7.6.7`
- Version of node.js (run `node --version`): `v10.0.0`
- OS: `Windows 10`

**Comment by ronjouch** [comment]
See https://github.com/jiahaog/nativefier/blob/master/docs/api.md#flash
