### ISSUE TITLE
messages.android.com does not send desktop notifications.

### ISSUE THREAD

**Issue by yharaskrik** [jiahaog/nativefier#671]
### Description

Desktop notifications are not popping up for messages.android.com on Windows 10.

### Steps to reproduce issue

nativefy messages.android.com
connect android phone to the website.
Receive text message

### Details

- Are you nativefying a *public* website?
yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
N/A
- Full nativefier command used to build your app: `nativefier messages.android.com`
- Version of Nativefier (run `nativefier --version`): `v7.6.7`
- Version of node.js (run `node --version`): `v8.11.3`
- OS: `Windows 10`
- Error message / stack trace (if any):
N/A

**Comment by jeffreysmall** [comment]
The app needs an AppUserModeID in Windows 10 in order to display notifications. There's was a manual method posted  previously [here](https://github.com/jiahaog/nativefier/issues/88) but this can also be accomplished by creating an installer with something like InnoSetup (which is free)

**Comment by ronjouch** [comment]
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/88
