### ISSUE TITLE
Add support for package a installer

### ISSUE THREAD

**Issue by liudonghua123** [jiahaog/nativefier#675]
### Description

Since the build app has a lot files and the user maybe create a shortcut on the desktop manual, that's not quit convenience and is also not release or share to anyone else.

### Details

1. add a `-p, --package` option to create a installer.
2. run `nativefier -p http://<your_web_app_url>` to create a platform related installer.

ps: I tried to package the build app using `electron-installer-windows` or `windows-installer`, but all end to the `The Product/@Version attribute` problem, see https://github.com/jiahaog/nativefier/issues/674 for more details.

**Comment by ronjouch** [comment]
@liudonghua123 thanks for the feedback but I don't think that's Nativefier's job. Closing.
