### ISSUE TITLE
Windows Menu Bar

### ISSUE THREAD

**Issue by manngo** [jiahaog/nativefier#676]
### Description

I use option/alt + click for one of my features. On the Mac it’s OK, but I notice that on Windows it shows the menu bar, which is otherwise suppressed. This produces an annoying re-appearance.

Is there a way to stop this on the Windows application?

Currently I show the menu bar to make it less annoying.

### Details

- Are you nativefying a *public* website? Yes

- Full nativefier command used to build your app: 

	`nativefier --name 'Text Pager 0.2.1' --title-bar-style 'hiddenInset' --show-menu-bar --app-copyright 'Copyright © Mark Simon' --app-version '0.2.1' --build-version something --icon ~/favicon.png --internal-urls '^banana$' --fast-quit --platform windows https://pager.internotes.net/?test=something ~/icloud/`

- Version of Nativefier (run `nativefier --version`): `v7.6.7`
- Version of node.js (run `node --version`): `v7.1.0`
- OS: `MacOS 10.13.6`

**Comment by ronjouch** [comment]
@manngo thanks for the feedback! Closing as standard Electron behavior, taking vscode as example. Feel free to talk to Electron.
