### ISSUE TITLE
Support for Emojis

### ISSUE THREAD

**Issue by allo-** [jiahaog/nativefier#681]
It would be nice, if some emoji-font would be included, currently all emojis are rendered as outlines.

Possibly a linux only problem, as it may depend on the default fonts of the platform.

**Comment by Aidoboy** [comment]
It uses the default platform fonts. On the latest Windows 10, they render in color. I don't know what Distro you use, but Ubuntu 18.04 will have color emoji by default: https://www.omgubuntu.co.uk/2017/11/ubuntu-finally-long-last-time-support-color-emoji

**Comment by allo-** [comment]
It's a Debian testing.

Where is configured, what's the default (emoji) font used by electron/nativefier?  
I think locally installing an font is not the problem, but then the app needs to use it for emojis.

**Comment by Aidoboy** [comment]
It uses the system default. You can Google how to set up color emoji on
Debian.

**Comment by allo-** [comment]
There is no such thing as a "Linux default font". Chrome has a default font, firefox has an own one. KDE has one for its applications, but chrome does not respect this. Electron probably has some, but the question is how it selects it (and how nativefier configures it, as it seems not to choose one with emoji support).

**Comment by ronjouch** [comment]
Hm yes there is a Linux default font, that Chrome will follow. Read about fonts and fontconfig; https://wiki.archlinux.org/index.php/Fonts is a good resource.
