### ISSUE TITLE
Counter option does not work in Gnome/Unity DE

### ISSUE THREAD

**Issue by klemy** [jiahaog/nativefier#688]
### Description

When I build an nativefier application with `--counter` option on my Ubuntu desktop and when app display a title with `(X) ABC`, counter dot is not visible.

### Steps to reproduce issue

1. Build an app with `--counter` option (ex, ```mobile.twitter.com```)
2. Wait for a notification
3. Observe the non presence of the dot icon

### Details

- **Are you nativefying a *public* website?:** Yes, `mobile.twitter.com`.

- **Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?:** No. Its' relative to the `--counter` option.

- **Full nativefier command used to build your app:** `nativefier --name "Twitter" "https://mobile.twitter.com" --single-instance --tray --counter`

- **Version of Nativefier:** `7.6.7`

- **Version of node.js:** `v8.10.0`

- **OS:** `Ubuntu 18.04 on GNOME Shell 3.28.3 / Unity`

- **Error message / stack trace (if any):** n/a

**Comment by JMarteF** [comment]
Hello Klemy, What "dot icon" are you referring to?

**Comment by ronjouch** [comment]
Closing as issue wasn't reproducible and didn't get feedback. Feel free to chime in and re-open the discussion anytime 🙂!

**Comment by JMarteF** [comment]
Hey Ron, I am currently working on finding a fix for this issue. I read a little more into what Klemy meant and found out he was talking about the notification badges on applications like whatsapp and facebook messenger.

**Comment by fakhamatia** [comment]
It's 2020
Any update?

**Comment by avlm** [comment]
@JMarteF I don't know if you ever found a solution to this, but I found here https://www.leowkahman.com/2018/03/22/running-whatsapp-allo-todoist-onenote-on-ubuntu/
