### ISSUE TITLE
WhatsApp won't remember credentials

### ISSUE THREAD

**Issue by giovannicaligaris** [jiahaog/nativefier#689]
### Description

Everytime I close the app, it will ask me to log in again when the app is launched again. 

What am I missing?

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Yes

- Full nativefier command used to build your app: `nativefier --name "WhatsApp Desktop" "https://web.whatsapp.com"  --platform "linux" --icon "/home/caligaris/whatsapp.png" --show-menu-bar --disable-dev-tools --single-instance `

- Version of Nativefier: `v7.6.7`
- Version of node.js: `v8.10.0`
- OS: `Ubuntu 18.04`

```

**Comment by bakeiro** [comment]
Same here with waveapps

**Comment by JMarteF** [comment]
I believe that this issue is solved. I just tried to reproduce the issue and it actually works fine.

**Comment by ronjouch** [comment]
> *"I believe that this issue is solved. I just tried to reproduce the issue and it actually works fine."*

@JMarteF thanks for the feedback! Can you share your nativefier options (full line used to nativefy Whatsapp), in case you're doing something the others aren't?

@bakeiro @TheGoddessInari @giovannicaligaris do you confirm the problem is gone?

**Comment by TheGoddessInari** [comment]
It looks like WhatsApp changed the default storage away from session.

**Comment by ronjouch** [comment]
@TheGoddessInari can you precise what you mean by "session"? SessionStorage?

**Comment by TheGoddessInari** [comment]
@ronjouch Yes, sessionStorage. Electron doesn't offer an easy way to persist sessionStorage as Chrome does by default, which some badly-made web apps, like formerly WhatsApp, T-Mobile DIGITS, and others, depend on being just another localStorage.

Convincing the apps themselves to change is generally difficult with webdevs thinking that Chrome = "the web".
