### ISSUE TITLE
Google Calendar crashes on print dialog

### ISSUE THREAD

**Issue by ndroftheline** [jiahaog/nativefier#692]
### Description

Nativefied Google Calendar crashes on trying to print. No error messages, able to re-launch it immediately, but unable to print. Have to drop to a "normal" Google Calendar tab on Chrome to print, which works fine. 

### Steps to reproduce issue

1. Try to print, Nativefied Google Calendar closes

### Details

- Are you nativefying a *public* website?
It's Google Calendar, so I would say yes but it depends on what you mean by public. It's certainly a private company's website/product. 

- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Not a feature request as far as I know.

- Full nativefier command used to build your app: `<command here>`
nativefier "http://calendar.google.com/"

- Version of Nativefier (run `nativefier --version`): `v0.0.0`
7.6.7

- Version of node.js (run `node --version`): `v0.0.0`
v8.12.0

- OS: `<OS here>`
MacOS High Sierra

- Error message / stack trace (if any):
n/a, but happy to run whatever log collection commands would be helpful.

**Comment by JMarteF** [comment]
When you run the executable, Does it require you to sign into your google account? If so, does it redirect you to a tab on your default browser. I'm trying to reproduce...

**Comment by mporter2016** [comment]
This will be fixed with the next version of electron. Here is the issue from electron: https://github.com/electron/electron/issues/15188

**Comment by ronjouch** [comment]
@ndroftheline do you confirm [latest Electron 3.x](https://github.com/electron/electron/releases) fixes the issue, as suggested by @mporter2016 ? Try `nativefier -e 3.0.10 ...`
