### ISSUE TITLE
Creating Installers

### ISSUE THREAD

**Issue by nogats07** [jiahaog/nativefier#697]
So, I successfully created a desktop app for my site and it's awesome but the generated app is inside a folder with hundreds of files and it makes it hard to be run for people with low computer knowledge, I've searched a lot for how to create a simple msi installer for nativefier to create shortcuts and move the app directory to "Program Files" but no luck, can anyone please create a guide? I'm a web developer and that seriously complicates everything.

**Comment by ronjouch** [comment]
Hi @nogats07. Please ask for support using a support channel for nodejs or an installer package.

**Comment by AdrianDucao** [comment]
so is there any updates to this?
