### ISSUE TITLE
Have the option to hide tray

### ISSUE THREAD

**Issue by giovannicaligaris** [jiahaog/nativefier#700]
If possible, it would be nice to be able to hide the tray icon either from the menu bar or from the tray it self.

**Comment by giovannicaligaris** [comment]
--tray will automatically create a tray icon, but later if you want to hide it, you can't. Unless you heavily tweaked your electron app. I'm personally not a developer, so I rely default API options created by notifier.

It would be nice if everytime you build a new app with --tray then you can hide the tray icon from the menu bar. Something like this.

![screenshot from 2018-10-25 21 26 19](https://user-images.githubusercontent.com/26255347/47528427-13e46380-d89d-11e8-86c6-dcf79c6caa6b.png)

**Comment by ooker777** [comment]
The tray will be less clutter. Don't underestimate it, cognitive load is a big deal

**Comment by ronjouch** [comment]
> *"The tray will be less clutter. Don't underestimate it, cognitive load is a big deal"*

Then don't `--tray`. But why make it hideable at runtime?

**Comment by ooker777** [comment]
Not an OP so I can't answer for them. But for me, there are programs that I want it to run at startup to reduce the loading time, but don't need to use it occasionally. As long as I know that it still run in background, then I don't need the tray icon.

But that's not a strong reason for wanting to hide the icon completely I admit. I can still hide it in the drop down menu
