### ISSUE TITLE
Tray icon isn't properly resized on Linux

### ISSUE THREAD

**Issue by HelmicNewciv** [jiahaog/nativefier#701]
### Description

The tray icon is zoomed in to part of the icon, rather than displaying the entire icon at a proper size.

### Steps to reproduce issue

Specify a .PNG or .SVG with dimensions larger than the icons in your tray when building an app, then use the `--tray` flag.  When running the app, the tray icon will be zoomed into just part of the full icon.

This also occurs when using website favicons.

### Details

- Are you nativefying a *public* website? Yes, mastodon.social
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? No
- Full nativefier command used to build your app: `nativefier --name "Mastodon" -i ~/Pictures/Mastodon.png --min-width 359 --min-height 160 --honest --single-instance --tray "https://elekk.xyz/"`
- Version of Nativefier (run `nativefier --version`): `v7.6.8`
- Version of node.js (run `node --version`): `v10.12.0`
- OS: `Manjaro KDE`

**Comment by qdrop17** [comment]
Yes, I have the same issue using KDE Plasma. Is there a workaround available to that issue?

**Comment by qdrop17** [comment]
This seems to be resolved in release [7.7.0](https://github.com/jiahaog/nativefier/releases/tag/v7.7.0):

![image](https://user-images.githubusercontent.com/42340241/71812806-6eb84400-3078-11ea-98fd-f5ecf292062f.png)

**Comment by ronjouch** [comment]
> This seems to be resolved in release [7.7.0](https://github.com/jiahaog/nativefier/releases/tag/v7.7.0):
> 
> ![image](https://user-images.githubusercontent.com/42340241/71812806-6eb84400-3078-11ea-98fd-f5ecf292062f.png)

Thanks. Running a quick test, this seems fixed too in recently-released 8.0.4. Closing, feel free to re-open with fresh debug info if I'm wrong.
