### ISSUE TITLE
Device orientation - CSS injection?

### ISSUE THREAD

**Issue by mattsayward** [jiahaog/nativefier#704]
I have built a suite of native Instagram apps for my publishers various accounts using Nativefier. I've got custom icons for each profile, set min and max widths so that it always feels like Instagram, and I've got the mobile version of the site by using an iPhone user agent.

The one thing that I've not been able to do with these apps is post to Stories, and that's because I get a little pop up at the bottom that says 'Rotate your device to add to your story'.

Is there anything I could insert via CSS, or something else I could do to make the app think that the window was in portrait orientation?

**Comment by ronjouch** [comment]
@mattsayward that feels like a question to StackOverflow / a webdevelopment reddit. Closing.
