### ISSUE TITLE
Folder naming logic is weirdly dependent on platform

### ISSUE THREAD

**Issue by Enverex** [jiahaog/nativefier#708]
### Description
I'm seeing different behaviour of the folder name depending on whether it's being built for Windows or Linux when using spaces or mixed case.

For example, if I use "--name retrotracks" I get:
```
retrotracks-win32-x64
retrotracks-linux-x64
```

Which is fine. But if I try "--name RetroTracks" I get:
```
RetroTracks-win32-x64
retro-tracks-linux-x64
```

So the output for the Windows platform is correct, but it's wrong for Linux. I'm not even sure how it's deciding to split the two words there. The title tag of the live site is "RetroTracks" and the name I've just given it is identical. So it's rather cryptic how/why it's deciding to add a split in the middle, as well as ignoring the casing. The only reference to the name with a space in is JSON on the site where it's listed as the alternateName (the "name" field is correct, so even if it is using the JSON, it should be using name rather than alternateName).

The second issue is the Windows name, in that win32-x64 doesn't make any sense. It's either win32 or win64, it can't be a 64bit Win32 program ;)

### Details
- Are you nativefying a *public* website? Yes
- Full nativefier command used to build your app: `nativefier --platform windows (or linux) --arch x64 --name RetroTracks --width 1100 --height 960 --honest --ignore-gpu-blacklist --disable-context-menu --disable-dev-tools --single-instance --tray retro.sx RetroTracks-Electron`
- Version of Nativefier: `v7.6.8`
- Version of node.js: `v11.1.0`
- OS: `Arch Linux`

**Comment by evdcush** [comment]
+1 same issue on linux.

 

I have "nativefy" wrapper script for nativefier and have to have to workaround nativefier's bizarre directory naming logic

**Comment by mikeholler** [comment]
Is there a way to specify a custom name for the output directory? I'm having this same problem.
