### ISSUE TITLE
Shrink bundle size with catalyst

### ISSUE THREAD

**Issue by FGRibreau** [jiahaog/nativefier#71]
Hello!

Awesome project you got there! I'm highly interested to use it for production projets however the current bundle size is quite large (got 108Mo using `nativefier --app-name "Redsmin" "https://app.redsmin.com"`)

I discovered https://github.com/gokmen/electron-catalyst that could reduce the **shipping size** from ~108MB to ~8,7MB, and then, on first load, download the large assets.

**Comment by jiahaog** [comment]
Thanks for the suggession, this could be a future addition!
