### ISSUE TITLE
can't Frameless properly resized on windows size 1920 1080

### ISSUE THREAD

**Issue by MDALIMULALRAZY** [jiahaog/nativefier#710]
### Description

<Detail your problem here as clearly and concisely as possible 🙂. Help us help you by saying why and giving some context!>

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Hi @MDALIMULALRAZY ! Thanks for the feedback, but there isn't much we can do with this little information. This project is a hobby with few maintainers at the wheel, helping during spare time. Do not expect "customer support"-style interaction; we need *you* to investigate as much as possible before opening an issue: try to narrow it as much as possible, provide the minimum details requested by [the issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md), intuitions, a reproducible website & scenario, etc: help us help you 🙂, maintainers are not wizards and do not read your mind. Of course, the best you can provide is code, PR very welcome.

With that, closing, but will re-open if you find the time to bring details. Cheers!

*<sub>Text inspired by [uBlock's CONTRIBUTING.md](https://github.com/gorhill/uBlock/commit/d3cd79c5b019612abe64e753eecf0417af9dfb78).</sub>*
