### ISSUE TITLE
Print don´t work

### ISSUE THREAD

**Issue by luisemz** [jiahaog/nativefier#713]
### Description

I tried "pdfMake.createPdf(pdf).print()" and the nativefier don´t show anything.
What is wrong?

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `nativefier --verbose --maximize -i "/Desktop/icon.png" -n "Local-Development" "http://localhost:1113"`
- Version of Nativefier (run `nativefier --version`): `v7.6.8`
- Version of node.js (run `node --version`): `v8.5.0`
- OS: `Mac OS 10.14`

**Comment by ronjouch** [comment]
@luisemz to help, we'll need a publicly available site, not a local development instance. Please provide one and I'll re-open.
