### ISSUE TITLE
Tray icons in KDE Plasma 

### ISSUE THREAD

**Issue by dauntedvariable** [jiahaog/nativefier#717]
### Description

The Nativefier tray icons are not being shown in the system tray in KDE Plasma.

### Details
- Full nativefier command used to build your app: `nativefier --tray --conceal --disable-dev-tools --name Whatsapp web.whatsapp.com`
- Version of Nativefier : `v7.6.8`
- Version of node.js : `v10.13.0`
- OS: `Ubuntu 19.04 disco`
- DE `KDE Plasma 5.14.2`

**Comment by frealgagu** [comment]
That is working to me.
nativefier --tray --disable-dev-tools --name Whatsapp web.whatsapp.com

Version of Nativefier : v7.6.8
Version of node.js : v11.3.0
OS: ArchLinux
DE KDE Plasma 5.14.4
