### ISSUE TITLE
Client side caching?

### ISSUE THREAD

**Issue by howardroark2018** [jiahaog/nativefier#724]
Hi, 
Excellent utility.
I was wondering if there's any possible option right now to enable caching (client side) in the app, which I suppose will make the resulting packaged apps to perform better. 

Regards,

Roark

**Comment by ronjouch** [comment]
Hi! Thanks for the feedback, but there isn't much we can do with this little information. This project is a hobby with only one maintainer at the wheel, looking at issues and merging the occasional Pull Request during spare time.

- **Feature requests**: do not expect new features (see manpower comment above) and do not expect Nativefier to fill every niche feature provided by a full-blown browser. Still convinced you want something? Build it. If you don't have the resources to build it and are sure you want to file an issue, then take the time to write a concise & clear title / description; I'll leave the issue open and maybe someday someone will take a stab at it.
- **Bugs reports**: do not expect "customer support"-style interaction; we need *you* to investigate as much as possible before opening an issue: try to narrow it as much as possible, provide the minimum details requested by [the issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md), offer intuitions, a reproducible public website & scenario, etc: help us help you 🙂, contributors are not wizards and do not read your mind. Of course, the best you can provide is code, PR very welcome.

With that, closing, but will re-open if you find the time to bring details. Cheers!

*<sub>Text inspired by [uBlock's CONTRIBUTING.md](https://github.com/gorhill/uBlock/commit/d3cd79c5b019612abe64e753eecf0417af9dfb78).</sub>*
