### ISSUE TITLE
Please Implement Referrer Bypassing?

### ISSUE THREAD

**Issue by skylerspark** [jiahaog/nativefier#726]
### Description

When I visit key.thundermods.com it redirects me to an ad site if I'm not coming from the specific clicksfly site or whatever, and was wondering if you can implemenet a feature to turn off/on referrer bypass?? I want to bypass this, as recently you have no way of successfully accessing the site. so i can't get the key for my program

### Steps to reproduce issue
Open the App, it autoredirects (via referrer script) to ad site.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `cd desktop nativefier https://key.thundermods.com`
- Version of Nativefier (run `nativefier --version`): `v7.6.9`
- Version of node.js (run `node --version`): `v11.4.0`
- OS: `Windows 7`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Hi! Thanks for the feedback, but there isn't much we can do with this little information. This project is a hobby with only one maintainer at the wheel, looking at issues and merging the occasional Pull Request during spare time.

- **Feature requests**: do not expect new features (see manpower comment above) and do not expect Nativefier to fill every niche feature provided by a full-blown browser. Still convinced you want something? Build it. If you don't have the resources to build it and are sure you want to file an issue, then take the time to write a concise & clear title / description; I'll leave the issue open and maybe someday someone will take a stab at it.
- **Bugs reports**: do not expect "customer support"-style interaction; we need *you* to investigate as much as possible before opening an issue: try to narrow it as much as possible, provide the minimum details requested by [the issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md), offer intuitions, a reproducible public website & scenario, etc: help us help you 🙂, contributors are not wizards and do not read your mind. Of course, the best you can provide is code, PR very welcome.

With that, closing, but will re-open if you find the time to bring details. Cheers!

*<sub>Text inspired by [uBlock's CONTRIBUTING.md](https://github.com/gorhill/uBlock/commit/d3cd79c5b019612abe64e753eecf0417af9dfb78).</sub>*
