### ISSUE TITLE
Can't login with google oauth

### ISSUE THREAD

**Issue by Hatko** [jiahaog/nativefier#728]
### Description

I can't log in to a created application with as a google user

### Steps to reproduce issue

1) Make an app from the [pomodoro tracker site](https://pomodoro-tracker.com/)
2) Try to log in as a google user; the app will transfer me to the actual chrome at this step; if I select my account - it will show error `403: Invalid token "".`; meanwhile the created application doesn't respond

### Details

- Are you nativefying a *public* website? - Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? - Not applicable 
- Full nativefier command used to build your app: `nativefier https://pomodoro-tracker.com/`
- Version of Nativefier (run `nativefier --version`): `v7.6.9`
- Version of node.js (run `node --version`): `v11.4.0`
- OS: `Mac OS 10.14.2`
- Error message / stack trace (if any):

```
403: Invalid token "".
```

**Comment by Hatko** [comment]
A similar issue is with [To do from microsoft](https://to-do.microsoft.com/). If you try to sign in - it will just show loading and redirect you to the browser

**Comment by jebeld17** [comment]
Similar issue at #745.

**Comment by ubuntudroid** [comment]
For me just adding the main domain again to the internal urls (in addition to the Google authentication domain `accounts.google.com`) did the trick.

Example for `https://next.focuster.com` which uses Google OAuth for login:

```
nativefier --name "Focuster" "https://next.focuster.com" --internal-urls "accounts.google.com|next.focuster.com"
```

**Comment by danielkuhlwein** [comment]
Thank you @ubuntudroid, this solution saved me.

For anyone trying to add Jira (without access to a Jira account with Google login) a slightly modified version of the code above worked for me:

`nativefier --name "Jira" "https://safetysync.atlassian.net" --internal-urls "id.atlassian.com/login|safetysync.atlassian.net"`

This will let you login with email/password without booting you to a browser window which displays an error.

**Comment by disklosr** [comment]
If you're authentication using Microsoft AD then you need to add `login.microsoftonline.com` to internal urls.

**Comment by ronjouch** [comment]
Looks like `--internal-urls` is doing the trick. Closing to centralize discussion around https://github.com/jiahaog/nativefier/issues/706#issuecomment-602057644 , PR welcome.
