### ISSUE TITLE
Prevent External Links to open in Browser

### ISSUE THREAD

**Issue by momosby** [jiahaog/nativefier#73]
Sorry to bother you again.
I created a soundcloud app and whenever i hit the sign in button,
it opens a "Log In"-Tab in my browser, which does not affect the app (i.e. does not sign me in in the app).
Not sure if I am doing something wrong...

However if there is a way to use an auth-token and place it manually somewhere in the contents of the app, let me know.

**Comment by mattmo** [comment]
I'm seeing the same thing with Asana. An oauth url is opened in a new tab in chrome and it doens't change the login state of Asana inside the nativefier app.

**Comment by jiahaog** [comment]
@momosby Does right clicking and selecting open in new window work for the login now?

**Comment by momosby** [comment]
It was left clicking on regular links that didnt work... Does now :)

**Comment by floeschie** [comment]
I still have the issue…

Steps to reproduce:

1. Create an app for Tolino WebReader (https://webreader.mytolino.com/library/)
1. Open the app
1. Click the login button (German: "Anmelden")
