### ISSUE TITLE
Javascript injection isn't working on macOS w/ electron 3.0.x

### ISSUE THREAD

**Issue by grork** [jiahaog/nativefier#731]
### Description

When using the `--inject` option with javascript, the script is not actually executed because of a timing between when `preload.js` attaches the `DOMContentLoaded` event, and when that event is raised. On my Core m3 MacBook, the even is already raised/handled by the time the require calls execute.

### Steps to reproduce issue

a) Create a `foo.js` file to inject, and add the line `console.log("I am preloaded")` to it
b) `nativefier --inject foo.js https://www.example.com`
c) Run the electron app under a debugger/show the dev tools/add something more conspicuous to the injected JS

### Details

- _Are you nativefying a *public* website?_ Yes
- _Feature request?_ No
- _Full nativefier command used to build your app:_ See Repro Steps
- _Version of Nativefier_: v7.6.9
- _Version of node.js:_ `v8.15.0`
- _OS:_ macOS Mojave 10.14.2

### Likely Fix
Move the attachment of the `DOMContentLoaded` handler earlier in `preload.js`

**Comment by ronjouch** [comment]
Fixed with Nativefier 7.6.10, which will hit npm in a few minutes/hours. :clap: :pray: @grork !
