### ISSUE TITLE
Support macOS Mojave dark mode

### ISSUE THREAD

**Issue by weiran** [jiahaog/nativefier#733]
### Description

Electron 4.0 adds support for Mojave dark mode: https://github.com/electron/electron/issues/13387. Can nativefier support this as well? Currently the window title bar is "light" grey even if the dark theme is selected on macOS.

### Steps to reproduce issue

Run nativefier on any website on macOS Mojave. With dark system theme selected, nativefier should then adapt the window title bar to be dark as well.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes

**Comment by ronjouch** [comment]
Would be cool.

Depends on [#727 - Review and adapt to electron 4.0 breaking changes](https://github.com/jiahaog/nativefier/issues/727).

**Comment by danielkuhlwein** [comment]
I would pay for this feature. Keep up the greet work @ronjouch. I look forward to future updates!

**Comment by ronjouch** [comment]
Closing as fixed since https://github.com/jiahaog/nativefier/commit/54335699218ac79e75a13c314cf48ff25fee1a80 .
