### ISSUE TITLE
Help Menu Links

### ISSUE THREAD

**Issue by oleteacher** [jiahaog/nativefier#734]
Wonderful work, thank you!

Would like use this in school classroom but cannot have links which open default browser and access the internet. The "Help" menu has such links...

Looking at API and see no way to change this? Is it possible to remove links leading to external sites?

Thanks again.

**Comment by ronjouch** [comment]
@oleteacher glad you find it useful 🙂!

The help menu has such links, and links can also be opened in the default browser with a simple Ctrl+click (or Shift+click, not sure), and some links considered extenal will open in the default browser. I don't think Nativefier has the enforcement mechanisms you need for your specific use case, sorry.

**Comment by oleteacher** [comment]
Ok, thanks for trying to support school kids wishing to learn!
