### ISSUE TITLE
Dropbox Paper app opens dropbox file chooser on entering Paper doc

### ISSUE THREAD

**Issue by ahappydad** [jiahaog/nativefier#737]
### Description

On my nativefier Paper app when I open up a Paper document, the Dropbox file selector appears and on any button interaction, Cancel or file select and Save, the file selector window appears. 

### Steps to reproduce issue
Open Paper app
Select any Paper doc
File chooser appears

### Details

- Are you nativefying a *public* website? No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? I tried --disable-context-menu to see if that was it, but don't see anything else. 
- Full nativefier command used to build your app: 'nativefier "https://paper.dropbox.com/home/recents" --disable-context-menu --name "Dropbox Paper"'
- Version of Nativefier (run `nativefier --version`): `v7.6.10`
- Version of node.js (run `node --version`): `v10.15.0`
- OS: `Mac Mojave 10.14.2`
- Error message / stack trace (if any): 
No stack trace error

**Comment by otsaloma** [comment]
You can work around this by injecting (`--inject=...`) the following JavaScript. This probably breaks the file chooser completely, so any possible legitimate use is disabled as well.

```javascript
window.onload = function() {
    Dropbox.choose = undefined;
};
```
