### ISSUE TITLE
Discussion/Feature: Distribution Ready Packaging

### ISSUE THREAD

**Issue by Skillz4Killz** [jiahaog/nativefier#739]
### Description
Is there any way to possibly make distribution ready applications? I read the entire API documentation and found no mention of something similar to this.

```js
nativefier --distribution
```

This could create a basic working copy for all platforms that nativefier supports. Dev teams could simply make those files be able to be downloaded from their website because trying to teach users how to install nativefier and download the website as an app is much more difficult than having them click a button like Download Mac, Download Linux, Download Windows 32bit 64bit etc.... Trying to have a user open up a command line terminal is already difficult enough. The second that a average user opens it up they are too afraid to try anymore.

### Use Case

In my small dev team on a side project that we enjoy doing on our free time, it is not so easy to have the time or ability to make native cross-platform applications. Nativefier would be a huge asset to a bunch of development teams in my opinion if it was possible to do something like this.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes and also the API docs and no mention of anything similar
- Version of Nativefier (run `nativefier --version`): `v7.6.9`
- Version of node.js (run `node --version`): `v10.10.0`
- OS: `OSX Mojave`

Thank You!

**Comment by DGxInfinitY** [comment]
Bump.
This would be awesome to add. 
I would use it to package in .deb

**Comment by Skillz4Killz** [comment]
Closing this as I found using a PWA is much easier on the user. Especially with Google Chrome now supporting it so nicely.
