### ISSUE TITLE
Outlook365 

### ISSUE THREAD

**Issue by ranzou06** [jiahaog/nativefier#743]
### Description
Open email composer on a separete windows will open a black page.

<Detail your problem here as clearly and concisely as possible 🙂. Help us help you by saying why and giving some context!>

### Steps to reproduce issue
open email composer.

![image](https://user-images.githubusercontent.com/4295849/51401155-41098080-1b31-11e9-9a26-ca40014f5c4e.png)

click to open on a separated window.

![image](https://user-images.githubusercontent.com/4295849/51401216-5e3e4f00-1b31-11e9-8f06-2578df521d7f.png)

### Details

- Are you nativefying a *public* website? 
No
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
yes
- Full nativefier command used to build your app:
<nativefier --name "Outlook" "https://outlook.office365.com/"  --internal-urls "^((?!projection.aspx).)*" --single-instance>
- Version of Nativefier (run `nativefier --version`): `v7.6.10`
- Version of node.js (run `node --version`): `v10.15.0`
- OS: `Windows 10`

**Comment by jebeld17** [comment]
Might be similar to #699

**Comment by jizusun** [comment]
Outlook 365 works on my machine now, and don't know whether it relates to "The new Outlook" feature.

* Full nativefier command used to build your app:
```
nativefier \
-n "Outlook-Office365" \
--maximize \
--show-menu-bar \
--internal-urls ".*(office|office365|sharepoint|microsoft|onenote)\.(com).*" \
--tray \
--counter \
--single-instance \
'https://outlook.office.com/owa'
```
* Version of Nativefier (run `nativefier --version`): `v7.6.10`
* Version of node.js (run `node --version`): `v10.14.2`
* OS: `Ubuntu 16.04`

![image](https://user-images.githubusercontent.com/4011348/52617666-8d00d880-2ed7-11e9-9958-3c2292a9baf7.png)

**Comment by mickaobrien** [comment]
Just to add to this, I had to add `microsoftonline.com` to the list of internal URLs to be able to login correctly. So:

```
nativefier \
-n "Outlook-Office365" \
--maximize \
--show-menu-bar \
--internal-urls ".*(office|office365|sharepoint|microsoft|microsoftonline|onenote)\.(com).*" \
--tray \
--counter \
--single-instance \
'https://outlook.office.com/owa'
```
