### ISSUE TITLE
⚠ Read before asking: Nativefier is unmaintained, we need your help! ⚠

### ISSUE THREAD

**Issue by ronjouch** [jiahaog/nativefier#746]
Hello. This project is a hobby with only one maintainer at the wheel, me, these days barely using Nativefier, looking at issues once in a blue moon, and merging the occasional Pull Request during spare time.

- **Feature requests**: do not expect new features (see manpower comment above) and do not expect Nativefier to fill every niche feature provided by a full-blown browser. A big part of Nativefier's minimalist appeal is precisely that it's *not* a full-blown browser!  
Still convinced you want something? Build it. If you don't have the time/will/expertise to build it and are sure you want to file an issue, then take the time to write a concise & clear title / description; I'll leave the issue open and maybe someday someone will take a stab at it.
- **Bugs reports**: do not expect "customer support"-style interaction; we need *you* to investigate as much as possible before opening an issue: try to narrow it as much as possible, provide the minimum details requested by [the issue template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE.md), offer intuitions, a reproducible public website & scenario, etc: help us help you 🙂, contributors are not wizards and do not read your mind. Of course, the best you can provide is code, PR very welcome.

Finally, that goes without saying: ***contributions welcome! If you have the skills and time, consider helping, with issue triaging or code, once or regularly. The maintainer is you***. Triaged issues: [bugs](https://github.com/jiahaog/nativefier/issues?q=is%3Aopen+is%3Aissue+label%3Abug), [feature requests](https://github.com/jiahaog/nativefier/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22+). ***Nativefier needs more hands!***

Users, thanks for your interest, and contributors: thanks for the help 🙂!

*<sub>Text inspired by [uBlock's CONTRIBUTING.md](https://github.com/gorhill/uBlock/commit/d3cd79c5b019612abe64e753eecf0417af9dfb78).</sub>*

**Comment by isaac-martin** [comment]
@ronjouch is there any way to add some maintainer(s) to the nativefier-icons repo? I can take on the work on that..

**Comment by ronjouch** [comment]
> @ronjouch is there any way to add some maintainer(s) to the nativefier-icons repo? I can take on the work on that..

@isaac-martin thanks for chiming in! I'm not active in any way in that repo, please get in touch with @jiahaog .

**Comment by isaac-martin** [comment]
@ronjouch understandable - @jiahaog has gone MIA.

**Comment by saulocastelo** [comment]
Sooooo let's help! How can I help? Fork and submit pull requests?

**Comment by ronjouch** [comment]
> Sooooo let's help! How can I help? Fork and submit pull requests?

@saulocastelo yup, PRs welcome! Look at the issues with activity/votes if you need inspiration 🙂.

**Comment by saulocastelo** [comment]
@ronjouch how can i assign an issue for me?

**Comment by ronjouch** [comment]
> how can i assign an issue for me?

@saulocastelo don't, just work on something that speaks to you and submit a PR 🙂. It's pretty quiet here, there's veeeeery little chance someone would submit a PR at the same time for the same issue.

**Comment by mxdpeep** [comment]
I try to answer questions if I know the answer 👍 
I have come over Nativefier several hours ago and it works for me...

**Comment by voltechs** [comment]
@ronjouch There are a few PRs ready to go. As per this issue/request for PRs, can we get some support in merging these in? It's a cool project. I've found one of the best ways to keep an Open Source project alive is to pull in contributions from members of the community.

**Comment by ronjouch** [comment]
> There are a few PRs ready to go. As per this issue/request for PRs, can we get some support in merging these in? It's a cool project. I've found one of the best ways to keep an Open Source project alive is to pull in contributions from members of the community.

@voltechs thanks for the ping. But there aren't so many PRs ready to go. I just looked at them: merged one, closed a few (3 I think) stale-since-long ones missing fixes/changes/doc, remains four: three with requested changes, and one breaking CI.

**Comment by voltechs** [comment]
@ronjouch I totally agree/feel ya (closing PRs)! Thanks for the housekeeping efforts. I'm trying to rouse the authors where applicable to move them along.
