### ISSUE TITLE
moving a task with multiple assignees reduces them

### ISSUE THREAD

**Issue by mrcsdwdn** [jiahaog/nativefier#749]
Moving a task with multiple assignees from one sprint to another, removes all assignees except the one who is moving the task.

**Comment by ronjouch** [comment]
@mrcsdwdn

![giphy](https://user-images.githubusercontent.com/522085/52061886-65a42600-253d-11e9-811d-a7672fa8d3f7.gif)

**Comment by mrcsdwdn** [comment]
@ronjouch I'm sorry, was totally my fault.

**Comment by ronjouch** [comment]
@mrcsdwdn no worry and gently-sorry about the sarcastic GIF. Sometimes I'm in the mood to offer to unresearched/off-topic issues a relax & helpful answer, and sometimes I'm the mood to close with a sarcastic GIF 🙂. Good day to you!
