### ISSUE TITLE
Simulating Slack Client with nativefier?

### ISSUE THREAD

**Issue by janpio** [jiahaog/nativefier#750]
Hey,

I am currently looking for a better way to run my several Slack accounts. I have several of them, but only 2 or 3 need to be running (and eating RAM) all day. The others I just want to look at on demand.

One way of course would be to dump the native Slack client, or at least remove all the on-demand workspaces, and just use it for the important ones. Then use the normal web app of Slack for the other Slacks. But I don't really want to have Slack in my browser.

Another way would be to create standalone apps for each workspace with nativefier. That way I could keep the important ones running all day, and start the others only on demand. This definitely works, but comes with its own "management" problems re app names, app icons, taskbar and systray space and so on.

So I thought about creating one nativefier app that can include all my workspaces, but an added option to deactivate and activate (unload/load) workspaces on demand. How could I implement something like that?

My current idea is to write a small web app where you can add your workspaces, create a "tab" for each one and load it into an iframe in there. Add a button to "unload" a workspace to remove the iframe, and another one to "reload" it.

Does this make sense?
Are there better tools available for nativefier that I missed that could help me here?

**Comment by ronjouch** [comment]
That makes sense. However, Nativefier is all about simplicity, one app in a window.

I think what you want is to re-write a slack web wrapper doing the loading/unloading you expect. Or maybe look at unofficial lightweight Slack clients, there are a few in text mode or in Qt.
