### ISSUE TITLE
the HTML5 player looks super old, possible to redesign it?

### ISSUE THREAD

**Issue by DParty** [jiahaog/nativefier#753]
### Description

<Detail your problem here as clearly and concisely as possible 🙂. Help us help you by saying why and giving some context!>

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by Vresod** [comment]
You could possibly make your video player, but nativefier uses electron which uses chromium. maybe go ask somewhere on [the chromium projects](https://www.chromium.org)?
