### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by shsteven** [jiahaog/nativefier#76]
Hi there,

Awesome tool!
I'm running this in El Cap 10.11.2 and Node v.0.5.4.
Got this error on launch, no matter which website I tried:

<img width="532" alt="screen shot 2016-01-25 at 9 25 43 am" src="https://cloud.githubusercontent.com/assets/96500/12540548/d803698e-c345-11e5-9d05-06d53875d692.png">

**Comment by outsideris** [comment]
+1

**Comment by jiahaog** [comment]
Give me a moment, I'm looking into it now

**Comment by shsteven** [comment]
Thanks for the fast response!

**Comment by jiahaog** [comment]
Sorry, are you on node.js v0.5.4? I've never actually tested it with that version of node, and my CI tests are from v0.12 onwards.

**Comment by shsteven** [comment]
Oops sorry it's v5.4.1

**Comment by shsteven** [comment]
node v5.4.1 
npm v3.3.12

**Comment by jiahaog** [comment]
Right, just give me a moment

**Comment by shsteven** [comment]
Thank you @jiahaog !

**Comment by jiahaog** [comment]
Okay this should have been fixed now in `v6.6.1`, I seem to have misunderstood how webpack externals work and it broke everything ><
