### ISSUE TITLE
 start application -  run single instance

### ISSUE THREAD

**Issue by danieltomasz** [jiahaog/nativefier#763]
I create simple command line for open my app (google calendar). Is there any argument for command line that will start existing instance of this app rather than starting another window?

**Comment by bnadji** [comment]
Not sure if I fully understand your question.  But if you are trying to always use one instance of your app and not create a new instance every time you run it, try to rebuild your app using the `--single-instance` command line option.

**Comment by danieltomasz** [comment]
thanks, that was what I wanted!
