### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by crashbdx** [jiahaog/nativefier#764]
### Description

I tried nativefier over 2 differents websites and for both when i open the nativefied app it give me a white page and take an average of 30 secondes before displaying the page, is it normal behavior ?

### Details

- Are you nativefying a *public* website? 
Yes

- Full nativefier command used to build your app: `<command here>`
nativefier --name "Asana" "https://app.asana.com"

- Version of Nativefier 7.6.11
- Version of node.js 8.12.0
- OS: win10

**Comment by ronjouch** [comment]
Cannot reproduce; here Asana opens in Nativefier just as fast as in Chrome. Feel free to come back with more debug info

**Comment by Xachman** [comment]
This happens for me as well using windows 10 and node 13.9.0 and version 10.1.0 nativefier

Anyone find a solution to this?
