### ISSUE TITLE
Error: Cannot find module 'source-map'

### ISSUE THREAD

**Issue by izakman** [jiahaog/nativefier#77]
After running nativefier, when I try to run the generated app I get a error box saying a javacript error has occured.  Seems to happen no matter what site I try.

![nativefier-error](https://cloud.githubusercontent.com/assets/773460/12541355/e2770aee-c361-11e5-9289-eb42c2faf846.png)

**Comment by jiahaog** [comment]
What version of nativefier and node are you using?

**Comment by izakman** [comment]
Ahh, I had 6.6.0.  I'd only just installed it off npm today.  I've now reinstalled it and it's at 6.6.1 and working correctly.

Cheers.

**Comment by jiahaog** [comment]
Sorry about that, glad its working!
