### ISSUE TITLE
Nativefier not working

### ISSUE THREAD

**Issue by noufalas** [jiahaog/nativefier#770]
### Description

I am trying to use nativefier getting below error. i can see an icon named app is created but it's not opning anything, just a blank screen, 

- Are you nativefying a *public* website?
yes, tried for others getting same issue.
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
yes
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): 7.6.11
- Version of node.js (run `node --version`): v11.12.0
- OS: `linux
- Error message / stack trace (if any):

```
nativefier -p linux -a x64 –name "youtube" "https://www.youtube.com/" --verbose
  inferring [=====                                             ] 10%Unable to automatically determine app name, falling back to 'APP'. Reason: Error: getaddrinfo ENOTFOUND xn--name-z86a xn--name-z86a:80
Unable to infer chrome version for user agent, using 61.0.3163.100
  inferring [==========                                        ] 19%Cannot automatically retrieve the app icon: { Error: getaddrinfo ENOTFOUND xn--name-z86a xn--name-z86a:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'xn--name-z86a',
  host: 'xn--name-z86a',
  port: 80 }
  packaging [==============================                    ] 60%Packaging app for platform linux x64 using electron v3.1.3

App built to youtube/app-linux-x64
```

**Comment by denisgolius** [comment]
> ### Description
> 
> I am trying to use nativefier getting below error. i can see an icon named app is created but it's not opning anything, just a blank screen,
> 
>     * Are you nativefying a _public_ website?
>       yes, tried for others getting same issue.
> 
>     * Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
>       yes
> 
>     * Full nativefier command used to build your app: `<command here>`
> 
>     * Version of Nativefier (run `nativefier --version`): 7.6.11
> 
>     * Version of node.js (run `node --version`): v11.12.0
> 
>     * OS: `linux
> 
>     * Error message / stack trace (if any):
> 
> 
> ```
> nativefier -p linux -a x64 –name "youtube" "https://www.youtube.com/" --verbose
>   inferring [=====                                             ] 10%Unable to automatically determine app name, falling back to 'APP'. Reason: Error: getaddrinfo ENOTFOUND xn--name-z86a xn--name-z86a:80
> Unable to infer chrome version for user agent, using 61.0.3163.100
>   inferring [==========                                        ] 19%Cannot automatically retrieve the app icon: { Error: getaddrinfo ENOTFOUND xn--name-z86a xn--name-z86a:80
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
>   errno: 'ENOTFOUND',
>   code: 'ENOTFOUND',
>   syscall: 'getaddrinfo',
>   hostname: 'xn--name-z86a',
>   host: 'xn--name-z86a',
>   port: 80 }
>   packaging [==============================                    ] 60%Packaging app for platform linux x64 using electron v3.1.3
> 
> App built to youtube/app-linux-x64
> ```

Try to use English chars for icon and app.

**Comment by RA80533** [comment]
> Try to use English chars for naming icon and app.

This is non-compliant with RFC 3492. Hostnames can be encoded in [punycode](https://en.wikipedia.org/wiki/Punycode).

**Comment by TheCleric** [comment]
> > Try to use English chars for naming icon and app.
> 
> This is non-compliant with RFC 3492. Hostnames can be encoded in [punycode](https://en.wikipedia.org/wiki/Punycode).

This is actually no longer an issue since v44.0.0

**Comment by SoulUchiha** [comment]
same
