### ISSUE TITLE
Widevine , DRM , User Agent

### ISSUE THREAD

**Issue by BondasH** [jiahaog/nativefier#773]
Hi. 
Thanks for your project

problems:

1). Material is not available in this browser. Use the Firefox, Opera or application browser on your Android / iOS phone

2).User Agent not really changet / black scree on player or similar

3). Widevine / DRM missing

you have to make some corrections in your plans?

Regards

**Comment by agigao** [comment]
+1.

In my case I tried to package grammofy as an app and the content on that web-page needs Widevine.

Any plans for tackling DRM issue here?

I don't want to get Chrome anywhere near my lap.

**Comment by ronjouch** [comment]
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/435
