### ISSUE TITLE
Trying to find Chrome version for flash

### ISSUE THREAD

**Issue by oleteacher** [jiahaog/nativefier#777]
Nice project and totally understand the "one man hobby project" status. Got a few on those myself:)

I am trying to figure out the "Chrome Version" used in your latest release. Need to get the pepperflash plugin but without correct version, shooting in the dark.

Can you help?

Thank you,

Susan

**Comment by ronjouch** [comment]
> I am trying to figure out the "Chrome Version" used in your latest release.

@oleteacher pop open an inspector(<kbd>CtrlOrCmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>), click the `Console` tab, and evaluate `navigator.userAgent`. It will include something like `Chrome/66.0.3359.181`

**Comment by oleteacher** [comment]
Thanks!
