### ISSUE TITLE
Nativefier not creating app

### ISSUE THREAD

**Issue by cwbuck** [jiahaog/nativefier#778]
### Description

Hi! I am using Nativefier on Ubuntu 18.04 under WSL.
I am trying to make an app out of youtube.com, as an example. 
It is failing for me. Please see below for details.

### Steps to reproduce issue

sudo nativefier --name "Youtube" --platform windows "https://www.youtube.com/"

### Details

- Full nativefier command used to build your app: sudo nativefier --name "Youtube" --platform windows "https://www.youtube.com/"

- Version of Nativefier (run `nativefier --version`): v7.6.12

- Version of node.js (run `node --version`): v8.10.0

- OS: Ubuntu 18.04 (WSL) on W10

- Error message / stack trace (if any):
 packaging [===============================                   ] 61%Packaging app for platform win32 x64 using electron v3.1.7
  packaging [====================================              ] 72%Error: rcedit.exe failed with exit code 1. wine: /home/le0pard/.wine is not owned by you
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativefier/node_modules/rcedit/lib/rcedit.js:68:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  packaging [========================================          ] 79%%

**Comment by cwbuck** [comment]
Note: I have used chown to ensure that I do own .wine.

**Comment by hashfunktion** [comment]
Hi! I have the same problem.
I'm using Nativefier to create a Windows App direct under Windows.

Same version like cwbuck and node.js v10.15.3

**Comment by hashfunktion** [comment]
Hi, I had the same error and solved the problem for me with these steps.

I run Nativefier under Windows so I had also chance the terminal path from _C:\Windows\System32_ to _C:\Users\<USERNAME>_. So that the user have definitely full access to this folder.

The same for the export path. When I submit the explicit export path to my home folder then the build runs successfully.
`nativefier --name "Test-App" "https://www.google.de"  C:\Users\<USERNAME>`

Hope that's help you too @cwbuck .

**Comment by cwbuck** [comment]
Hi, @hashfunktion -
That's really interesting - I went through the steps you suggested and was presented with a different error. Stack trace below:
 nativefier --name "Test-App" --platform windows "https://www.google.de" C:\Users\chris
  packaging [===============================                   ] 61%Packaging app for platform win32 x64 using electron v3.1.7
  packaging [========================================          ] 79%Error: rcedit.exe failed with exit code 193. wine: Bad EXE format for Z:\usr\local\lib\node_modules\nativefier\node_modules\rcedit\bin\rcedit.exe.
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativefier/node_modules/rcedit/lib/rcedit.js:68:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)

**Comment by hashfunktion** [comment]
The part after the url is the export path. You run Nativefier under Ubuntu right? Than I think so you have to change the export page to /home/Chris/ or something else.

**Comment by cwbuck** [comment]
That worked! Thanks @hashfunktion - Had the path to my windows box, not WSL. Appreciate it!

**Comment by hashfunktion** [comment]
@cwbuck that sounds good!
Can you close the issue?

**Comment by cwbuck** [comment]
Absolutely - thanks.

**Comment by cwbuck** [comment]
Closed #778
