### ISSUE TITLE
Android and iOS apps

### ISSUE THREAD

**Issue by nikhildaga** [jiahaog/nativefier#78]
First of all, Thank you! Great package.

Is it possible to have similar functionality for android and iOS apps ?
Are you aware of anything that does it?

**Comment by dimd13** [comment]
+1

**Comment by dirkk0** [comment]
+1.
Same suggestion/question here.
Otherwise great idea and product, and thanks for open sourcing it.

**Comment by gavinengel** [comment]
+1 heck yea! Watching this

**Comment by MakuSensei** [comment]
+1
XD interesante

**Comment by jiahaog** [comment]
Thank you! Mobile functionality is not planned, but @samkho10 was working on https://github.com/samkho10/appify which is what you want!

**Comment by samkho10** [comment]
Thanks for the mention @jiahaog! @nikhildaga, I am currently working on making the process more automated and simple, let me know if you are interested in collaborating! :smile:

**Comment by leovarmak** [comment]
@samkho10 Get it to life quickly. Can't wait to try it. I am not exactly much of a developer but if you have something for me, I would love to help

**Comment by samkho10** [comment]
@leovarmak in serious need of dev wizardry. if anyone  (@nikhildaga) would like to help let me know!
