### ISSUE TITLE
blocking adds

### ISSUE THREAD

**Issue by ZOIIOZ** [jiahaog/nativefier#786]
### I Need to block adds

well having the page open in my browser with the addblocker on was great, now with the web page built in node js without any addfilter is a very unsatisfayin experince. Sooo... any idea to how block add inside node js/Nativefier

**Comment by ronjouch** [comment]
@ZOIIOZ there's no way right now.

- Consider lower-level blocking (OS through a hosts file, or network through a [router adblock](https://github.com/openwrt/packages/blob/master/net/adblock/files/README.md))
- Closing as (more general) https://github.com/jiahaog/nativefier/issues/207 .
