### ISSUE TITLE
Old deleted mails are again visible in Inbox

### ISSUE THREAD

**Issue by akgunjal** [jiahaog/nativefier#787]
### Description

There are lot of deleted old mails that I am seeing in my Inbox from today. Ideally I should not see them but I see them. I also see them only in IBM Verse and not in IBM Notes mail.

**Comment by ronjouch** [comment]
Hi @akgunjal. This is Nativefier, the software IBM Verse is based on. We Nativefier have no control on fixing IBM Verse. Please contact the support for IBM Verse with your problem, and please also tell them we'll welcome a patch to customize the "Help → Report an issue" link. Thanks slightly_smiling_face.
