### ISSUE TITLE
Mint.com not working

### ISSUE THREAD

**Issue by eni9889** [jiahaog/nativefier#788]
### Description

Trying to use the app to bundle mint.com but no luck I just get a redirect to chrome

### Steps to reproduce issue

`nativefier mint.intuit.com --name "Mint"`

**Comment by zhm** [comment]
Try this:

```sh
nativefier www.mint.com --name "Mint" --internal-urls "^(https://accounts.intuit.com)|(https://mint.intuit.com)"
```

**Comment by eni9889** [comment]
@zhm that worked thanks. I must have missed that in the docs
