### ISSUE TITLE
Feature: Auto-refresh every X seconds (provide as cmd arg)

### ISSUE THREAD

**Issue by bfelbo** [jiahaog/nativefier#798]
Nativefier is amazing, thanks a lot for building it!

We're using nativefier for many sites, including circleci.com. CircleCI requires a full page refresh to update the status of a CI run from "In Progress" to "Success" or "Failed". It'd be great if we could provide a simple command-line argument like `--refresh 60` to make the page reload every 60 seconds as if someone had hit Cmd + R.

**Comment by felipemarinho97** [comment]
Why not insert a javascript code to do this into the page?

**Comment by bfelbo** [comment]
We don't own the site, but are just using it through nativefier. I've reached out to circleci to get them to auto-refresh, but they're not doing it anytime soon.

**Comment by felipemarinho97** [comment]
I mean, there are a option called `--inject` that allows you to load javascript code into the page, you can use it to inject something like this `setInterval(reloadPage, 60)` 

Checkout at the docs [here](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#inject)

**Comment by bfelbo** [comment]
Ah, cool. Thanks!
