### ISSUE TITLE
[Feature Request] Freedesktop `.desktop` files

### ISSUE THREAD

**Issue by rspencer01** [jiahaog/nativefier#799]
It would be cool if nativefier generated an appropriate `.desktop` file that could be used by launchers supporting freedesktop config files.

**Comment by cassidyjames** [comment]
For added context, this affects nearly every Linux-based desktop OS out there, like Ubuntu, Fedora, elementary OS, Pop!_OS, Red Hat Enterprise Linux, etc. as desktop environments like GNOME, KDE, Pantheon, XFCE, etc. all use FreeDesktop `.desktop` launcher files for their application launchers and docks.

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/jiahaog/nativefier/issues/204 . There's also an open PR for that, https://github.com/jiahaog/nativefier/pull/729 , but I didn't merge it before my big 8.0 refactor so it needs a bit of work now, and I have one issue in particular with paths, that I'll write now in the other issue. Closing this one, please move discussion to the other issue.
