### ISSUE TITLE
Related to #78, adding custom window sizes

### ISSUE THREAD

**Issue by josephdburdick** [jiahaog/nativefier#80]
Great package, thanks a lot! I'm planning on developing my sites in a separate window now because this thing is so sweet.

It would be really nice to automatically switch the window width/height so I can see how this chromeless browser looks when it's supposed to be a mobile device, tablet, etc. I see that there are window width/height options on the CLI, would it be possible to add user-generated lists of window widths/heights to the menu bar to quickly toggle between?

**Comment by jiahaog** [comment]
Hi, this is quite a specific use case and I don't really have plans for this. I believe the app remembers the state of the window when it is closed, could you work with that instead?

**Comment by MacWorks** [comment]
One thing that does not persist is the window being in fullscreen mode when quit and relaunched.

**Comment by jiahaog** [comment]
@MacWorks You're right, that could be an enhancement to save the state of the window

**Comment by jiahaog** [comment]
@MacWorks  Are you sure it does not remember its full screen state? It seems to work for me. I'm on nativefier 6.9.1 on OSX 10.11.2

**Comment by MacWorks** [comment]
I'm on OS X 10.11.2 and my apps were last built with 6.8.0, I updated to 6.10.0 and rebuilt the apps. But they still do not remember full screen mode. If I put one in full screen mode then quit the app and relaunch, it will launch in window mode (not full screen).

**Comment by surreal8** [comment]
Hi, is there a fix to remember fullscreen mode? I'm on OS X 10.12, after I close the application, the app does not launch in fullscreen mode after that.

**Comment by MacWorks** [comment]
@surreal8 I'm using 7.0.1 and on macOS 10.12 my apps do remember fullscreen mode.

**Comment by surreal8** [comment]
Thanks @MacWorks. I was just testing and my app was not remembering full screen mode after the first time. So then I did Control+Cmd+F to enter fullscreen. After that when I quit, the app is remembering fullscreen - weird?
