### ISSUE TITLE
[SUGGESTION] Microsoft Defender and ATP integration

### ISSUE THREAD

**Issue by jebeld17** [jiahaog/nativefier#808]
With Microsoft Defender and ATP APIs now available for non-Microsoft browsers such as Firefox and Chrome, it just makes sense to include this integration out-of-the-box for Nativefier users.

Such integration could be as easy as shipping Nativefier with Microsoft's open source Chrome extensions for these.

**Comment by mxdpeep** [comment]
what?!
Microsoft is using Chromium for it's browser

I am quite sure I don't understand your issue at all! :)

**Comment by jebeld17** [comment]
Yes... which in turn uses the Chromium browser, which then in turn means it can easily be compatible with a Chrome extension such as Defender ATP

**Comment by mxdpeep** [comment]
so you want to add https://chrome.google.com/webstore/detail/windows-defender-browser/bkbeeeffjjeopflfhgeknacdieedcoml
inside the container?

**Comment by mxdpeep** [comment]
> Yes... which in turn uses the Chromium browser, which then in turn means it can easily be compatible with a Chrome extension such as Defender ATP

see this thread: https://github.com/electron/electron/issues/19447

**Comment by ronjouch** [comment]
What mxdpeep said: Nativefier doesn't support extensions for now.
