### ISSUE TITLE
PNG icons do not show up in Ubuntu/Unity's alt-tab

### ISSUE THREAD

**Issue by ronjouch** [jiahaog/nativefier#81]
Hi.

I'm trying to package an app with a PNG icon under Linux (Ubuntu, x64, 14.04.3LTS):

```bash
/opt node --version
v5.5.0

/opt which node
/home/ronj/.nvm/versions/node/v5.5.0/bin/node

/opt nativefier --version
6.6.1

/opt ls -la "/opt/google-hangouts-icon.png"
-rw-rw-r-- 1 ronj ronj 56364 Jan 25 09:35 /opt/google-hangouts-icon.png

/opt nativefier -o -n "hangouts" -i "/opt/google-hangouts-icon.png" "https://hangouts.google.com/"
Packaging app for platform linux x64 using electron v0.36.4
App built to /opt/hangouts-linux-x64
```

The `/opt/google-hangouts-icon.png` icon is a 512x512 PNG: http://icons.iconarchive.com/icons/martz90/circle-addon2/512/google-hangouts-icon.png

Packaging is okay and the app works as intended, but the icon never shows up in Unity's Alt-Tab, showing instead Unity's placeholder "question mark" icon:

![nativefier_icon_linux-ubuntu-14 04 3_electron0 36 4](https://cloud.githubusercontent.com/assets/522085/12554151/22cb47cc-c349-11e5-9852-39310914cc9e.png)

Am I doing anything wrong? Ideas? Feel free to ask for additional debug info :)

Might be related to https://github.com/jiahaog/nativefier/issues/53 , or might not (this bug is about Linux, the other one seems `.icns` / Mac-specific).

**Comment by zweicoder** [comment]
Hey, try putting the icon into the `/resources/app` folder and name it `icon.png`.

**Comment by zweicoder** [comment]
I believe the `electron-packager` module that was being used doesn't really work. I sent in a PR with this hotfix a while ago so that it checks `<packaged_app>/resources/app/icon.png` while the official fix is still being worked on. This should work for Windows as well.

**Comment by ronjouch** [comment]
@zweicoder moving the icon to `<packaged_app>/resources/app/icon.png` didn't work. Buuuuuut now that I know the feature exists, good'ol' `strace` can help!

```bash
/opt/hangouts-linux-x64 sudo strace -f ./hangouts 2>&1 | grep icon\.png
[pid 10614] open("/opt/hangouts-linux-x64/resources/app/lib/icon.png", O_RDONLY <unfinished ...>
^C
```

Icon should go to `<packaged_app>/resources/app/lib/icon.png` (your hint was missing `.../lib/...`), and it works! Thanks for the fast feedback :) . Want me to send a quick doc. PR mentioning this temporary workaround in README.md, or do you prefer to wait for the actual fix?

**Comment by jiahaog** [comment]
Hi, I'm working on a fix for this right now, there seems to be some issues with the library I'm using, and I have a workaround in mind for this.

**Comment by miduga** [comment]
Good to know @jiahaog :+1:

**Comment by resilva87** [comment]
I have the same issue, doing what @ronjouch mentioned did the trick. Hope to see it fixed in future releases :+1:

**Comment by jiahaog** [comment]
This has been fixed since 5475c6e9685d459509d856f6b4457eeec57ab47a and is released in `v6.7.0`, the `--icon` command line flag should work now.

**Comment by ronjouch** [comment]
@jiahaog confirmed fixed in v6.7.0, `--icon` works as advertised! Thanks :+1: 

---

One detail: since this new version, `--app-name` capitalizes the name I'm asking for. Suppose I'm asking for `--app-name hangouts`,

* nativefier used to create ./hangouts-linux-x64/hangouts
* nativefier now creates ./Hangouts-linux-x64/Hangouts

Is this intentional?

**Comment by jiahaog** [comment]
@ronjouch Ah, that is not intentional, could you open a new issue for this? I wanted to sanitize app names as ubuntu does not allow seem to allow spaces in app names for the dock, and I seemed to have overlooked that.

**Comment by ronjouch** [comment]
> @ronjouch Ah, that is not intentional, could you open a new issue for this? I wanted to sanitize app names as ubuntu does not allow seem to allow spaces in app names for the dock, and I seemed to have overlooked that.

Sure, done: https://github.com/jiahaog/nativefier/issues/103

**Comment by ronjouch** [comment]
@jiahaog you're probably already aware of it, but I saw [Electron v0.36.6](https://github.com/atom/electron/releases/tag/v0.36.6) just learned a new trick that might help your OSX icon code:

> - Add app.dock.setIcon API.
