### ISSUE TITLE
Nativefier not found

### ISSUE THREAD

**Issue by Mydoge** [jiahaog/nativefier#810]
I tried to run nativefier today and my windows said not found. Anyone know why this is happening and how I can fix this?
![nf](https://user-images.githubusercontent.com/18246474/58739761-04e90500-83da-11e9-8858-d9e6ac25e1dc.png)

**Comment by mxdpeep** [comment]
1) install yarn for Windows and clink for Windows
2) run clink as Administrator and run:

`yarn global add nativefier`
