### ISSUE TITLE
[Feature Request] make app for other os

### ISSUE THREAD

**Issue by tddschn** [jiahaog/nativefier#811]
### Description

Nativefier works perfectly on macOS. 

but it would be even better if I can use it to make apps for other platforms by specifying the specs of the OS Nativefier needed. is that possible?

thank you for making such an amazing app!

**Comment by ryan-ccn** [comment]
You can overwrite the default OS by specifying `--platform [platform]` in the Nativefier CLI. For example:
```bash
$ nativefier "https://mail.google.com/mail/u/0/#inbox" --platform windows
```
Will create a Gmail app for Windows.
Or:
```bash
$ nativefier "https://mail.google.com/mail/u/0/#inbox" --platform linux
```
Will create a Gmail app for Linux.

Reference [here](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#platform) for more info.

**Comment by tddschn** [comment]
thank u! very helpful :)
