### ISSUE TITLE
Turn Off Pop up Blocker in nativefier

### ISSUE THREAD

**Issue by shenal303** [jiahaog/nativefier#814]
the guest page will be allowed to open new windows. Popups are disabled by default I guess.. how can I allow pop-ups on the site?

**Comment by k1ck3r** [comment]
that's some deep thinking out there... and i think you are missing the main idea/purpose of the tool.

said with two word - you can't allow such behavior, in the web, because ... it'll bypass whole framework, and this is kinda 'escaping kernel's reserved blocks for app/virtual process ;)

**Comment by mxdpeep** [comment]
Electron build apps can open a new browser Window outside the current app, the same way like Google OAuth for Installed Apps does (I have verified that just now).

**Comment by ronjouch** [comment]
They do work. Provide the information requested by the issue template if you want more help.
