### ISSUE TITLE
Google Sign-in + Yubikey

### ISSUE THREAD

**Issue by enck** [jiahaog/nativefier#815]
### Description

The Google Sign-in with 2FA does not support hardware tokens such as the Yubikey. An error message appears for trying to log in another way. The 2FA authenticator app or SMS method can still be used; however, the hardware token is more secure and more convenient.

### Steps to reproduce issue

1) nativefier --name "Google Calendar" https://calendar.google.com
2) ./google-calendar-linux-x64/google-calendar
3) Sign in to account that uses a Yubikey for 2FA

### Details

- Are you nativefying a *public* website?
Yes

- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
Feature request. Does not exist.

- Full nativefier command used to build your app: `nativefier --name "Google Calendar" https://calendar.google.com`
- Version of Nativefier (run `nativefier --version`): `v7.6.12`
- Version of node.js (run `node --version`): `v10.15.3`
- OS: `Fedora 30`
- Error message / stack trace (if any):
N/A

**Comment by jolan** [comment]
nativefier defaults to electron 3.1.7 which doesn't include this functionality.  Specifying a newer version of electron will work.

```bash
--electron-version 5.0.4
```

**Comment by enck** [comment]
That worked. Thanks!
