### ISSUE TITLE
Min/Max width/height

### ISSUE THREAD

**Issue by kylehayes** [jiahaog/nativefier#82]
I would like to be able to specify a minimum or maximum width/height the application may be expanded to.

**Comment by jiahaog** [comment]
Hi, I don't have any plans for this. What would be the use case for such a feature?

**Comment by AdrianoCahete** [comment]
For me, is i need to run a system for some clients who can't update IE (alreadty using older IE's) or install new browsers, so i'll use nativifier to generate the "client".

I need to set **min** width/height to be sure that will run with the expected layout.

Probably kyle has the same problem.

**Comment by jiahaog** [comment]
@AdrianoCahete Oh, are you saying that you wish to prevent users from resizing the window till it messes up the layout?

**Comment by peter-mw** [comment]
@jiahaog support of fixed size windows would be awesome

**Comment by AdrianoCahete** [comment]
@jiahaog Yes! The system I work is limited to min 1024x768... :(

**Comment by miduga** [comment]
I'm up to this. I would say that preventing users to minimize the browser window is important to first, keep the sense that the app is native, and second avoid user to mess the layout. According to electron documentation is only a browserWindow option (minWidth, minHeight, maxWidth, maxHeight...).

**Comment by Saganic** [comment]
Would be good if you could imitate the minimum window width found in Google Chrome, as well as that, we can specify media queries in our css for different screen sizes. 

This application is fantastic for lightweight front ends for web apps. Please continue to develop it. Great work.

**Comment by lifeluvr** [comment]
Sounds like you need an .ini file!
That is the sole purpose of .ini files! 
ini is an abreviation for _initialization file_
Could an .ini file be generated upon closing? Or written by hand and placed in the same folder as the executable? I do know you lose whatever preferences they were saving when you delete them... It's a terrible cycle to keep deleting weird .ini files and making new ones every time you get your favorite program set up! Like doing work to get rid of them and then getting pissed when they keep coming back! That's probably why they're typically a hidden file.  

Definition:
An .INI file is a type of file that contains configuration information in a simple, predefined format. It is used by Windows OSs and Windows-based applications to store information about the user's preferences and operating environment. These files are plain text files with a basic structure comprised of properties and sections.

<8^)

**Comment by stewhouston** [comment]
Not sure if this issue has any momentum, but I am building an application that is going to be used by gamers/the gaming community, who more often than not are using 24" monitors at 1920x1080. My app's design is responsive, but its utility becomes increasingly limited as the window size is reduced. It would be nice to be able to set specific/preferred dimensions for the app when it is launched.
