### ISSUE TITLE
How to add a splash screen?

### ISSUE THREAD

**Issue by sailnationcove** [jiahaog/nativefier#821]
### Description

Hello! I am new to Nativefier and I am wondering how can I add a splash screen when the app is loading. I have seen it with electron and I tried the steps but it's not working with nativefier. Does anyone knows how? 

thank you!

**Comment by GabrielTheCoder** [comment]
bump for interest

**Comment by gitfib** [comment]
[electron-splashscreen](https://github.com/trodi/electron-splashscreen) looks like a good place to start

**Comment by ronjouch** [comment]
Hi. Sorry, but not interested into that. Nativefiers aims at being lean & mean, a splash screen seems like clutter.

**Comment by LarsSab** [comment]
I would also prefer a splashscreen - for the beginning a simple local html file or image would be enough

**Comment by MelodicCrypter** [comment]
I also agree, can just add as a property when building the app like --splash or --intro

can be logo_video(mp4), as long as below < 20kb or 30kb in size, tiny videos are nice so that animations are compressed and already processed.
