### ISSUE TITLE
.app to .IPA for iOS phones and tablets?

### ISSUE THREAD

**Issue by Alex-Goaga** [jiahaog/nativefier#824]
### Description
It's possible to create .IPA files using nativefier? (for iOS phones and tablets?). I can't seem to find any information about this. I've tested it on Windows, Linux and MacOS and works like a charm. 

I've tried to use an old method found manual trick to convert iPhone apps to IPA files (.app to .ipa) but task failed successfully :)  

More info: I don't have an iOS device (i do own a Mini Mac) so testing new things is difficult and it will take time for a test.

### Details

- Are you nativefying a *public* website? Yes, if is necessary i can type it
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? I don't know for sure

**Comment by ronjouch** [comment]
Nope.
