### ISSUE TITLE
Not working with HubSpot

### ISSUE THREAD

**Issue by robertmylne** [jiahaog/nativefier#829]
Nativefier does not work with `HubSpot`, it always says `login error check browser`. But when I create a new electron project and do `mainWindow.loadURL("https://app.hubspot.com")` it works just fine. What setting in nativefier is causing the login to fail? Can I remove all restrictions by default?

**Comment by gitfib** [comment]
Most likely the Electron version. Use --electron-version or -e to set a newer version

**Comment by mxdpeep** [comment]
> Nativefier does not work with `HubSpot`, it always says `login error check browser`. But when I create a new electron project and do `mainWindow.loadURL("https://app.hubspot.com")` it works just fine. What setting in nativefier is causing the login to fail? Can I remove all restrictions by default?

use `--electron-version 6.0.3`

**Comment by robertmylne** [comment]
Thanks guys, that worked :)

**Comment by mxdpeep** [comment]
> Thanks guys, that worked :)

plz close the issue then :)

**Comment by ronjouch** [comment]
Thanks for the help, mxdpeep. Electron 5 is the default now, and will be bumped to 6 or 7 soon.
