### ISSUE TITLE
Creating easily distributable applications [feature-request]

### ISSUE THREAD

**Issue by dtmunir** [jiahaog/nativefier#83]
I write a web-app that is used by doctors. Some of the older doctors I work with have low computer literacy and even basic concepts like browsers and address bars can sometimes be challenging for them. I try to mitigate some of that by creating shortcuts to our app url on their desktop that open up in a browser. However that's something that our users will often still get mixed up on, if for instance they have something else already open in their browser (like their webmail client).

Nativefier and Electron look like they could really solve this problem. What would be amazing is if there was a way ship / distribute these as packaged applications. I'm imagining an experience where the next time a doctor logs on, if I could use some kind of feature detection or browser-agent detection, and if they are not using my app inside a native container, I can show a link that lets them download and run something that installs the native container with my app that I've created for their OS version. Having some way of making these apps deployable / distributable would go a long way in enabling that scenario.

**Comment by jacobsmith** [comment]
You should be able to distribute these like any other application -- I believe that Electron is self-contained in terms of dependencies for someone to run. I'm not 100% sure of the User Agent that is used for the default case, but I do know you can set it with `--user-agent USER_AGENT_HERE`, so you could always send out an executable that was created with `--user-agent Electron_Wrapped_Site` (or something of the sort) and then optionally display a message on your website based off of the User Agent string used in the request.

**Comment by BugiDev** [comment]
Hi @dtmunir, although what @jacobsmith said is true ("I believe that Electron is self-contained in terms of dependencies for someone to run") you are probably referring to creating an installation files/wizard so you can help your users easily install it on their machine. What I do is, I use https://github.com/LinusU/node-appdmg for creating MacOS dmg installation and http://www.jrsoftware.org/isdl.php for Windows installation (just be careful, when creating install wizard for Win, in the install script, change install path of the folders, or they are going to be installed on the root path). You can also easily write scripts that will do all the work automatically, creating the app and then the install wizards. Hope this helps you.

**Comment by jiahaog** [comment]
@dtmunir Are you referring to a way to create an installer `.exe` or `.dmg` for the target page instead of the current app which is already in an 'installed' form? This was actually brought up somewhere and it would be cool to use https://github.com/loopline-systems/electron-builder to create the installers as an alternative.
