### ISSUE TITLE
nativefier about install ActiveX

### ISSUE THREAD

**Issue by llgray** [jiahaog/nativefier#830]
### Description

<Detail your problem here as clearly and concisely as possible 🙂. Help us help you by saying why and giving some context!>

### Details

- Are you nativefying a *public* website?
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
- Version of node.js (run `node --version`): `v0.0.0`
- OS: `<OS here>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```
er,maybe there is no error  or i can't find it , what i want to ask actually is 'is the nativefier support ie ActiveX plugin?' thanks 🙂🙂🙂🙂🙂🙂🙂

**Comment by mxdpeep** [comment]
nativefier uses Chromium inside Electron framework

ActiveX is a software framework created by Microsoft that adapts its earlier Component Object Model (COM) and Object Linking and Embedding (OLE) technologies for content downloaded from a network

it's apples and oranges! <3

**Comment by llgray** [comment]
> nativefier uses Chromium inside Electron framework
> 
> ActiveX is a software framework created by Microsoft that adapts its earlier Component Object Model (COM) and Object Linking and Embedding (OLE) technologies for content downloaded from a network
> 
> it's apples and oranges! <3

fine,i just a novice to use this tool and i have solved the problem by other way thanks :)
