### ISSUE TITLE
Pop!_OS / Ubuntu Gnome not allowing favourite pinning

### ISSUE THREAD

**Issue by BobbyByrne** [jiahaog/nativefier#832]
### Description

pinning to favourites in Gnome Ubuntu 19.04 (Pop!_OS actually) is not available when running the executable from inside the generated folder. I then tried creating a .desktop file which points to the exec file, but this opens a separate window and icon in the Gnome favourites dock. Wondering how I can modify the generated application and it's contents so that I correctly uses a .desktop file. 

### Steps to reproduce issue

1. On Ubuntu create google calendar app using nativefier
2. run executable from inside generated folder
3. try to pin to favourites (no option available)
4. create .desktop file where exec=[path/to/executeable]
5. Use Gnome to launch newly created .desktop app
6. Notice application is launching a separate application instead of using the .desktop file created. 

### Details

Are you nativefying a public website? It doesn't matter
Feature request? Have you looked at nativefier --help to see if an existing option could fit your needs? Yes
Full nativefier command used to build your app: `sudo nativefier -n Calendar -p linux --disable-gpu --single-instance https://calendar.google.com /home/[user]/.local/share/
`
Version of Nativefier (run nativefier --version): v7.6.12
Version of node.js (run node --version): v10.16.3
OS: Pop!_OS 19.04 (Ubuntu)

**Comment by BobbyByrne** [comment]
Oh never mind I figured it out. 
The StartupWMClass needs to be set to the same name with Hexidecimal code as what's generated when the app first launches. Here was the tutorial that I found to resolve this issue, for anyone who stumbles onto this with the same problem. 
https://www.leowkahman.com/2018/03/22/running-whatsapp-allo-todoist-onenote-on-ubuntu/

**Comment by ssalbdivad** [comment]
@BobbyByrne Thanks for the info. I spent longer than I'd care to admit trying to figure this out.

I wonder if there is a way to integrate tricky installation steps like this for common platforms.

**Comment by BobbyByrne** [comment]
@ssalbdivad I'm not sure. Depends on what "common platforms" you mean. If it's Linux distros using Gnome, then my guess is the logic could be built out based on best practices of .desktop files etc. But I'm not super familiar with how other distros handle .desktop files. 

For Gnome though, if Nativefier is aware of the to-be-generated .config folder name for the app (or auto run the app and look for the folder name), then the .desktop file could be created in the "~/.local/share/applications" directory (or another appropriate location)

**Comment by ronilaukkarinen** [comment]
FYI if anyone stumbles in to this, you can find out the ID in resources/app/package.json on the "name" field. Then you need to have 'StartupWMClass=` set exactly like it AND `StartupNotify=false`. After this the pinning works.

Example .desktop in /home/$USER/.local/share/applications/thelounge.desktop:

```ini
[Desktop Entry]
Encoding=UTF-8
Version=1.1
Type=Application
Name=The Lounge
GenericName=The Lounge
Comment=Web App
Icon=web-lounge
DBusActivatable=true
X-GNOME-UsesNotifications=true
TryExec=/home/rolle/TheLounge-linux-x64/TheLounge
Exec=/home/rolle/TheLounge-linux-x64/TheLounge
Path=/home/rolle/TheLounge-linux-x64/
Terminal=false
Actions=
MimeType=text/html;text/xml;application/xhtml_xml;
Categories=GTK;Network;         
StartupNotify=false
StartupWMClass=thelounge-nativefier-78b623
```

Confirmed working on Pop!_OS 22.04 LTS.
