### ISSUE TITLE
Soundtrap Google auth doesn't works.

### ISSUE THREAD

**Issue by darltrash** [jiahaog/nativefier#834]
### Soundtrap Google auth doesn't works.
When i try to authenticate with Google, I get an error from the nativefied website

### Steps to reproduce issue
nativefier --name "Soundtrap" "soundtrap.com"
and run the "soundtrap" file in the soundtrap-linux-x64 folder

### Details

- Public website
- Full nativefier command used to build your app: `nativefier --name "Soundtrap" "soundtrap.com"`
- nativefier --version: "v7.6.12"
- node --version: "v11.15.0"
- OS: `Manjaro Deepin (arch linux)`

**Comment by mxdpeep** [comment]
This is not an issue of nativefier or electron itself.
Google bans logins from embedded browser frameworks to prevent MitM phishing.

**Comment by darlex256** [comment]
> This is not an issue of nativefier or electron itself.
> Google bans logins from embedded browser frameworks to prevent MitM phishing.

Should i put the "wontfix" label?

**Comment by ronjouch** [comment]
See workarounds at https://github.com/jiahaog/nativefier/issues/831
