### ISSUE TITLE
Changing files

### ISSUE THREAD

**Issue by yunylas** [jiahaog/nativefier#836]
### Description

I wonder if it's possible to change the website's HTML and many more stuff. If it's possible, i'd like to know how because I really want to edit a lot of files.
### Details

- Are you nativefying a *public* website? Yup.
- OS: `Windows 10`

**Comment by mxdpeep** [comment]
So you want to hijack a website by injecting your own code? Did you read the API docs?

https://github.com/jiahaog/nativefier/blob/master/docs/api.md

`nativefier http://google.com --inject ./some-js-injection.js --inject ./some-css-injection.css ~/Desktop`

**Comment by yunylas** [comment]
> So you want to hijack a website by injecting your own code? Did you read the API docs?
> 
> https://github.com/jiahaog/nativefier/blob/master/docs/api.md
> 
> `nativefier http://google.com --inject ./some-js-injection.js --inject ./some-css-injection.css ~/Desktop`

What about editing the HTML?

**Comment by yunylas** [comment]
Guuuys I want to edit the html :(

**Comment by yunylas** [comment]
...............

**Comment by mxdpeep** [comment]
> > So you want to hijack a website by injecting your own code? Did you read the API docs?
> > https://github.com/jiahaog/nativefier/blob/master/docs/api.md
> > `nativefier http://google.com --inject ./some-js-injection.js --inject ./some-css-injection.css ~/Desktop`
> 
> What about editing the HTML?

you get the concept, that the site HTML is downloaded every time you run the app?
if you need to edit the HTML, you must do it through the JavaScript injection AFTER it is downloaded from the internet

**Comment by ronjouch** [comment]
What mxdpeep said: you can do what you're asking for, with JS. Read about JS and use JS injection.
