### ISSUE TITLE
Menubar not working correctly

### ISSUE THREAD

**Issue by Ale-Zan** [jiahaog/nativefier#838]
Hello,
After turning one of our Webpages into an App we have run into a rather persistent problem with the menubar of the new app.

### Description
In the menubar of the app we have the persistent issue that the different menu items do not work at all, they always open the same no matter which Menu-Icon we click. We have items like 'Activity', 'Contacts', 'Archive' and more, but no matter what we click on, it opens the 'Archive' every time. 

Oddly enough, when we right click on the icon an select 'open in new window' everything works fine.  When we resize the app window to make it smaller, the menu changes to a dropdown, similar to the mobile view of a normal webpage. The menu-items in the dropdown menu work fine, no troubles here at all. We only have the problem when the app is openened in the 'normal' view with the menubar on top.

We have checked the CSS and other files, to make sure that there are no overlapping fields, but there are no issues here. The links and all the files involved in opening the other sites are always the same, so this shouldn't be the issue either. It's quite puzzling.

We also tried different versions of Node.js to create the app, both 10.16.3 LTS and 12.9.0, but the issue appears every time, so we can rule that out as well.

### Details

- we nativefy our own webpage which allows us access to our cloud created with nextcloud
- Version of Nativefier: `v7.7.0`
- Version of node.js: `v10.16.3`
- OS: `MS Windows 10 PRO`

**Comment by mxdpeep** [comment]
how do you populate the menu? it looks to me, that no nativefier menu functionality is working...

**Comment by ronjouch** [comment]
This looks like a bug report for IBM Verse, which is based on Nativefier. Please contact IBM support.
