### ISSUE TITLE
How would I add chrome extensions?

### ISSUE THREAD

**Issue by jottr** [jiahaog/nativefier#84]
I.e. this would allow to create a [Signal Desktop](https://github.com/WhisperSystems/Signal-Desktop) App.

**Comment by jottr** [comment]
Seems to be impossible for now, due to electron limitations.
https://github.com/atom/electron/issues/1498

**Comment by Shaked** [comment]
Hey @jottr, I think that they have solved the problem\will solve it in the next version. Have you seen the last comment in the thread you have posted?

**Comment by jottr** [comment]
@Shaked Not sure which comment you mean. Is it [this](https://github.com/electron/electron/issues/1498#issuecomment-254401080) one?

**Comment by Shaked** [comment]
@jottr - I think I was looking into another issue but unfortunately probably misread it. 

Thanks and sorry for wasting your time.
