### ISSUE TITLE
--disable-dev-tools disables keyboard shortcut, but devtools still accessible from View menu

### ISSUE THREAD

**Issue by modermo** [jiahaog/nativefier#842]
### Description

`--disable-dev-tools` doesn't seem to be working. The menu bar still shows the ability to toggle it on and off

### Steps to reproduce issue

When creating an app, use `--disable-dev-tools` as an option

### Details

- Are you nativefying a *public* website?

Yes. This is just a basic website.

**Comment by mxdpeep** [comment]
confirmed

**Comment by mxdpeep** [comment]
it seems to me, that the app build on Windows does use the original electron menu and not the nativefier menu at all

**Comment by mxdpeep** [comment]
I have found a solution > https://electronjs.org/docs/api/browser-window#winremovemenu-linux-windows

I was able to fix the app's main code so that there's no menu at all (using docker builder).

**Comment by modermo** [comment]
So I have to install using docker to make this work?

**Comment by mxdpeep** [comment]
> So I have to install using docker to make this work?

I have just fetched the repo, build docker, added the line to remove the menu altogether
no menus = no DevTools either

https://github.com/jiahaog/nativefier/compare/master...mxdpeep:nomenus

**Comment by partynikko** [comment]
Nativefier accepts the `browserWindowOptions` argument, which means you can dig deeper into customization of the instance.

This partially solves it as the dev tools will not be opened. However, the menu entry is still there.
```json
"browserwindowOptions": {
  "webPreferences": {
    "devTools": false,
  }
}
```

See here:
https://electronjs.org/docs/api/browser-window#new-browserwindowoptions

**Comment by mxdpeep** [comment]
> Nativefier accepts the `browserWindowOptions` argument, which means you can dig deeper into customization of the instance.
> 
> This partially solves it as the dev tools will not be opened. However, the menu entry is still there.
> 
> ```json
> "browserwindowOptions": {
>   "webPreferences": {
>     "devTools": false,
>   }
> }
> ```
> 
> See here:
> https://electronjs.org/docs/api/browser-window#new-browserwindowoptions

I am satisfied with NO menu at all, web apps do not need Chrome menu

**Comment by jmalarcon** [comment]
If you use the shortcut `CTRL/CMD+SHIFT+I` it still opens though 😞 

I've tried to overwrite the global shortcut with the `disable-dev-tools` to no avail.

I've read [this](https://discuss.atom.io/t/a-way-to-prevent-developer-tools/29746/6) or [maybe this](https://discuss.atom.io/t/a-way-to-prevent-developer-tools/29746/11) as a possible solution.

That would be a great thing to have!

Thanks.

**Comment by zulfirman** [comment]
If u want to disable developer tools read this : https://codemyway.com/disable-to-open-inspect-element-in-javascript-and-html/

and if u want to disable menu by pressing alt use :

	$(document).on('keydown', function (e) {
			if (e.key === 'Alt') {
				e.preventDefault();
			}
		});
