### ISSUE TITLE
Application "damaged or incomplete"

### ISSUE THREAD

**Issue by chris-79** [jiahaog/nativefier#85]
Getting this error when trying to run the app:

![error message](https://i.imgur.com/hAY2Ed2.png)

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50

$ node -v
v5.5.0

$ nativefier -V
6.6.1

$ nativefier --app-name "Music" --icon "Play-Music.icns" "https://play.google.com/music/listen"
Packaging app for platform darwin x64 using electron v0.36.4
App built to /Volumes/RAMDisk/Music-darwin-x64
```

Any ideas?

**Comment by jiahaog** [comment]
Hi there, I can't seem to replicate this problem. Could you try leaving out the `--icon` flag and see if the error persists?

**Comment by chris-79** [comment]
No luck. Even just a plain…

```bash
$ nativefier "https://play.google.com/music/listen"
```

…fails to make a working app :(

I tried uninstalling/reinstalling node, but to no avail. Any other ideas?

**Comment by gesquive** [comment]
I can verify that this occurs for me too.

I have one more piece of information, I created my apps in os x yosemite (10.10.4) and they worked without problem.

I just upgraded to 10.11.3 today and the exact same applications that worked under 10.10.4 give me the "damaged or incomplete" message under 10.11.3. I tried recreating all of my apps and all of them just give the same message now.

**Comment by gesquive** [comment]
I retract my previous comment.

It turns out the app was actually corrupted. In case it helps anyone:

I was reusing the same commands to build with nativefier and then rsync the package to `~/Applications`. Turns out there was slight error in my rsync command so I was actually rsyncing one level deeper then I thought to `~/Applications/app_name.app/app_name.app`. Apparently OS X 10.10 did not care about the extra directory, but 10.11 does.

**Comment by jiahaog** [comment]
I'm not really sure how to replicate this, as it's not happening on my end. Any ideas?

**Comment by chris-79** [comment]
For me, at least, I now think it might be an issue related to trying to create apps on a [RAM drive/disk](http://apple.wikia.com/wiki/RAM_disk#Creating_a_RAM_disk). Not a huge deal anymore, I guess.

**Comment by gesquive** [comment]
Seems like it wasn't nativefiers fault in either case.
