### ISSUE TITLE
Verse doesn't open emails in Full Screen (Mac)

### ISSUE THREAD

**Issue by Pasoka** [jiahaog/nativefier#858]
![Screenshot 2019-10-01 at 12 11 44](https://user-images.githubusercontent.com/9061577/65953694-cd9c6a80-e444-11e9-9af5-2c4228c93137.png)

**Comment by ronjouch** [comment]
@Pasoka hi, this is the support for Nativefier, not IBM Verse. Please talk to IBM folks for Verse support.
