### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type text/csv

### ISSUE THREAD

**Issue by trgcyln** [jiahaog/nativefier#859]
- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- OS: `Windows 10`
- Error message / stack trace (if any):
Resource interpreted as Document but transferred with MIME type text/csv: "https://www.example.com/wp-admin/admin-ajax.php?action=export_appointments".

I'm trying to export csv file using php script. In chrome browser (or any), it works. It prompts download dialogue and able to save it.

When I natified the website, I can't able to do it.
It gived me a warning like this: "Resource interpreted as Document but transferred with MIME type text/csv:" and there is no download dialogue.

Is there a way to fix this ?

**Comment by ronjouch** [comment]
@trgcyln thanks for the feedback.

1. Can you provide a reproduction scenario on a public website?
2. Is this still reproducible in the latest nativefier?
3. Please provide the information requested by the issue template.
