### ISSUE TITLE
Show Menu Bar Not Working On Windows Build

### ISSUE THREAD

**Issue by StuffBySpencer** [jiahaog/nativefier#86]
The menu bar shows up in the app, regardless if I use `--show-menu-bar` or not.

Adding `"showMenuBar": false` to *app/nativefier.json* doesn't make any changes either.

**Nativefier Version** - *6.5.6*
**Node.js Version** - *4.2.6*
I'm running **Windows 7 64-bit**, and building for it as well.

**Comment by technopagan** [comment]
+1 for this on Windows 10. "showMenuBar" has no effect.

**Comment by StuffBySpencer** [comment]
@technopagan I don't know if you know this, but the workaround I'm using until this gets fixed is as follows:

Goto `app/src/main.js` and delete all references to *menu* (there're a few different ones that need to be removed, just briefly read through it and delete things that refer to *menu*).

As I said, it's a workaround / hack, but this is fine in the meantime until it gets fixed.

**Comment by jiahaog** [comment]
Hi, sorry for the late reply, I was busy with school and working on another feature. Could you please try again with the latest version of nativefier (v6.8.0)? I've tried but I can't seem to replicate the issue.

**Comment by StuffBySpencer** [comment]
The latest version fixes it, thanks and great wrok! :)
