### ISSUE TITLE
Fail to add new websites as apps on desktop

### ISSUE THREAD

**Issue by loryhndol** [jiahaog/nativefier#861]
### I have tried the following websites, but failed. 

- www.csdn.net

- www.500px.com

- www.github.com

- www.baidu.com

When the program runs ` packaging [==============================                    ] 60%Packaging app for platform win32 x64 using electron v5.0.10`， it suddenly stops and return to default.

and I would like to know what other websites are available to be added by using the _nativefier_ method.

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? No
- Full nativefier command used to build your app: `<command here>`
- Version of Nativefier (run `nativefier --version`): `v7.7.0`
- Version of node.js (run `node --version`): `v12.11.1-x64`
- OS: `<Window 10>`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
Hi. Is this still an issue with the latest version? Please fill the information requested by the [bug report template](https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and use the `--verbose` to be able to provide useful logs.

Closing, do come back with more info if the problem persists.
