### ISSUE TITLE
Installation & Usage Without NPM

### ISSUE THREAD

**Issue by ForgivenNin** [jiahaog/nativefier#863]
### Description

Is there any way to install and use `nativefier` without using `npm`?

I saw the `gh-pages` branch for the code, and it appears to be the same code as the repo...
Is there a reason why it hasn't been added in the website bar next to the repo description?

**Comment by ForgivenNin** [comment]
I just saw the `gh-pages` branch for the code, and it appears to be the same code as the repo...
Is there a reason why it hasn't been added in the website bar next to the repo description?

**Comment by ronjouch** [comment]
Nope, use npm. Some linux distros provide user-built recipes, e.g. [Arch User Repository / Nativefier](https://aur.archlinux.org/packages/nodejs-nativefier/).
