### ISSUE TITLE
No go back key

### ISSUE THREAD

**Issue by 100101001** [jiahaog/nativefier#864]
### Description

I use nativefier to nativefier a website app like github, but it bothers me a lot as i cannot go back if i click a hyperlink to a new place. I'm a new user of the app, so can anyone give some ideas on how to go back in the netivefiered app like we do in the browser?

### Steps to reproduce issue
1、on windows , open cmd and enter nativefier github --https://github.com
2、open the github app, and u can find no goback key to use
 

### Details

- Are you nativefying a *public* website? YES
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? YES
- Full nativefier command used to build your app: `nativefier github --https://github.com`
- Version of Nativefier (run `nativefier --version`): `v7.7.0`
- Version of node.js (run `node --version`): `v10.16.3`
- OS: `windows`
- Error message / stack trace (if any): none

```
<Error message / Stack trace here>
```

**Comment by puremana** [comment]
You should be able to press `alt` to open the menu and under View be able to go back or forward, however this is not showing up currently. Not too sure what is going on as the code clearly defines back and forward functions in both `app/src/components/menu/menu.js` and `app/src/components/mainWindow/mainWindow.js`

**Comment by ronjouch** [comment]
Hi and thanks for the feedback. I cannot reproduce the issue though, for me the the Alt menu works, the Back/Forward actions it contain work, and the keyboard shortcuts work.
