### ISSUE TITLE
Is there a way to login into a Google App using SSO?

### ISSUE THREAD

**Issue by pauljfx** [jiahaog/nativefier#865]
Hey All!

I just discovered Nativefier and it is amazing! I was able to use Evernote on Linux with it and so far it is much better than in browser! Yay!

Though I am struggling to use Google apps like calendar or Gmail: In order to do so I need to login using Single Sign On (SSO) - basically what it means - google redirects me to my company's login screen where I enter my credentials and then redirects back to Google.

The problem is when I am using Nativefier the SSO login screen is being opened in a Chrome, as opposed to in my generated app. So Once I login in browser - I am good but I am logged in in browser, while the generated app shows google login screen in awaiting state.

Does anyone has any suggestions? 
Thanks!

**Comment by jasonfma** [comment]
Check out the `--internal-urls` option
https://github.com/jiahaog/nativefier/blob/master/docs/api.md#internal-urls

**Comment by rjhilgefort** [comment]
I tried this using the `--internal-urls` options and it still says "couldn't sign you in". Has anyone else gotten Google Calendar to work?

![image](https://user-images.githubusercontent.com/2034823/72207549-73557180-3457-11ea-9aee-8a1b9718fcfc.png)

**Comment by danielgwilson** [comment]
> I tried this using the `--internal-urls` options and it still says "couldn't sign you in". Has anyone else gotten Google Calendar to work?
> 
> ![image](https://user-images.githubusercontent.com/2034823/72207549-73557180-3457-11ea-9aee-8a1b9718fcfc.png)

Check out #831

**Comment by mclamb** [comment]
Only way I found around this right now is to use an alternate User Agent string that specifies Windows and no Chrome at all, e.g.:

`-u "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/73.0"`

If the string has "Chrome" in it it will work but it will use the old HTML-only version of Gmail. If it has version information, e.g. "Chrome/80.x.y" then it will give the above error.

**Comment by jamesdo** [comment]
@mclamb this worked for me. Thank you so much.

**Comment by mclamb** [comment]
No problem. Next up is to figure out how to get links to open in Gmail.app without having to context-click open link. Direct-clicking doesn't work, regardless of my `--internal-urls` settings.

**Comment by ronjouch** [comment]
Thanks @mclamb . Closing, letting discussion go on at https://github.com/jiahaog/nativefier/issues/831 .
