### ISSUE TITLE
Website top cut off in v7.7.0

### ISSUE THREAD

**Issue by jackHedaya** [jiahaog/nativefier#867]
### Description

Scrolling to the top of the page stops before the entire frame is visible.

![Screen Shot 2019-10-16 at 4 49 31 PM](https://user-images.githubusercontent.com/20172754/66957946-2e2aca80-f035-11e9-8257-57b4b580cbc7.png)

### Details

- Are you nativefying a *public* website? Yes: github.com
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? No
- Full nativefier command used to build your app: `nativefier github.com --name Github --darwin-dark-mode-support`
- Version of Nativefier (run `nativefier --version`): `v7.7.0`
- Version of node.js (run `node --version`): `v12.10.0`
- OS: `macOS Catalina`

**Comment by J0HAN85** [comment]
Same issues here. You can solve it by using another Electron version.
For me version I added this parameter: `--electron-version "5.0.11"`

**Comment by ronjouch** [comment]
Nativefier 7.7.1 ships with Electron 5.x by default, if Johan is right you should be okay
