### ISSUE TITLE
--browserwindow-options does not seem to work

### ISSUE THREAD

**Issue by akkhilaysh** [jiahaog/nativefier#870]
### Steps to reproduce the issue

I tried these commands:
$ nativefier "www.medium.com" --browserwindow-options '{"kiosk" : "true"}'
$ nativefier "www.medium.com" --browserwindow-options '{"closable" : "false"}'

The resulting application does not open in Kiosk mode and no Browser window options seem to apply. 

My goal is to generate an application that has these browser window options associated with it:
    kiosk: true,
    alwaysOnTop: true,
    closable: false,
    resizable: false,
    movable: false,
    minimizable: false,
    frame: false,
    fullscreen: true,

To test, I ran the electron-quick-start and added these options into BrowserWindow() in main.js and it all worked.

Is there a way for me to edit the method BrowserWindow() in a file(main.js) and apply changes after Nativefier generates the app? Just so that I don't have to rely on the command line arguments. If I edit main.js in the Nativefier package, how do I save the changes?

### Details

- Are you nativefying a *public* website? YES
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `nativefier "www.medium.com" --browserwindow-options '{"kiosk" : "true"}'`
- Version of Nativefier (run `nativefier --version`): `v7.7.0`
- Version of node.js (run `node --version`): `v8.11.4`
- OS: `Windows' using Git Bash
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by ronjouch** [comment]
@akkhilaysh thanks for the report. This appears fixed in 8.x, I tried `--browserwindow-options '{ "alwaysOnTop": true, "kiosk": true }'` in 8.0.4 and it behaves as expected. Closing, feel free to come back with more debug info if I'm missing something.
