### ISSUE TITLE
getaddrinfo ENOTFOUND downloading electron

### ISSUE THREAD

**Issue by farzeni** [jiahaog/nativefier#871]
### Description
Hello,

Launching natifier bin I get a ENOTFOUNT during electron download phase

```
$ nativefier -p linux -a x64 --name Testapp https://google.com
Downloading tmp-3817-0-electron-v5.0.10-linux-x64.zip
Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
{ Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'github-production-release-asset-2e65be.s3.amazonaws.com',
  host: 'github-production-release-asset-2e65be.s3.amazonaws.com',
  port: 443 }
  packaging [========================================          ] 79%
```

My current connection is working
```
$ ping amazonaws.com
PING amazonaws.com (207.171.166.22) 56(84) bytes of data.
64 bytes from 166-22.amazon.com (207.171.166.22): icmp_seq=1 ttl=234 time=145 ms
64 bytes from 166-22.amazon.com (207.171.166.22): icmp_seq=2 ttl=234 time=125 ms
```

### Steps to reproduce issue

`
$ nativefier -p linux -a x64 --name Testapp https://google.com
`

### Details

- Are you nativefying a *public* website? Yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? Yes
- Full nativefier command used to build your app: `nativefier -p linux -a x64 --name Testapp https://google.com`
- Version of Nativefier (run `nativefier --version`): `v7.7.0`
- Version of node.js (run `node --version`): `v10.15.2`
- OS: `linux`

Thanks for this project

**Comment by ronjouch** [comment]
Hi @farzeni.. Does that still happen?

**Comment by farzeni** [comment]
No, it doesn't.

It is working correctly, thank you

**Comment by ronjouch** [comment]
@farzeni thanks for the fast feedback.
