### ISSUE TITLE
Open new tab in fullscreen causes crash

### ISSUE THREAD

**Issue by jasonfma** [jiahaog/nativefier#874]
### Description
Was testing https://github.com/jiahaog/nativefier/pull/767#issuecomment-523232944 and wanted to see if it was related to the PR. 

### Steps to reproduce issue
1) Open nativefied app and make it full screen
2) Right click a link in that app
4) Choose "Open Link in New Tab"

See crash.

### Details

- Are you nativefying a *public* website? yes
- Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs? yes
- Full nativefier command used to build your app: `nativefier https://github.com --name Github` 
- Version of Nativefier (run `nativefier --version`): `v7.7.0`
- Version of node.js (run `node --version`): `v10.16.3`
- OS: `macOS`
- Error message / stack trace (if any):

```
<Error message / Stack trace here>
```

**Comment by voltechs** [comment]
I cannot reproduce this.
```
nativefier --version: 7.7.0
node --version: v13.2.0
OS: macOS 10.14.6
```

Can you retry with a newer version of node?

**Comment by jasonfma** [comment]
Just tested a more recent app I nativified and it works! Using node 14.
