### ISSUE TITLE
Display verbose download information during electron-packager work

### ISSUE THREAD

**Issue by ghostry** [jiahaog/nativefier#881]
Downloading tmp-1-0-electron-v5.0.10-linux-x64.zip too slow and it will fail,

If the URL is displayed, we can use the download tool

**Comment by ronjouch** [comment]
@ghostry fixed with the `--verbose` flag in https://github.com/jiahaog/nativefier/pull/898 soon-to-be-released, please give it a try if you have the time 🙂. See instructions at https://github.com/jiahaog/nativefier/pull/898#issuecomment-581062794 .
