### ISSUE TITLE
Does not work with my subdomain

### ISSUE THREAD

**Issue by KimTranjan** [jiahaog/nativefier#89]
I tried to use nativefier with a subdomain, but it hangs on this message:
"Packaging app for platform win32 x64 using electron v0.36.4"

There's something strange, because it only occurs with my website. For example, it does work with http://webpic.com.br, http://mail.google.com and http://login.yahoo.com, but doesn't with http://virgo.webpic.com.br.

**Nativefier version:** 6.6.1
**Node version:** 0.12.0
**Command line:** nativefier "http://virgo.webpic.com.br"
**OS:** Windows 8 and Windows 10

**Comment by yishn** [comment]
Seems this also happens on sites without subdomains, related to #87. `http://digg.com/reader` doesn't work for me.

**Comment by KimTranjan** [comment]
Oh well... I thought it was a problem with subdomains.  :|
