### ISSUE TITLE
External links open in a non-default browser

### ISSUE THREAD

**Issue by LWFlouisa** [jiahaog/nativefier#893]
Whenever I open a webpage in external browser, it doesn't choose the default browser I assign, but rather chooses its own default browser.

Right click on open in external browser. The external browser it opens is a default that you haven't set. I set TOR as my default browser, yet defaults to some other browser besides TOR: Vivaldi, Opera, Chrome, Waterfox, even Falkon.

But it doesn't open the default I assigned.

- The nativefier website I natified is an public site, but it happens on any site I natify.

**Comment by ronjouch** [comment]
@LWFlouisa please provide the information requested by the issue template.

**Comment by LWFlouisa** [comment]
Can you please show me the issue template? It's not even showing up when I try to make an issue. Otherwise I cannot help.

**Comment by ronjouch** [comment]
> Can you please show me the issue template? It's not even showing up when I try to make an issue. Otherwise I cannot help.

@LWFlouisa sure, here you go: https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by LWFlouisa** [comment]
I'll look over this to see if I still have the issue!
