### ISSUE TITLE
How do I call the standard print function?

### ISSUE THREAD

**Issue by nickbe** [jiahaog/nativefier#894]
After creating a virtual desktop app from a website I can't find any way to print something.
Ctrl-P doesn't work. And there's not menu entry for printing.
Can anyone help me out here?

**Comment by zulfirman** [comment]
Use this plugin, simple and effective..

https://jasonday.github.io/printThis/

**Comment by ronjouch** [comment]
Closing as duplicate of https://github.com/jiahaog/nativefier/issues/504
