### ISSUE TITLE
core-js error when installing nativefier

### ISSUE THREAD

**Issue by onelsonic** [jiahaog/nativefier#895]
I received the following error why trying to install nativefier :
core-js seems to be using an outdated version.

`npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3`

**Comment by ronjouch** [comment]
Yup, known and addressed in a cleanup I'm working on. Please ignore until fixed, thanks 🙂.
