### ISSUE TITLE
macOS 10.15.2 Catalina - nativefier not working

### ISSUE THREAD

**Issue by onelsonic** [jiahaog/nativefier#896]
while nativefier is working perfectly on windows10 I am having trouble to make it work correctly on macOS Catalina.

Nodejs is working fine.

Also nativefier seems to be installed correctly with the outdated version of core-js: 

installation log :

> nativefier % npm install nativefier -g 
> npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> /Users/onelsonic/.npm-global/bin/nativefier -> /Users/onelsonic/.npm-global/lib/node_modules/nativefier/lib/cli.js
> + nativefier@7.7.0
> updated 1 package in 11.878s

then why typing the command nativefier I get : 

`command not found: nativefier`

Anyone use it on a mac??

**Comment by ronjouch** [comment]
`command not found` means `nativefier` is not in your `PATH`. Search how to view and edit your `PATH` for your OS & Shell, and edit it to add `/Users/onelsonic/.npm-global/bin/` to it.

**Comment by onelsonic** [comment]
thank you, I succeed to run it on my mac.
