### ISSUE TITLE
App crash - Linux

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [jiahaog/nativefier#9]
Thanks for the awesome package, it's very useful. I can confirm this also works on Linux. However i do see an issue with it.

When a notification pop up, and you click on the notification. The app crashes. Are there any logs generated for the generated apps?

**Comment by jiahaog** [comment]
Hi, sorry for the late reply. I don't have convenient access to a linux machine, does this problem persist? atom/electron#3910 seems to suggest that it has been fixed.
