### ISSUE TITLE
[macOS] Mission control previews are blank

### ISSUE THREAD

**Issue by isakkeyten** [jiahaog/nativefier#900]
### Description

Title kinda explains everything

### Steps to reproduce issue

Make any app and put it in a separate desktop

Preview thumbnail is blank

![IRHcm8S](https://user-images.githubusercontent.com/18152578/73854446-dce85600-4832-11ea-98c3-a5509131ee6d.png)
> Ex.
> Left is Gmail and Google Calendar
> Right is CodeSandbox

### Details

- Are you nativefying a *public* website? 
-- yes
- ~Feature request? Have you looked at `nativefier --help` to see if an existing option could fit your needs?~
- ~Full nativefier command used to build your app: `<command here>`~
- Version of Nativefier (run `nativefier --version`): `v0.0.0`
-- v7.7.1
- Version of node.js (run `node --version`): `v0.0.0`
-- v12.14.1
- OS: `<OS here>`
-- Macos Catalina 10.15.2
- ~Error message / stack trace (if any):~

**Comment by bacongravy** [comment]
I’ve seen this, too.  I believe it is a bug in electron: https://github.com/electron/electron/issues/19430

**Comment by ronjouch** [comment]
Thanks @bacongravy . Closing.
