### ISSUE TITLE
JavaScript error shown when using electron 7+ and --tray option (every website)

### ISSUE THREAD

**Issue by leinardi** [jiahaog/nativefier#903]
### Description

The API `tray.setHighlightMode(mode)` has been be removed in electron v7.0 without replacement.
This causes the display of an error dialog every time an app is shown/hidden if the parameter `--tray` is used when nativefying. This is completely independent form the website you are nativefying and it happens with all the version of electron after 6.x.

![image](https://user-images.githubusercontent.com/273338/74601155-16268e80-509b-11ea-86e6-8c0b151ccd35.png)

source: https://www.electronjs.org/docs/api/breaking-changes#tray
similar fix: https://github.com/maxogden/menubar/pull/250/files#diff-332a438bdcfb7b2a05a4978d1cc7fce7L101

### Steps to reproduce issue

1. nativefy any webside using an electron-version 7+ and the tray parameter
2. hide or show the app windows

### Details

- Are you nativefying a *public* website? Yes, and the problem happens with **every** website
- Full nativefier command used to build your app: `nativefier --name "Google" --platform linux --arch x64 --electron-version 8.0.1 --tray --single-instance --honest https://www.google.com`
- Version of Nativefier (run `nativefier --version`): `7.7.1`
- Version of node.js (run `node --version`): `v10.15.2`
- OS: `Ubuntu 19.10`
- Error message / stack trace (if any): nothing shown in console, see screenshot above

**Comment by ronjouch** [comment]
Yeah. This is fixed in #898, which will be merged soon. Thanks for the feedback!

**Comment by leinardi** [comment]
Awesome! But please consider merging #904 if a new hotfix for 7.7 will be released.
