### ISSUE TITLE
Navigation pane preferred

### ISSUE THREAD

**Issue by nobody9999** [jiahaog/nativefier#909]
Is it possible to show up a navigation pane with the buttons Home, Left, Right

**Comment by ronjouch** [comment]
Hi @nobody9999 and thanks for the feedback.

No, a navigation pane is not planned. Minimal UI is a *goal* for nativefier; navigation should be done in-app, using the app features. Nativefier's goal is not to re-build a web browser, web browsers are good at that. Its goal is precisely to cut down on browser UI to focus the experience to one app, and let the app do its best at letting the user navigate. Alternatively, you can use keyboard shortcuts.
