### ISSUE TITLE
Add support for mas platform and arm architecture

### ISSUE THREAD

**Issue by citrusui** [jiahaog/nativefier#91]
Seeing as Electron [already provides](https://github.com/atom/electron/releases) mas (Mac App Store) and arm architecture builds for Linux, I see no reason not to implement this into nativefier.

**Comment by jiahaog** [comment]
Hi! Forgive me if I misunderstand you, but it is not planned, as the intention is for you to create apps for your own distribution or to share with friends. It's not really intended for users to put the apps you have created up on the app store.

**Comment by jakerabid** [comment]
Sorry to bump an old closed topic, but why not have armv7l support? I tried hacking it into the nativefier/lib/infer/inferOs.js file and the test passes but it still doesn't work, failing like this:

`jake@devotron:~/repos/nativefier$ nativefier --platform linux --arch armv7l "https://www.youtube.com/tv"
  packaging [==============================                    ] 60%
[Error: Unsupported arch armv7l; must be one of: ia32, x64]
  packaging [========================================          ] 80%jake@devotron:~/repos/nativefier$`

**Comment by Silent-Hunter** [comment]
Please consider ARM support, for Raspberry Pi 3 and Pyra will be able to use Nativefier if you do.
