### ISSUE TITLE
Thanks @jottr for the info.

### ISSUE THREAD

**Issue by nobody9999** [jiahaog/nativefier#910]
Thanks @jottr for the info. 

Yes the shortcuts don't seem to be working in the latest version 6.8.0. However they are working if I build the package locally. You can try that as a workaround.

_Originally posted by @krishkumar in https://github.com/jiahaog/nativefier/issues/121#issuecomment-180218514_

Can u code a toolbar please?

**Comment by ronjouch** [comment]
Hi @nobody9999 and thanks for the feedback.

No, a navigation pane is not planned. Minimal UI is a *goal* for nativefier; navigation should be done in-app, using the app features. Nativefier's goal is not to re-build a web browser, web browsers are good at that. Its goal is precisely to cut down on browser UI to focus the experience to one app, and let the app do its best at letting the user navigate. Alternatively, you can use keyboard shortcuts.
