### ISSUE TITLE
Is there a global exception capture and handling method

### ISSUE THREAD

**Issue by dakuohao** [jiahaog/nativefier#911]
### Description
**My English is not very good, sorry**

某些时候报错，有没有全局异常捕获和处理方式？
Sometimes a mistake is reported，Is there a global exception capture and handling method?
such as:

![image](https://user-images.githubusercontent.com/19989280/75102559-5e5c2880-5628-11ea-9e54-4bc5a01208af.png)

**Comment by ronjouch** [comment]
Hi @dakuohao and thanks for the feedback.

What would you expect when such an error happens?
