### ISSUE TITLE
How to open app on linux after creating it?

### ISSUE THREAD

**Issue by NIXOYE** [jiahaog/nativefier#912]
### Description

I am trying to make the apple music web app into an app to use on Linux (Elementary OS which is very similar to ubuntu)

### Steps to reproduce issue

I ran `nativefier beta.music.apple.com` and it created the folder. inside the folder are many files and folders although one is called AppleMusic but I try to open it it just asks what program to open it with.

![Screenshot from 2020-02-23 11-27-52](https://user-images.githubusercontent.com/12674582/75117552-9adf5280-562f-11ea-9453-55e71b5fffb9.png)

### Details

- Are you nativefying a *public* website? Yes
- Full nativefier command used to build your app: `nativefier https://beta.music.apple.com/`
- Version of Nativefier (run `nativefier --version`): `7.7.1`
- Version of node.js (run `node --version`): `v8.10.0`
- OS: `<Elementary OS 5.1.2>`

**Comment by ronjouch** [comment]
@NIXOYE the binary in the screenshot you shared is the first element listed by your file manager: `AppleMusic`

**Comment by thearkadia** [comment]
@ronjouch I know, i stated “one is called AppleMusic but I try to open it it just asks what program to open it with”

**Comment by ronjouch** [comment]
@NIXOYE hmmm I'm know your file manager does. What happens if you run from a terminal, running `~/AppleMusic-linux-x64/AppleMusic` ?

**Comment by NIXOYE** [comment]
@ronjouch that worked! Is there a way to have it open without the terminal? Should I just make a shortcut file that runs ~/AppleMusic-linux-x64/AppleMusic and add it to my app bar?

I can't login though. When I click Login it opens a window that says `ERROR_INSUFFICIENT_PARAMS`

**Comment by ronjouch** [comment]
> @ronjouch that worked! Is there a way to have it open without the terminal? Should I just make a shortcut file that runs ~/AppleMusic-linux-x64/AppleMusic and add it to my app bar?

@NIXOYE yeah, up to you depending on your preferences and your Desktop Environment 🙂.

> I can't login though. When I click Login it opens a window that says `ERROR_INSUFFICIENT_PARAMS`

Searching existing issues, I see that's https://github.com/jiahaog/nativefier/issues/849 .

**Comment by joshpetit** [comment]
I can only run the app from the terminal. Is there some way to allow it to run directly or is creating a shortcut file the only option?
