### ISSUE TITLE
Problems add an icon to an application on Windows

### ISSUE THREAD

**Issue by MakuSensei** [jiahaog/nativefier#92]
Hi, I have tried in many ways to put an icon for an application and have failed to work.
Nor it is not exactly the right way to place the icon
I tried the following ways
He intentado con la siguientes formas
"D:\Escritorio\icon175x175_48x48.png"
 D:\Escritorio\icon175x175_48x48.png
 "icon175x175_48x48.png"
 icon175x175_48x48.png
none has taken me icon
![captura de pantalla 387](https://cloud.githubusercontent.com/assets/16900914/12584538/b851342c-c426-11e5-8be0-f78df35f3e76.png)

**Comment by zweicoder** [comment]
Try putting it inside `resources/app/lib`

**Comment by MakuSensei** [comment]
@zweicoder thanks :) but as I should?
where I create the resources resources/app/lib

Disculpa mi ingles uso google traductor

**Comment by zweicoder** [comment]
@MakuSensei your icon should be `My Apps/ Google Play Music 6.62/ resources/app/lib/icon.png`

**Comment by MakuSensei** [comment]
@zweicoder thanks :) I try to do.
I set some file? After placing the image in the directory? "/resources/app/lib/icon.png"

**Comment by jiahaog** [comment]
This has been fixed since 5475c6e9685d459509d856f6b4457eeec57ab47a and is released in `v6.7.0`, the `--icon` command line flag should work now.

**Comment by MakuSensei** [comment]
thanks :)

**Comment by gasova** [comment]
This is not working in windows 10 even with imagemagick binaries installed
