### ISSUE TITLE
Zoom: Touchpad / zoom hotkeys not working

### ISSUE THREAD

**Issue by eladnava** [jiahaog/nativefier#921]
**Bug description**
Using the macOS touchpad / `Cmd` + `+` / `Cmd` + `-` doesn't seem to have any affect in latest builds of `nativefier`, including using `ts` branch.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , I'm sure I'm not misunderstanding expected behavior.
- [x] I searched existing open & closed issues. Yes, my bug is new.

**Steps to reproduce**
Give your ***full*** nativefier command, with the ***`--verbose` flag***, on a ***public*** site:
1. Run `nativefier https://soundcloud.com/ -f -i soundcloud.com.icns --name "SoundCloud" --verbose`
2. Open the app
3. Try zooming

**Expected behavior**
Page should zoom in/out

**Actual behavior**
Nothing. No change.

**Logs & screenshots**
N/A

**Context**
 - Nativefier: 7.7.1
 - Node.js: 10.16.3
 - Npm: 6.9.0
 - OS:  macOS 10.13.6
 - Additional context: N/A

Thanks!

**Comment by ronjouch** [comment]
Closing as dup of #379 and adding your context to #379. Thanks.

**Comment by ronjouch** [comment]
@eladnava actually: #379 is about broken zoom using Ctrl + the **numpad** +/- keys. Is it your case too, or are you complaining that zooming using +/- next between 0 and Backspace is broken too?

Also, what is your keyboard language? What happens if you switch it to English?

**Comment by eladnava** [comment]
Hi @ronjouch,
I was reporting an issue where `master` branch `nativefier` zoom hotkeys were broken. Upgrading to `ts` fixed that issue, and I've also been able to get "pinch-to-zoom" working again. 🎉 
https://github.com/jiahaog/nativefier/issues/379#issuecomment-598309817
