### ISSUE TITLE
Args needing a JSON argument are finicky to use with Windows' shell escaping

### ISSUE THREAD

**Issue by Tim-Paik** [jiahaog/nativefier#928]
**I am a student from China. Please forgive me if I have any English mistakes.**
**If you see #569, you can jump straight to **solution**, which I think is exactly the same**

**Bug description**
An error occurs when I add ` --file-download-options '{"saveAs": true}'` according to [This](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#file-download-options)
(The problem is limited to Windows. I don't have this problem on my manjaro)
The document reads:

> #### [file-download-options]
> 
> ```
> --file-download-options <json-string>
> ```
> 
> a JSON string of key/value pairs to be set as file download options.  See [electron-dl](https://github.com/sindresorhus/electron-dl) for available options.
> 
> Example:
> 
> ```bash
> nativefier <your-website> --file-download-options '{"saveAs": true}'
> ```

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [ ] I searched existing open & closed issues. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
Give your ***full*** nativefier command, with the ***`--verbose` flag***, on a ***public*** site:
1. Run `nativefier https://www.google.com/  --file-download-options '{"saveAs": true}'`
2. none

**Expected behavior**
I want the application to be packaged correctly and able to save as.

**Actual behavior**
See below:

**Debug info**
Console output:
```
F:\>nativefier https://www.google.com/ --file-download-options '{"saveAs": true}'
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJson (C:\Users\Tim_Paik\AppData\Roaming\npm\node_modules\nativefier\src\cli.ts:32:15)
    at Command.<anonymous> (C:\Users\Tim_Paik\AppData\Roaming\npm\node_modules\nativefier\node_modules\commander\index.js:442:13)
    at Command.emit (events.js:311:20)
    at Command.parseOptions (C:\Users\Tim_Paik\AppData\Roaming\npm\node_modules\nativefier\node_modules\commander\index.js:988:14)
    at Command.parse (C:\Users\Tim_Paik\AppData\Roaming\npm\node_modules\nativefier\node_modules\commander\index.js:639:21)
    at Object.<anonymous> (C:\Users\Tim_Paik\AppData\Roaming\npm\node_modules\nativefier\src\cli.ts:266:6)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

F:\>
```

**Context**
 - Nativefier:8.0.4
 - Node.js:v12.16.1
 - Npm:6.14.2
 - OS:Windows 10 LTSC (build 1809)

Fortunately, I solved the mistake.
After I read #569, I found another way to solve this problem,
And I think it's more friendly.

**solution**
Replace `--file-download-options '{"saveAs": true}'` with `--file-download-options "{\"saveAs\": true}"` and it will work.
(My Windows and my manjaro both work `--file-download-options "{\"saveAs\": true}"`)
It looks like the command line argument in Windows does not support `''`to surround the `""` in the json that you want to use,
It works fine when I use `""` and escape the `""` in json with the `\`
In fact, running `cd 'C:\Program Files'` under Windows also causes errors, but `cd "C:\Program Files"` is fine.
I think it would be more appropriate to change the `--file-download-options '{"saveAs": true}'` in [api.md](https://github.com/jiahaog/nativefier/blob/master/docs/api.md#file-download-options) to `--file-download-options "{\"saveAs\": true}"`, which applies to all platforms
So why not change api.md to support full platform?I think this is better for Windows users)
Is there something wrong with the way I use it?
I would appreciate it if you could point out what mistake I have made.

**Comment by ronjouch** [comment]
Thanks for the feedback @Tim-Paik. I've seen a fair share of users being confused by JSON args, not isolated to your specific case, so I pushed a commit offering a helpful message when JSON.parse fails. I won't change api.md, as the escaping with only double-quotes is specific to windows cmd, ugly, and confusing for other users. But the better error message will help. It looks like this:

```bash
~ nativefier https://www.google.com/ --file-download-options '{"saveAs: true}'
Unable to parse JSON value: {"saveAs: true}
JSON should look like {"someString": "someValue", "someBoolean": true, "someArray": [1,2,3]}.
 - Only double quotes are allowed, single quotes are not.
 - Learn how your shell behaves and escapes characters.
   In particular, Windows cmd doesn't have single quotes, so you have to use only double-quotes plus escaping: "{\"someKey\": \"someValue\"}"
 - If unsure, validate your JSON using an online service.
Failed to parse command-line arguments. Aborting.
```

**Comment by Tim-Paik** [comment]
Thank you for your contribution to this software!
It really helped me a lot.

**Comment by damobeanrod** [comment]
Commenting out the code block in the main.js file does function as a workaround. 
e.g. 
APPLICATIONLOCAL/resources/app/lib/main.js

Update this block 
if (options.saveAs) {
				item.setSaveDialogOptions({defaultPath: filePath});
			} else {
				item.setSavePath(filePath);
				}*

to
/*if (options.saveAs) {
				item.setSaveDialogOptions({defaultPath: filePath});
			} else {
				item.setSavePath(filePath);
				}*/

note /*  */ 
means comment out everything in the middle
