### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by koorb** [jiahaog/nativefier#93]
Would it possible to have an option to remember window size and position?

**Comment by momosby** [comment]
add --width and --height flags like this: 
~user$: nativefier "http://somepage.org" -w "720px" -h "900px"

about window position i am not sure. but check this out:
https://github.com/atom/electron/issues/526

looks like if you do some hand work it might work

**Comment by zweicoder** [comment]
@koorb Actually I added a window state manager quite a while ago to track your window size/position. Is it not working for you?

**Comment by koorb** [comment]
Hey @zweicoder, no I position and size the app, next launch it just defaults to the middle of the screen

**Comment by jiahaog** [comment]
@koorb Could you please include the following:

> - Version of Nativefier (run $ nativefier --version)
- Version of Node.js (run $ node --version)
- Command line parameters
- OS and architecture you are running Nativefier from

**Comment by koorb** [comment]
Sorry for slow reply. Running on a Mac—OS X 10.11.3 – x86_ 64

nativefier --version = **6.5.3**
node --version = **v5.5.0**

Command line parameters:
`nativefier http://devdocs.io -n DevDocs -i devdocs.icns --overwrite`

**Comment by jiahaog** [comment]
@koorb Hi, please update to the latest version of nativefier, this has been implemented since [`v6.6.0`](https://github.com/jiahaog/nativefier/blob/development/History.md#660--2016-01-25)!

**Comment by koorb** [comment]
Nice, thank you @jiahaog works great
