### ISSUE TITLE
[osx] Nativefier app globally captures Option + Left/Right arrow keys shortcuts

### ISSUE THREAD

**Issue by NiklasRosenstein** [jiahaog/nativefier#930]
**Bug description**

While an application that I created with nativefier is open, I cannot use the Option + Arrow Left/Right key combination in any application. Closing the application again makes the shortcut work again. 

Other application don't get to see this key combination even if the nativefier application is in the background. (For example when you try to configure an iTerm2 shortcut, it does not register the combination until you close the nativefier app).

- [ ] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing open & closed issues. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**

1. Create and open a nativefier app (I used `https://outlook.office365.com/owa/`)
2. Try to use Optiona + Arrow Left/RIght to jump between words in a text editor

**Context**
 - Nativefier: 8.0.4
 - Node.js: 3.11.0
 - Npm: 6.13.7
 - OS: OSX 10.14.6

**Comment by ronjouch** [comment]
> While an application that I created with nativefier is open, I cannot use the Option + Arrow Left/Right key combination in any application. Closing the application again makes the shortcut work again.
> 
> Other application don't get to see this key combination even if the nativefier application is in the background. (For example when you try to configure an iTerm2 shortcut, it does not register the combination until you close the nativefier app).

@NiklasRosenstein thanks for the feedback. Are you sure you're talking about **<kbd>Option</kbd>** (a.k.a. Alt) + Arrows? I'd find this surprising, as I think Option + arrows is entirely unused by Nativefier.

Also, can you try with an older Electron? Try passing flag `-e 6.1.9`

**Comment by NiklasRosenstein** [comment]
Hey @ronjouch,

Yes I am talking about this key: <img src="https://www.macworld.co.uk/cmsdata/features/3462401/what_is_the_option_key_on_mac_742.jpg" width="40px"> in combination with the left or right arrow key. This combination is used in many text editing applications to jump between words.

As far as I can see,  only the combinations `Option + <-` or `Option + ->` are affected. I can still add `Shift` to the combination and select + jump between words.

Per your suggestion I tried

    $ nativefier https://outlook.office365.com/owa/ --name 'Outlook Web' -e 6.1.9

Unfortunately it is still the same. As soon as I open the application, the key combinations don't work anymore (that is system-wide, not just in the Nativefier application) and it works again when I close it.

**Comment by ronjouch** [comment]
@NiklasRosenstein okay, thanks for looking and confirming. Weird, I don't know. I'm only doing minimal maintenance and don't even run macOS, so don't expect a quick fix. If you have the time to dig, PR very welcome 🙂.

**Comment by Abruptive** [comment]
This is happening for me as well. If you have a Nativefier app open, the Option + Left/Right combo is overwritten. Which is a bummer because it's a shortcut you use to navigate text quite a lot.

**Comment by straschek-io** [comment]
I have the same issue with:

Nativefier: 8.0.4
Node.js: 10.19.0
Npm: 6.13.4
OS: MacOs Mojave 10.14.6

Thanks for investigation!

**Comment by luuf** [comment]
I had the same issue with nativefier 8.0.4 (node 13.11.0, npm 6.14.4, mac 10.14.6). Rolling back to nativefier 7.7.1 solved it for me.

While I didn't test the versions in between, I'm guessing that the problem was created by "Add common Alt+Left/Right for previous/next navigation.", introduced in 8.0.0.

**Comment by ronjouch** [comment]
Thanks folks 🙂, fixed. Pushing in a release soon.

**Comment by ronjouch** [comment]
Released in 8.0.6 now on npm!

**Comment by luuf** [comment]
Works great!

**Comment by straschek-io** [comment]
Works for me, thank you very much!
