### ISSUE TITLE
Popup window does not use size of parent window

### ISSUE THREAD

**Issue by robertmylne** [jiahaog/nativefier#931]
Popup windows do not use dimensions of parent window. So when creating using nativfier if I set it to 1000x800 the windows that would normally open in a new tab do not follow these dimensions.

**Comment by ronjouch** [comment]
Please come back providing the information requested by the issue template; https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
