### ISSUE TITLE
VimFX or cVim option for native apps

### ISSUE THREAD

**Issue by lcota** [jiahaog/nativefier#933]
**Problem statement**
When browsing nativefied websites, it would be fantastic to enable keyboard only navigation which is made available to Chrome/Firefox browsers via extensions such as VimFX or cVim. 
Extension websites: 
https://github.com/1995eaton/chromium-vim  

- [x] I looked at `nativefier --help` and it may be possible to use the --inject 
 switch, though i am not sure how I may go about this. I've browsed https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [x] I searched existing open & closed issues. Yes, my issue is new.

**Suggested solution**
A way to bundle cVim extension with nativefied apps with a command line switch to enable for each site. 

**Alternative solutions**
A clear and concise description of alternative solutions or workarounds you've considered.

**Context**
 - Nativefier: (for example: 7.7.0)
 - Node.js: (for example: 12.10.0)
 - Npm: (for example: 6.10.3)
 - OS: (for example: Windows 10 build 19041)
 - Additional context: None

**Comment by ronjouch** [comment]
@lcota thanks for the feedback. You may get to a fraction of the experience with `--inject`, yeah. For a real packaging of the VimFx Chrome extension, see https://github.com/jiahaog/nativefier/issues/207 . Closing as duplicate.
