### ISSUE TITLE
how to translate the menubar?

### ISSUE THREAD

**Issue by qt06** [jiahaog/nativefier#936]
Hi, I want to translate the menubar into other language, but I don't know hwo to do it.
Thank you.

**Comment by ronjouch** [comment]
Hi @qt06 and thanks for the feedback. Nativefier right now isn't built to be localized. If you really want to do so, you can by reaching for the big `/path_to_nativefied_app/resources/app/lib/main.js` file, which contains all the application code. Open it and search for an easy-to-find menu entry name, like `Clear App Data`, and you'll find where the menu is declared. Edit, save, and re-run.
