### ISSUE TITLE
[OSX] Javascript Error

### ISSUE THREAD

**Issue by mcharron** [jiahaog/nativefier#94]
Hi,

I currently try to deploy a webapp with nativefier. It works on Linux x64, Windows ia32 and x64 but not OSX x64.

The error I get is : 
![index](https://cloud.githubusercontent.com/assets/6449337/12586350/337ff3f8-c450-11e5-8f69-fe0dba9b63a2.png)

I used the following params : 
--pretend -p darwin -a all "myurl"
On an Ubuntu 15.04 with Node v5.5.0

It does not compile to OSX ie32, but since OSX 10.6 there's no more PPC so everything should run in x64.

Can you help me ?

Thanks

**Comment by jiahaog** [comment]
Just to clarify, you're trying to package your app from windows?

**Comment by jiahaog** [comment]
I meant linux, you mentioned that you are using Ubuntu, so I assume you tried to package the app on Ubuntu for all the platforms mentioned?

**Comment by mcharron** [comment]
Yes thats it. I test on Windows and Linux, no problem. On Mac OS X, I got the previous error.

**Comment by mcharron** [comment]
Hello,

I add some informations : it works on 2 Macs, and not on one other.
OS X Yosemite 10.10.2, iMac Mid 2011: Works
OS X El Capitan, MacBook Pro Retina 13 Late 2015: Works
OS X Yosemite 10.10.5, Mac Mini Late 2012: Not working

I compare hardware, and I don't found something wrong between these machines...

I hope it'll helps you to find why it doesn't work on the Mac mini.

**Comment by jiahaog** [comment]
Could you try building the app on the mac mini itself and see if it works?

**Comment by mcharron** [comment]
Ok so right after installing node and npm on the mac mini, I compiled and it works. Hopefully, the problem is only on this Mac, I hope it'll not be on another. Thanks for all

**Comment by jy1989** [comment]
same error on my iMac .   OSX 10.11 (15A284)

**Comment by jiahaog** [comment]
Hi, I can't seem to replicate this error. Could you please provide me with the following:

> Version of Nativefier (run $ nativefier --version)
Version of Node.js (run $ node --version)
Command line parameters
OS and architecture you are running Nativefier from
Stack trace from the error message (if any)
Instructions to reproduce the issue

**Comment by jy1989** [comment]
Hi 
Three are the infomations:


Version of Nativefier (run $ nativefier --version) 
6.7.0
Version of Node.js (run $ node --version) 
v4.0.0
Command line parameters 
nativefier github.com
OS and architecture you are running Nativefier from
 OSX 10.11 (15A284) 
Stack trace from the error message (if any)
![](https://cloud.githubusercontent.com/assets/1291756/12665616/de8ff764-c673-11e5-8f0d-818ffbd0d983.png)

**Comment by mcharron** [comment]
Version of nativefier : 6.6.2
Version of node : 5.5.0
OS : Ubuntu 15.04 x64
Stack trace already given in the first comment. Problem appears on a Mac mini late 2012 on Yosemite 10.10.5

**Comment by mcharron** [comment]
Hi,

There's some news here : I tried on another Linux 64 bits computer, and it crashed with the same error.

Have you any news by your side ?

**Comment by jiahaog** [comment]
I've tried to replicate this on my Ubuntu 14.04  and OSX on 10.11.4 and I can't seem to get the same errors. Any ideas?

**Comment by guettaf** [comment]
guys , check the permission

**Comment by thegrubbsian** [comment]
Not sure if this is related at all but I get this error when trying to download a document from Google Drive within a nativefier app:

<img width="532" alt="screen shot 2016-08-12 at 12 12 02 pm" src="https://cloud.githubusercontent.com/assets/77794/17629003/235d7c66-6086-11e6-82df-75116cc4a70c.png">

**Comment by thegrubbsian** [comment]
Anyone looking into any of these errors?

**Comment by blakeeddins** [comment]
I get the same javascript error as @thegrubbsian when downloading files from Google Inbox: 

<img width="895" alt="screen shot 2017-05-07 at 07 39 44" src="https://cloud.githubusercontent.com/assets/2955861/25780624/640e5e52-32f8-11e7-9787-d4ac8b8ceec0.png">

**Comment by bacongravy** [comment]
The issue described by @mcharron and @jy1989 appears to be the same as #575, and if so, will be resolved by #581.
