### ISSUE TITLE
[Discussion] I integrated Nativefier into my project

### ISSUE THREAD

**Issue by cristianovitorino** [jiahaog/nativefier#946]
Hello @jiahaog! I wanted to drop a quick note to let you know that I'm using **Nativefier** into my project, [Figwrapper](https://github.com/cristianovitorino/figwrapper), a script that fully integrates the Figma design tool (web version)  into a complete app for Linux, and now thanks to you and @tryvin's work, I have full local font support, and a nice Electron wrapped Figma Linux app.

Really, thank you.

**Comment by ronjouch** [comment]
Thanks! 🙂 Closing.
