### ISSUE TITLE
Live --inject scripts for iterative development

### ISSUE THREAD

**Issue by ericclemmons** [jiahaog/nativefier#953]
**Problem statement**

For iterating on & testing the `--inject`ed CSS & JS, I'd like to be able to reload the app/page & test out my changes for a faster feedback-loop.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [x] I searched existing open & closed issues. Yes, my issue is new.

**Suggested solution**

`--dev` flag or similar for the loaded scripts to be read off the filesystem directly vs. the package.

**Alternative solutions**

None that I know of.

**Context**
 - Nativefier: 8.0.7
 - Node.js: v10.16.3
 - Npm: 6.9.0
 - OS: macOS 10.14.6 (18G4032)

**Comment by ericclemmons** [comment]
Maybe this just needs documentation.

I found that I can edit `~/Desktop/My App-darwin-x64/My App.app/Contents/Resources/app/inject/inject.js` and refresh for changes 😍

**Comment by ronjouch** [comment]
> Maybe this just needs documentation. I found that I can edit `~/Desktop/My App-darwin-x64/My App.app/Contents/Resources/app/inject/inject.js` and refresh for changes heart_eyes

@ericclemmons yup! PR welcome, probably in https://github.com/jiahaog/nativefier/blob/master/docs/development.md
