### ISSUE TITLE
No notifications in Ubuntu 20.04

### ISSUE THREAD

**Issue by AlexSjr** [jiahaog/nativefier#956]
Hello, I have a issue with notifications in Ubuntu 20.04.
If I click on send on this site the notification is not shown
![Captura de tela de 2020-04-26 01-56-25](https://user-images.githubusercontent.com/19698413/80298328-8586c180-8761-11ea-8728-9be2435b9232.png)

**Comment by exander77** [comment]
No, notifications anywhere, I have made a pull request to fix it:
https://github.com/jiahaog/nativefier/pull/955
