### ISSUE TITLE
[question] Help with China GFW and using a cached / pre-downloaded Electron

### ISSUE THREAD

**Issue by MX-Qulin** [jiahaog/nativefier#965]
Hi,there.
I'd like to know how to build Windows App like ***.exe on my Ubuntu18.04.
I'm in China...So you know that the network of downloading is big problem.
After I successfully built my linux app on Ubuntu18.04, I found it will cost me 11211s finish downloading...
Hope to hear from you soon
Yours sincerely.

**Comment by MX-Qulin** [comment]
Also,may i know how can i use my downloaded zipfile "electron-v8.2.3-win32-x64.zip"to package, instead of take 11211s to download?
as you know, our Net is much more "different"&"difficult"~

**Comment by MX-Qulin** [comment]
Actually, i've download "electron-v8.2.3-win32-x64.zip"from a Chinese mirror, and i use `npm i electron@8.2.3 -g`to install it. However, after i began to package my website, it started downloading  "electron-v8.2.3-win32-x64.zip" again...... That's rellay annoying...

**Comment by ronjouch** [comment]
@MX-Qulin yeah, trouble with China's Great FireWall happens for some of our users; see [existing issues](https://github.com/jiahaog/nativefier/issues?q=gfw).

As for your caching question, under Windows I don't exactly know. You should put the downloaded Electron zip at the place electron-packager does its caching. Under Linux it's in `~/.cache/electron`, under Windows it must be somewhere in `C:\Users\YourUsername\AppData\...`. Feedback welcom if you figure it out.

**Comment by MX-Qulin** [comment]
Will, what to do next after i moved the zip file to `~/.cache/electron`?

**Comment by MX-Qulin** [comment]
emmm.... i met another problem.
After packageing, i ran the exe but it looks like this:
![Uploading 图片1.png…](img1)
the image's url is [img1](https://s1.ax1x.com/2020/05/01/JOI68s.png)
Also i'll show you the package folder.
![Uploading 图片2.png…](img2)
the image's url is [img2](https://s1.ax1x.com/2020/05/01/JOILKx.png)

**Comment by imydou** [comment]
export ELECTRON_GET_USE_PROXY=1 # 值为1或true
export GLOBAL_AGENT_HTTP_PROXY=http://proxy.example.com:1080
export GLOBAL_AGENT_HTTPS_PROXY=https://proxy.example.com:1080
