### ISSUE TITLE
Implement electron-push-receiver

### ISSUE THREAD

**Issue by BananaManCJ** [jiahaog/nativefier#966]
Some websites use a different api for notifications (Twitter, for example) and are therefore unable to display notifications. https://github.com/MatthieuLemoine/electron-push-receiver should be implemented so that sites like Twitter can send notifications from the Nativefier Electron app.

**Comment by BananaManCJ** [comment]
This would enable sites that use Firebase Cloud Messaging (FCM) to receive push notifications.

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/jiahaog/nativefier/issues/652
