### ISSUE TITLE
Minimize to system tray icon

### ISSUE THREAD

**Issue by mistic100** [jiahaog/nativefier#97]
I wrapped SoundCloud and it work like a charm.

But a nice feature would be that the minimize or close button actually minimize the app to the system tray (Windows).

See http://electron.atom.io/docs/v0.36.5/api/tray

Something even cooler would be to personalize the tray icon actions, but as it require programming it might be out of scope.

**Comment by MakuSensei** [comment]
I also suggest that option especially when using Facebook Messenger, Hangouts and Skype web version
Disculpen mi ingles, Uso el Traductor de Google

**Comment by zweicoder** [comment]
I'm working on this but this will have to wait til we get a fix for the icon issue, which might be done soon

**Comment by jiahaog** [comment]
Yeap, this could be a future enhancement for the packaged app.

**Comment by hobbs** [comment]
was this closed as resolved, or not going to be added?

**Comment by ronjouch** [comment]
@hobbs `--tray` was recently added, see `nativefier --help` or https://github.com/jiahaog/nativefier/blob/master/docs/api.md#tray

**Comment by hobbs** [comment]
@ronjouch yep, I'm using `--tray`. I didn't see anything in the docs about specifying the tray icon, which is the topic of this ticket.

Right now it goes to tray with a blank icon, ie, empty space (Linux + KDE).

**Comment by ronjouch** [comment]
@hobbs if passing a `--icon /path/to/icon.png`, you should have it used in the tray. Are you?

**Comment by hobbs** [comment]
Yes, I'm passing an icon, and it's using it in the KDE task menu, but it does not use it in the tray.

**Comment by cutzenfriend** [comment]
Same here on OSX Icon is used in the Dock but not at the top in the system tray area
