### ISSUE TITLE
Whatsapp on Nativefier doesn't show notifications

### ISSUE THREAD

**Issue by raulcraveiro** [jiahaog/nativefier#970]
**Bug description**
I've made a Whatsapp Web through nativefier. I receive the notification sound, but It doesn't show any notification popup.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [X] I searched existing open & closed issues. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
Give your ***full*** nativefier command, with the ***`--verbose` flag***, on a ***public*** site:
1. Run "nativefier --name "Whatsapp" --inject "dark.css" https://web.whatsapp.com
2. Connect your Whatsapp account

(The dark.css is from here: https://github.com/dcferreira/franz-themes/blob/master/whatsapp/darkmode.css)

**Expected behavior**
When I receive a message, It should appear as a notification.

**Actual behavior**
When I receive a message, It just make sound but no notification appears.

**Context**
 - Nativefier: 8.0.7
 - Node.js: 12.16.3
 - Npm: 6.14.4
 - OS: Fedora 32 Workstation
 - Is it a regression? I have a Whatsapp web packaged through Nativefier 7 that has notification working (but I get a lot of other bugs in that version)

**Comment by MusselCelery** [comment]
Same problem here.

OS: Manjaro 20.0.1
Node.js 14.2.0

**Comment by Whallas** [comment]
Same problem, I'm using Whatsapp-web and Trello.
Nativefier 8.0.7.
node 12.18.
Pop os 20.04

**Comment by bkmo** [comment]
Yes notifications are still broken in 8.0.7 for me too.  This is a workaround: 
sudo sed -i "s/const newNotify =.*/const newNotify = function (title, opt) {/" /opt/YOUR-FOLDER/resources/app/lib/preload.js

**Comment by ronjouch** [comment]
Hi. I just released Nativefier v9.0.0, which includes the above-mentioned commit. Closing, feel free to re-open if the issue persists.
