### ISSUE TITLE
Receive icon path error (ERRNO -4058) only when executing with --conceal parameter 

### ISSUE THREAD

**Issue by sabzstudio** [jiahaog/nativefier#975]
Greetings,

First and foremost, thank you for this amazing creation!
I would like to bring this to your attention and seek help to overcome this issue.

When running nativefier with the --conceal parameter, I get the following error in the console:
```
Copying icon icon.ico to CompanyName\test-win32-x64\resources\app\icon.ico
Error during build. Run with --verbose for details. [
  [Error: ENOENT: no such file or directory, open 'C:\Users\Sabz\CompanyName\test-win32-x64\resources\app\icon.ico'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Users\\Sabz\\CompanyName\\test-win32-x64\\resources\\app\\icon.ico'
  }
]
```
This does not happen without the conceal parameter.
I think this error is caused by the following but I am not sure how to fix it:

- Only with the conceal mode, the path resources/app no longer exists. Because it's concealed to resources/app.asar thus the script is failing to copy/retrieve to a path that does not exist.

Thank you again, and I hope that you and your families are safe and well during this pandemic.
Cordially, Sabz

**Comment by jmalarcon** [comment]
Hi:

Yes this happens every time in conceal mode. If you use Electron 8.x it doesn't matter and the resulting nativefier app works flawlessly.

But if you use the just released Electron 9.0.0, it fails to run.

I've managed to fix it but manually adding the icon inside de `.asar` package using the npm asar package (it's straightforward) but it's definitely a bug.

**Comment by ocraviotto** [comment]
FWIW, on linux using electron 8.X (initially setting `-e` to `8.3.0`) I had the same error. Tried a couple of more electron 8.X releases to check if they'd work and met the same error each time.

**Comment by jmalarcon** [comment]
The difference is that, despite the error when compiling, the 8.x apps run without a warning or a problem, but with electron 9.x the show an exception and won't run. You can fix it manually as explained in my comment, but this is definitely a bug that would be nice to have squashed.

**Comment by sabzstudio** [comment]
@jmalarcon @ocraviotto 
Thank you both for your input.

José, many thanks for your detailed response.
Since I do not have your expertise to manually work around this, I will await and look for a bug fix. 

Have a great weekend!

**Comment by jmalarcon** [comment]
Hi:

It's very simple. Here are the steps needed just in case you want to do it:

1. Open a command line and Install asar with npm: `npm install -g --engine-strict asar`
2. With the command line go into the `resources` folder of your app and run: `asar extract app.asar ./app`. This will create an app folder with the code of the app.
3. Inside the new `app` folder, copy the icon you want to use, with the name `icon.ico`.
4. Pack the app again with: `asar pack ./app app.asar`. This will overwrite the original  `app.asar` file including the icon.
5. Delete the `app` folder.

That's it. Now if you run the app it will work as expected.

HTH
