### ISSUE TITLE
Add "Open New Window" to Window navbar dropdown

### ISSUE THREAD

**Issue by ian** [jiahaog/nativefier#983]
**Problem statement**

Currently, there doesn't seem to be any way to allow multiple windows to be created.  A use case for this would be to have a github app created and open one window for a repo, and a second window for another repo.

There seems to be a way to add tabs but not create second, third windows.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md , no existing option fits my needs.
- [x] I searched existing open & closed issues. Yes, my issue is new.

**Suggested solution**

Add an option in the Window dropdown to open a second window.  Also add Shift + Command + 
N to open a second window.

**Alternative solutions**
Unsure

**Context**
 - Nativefier: (for example: 7.7.1)

8.0.7

 - Node.js: (for example: 13.10.1)

v12.13.1

 - Npm: (for example: 6.14.7)

6.12.1

 - OS: (for example: Windows 10 build 1809)

MacOS 10.15.4

 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y")

Trying to create native window for https://clubhouse.io

**Comment by ronjouch** [comment]
That's not the goal of Nativefier. Nativefier aims at wrapping one web app, and all the UX assumes that. Use a real web browser, or make several Nativefier apps.
