### ISSUE TITLE
Forcing to open all links in same window.

### ISSUE THREAD

**Issue by mathsbeauty** [jiahaog/nativefier#984]
I am using nativefier with new google sites and Mozilla user agent (to avoid the message that this app is not secure while signing in). It opens every link on navigaion in new window. I have added custom links to my navigation and new tab option is disabled. This is very annoying. This is not the behavior with chrome browser. Can this issue be fixed?
Is it possible to force to open all links whether internal or external in same window.( I have andriod web view app where all links get opened in same window).

**Comment by ronjouch** [comment]
Yes, see https://github.com/jiahaog/nativefier/issues/706 for example of passing a `--internal-urls`

**Comment by KonstantMan** [comment]
I know that's an old issue but i just used nativefier and i can't figure out how to force links that in the browser  open in a new tab , to open in the  same app window , --internal-urls did not wotk
