### ISSUE TITLE
Injecting JS and CSS builds fine, but CSS does not load

### ISSUE THREAD

**Issue by incace** [jiahaog/nativefier#987]
**Bug description**
Specifically, doing a WhatsApp build with two --inject references, first JS then CSS results in CSS never loading. Both files show in the Contents/Resources/app/inject folder. The CSS file will load if injected by itself without the JS file. It seems that only the first --inject works.

- [x] I looked at `nativefier --help` and https://github.com/jiahaog/nativefier/blob/master/docs/api.md
- [x] I searched existing open & closed issues.
- [x] I'm using the latest version available at https://github.com/jiahaog/nativefier/releases

**Steps to reproduce**
1. Run `nativefier --verbose https://web.whatsapp.com/ --name WhatsApp --title-bar-style hiddenInset --icon ../whatsapp.png --inject ../whatsapp.js --inject ../whatsapp.css`
2. CSS never loads.

**Expected behavior**
All injected files to load.

**Actual behavior**
Only first injected file loads.

**Context**
 - Nativefier: 8.0.7
 - Node.js: 10.16.3
 - Npm: 6.14.5
 - OS: MacOS 10.13.6

**Comment by ronjouch** [comment]
@incace thx for the detailed report :pray: . Hmmm, I dunno, I even have a pre-release script helping me test that: https://github.com/jiahaog/nativefier/blob/master/docs/manual-test#L28-L29 , and as of current release, injecting both a js and a css. Screenshot below of me running this script right now; as you can see both the css inject (blue body) and the js inject (an `alert`) work. Try fiddling with your js / css / nativefier command, and take inspiration from the script.

With that, closing as cannot repro, but feel free to come back if you're sure it's actually broken and I'll re-open 🙂.

![screenshot_two-injects_2020-07-18-02:02:33](https://user-images.githubusercontent.com/522085/87846046-eaeada00-c89a-11ea-9c27-c6572f2f1a87.png)
