### ISSUE TITLE
Allow insecure content over HTTPS

### ISSUE THREAD

**Issue by aubreypwd** [jiahaog/nativefier#99]
![](https://cloudup.com/ce8SyTOtD6w+)

As you can see an image wasn't served in the app.

![](https://cloudup.com/iVf3wysThNx+)

______________

But the app in Chrome allows the mixed content. 

![](https://cloudup.com/culT82Tc2Fd+)

**Comment by jiahaog** [comment]
It is possible to do this, it is the `webSecurity` options for the [BrowserWindow](https://github.com/atom/electron/blob/master/docs/api/browser-window.md).

**Comment by jiahaog** [comment]
I'll be great if someone could add a command line flag `--disable-web-security` that sets `webSecurity` of the BrowserWindow to false

**Comment by wiederkehr** [comment]
Hi Jia,
I think I have a solution for disabling the webSecurity setting. 
I'll send you a pull request tomorrow.

–Ben
