### ISSUE TITLE
Tray icon left-click on KDE acts as right-click

### ISSUE THREAD

**Issue by bkmo** [jiahaog/nativefier#990]
Version 9.0.0 Clicking on tray icon does not open program. Left click brings up the whatsapp-quit dialog the same as a right click would. This was fixed in the 8.0.7 version, but is now back. Could this be a regression in Electron?

**Comment by bkmo** [comment]
After digging this is an Electron 9.0.4 issue where they have reverted the tray handling via gtk appindicator and not the Dbus implementation. This is by design and is not a bug.

**Comment by SamDc73** [comment]
is their any work around for this problem ?
