### ISSUE TITLE
--allow-file-access-from-files

### ISSUE THREAD

**Issue by coolcraftnet18** [jiahaog/nativefier#991]
Is it possible to allow nativefier to access any local file? I can't get it to work with that flag.

**Comment by ronjouch** [comment]
> Is it possible to allow nativefier to access any local file? I can't get it to work with that flag.

What for? Please detail your use case and fill the information requested by the template: https://github.com/jiahaog/nativefier/blob/master/.github/ISSUE_TEMPLATE/feature_request.md
