### ISSUE TITLE
Detect filename and extension and determine whether to show a SaveAs prompt?

### ISSUE THREAD

**Issue by coolcraftnet18** [jiahaog/nativefier#993]
Is it possible to edit the main.js file to detect whether a file is an image (png, jpg, etc) or a project file(.project)?
Also. to detect whether the project is a new project that doesn't exist on the disk, or a just saved to disk/opened from disk project that does exist?

For my program, I want it to show the Save As dialog for exporting images and for new project files that need to have a save location and name chosen. But, I do not want it to show a Save As dialog for projects that were opened or projects that were already saved at least once. 

I have tried to write a solution in the main.js file, but my code was horrendous and I keep getting call stack exceeded errors, and object has been destroyed errors. If you could help, that would be great.

**Comment by sarweshparajuli** [comment]
Inside Main.js file, navigate to:
-------------------
```
if (!options.saveAs) {
	item.setSavePath(filePath);
}
```
----------------------
Then, replace that whole chunk with:
```
 if (file && file['type'].split('/')[0] === 'image') {
    	if (options.saveAs) {
		item.setSavePath(filePath);
	}
  } else {
    	if (!options.saveAs) {
		item.setSavePath(filePath);
	}
  }	
```
**Disclaimer:** I have not tested this code myself, will let you know upon testing.

**Comment by coolcraftnet18** [comment]
[image: image.png]

**Comment by coolcraftnet18** [comment]
![image](https://user-images.githubusercontent.com/18317131/86532062-e4209800-be94-11ea-80d4-bce1d8a69616.png)

**Comment by coolcraftnet18** [comment]
const filename = item.getFilename();
		 if (filename && filename['type'].split('/')[0] === 'image') {
    	if (options.saveAs) {
		item.setSavePath(filePath);
	}
  } else {
    	if (!options.saveAs) {	
		item.setSavePath(filePath);
	}
  }	
![image](https://user-images.githubusercontent.com/18317131/86532171-b9830f00-be95-11ea-9937-07bcf83f29ae.png)
@sarweshparajuli

**Comment by ronjouch** [comment]
Hi and thanks for the interest. Yeah, Nativefier's download experience sucks. Closing as dup of https://github.com/jiahaog/nativefier/issues/335 to centralize discussion, maybe ask for help there.
