### ISSUE TITLE
Error when adding icon

### ISSUE THREAD

**Issue by dragonBall561** [jiahaog/nativefier#998]
Nativefier says that it needs ImageMagick to convert icons. It said that is needed png icons and I gave it png icons. But it still gives error. How do you fix it?

**Comment by ronjouch** [comment]
Closing as dup of https://github.com/jiahaog/nativefier/issues/992 , which should be fixed in f234473. Please try it with a [developer build](https://github.com/jiahaog/nativefier/blob/master/docs/development.md), or wait for the next release.
