### ISSUE TITLE
Autostart app on OS boot

### ISSUE THREAD

**Issue by shyamal890** [jiahaog/nativefier#999]
**Problem statement**
Autostart the application on windows / mac boot. 

**Context**
 - Nativefier: 9.0.0

**Comment by sarweshparajuli** [comment]
Even I have been trying to do the same, however, I don't know if it's actually possible through Nativefier itself. 
So for Windows, I have used an alternative, through Inno Setup.
I made an installation script for my program, via Inno Setup ([https://jrsoftware.org/isinfo.php]).
And in the script prior to compiling it I added a bit of code to start upon startup:
`[icons]
Name: "{userstartup}\My Program"; Filename: "{app}\MyProg.exe"; Tasks:StartMenuEntry;
Name: "{commonstartup}\My Program"; Filename: "{app}\MyProg.exe"; Tasks:StartMenuEntry;`

![image](https://user-images.githubusercontent.com/60316871/86509843-99f2d480-be0a-11ea-9de3-dd12e0d14637.png)
There might already be some code under [icons] section, but do not remove that.

Then, you need to compile the installer.
After which you can install the software to your PC, and then it will launch on startup.

I hope we can hear some good news soon.

**Comment by ronjouch** [comment]
Hi. Just add a startup entry relevant to your OS. No need to make a script for that, in Windows, drop a shortcut in the Startup folder, or add a registry key for CurrentUser. Google for help.
